### ISSUE TITLE
Default behaviour when hitting a limit switch

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1004]
Hej,

I was wondering what is the default behaviour when sardana moves a motor into a limit switch?
I implemented a motor controller which returns the according MotorController.UpperLimit or .LowerLimit in the StateOne method.

However, there is no feedback in spock that a limit switch is active

**Comment by reszelaz** [comment]
I see the following feedback in spock (you can reproduce it with a dummy motor), is it what you are looking for?

```
Door_zreszela_1 [1]: mot01.UpperLimitSwitch = 100

Door_zreszela_1 [2]: mv mot01 101
Motion ended in ALARM
mot01:
       State: Alarm
      Status: mot01 is in Alarm. Hit upper switch
              Motor HW is in ALARM. Hit hardware upper limit switch
    Position: 100.0

Door_zreszela_1 [3]:
```

Also the PMTV widget shows this information:

![image](https://user-images.githubusercontent.com/6735649/50842177-7ad6cc00-1366-11e9-9bfe-f1b7827b9f8f.png)

Maybe you hit a limit, this stopps the move and then the limit gets released immediatelly? I'm not sure if this kind of situation is correctly handled.

**Comment by dschick** [comment]
hm, here is what I did in the controller `StateOne` method:

```
limit_plus = 0
limit_minus = 0
switch_state = MotorController.NoLimitSwitch
if tau_limit_plus:
    limit_plus = tau_limit_plus.read().value
if tau_limit_minus:
      limit_minus = tau_limit_minus.read().value
                
if limit_plus:
     switch_state |= MotorController.UpperLimitSwitch
elif limit_minus:
    switch_state |= MotorController.LowerLimitSwitch
                
return (state, status, switch_state)
```

I have a motor `xmag` with an active neg. limit switch:
```
Door_xmcd_1 [4]: xmag.limit_switches
Result [4]: array([False, False,  True], dtype=bool)
```
current position is at 29100
```
Door_xmcd_1 [8]: wum xmag
               xmag
User               
 High           inf
 Current    29100.0
 Low           -inf
```
if I do a move towards negative direction the is just a return but no error:
```
Door_xmcd_1 [5]: umv xmag 25000
      xmag
29100.0000
```

**Comment by reszelaz** [comment]
That's strange. Your `limit_switch` attribute correctly reports the lower limit active.

Have you tried to reproduce it with a dummy motor? Are you able to see what I posted above?

I see that you use an `umv` macro. I tried it also using this macro and it works correctly for me. But just in case please try with the normal `mv`.

Which version of Sardana are you using, I'm with the most recent develop branch.

**Comment by reszelaz** [comment]
Could you please consult the MacroServer server (or Sardana server) logs? Another thing could be that the Door Info and Warning events does not reach the spock.

The logs should be either in:
`/tmp/tango-<user_name>/MacroServer/<server_instance_name>/log.txt`
or
`/tmp/tango-<user_name>/Sardana/<server_instance_name>/log.txt`

**Comment by dschick** [comment]
hej @guifrecuni , so I need to change the state in the controller according to the limit switches?

**Comment by reszelaz** [comment]
Yes, I thinkt that @guifrecuni found the reason for that. Currently you must report the ALARM state if there is a limit switch active. It is documented in the [Tango Motor API](https://sardana-controls.org/devel/api/sardana/tango/pool/Motor.html#sardana.tango.pool.Motor.Motor) but I think should be moved to the core documentation.

We left an opened discussion whether reporting an ALARM in case of hitting a limits is optimal or not in #507.

**Comment by dschick** [comment]
alright, so if I raise the ALARM state in the controller, it is working as expected, but then I do have similar issues when trying to leave the limit switch is active as in #507

**Comment by reszelaz** [comment]
> but then I do have similar issues when trying to leave the limit switch is active as in #507 

Then you must be facing the emergency stop feature. This feature is very usefull when dealing with a group motion. It basically stop the move if the state of the motor is ALARM.
Most of the motion controllers are self protecting themself so if something is wrong they stop the motion anyway.

To avoid this feature to prevent you from leaving the hysteresis area of the limit switch simply return MOVING state if the motor is moving even if the limit is active and return ALARM state if the motor is stopped and the limit is active.

**Comment by dschick** [comment]
thanks
