### ISSUE TITLE
Order of loading controllers when one imports another

### ISSUE THREAD

**Issue by pjb671** [sardana-org/sardana#1005]
Hello,

Just recently we encountered a problem with the order in which modules are loaded and the check isValidModule is called, when the pool starts.

We have a 2d exp channel controller called Lima2DCtrl that inherits from another controller in order to implement some common features, and as such there is an import statement 

from CounterMultiMode import MultiMode

where CounterMultiMode.py provides the class MultiMode(Controller)

The "isValidModule" method does something like:

try:
    mfile, pathname, desc = imp.find_module(module_name, path)
    self.info("(re)loading module %s...", module_name)
    m = imp.load_module(fake_name, mfile, pathname, desc)
except:
   self.error("Invalid module %s", module_name)
   return False, sys.exc_info()

and this fails if

MainThread INFO 2019-01-07 13:41:06,977 ModuleManager: loading module CounterMultiMode

does not happen before the Lima2DCtrl is loaded, like

MainThread INFO 2019-01-07 14:42:59,957 ModuleManager: (re)loading module Lima2DCtrl
MainThread ERROR 2019-01-07 14:42:59,957 ModuleManager: Invalid module Lima2DCtrl
MainThread DEBUG 2019-01-07 14:42:59,957 ModuleManager: Details:
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/sardana/sardanamodulemanager.py", line 194, in isValidModule
m = imp.load_module(fake_name, mfile, pathname, desc)
File "/controls_src/nanomax-controllers/Lima2DCtrl.py", line 10, in <module>
from CounterMultiMode import MultiMode
ImportError: No module named CounterMultiMode

Other controllers that use CounterMultiMode that are loaded after this point are OK. We never noticed this for several years until yesterday, so I can only think that the order is random and we were always lucky that CounterMultiMode had previously always been loaded first. I am working around this for now by simply commenting out the check in isValidModule.  Is there some way to force the order of the loading of the modules, or is is not expected that controllers are written that inherit from other controllers?

thanks a lot and best  regards,

Paul

**Comment by reszelaz** [comment]
> Is there some way to force the order of the loading of the modules, or is is not expected that controllers are written that inherit from other controllers?

Just thinking quickly, maybe the `PoolPath` property order? Could you try to put the base class in the before the sub class?

**Comment by pjb671** [comment]
thanks for the fast suggestion, but the two controllers live in the same dir and the pool path is only a list of dirs as I recall, not a list of files. Having said that, for the controllers that do live in different directories, the order of the dirs in the pool path does not seem to relate to the order of the lines like
ModuleManager: loading module IcePAPCtrl...
etc

**Comment by reszelaz** [comment]
I think that the order of loading controllers is known, so the controllers found in the first PoolPath directory will override the ones from the following directories. If you keep the controllers in the same directory, then the order is unknown. I would not do much about it and focus on the [SEP19](https://github.com/sardana-org/sardana/pull/1328) which should solve this limitation.
@pjb671, @13bscsaamjad, @HEnquist, @johanfforsberg, please re-open if there is anything which does not work as expected, or you continue with doubts about it. Thanks a lot!
