### ISSUE TITLE
Add support to Qt5 and drop support to Qt4.4

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1006]
Debian 10 will come with Qt5 only. In order to be included in the release we need to adapt Sardana to Qt5. The deadline is: [2019-Feb-12] Soft freeze (no new packages, no re-entry, 10-day migrations). But we should target the Jan19 release (31.01.2019).

Similar works on Taurus are already quite advanced - see [TEP18](https://github.com/taurus-org/taurus/pull/814).

In order to facilitate the work, we plan to drop support to Qt4.4, mostly due the signals syntax differences. Finally we will support Qt >= 4.7.4 (PyQt >= 4.8.5) and still use the `taurus.external.qt` shim module.

This issue is to coordinate the necessary works - any volunteers to help are more than welcome:)

Regarding the development environment. I think there are two alternatives. Either use conda environments or use a linux system with both 4.7.4 >= Qt < 5 and Qt >=5 installed. In the second case one can switch between the Qt versions using the `QT_API` environment variable.

The major work would be to remove the old-style signals and use the new Qt API. The list of things to have in mind when working on this is summarized in [Tips for writing code that is Qt binding agnostic](https://github.com/cpascual/taurus/blob/tep18/doc/source/tep/TEP18.md#tips-for-writing-code-that-is-qt-binding-agnostic) chapter of TEP18.

Thie issue could be considered as completed whenever the following widgets will work both on Qt4 or on Qt5.

- [x] expconf
- [x] macroexecutor
- [x] sequencer
- [x] macrobutton
- [ ] scan trends
- [x] door output
- [x] pool motor widget
- [x] pool channel widget
- [x] pool ior widget
- [ ] showscan widget
- [x] hkl widgets
- [ ] sardanaeditor

**Comment by mrosanes** [comment]
I'll try to do a first round to change old signal emission (older than Qt4.4) to new Qt5 signal emission; removing also 'try/excepts' in the cases where both types (old and new signals) where used.

Changes will be pushed to 'qt5' branch

**Comment by mrosanes** [comment]
In PR #1009 I began to convert the signals to new Qt style for code in:
sardana/src/sardana/taurus/qt/qtcore/tango 
and 
sardana/src/sardana/spock

There are still around 300 signals in old style (Qt.SIGNAL) to be changed.
Widgets in  
sardana/src/sardana/taurus/qt/qtgui 
should be quite independent one from another, so we could share the work of converting to new signal style. Everyone is welcome (for reference, Taurus tep18 branch, is already using new style Qt signals).

I'll try to pick now code in:
sardana/src/sardana/taurus/qt/qtgui/extra_macroexecutor/favouriteseditor

**Comment by teresanunez** [comment]
I try the code in: 

sardana/src/sardana/taurus/qt/qtgui/extra_sardana

**Comment by mrosanes** [comment]
Great @teresanunez!
 
I'll go for the code in:
sardana/src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroparameterseditor

**Comment by teresanunez** [comment]
HI @mrosanes, I work  now on the code in extra_hkl.

**Comment by reszelaz** [comment]
Done in #1009
