### ISSUE TITLE
update input of scan trend when changed outside of expconf

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1012]
I am not sure if this a duplicate, but when I open a scan trend from a expconf window, the plotted counters in the trend do not change, when I change the selection in the expconf window.

I need to close the trend window and reopen it, to let the changes take effect.

**Comment by dschick** [comment]
Hej @cpascual ,

actually I have to check, if I use the "Apply" button.

What I am pretty sure of is, that when I am using the propose plotselect macro #824 with expconf in auto-update mode, then it is also not changing.

**Comment by cpascual** [comment]
> What I am pretty sure of is, that when I am using the propose plotselect macro #824 with expconf in auto-update mode, then it is also not changing.

About that, I am not aware of the exact current state of those developments, so I cannot say if the behaviour is to be expected... but I think that it is an independent issue. 

What I can say fo sure is that the expconf trend is supposed to be updated when new settings are applied  **from the same expconf widget**

**Comment by dschick** [comment]
hej @cpascual , indeed I forgot to hit the apply button when changing the plotted channels in the expconf.
However, all changes I make from spock to the measurement group via macros are not applied to the trend window.
Therefor I am changing the title of the issue to:

> update input of scan trend when changed outside of expconf

**Comment by droldan** [comment]
Hi @dschick @cpascual,

I have checked what you say and yes, it seems like the expconf doesn't send a 'config changed' event to the plots opened, is necessary to close and reopen the plot.
The good news is that the expconf is aware of any changes made isn the measurement groups even if they are made using macros.

I will try to review the event connection between the expconf and plot.

I have reproduced the issue using the proposed plotselect macro #824

**Comment by droldan** [comment]
Hi @dschick ,
I've created a PR #1016 to solves this issue.
The event 'experimentConfigurationChanged' was only sent to scan plot when the changes were made with expconf widget.

With this fix, the event is also propagated when the measurement group is modified from external client, in this case Macros.

**Comment by dschick** [comment]
Thanks a lot @droldan ! it's working perfectly fine!
