### ISSUE TITLE
One-shot controller command at the beginning of scan

### ISSUE THREAD

**Issue by stanislaw55** [sardana-org/sardana#1014]
Hello Sardana community,
I'm looking for a way to execute some initialization in Counter/Timer controller just once, at the beginning of scan. I've found [SEP18](https://github.com/sardana-org/sardana/blob/develop/doc/source/sep/SEP18.md) and it looks promising. However, I'd like to know if there's any way to perform such action in Sardana lower than 2.5.0.

Many thanks in advance

**Comment by cmft** [comment]
Hi @stanislaw55 ,
Maybe is not so fancy but if you could do this configuration via a macro, you can configure an general hook to do this action before each scan.

https://sardana-controls.org/users/macro_hooks.html#sardana-macros-hooks-general

https://sardana-controls.org/devel/api/sardana/macroserver/macros/env.html#sardana.macroserver.macros.env.lsgh

**Comment by stanislaw55** [comment]
Hi @cmft 
Thank you for quick response. Solution using macro as a hook seems to be right but in that case I would need to extract step scan integration time from somewhere. This information is exactly what my controller needs. Is it possible?

**Comment by dschick** [comment]
Hej @stanislaw55 ,

I did something similar, and hooked the following macro to the preAcquisition place:

```
@macro()
def userPreAcq(self):
    acqConf  = self.getEnv('acqConf')
    altOn    = acqConf['altOn']
    waittime = acqConf['waitTime']
    
    if waittime:
        time.sleep(waittime)
        self.debug('waiting for %.2f s', waittime)
        
    if altOn:
        # move magnet to minus amplitude
        magnConf    = self.getEnv('magnConf')
        ampl        = magnConf['ampl']
        magwaittime = magnConf['waitTime']
        magnet      = self.getMotor("magnet")
        
        magnet.move(-1*ampl)
        
        self.debug('mag. waiting for %.2f s', magwaittime)
        time.sleep(magwaittime)        
        
        parent = self.getParentMacro()
        if parent:
            integ_time  = parent.integ_time
            mnt_grp     = self.getObj(self.getEnv('ActiveMntGrp'), type_class=Type.MeasurementGroup)
            state, data = mnt_grp.count(integ_time)
                       
        magnet.move(+1*ampl)
        
        self.debug('mag. waiting for %.2f s', magwaittime)
        time.sleep(magwaittime)                
    else:
        pass
```

**Comment by stanislaw55** [comment]
Thank you @dschick, your example was what I needed. `getParentMacro` is really cool feature. Is it documented? I haven't found it. Would be cool to have it in docs.

Any way, thank you @cmft and @dschick for your help!

**Comment by reszelaz** [comment]
[`getParentMacro`](https://sardana-controls.org/devel/api/api_macro.html#sardana.macroserver.macro.Macro.getParentMacro), together with any other classes/methods useful when developing macros, is documented in the [Macro API](https://sardana-controls.org/devel/api/api_macro.html).
