### ISSUE TITLE
Complete Spock Logging (SF#161)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#102]
Hello,
      some of our users want to have a file with the complete output from spock after each session (not only the history with the commands that have been sent).
I would like to start the discussion about the possibility of implementing this
 logging feature and to request this implementation.
Many thanks.

                             Regards,
                                             Teresa  

Reported by: teresanunez ( http://sf.net/u/tere29 )

Original Ticket: [sardana/tickets/161](https://sourceforge.net/p/sardana/tickets/161)

**Comment by teresanunez** [comment]
Hi,
     I have been working again on that. Our users requested it again and they want to have it.
I have changed the implementation and now:
-> the macro typed by the user is in the log file (sorry, not to have it was a bug in the first implementation,
 it was always intended to have it there)
-> warnings, info, errors from macroserver are included
-> errors from the door are included
-> result from the macro is included

The implementation is done in the current version of sardana used at DESY. If you are interested
in having/checking this, I can implement it in the version in develop and make a PR, so it could be
 reviewed. Just tell me, thanks.

                                        Regards,
                                                           Teresa

**Comment by teresanunez** [comment]
One comment more, I have also added the date (day and time) at which the macro is called.

**Comment by reszelaz** [comment]
Good to hear about this progress! I agree with the points that you added to the log file. I think that it is a good idea that you create a PR so we could take a look at it and help.

**Comment by teresanunez** [comment]
OK, thanks, I will prepare the PR.

**Comment by teresanunez** [comment]
Sorry, one question ... the implementation modifies also a file in taurus ... how should I proceed?. 
If I make a PR in Taurus, with the modified file, the PR in sardana could only be checked together
 with the PR in Taurus.

**Comment by reszelaz** [comment]
I think you should open two PR, one in Taurus and one in Sardana. And refer to them in the descriptions.
