### ISSUE TITLE
snapshot from external tango host

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1038]
I would like to have external tango Attributes in my measurement group snapshot.
This works pretty fine for everything which runs on the same Tango Host as Sardana.
But I do have many vairables which DS run on a different Tango Host.

I cannot add them using the expconf and even if I added them manually into the env I do get errors in the scan that they are not accessible.

Best

Daniel

**Comment by reszelaz** [comment]
I just tested it and it works for me. You can add them directly in the expconf.
Just right click on the list of snapshot elements (down part of Snapshot Group tab) and select "Add new row" option. Then type the address of the attribute:

![image](https://user-images.githubusercontent.com/6735649/52200516-4cff7d00-2869-11e9-9295-322c5ea291ef.png)

Please paste here the errors that you get. Thanks!

**Comment by dschick** [comment]
oh sorry for that. It seems that my epics2tango DS was broken.
