### ISSUE TITLE
work with hard ware

### ISSUE THREAD

**Issue by BykovAlexey** [sardana-org/sardana#1039]
Hello everyone!

I am new in Sardana, and don't understand state of things.  For work with hardware, Sardana use "controllers", which is wrote on python. But the python is not so good in this area, like c++. Is it normal or i don't know something?

I have a Tango server (C++), Sardana controller (python) with link to tango server and Taurus autoGui. Is it easiest way to get a result?

**Comment by BykovAlexey** [comment]
Thank you for your answer Teresa.

Can you explain me, advantages of using of Sardana? Why it is better than just Tango with QT designer from Taurus? I really new in it and try to choose a way.

"It aims to reduce cost and time of design, development and support of the control and data acquisition systems." Maybe Sardana include algorithms, which i don't know, but it will be nessesary when i will code acquisition systems?

**Comment by cpascual** [comment]
> But the python is not so good in this area, like c++

First, I must say that I am a python fan and I "hate" touching C++, so I am definitely biased towards python

In the case of talking to hardware, the problems are typically I/O bounded so the performance of C++ vs python does not play a big role... and IMHO it gets more than compensated by the fact that the simplicity of python allows you to concentrate on designing better algorithms (which ends up mattering more in terms of performance)

Also, even for number crunching, where in principle C++ outshines python, you can (should) use numpy, so you get C efficiency anyway with much more simpler code.

The only *practical* exception is if you really need a lot of threading hacks, where you may be penalized by python's Global Interpreter Lock. 

In practice we control the whole ALBA synchrotron almost exclusively in python (and the few systems that we still control with C/C++ tend to be migrated to python when we need to maintain them). Of course there are exceptions, but then we try to isolate and minimize the non-python parts (e.g. we may write a driver in C, but still use python for its Tango server)

>  Why it (sardana) is better than just Tango with QT designer from Taurus?

sardana and taurus are complementary: with sardana you get hardware synchronization and orchestration, and taurus gives you user interfaces.

For example, sardana provides you with ready-made "scans" which allow you to move a motor and acquire on various detectors, cameras, etc in a synchronized way.

Sardana also provides a common interface for different hardware categories (i.e., once a sardana controller is written for a given motor), it will be seen as a generic motor by the sardana system and you will be able, e.g. to use the generic "poolMotorTV" widget to interact with it in a Taurus GUI.

**Comment by teresanunez** [comment]
If you only want to display attributes from your devices you don't need Sardana. Sardana allows you to perform actions (for example step or continuous scans) in an unified way, one can say. It also offers
the same interface for devices of the same 'type' ... so this could also be an advantage only for
displaying ... but well ...
The Pool is, as its name say, a pool of devices which provides the devices of the same type with
the same interface. These devices can then be used by general procedures, implemented partially in the same pool and/or  partially in the macroserver, which are offered  as macros (running in the macroserver and that you can call through a door device - running in the macroserver process - from spock or any other client). These procedures are optimized and available for all devices in the
pool (one can also define own macros for specific purposes with devices in or outside the pool, that you can then easily use for your measurements/acquisitions ...).  In this way you can perform  the different actions you need for control, acquisition, analysis ... without having to redefine them at any point, you only have to have your devices in the pool.

**Comment by reszelaz** [comment]
If there is anything else you would like to know, don't hesitate to reopen this issue or create a new one. Thanks for your interest in Sardana!
