### ISSUE TITLE
Deactivate overshooting correction in ascanct

### ISSUE THREAD

**Issue by fbecheri** [sardana-org/sardana#1043]
Hi all,
Currently at the end of the "ascanct" macro the "correction overshooting" is performed.
We should be able to activate or deactivate this correction according to a parameter.
It is important, for example,
* To optimize the round trip time.
* To not make extra movements when the mechanics is not too good.

Regards,
Fulvio

**Comment by reszelaz** [comment]
Will be fixed when https://github.com/sardana-org/sardana/pull/1576 gets integrated.
