### ISSUE TITLE
redirect macro output to variable

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1050]
Hej all,

I was wondering if one can redirect the output of a macro to a variable in order to write that to a logbook?

In particular I am working right now with the elogy project and can post new entries into these kind of logbooks from within spock, smilar to what was discussed in #789 

Right now I would like to post the output of a `wu `or `ct `into the logbook.
Any idea how to do that without copying the code of these macros?

Best

Daniel

**Comment by reszelaz** [comment]
Just quickly thinking I see two possibilities..

One is a secondary PyTango client listeningo to the Door's Output attribute (or any other *stream* attributes) events. This one could run in parallel to the macro and gather the interesting messages and then whenever these are ready post them on to the elogy.

Another one could be to try to attach a logger handler to the macro object. This would require to write a wrapper macro and inside call `createMacro` and attach a log handler to the created macro object. Finally of course detach it.

I've not tried any of these. Well, the first is a standard PyTango client listening to the events so there should be no technical restricions there. The point is that it is a kind of *decoupled* from your Sardana system. The other one, if works:), is more coupled to the system e.g. it acts only when the macro runs, but on the other hand requires to write a wrapper macro.

Hope this helps you!

**Comment by dschick** [comment]
thanks a lot @reszelaz .
The option with the wrapper-macro seems more elegant to me.

Could you give me a code snippet how this wrapper might look like?
How do I attach the log handler to a macro ?

Best

Daniel

**Comment by reszelaz** [comment]
Something like this seems to work:

```python
from logging import FileHandler
from sardana.macroserver.macro import Macro


class WrapperToAddLogHandler(Macro):
    
    def run(self):
        m, _ = self.createMacro("wa")
        file_handler = FileHandler("/tmp/wa.txt")
        print(type(m), dir(m))
        m.addLogHandler(file_handler)
        self.runMacro(m)
        m.removeLogHandler(file_handler)
```
There is no error handling implemented there, and I have not tested it in a production environment. Please comment if you find any problems with that.
