### ISSUE TITLE
access the scan command in pre-scan hook

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1051]
Hej all,

I would like to write the log the scan command within a pre-scan hook macro.
Is there an easy way to access the command, e.g. via the macro server?
Unfortunately, the ScanHistory is only updated at the end of every scan.

Many thanks in advance.

Best

Daniel

**Comment by teresanunez** [comment]
Hi @dschick, if I understood correctly you want to read the scan command from somewhere,
 don't you?. You have it in the attribute Status of the door device, if you read it you get something
 like:

he device is in RUNNING state.
 Macro stack ([state] macro):
    -[step]	ascan mot05 1.0 100.0 100 1.0

Is this what you need?

**Comment by dschick** [comment]
oh great, thats exactly what I need.

**Comment by reszelaz** [comment]
Maybe an alternative to what @teresanunez points could be to access the scan environment.
I've not checked if this works already in the pre-scan hook place, but you could check something similar to what @droldan does in the [`madscan`](https://sourceforge.net/p/sardana/macros.git/ci/master/tree/ALBA_BL04_MSPD/mad_acq.py#l190) macro. The variables are still protected, but we should make them public or provide getters soon.
