### ISSUE TITLE
communication with elogy

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1052]
Hi all,

I just want to [share some macros](https://github.com/dschick/sardanaMacros/blob/elogy/elogy.py) which I started to code in order to let Sardana automatically communicate with [elogy](https://github.com/MaxIV-KitsControls/Elogy).

My goal is to post automatic entries to a logbook e.g. for every scan and then the experimentalists can add comments to this entry via the webinterface.
I am still working on posting also an image of the last scan result to the logbook.

I am happy for any comments - how about the proposed Sardana plugin system?

Best

Daniel

**Comment by reszelaz** [comment]
@dschick, thanks for sharing your sollution here! I couldn't test it yet. Maybe our MaxIV colleagues could try it, for them it would be easier to have the elogy instance running..

> how about the proposed Sardana plugin system?

Well, for logging the scans I think that one could write a dedicated recorder and plug it to the Sardana.

In general for macros, these includes the scans as well, I think that the easiest would be to let to attach a log handler to the macro being executed but do it as a configuration and programming. Basically this is what we do in the MacroLogging feature. So I would refactor the MacroLogging feature to allow to plugin a third party handlers.
