### ISSUE TITLE
Jan19 manual release tests: openSuse 11.1 & openSuse 12.1

### ISSUE THREAD

**Issue by daneos** [sardana-org/sardana#1055]
### Installation
- [x] Install Sardana (on Linux from the tar.gz : `pip install <tarball_artifact_URL>`
  and on Windows from MSI)
  **Note:** On openSuse 11.1 there are problems with pip, try `python setup
  .py install`

### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
  **Note:** I should remove lxml from requires, same problem on previous release.
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `PyTango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
- [x] In spock run `sar_demo` macro.
  **Note:** Problem #395. Change model name to demo_macros.py. Same problem on previous release.
- [x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [x] Run testsuite. In another console do `sardanatestsuite`
  **Note:** On openSuse 11.1 and Windows there are known problems with 
  testsuite. Check previous release comments.
  ```
  Ran 228 tests in 1102.723s

  OK (skipped=7, expected failures=1)
  ```
  [Full test suite output](https://gist.github.com/reszelaz/0d1bb112cfa3f23a4db3b307edc67a3e)

### Test Sardana using Spock and expconf
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
  **Note**: Change macros code from function to class. Same error than previous version 
- [x] Execute `umvr` macro and verify that the position updates arrives.
- [x] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
  **Note**: Bug on change directory name with the bottom. DOES NOT WORK
- [x] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [x] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
- [x] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
- [x] Open online plot. **DOES NOT WORK**
  **Note**: If the JsonRecorder is not active, it generates and exception. On the previous version it sends a message to activate it.  In addition raise: Plots cannot be updated. Only qwt5 is supported for now:
  commit b5b0068032214db66060b73c48fc073e05d69919
  Author: Carlos Falcon Date: 7/7/16 8:12 AM
  Fix bug-310: adapt taurusgui.macrolistener to taurus4  taurusgui.macrolistener module does not use   taurus4 API.  Change the uses of PyTango.DeviceProxy.name() method to taurus API. Disable the creation SardanaEditor since tauruseditor does not work.

- [x] Set JsonRecorder to true. In spock do `senv JsonRecorder True`
- [x] Run step scan
**Note**: I should change the h5 to use: NXscan_FileRecorder
- [x] Verify that records appear in spock output.
- [x] Verify that records were stored in scan files.
- [x] Verify that records were plotted on the online plot
- [x] Run `showscan` and access to the last scan data.
  **Note**: It assumes that the first file is a h5 file. I configure the spec file as first file and showscan raises an exception. This is a bug. 
- [x] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied.
- [x] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.
  **Note:** : If there is a bug on the macro, the system does not load the file, but the message is: Storing... DONE

### Test Sardana with TaurusGUI

- [x] Create the GUI using this [guide](https://sourceforge.net/p/sardana/wiki/Howto-GUI_creation)

#### PMTV (PoolMotorTaurusValue)
- [x] Move motors from the slit panel in absolute and relative modes.
- [x] Show expert view.
- [x] Show compact mode.

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [ ] Start new sequence 
**NOTE:**button does not work
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### sardanaeditor
**Note:** There are known bugs on CentOS and Windows
No tested on opensuse12 (deprecated system)
- [ ] Open sardanaeditor with macroserver name as argument.
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply changes.
- [ ] Execute macro to see if changes were applied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by rhomspuron** [comment]
After to change the directory name on expconf
```
Traceback (most recent call last):
  File "homelocal/sicilia/.local/lib/python2.7/site-packages/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py", line 408, in onChooseScanDirButtonClicked
    self.ui.pathLE.emit.textEdited.emit(ret)
AttributeError: 'builtin_function_or_method' object has no attribute 'textEdited'
```

**Comment by cmft** [comment]
> After to change the directory name on expconf with the bottom
Fixed in [#PR 1065](https://github.com/sardana-org/sardana/pull/1065)

**Comment by cmft** [comment]
>  Open online plot. **DOES NOT WORK**

Fix it in PR #1066

**Comment by rhomspuron** [comment]
Showscan error with .dat file: 
```
Door_demo2_1 [39]: %showscan
Trying to open local scan file /siciliarep/tmp/rhoms/demo1.dat...
IOError: unable to open file (File accessability: Unable to open file)
(For more detailed information type: python_error)

Door_demo2_1 [40]: python_error
ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (47, 0))

---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)

/homelocal/sicilia/<ipython console> in <module>()

/usr/lib/python2.7/site-packages/IPython/iplib.pyc in ipmagic(self, arg_s)
   1180         else:
   1181             magic_args = self.var_expand(magic_args,1)
-> 1182             return fn(magic_args)
   1183 
   1184     def ipalias(self,arg_s):

/homelocal/sicilia/.local/lib/python2.7/site-packages/sardana/spock/magic.pyc in showscan(self, parameter_s)
     90         else:
     91             scan_nb = int(params[0])
---> 92     door.show_scan(scan_nb, online=online)
     93 
     94 

/homelocal/sicilia/.local/lib/python2.7/site-packages/sardana/spock/spockms.pyc in show_scan(self, scan_nb, online)
    410         self._plotter.show_scan(scan_nb=scan_nb,
    411                                 scan_history_info=scan_history_info,
--> 412                                 directory_map=directory_map)
    413 
    414     def stateChanged(self, s, t, v):

/homelocal/sicilia/.local/lib/python2.7/site-packages/sardana/spock/spockms.pyc in show_scan(self, scan_nb, scan_history_info, directory_map)
    150 
    151         print "Trying to open local scan file %s..." % (local_file,)
--> 152         taurus_nexus_widget.openFile(local_file)
    153         taurus_nexus_widget.show()
    154         nexus_widget = taurus_nexus_widget.neXusWidget()

/homelocal/sicilia/lib/python/site-packages/taurus/qt/qtgui/extra_nexus/taurusnexuswidget.py in openFile(self, fname)
    108             fname = unicode(Qt.QFileDialog.getOpenFileName(self, "Choose NeXus File","/home/cpascual/local/tmp/scantest.h5"))#@TODO!!
    109         if fname:
--> 110             self.__nexusFile = self.__fileModel.openFile(fname)
    111 
    112     def onHDF5WidgetSignal(self, ddict):

/homelocal/sicilia/lib/python/site-packages/PyMca/HDF5Widget.py in openFile(self, filename, weakreference)
    443                 self.emit(qt.SIGNAL('fileUpdated'), ddict)
    444                 return item.file
--> 445         phynxFile = phynx.File(filename, 'r')
    446         if weakreference:
    447             def phynxFileInstanceDistroyed(weakrefObject):

/usr/lib64/python2.7/site-packages/h5py/_hl/files.pyc in __init__(self, name, mode, driver, libver, **kwds)
    148                 pass
    149             fapl = make_fapl(driver,libver,**kwds)
--> 150             fid = make_fid(name, mode, fapl)
    151         Group.__init__(self, fid)
    152         self._shared.lcpl = make_lcpl()

/usr/lib64/python2.7/site-packages/h5py/_hl/files.pyc in make_fid(name, mode, plist)
     43     Also validates mode argument."""
     44     if mode == 'r':
---> 45         fid = h5f.open(name, h5f.ACC_RDONLY, fapl=plist)
     46     elif mode == 'r+':
     47         fid = h5f.open(name, h5f.ACC_RDWR, fapl=plist)

/usr/lib64/python2.7/site-packages/h5py/h5f.so in h5py.h5f.open (h5py/h5f.c:1618)()

IOError: unable to open file (File accessability: Unable to open file)


```

**Comment by cmft** [comment]
Error launching the macroexecutor
```
~> macroexecutor 
MainThread     INFO     2019-02-22 10:06:13,541 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2019-02-22 10:06:14,643 TaurusMacroExecutor.MacroServer/demo2/1: MainWindow settings restored
Traceback (most recent call last):
  File "/homelocal/sicilia/lib/python/site-packages/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py", line 1079, in onDoorChanged
    self._qDoor = Device(doorName)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/taurushelper.py", line 356, in Device
    return Factory(scheme=getSchemeFromName(device_name)).getDevice(device_name)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/tango/tangofactory.py", line 358, in getDevice
    dev_klass = self._getDeviceClass(db=db, dev_name=dev_name)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/tango/tangofactory.py", line 480, in _getDeviceClass
    tango_dev_klass = db.get_class_for_device(dev_name)
Boost.Python.ArgumentError: Python argument types in
    Database.get_class_for_device(Database, unicode)
did not match C++ signature:
    get_class_for_device(Tango::Database {lvalue}, std::string)
Traceback (most recent call last):
  File "/homelocal/sicilia/lib/python/site-packages/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py", line 1079, in onDoorChanged
    self._qDoor = Device(doorName)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/taurushelper.py", line 356, in Device
    return Factory(scheme=getSchemeFromName(device_name)).getDevice(device_name)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/tango/tangofactory.py", line 358, in getDevice
    dev_klass = self._getDeviceClass(db=db, dev_name=dev_name)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/tango/tangofactory.py", line 480, in _getDeviceClass
    tango_dev_klass = db.get_class_for_device(dev_name)
Boost.Python.ArgumentError: Python argument types in
    Database.get_class_for_device(Database, unicode)
did not match C++ signature:
    get_class_for_device(Tango::Database {lvalue}, std::string)
```

**Comment by rhomspuron** [comment]
Bug on sequencer
```
sicilia@ct64suse121:~/tmp> sequencer 
MainThread     INFO     2019-02-22 11:36:39,484 TaurusRootLogger: Using "PyQt4" for Qt
Traceback (most recent call last):
  File "/homelocal/sicilia/.local/lib/python2.7/site-packages/sardana/taurus/qt/qtgui/extra_macroexecutor/sequenceeditor/sequenceeditor.py", line 962, in onDoorChanged
    self._qDoor = Device(doorName)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/taurushelper.py", line 356, in Device
    return Factory(scheme=getSchemeFromName(device_name)).getDevice(device_name)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/tango/tangofactory.py", line 358, in getDevice
    dev_klass = self._getDeviceClass(db=db, dev_name=dev_name)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/tango/tangofactory.py", line 480, in _getDeviceClass
    tango_dev_klass = db.get_class_for_device(dev_name)
Boost.Python.ArgumentError: Python argument types in
    Database.get_class_for_device(Database, unicode)
did not match C++ signature:
    get_class_for_device(Tango::Database {lvalue}, std::string)
Traceback (most recent call last):
  File "/homelocal/sicilia/.local/lib/python2.7/site-packages/sardana/taurus/qt/qtgui/extra_macroexecutor/sequenceeditor/sequenceeditor.py", line 962, in onDoorChanged
    self._qDoor = Device(doorName)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/taurushelper.py", line 356, in Device
    return Factory(scheme=getSchemeFromName(device_name)).getDevice(device_name)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/tango/tangofactory.py", line 358, in getDevice
    dev_klass = self._getDeviceClass(db=db, dev_name=dev_name)
  File "/homelocal/sicilia/lib/python/site-packages/taurus/core/tango/tangofactory.py", line 480, in _getDeviceClass
    tango_dev_klass = db.get_class_for_device(dev_name)
Boost.Python.ArgumentError: Python argument types in
    Database.get_class_for_device(Database, unicode)
did not match C++ signature:
    get_class_for_device(Tango::Database {lvalue}, std::string)
Traceback (most recent call last):
  File "/homelocal/sicilia/.local/lib/python2.7/site-packages/sardana/taurus/qt/qtgui/extra_macroexecutor/sequenceeditor/sequenceeditor.py", line 679, in onPlaySequence
    door = Device(self.doorName())
  File "/homelocal/sicilia/.local/lib/python2.7/site-packages/sardana/taurus/qt/qtgui/extra_macroexecutor/sequenceeditor/sequenceeditor.py", line 533, in doorName
    return self._doorName
AttributeError: 'TaurusSequencerWidget' object has no attribute '_doorName'
```

**Comment by reszelaz** [comment]
> Showscan error with .dat file

This is actually a known issue. Showscan does not work with dat file but only with h5 files. Now I realize it was not reported yet, so could you please report an issue for that, or maybe even a PR. I propose to just catch the IOError raised by h5py and re-raise a more descriptive exception.

> Bug on sequencer

This was actually also affecting the macroexecutor. This is already fixed in taurus-org/taurus@3.x-sdn2.5.1 branch.

**Comment by reszelaz** [comment]
Tests on openSUSE are finished and the results are satisfactory - IMHO there are no release critical problems. We have found some issues but these were already fixed (mostrly in taurus-org/taurus@3.x-sdn2.5.1 branch).
