### ISSUE TITLE
Jan19 manual release tests: Debian 9

### ISSUE THREAD

**Issue by daneos** [sardana-org/sardana#1056]
### Installation
- [ ] Install Sardana (on Linux from the tar.gz : `pip install <tarball_artifact_URL>`
  and on Windows from MSI)
  **Note:** On openSuse 11.1 there are problems with pip, try `python setup
  .py install`

### Create testing environment and run testsuite
- [ ] Start Pool demo2. In a console do `Pool demo2`.
- [ ] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [ ] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `PyTango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows
- [ ] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [ ] Create spock profile demo2. In another console do `spock --profile=demo2`
- [ ] In spock run `sar_demo` macro.
- [ ] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [ ] Run testsuite. In another console do `sardanatestsuite`
  **Note:** On openSuse 11.1 and Windows there are known problems with 
  testsuite. Check previous release comments.
### Test Sardana using Spock and expconf
- [ ] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
  **Note**: On Windows there are known bugs. 
- [ ] Execute `umvr` macro and verify that the position updates arrives.
- [ ] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
- [ ] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [ ] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
- [ ] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
- [ ] Open online plot.
- [ ] Set JsonRecorder to true. In spock do `senv JsonRecorder True`
- [ ] Run step scan
- [ ] Verify that records appear in spock output.
- [ ] Verify that records were stored in scan files.
- [ ] Verify that records were plotted on the online plot
- [ ] Run `showscan` and access to the last scan data.
- [ ] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied.
- [ ] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows

### Test Sardana with TaurusGUI

- [ ] Create the GUI using this [guide](https://sourceforge.net/p/sardana/wiki/Howto-GUI_creation)

#### PMTV (PoolMotorTaurusValue)
- [ ] Move motors from the slit panel in absolute and relative modes.
- [ ] Show expert view.
- [ ] Show compact mode.

#### macroexecutor
- [ ] Execute `ascan` macro
- [ ] Pause it in the middel and resume
- [ ] Abort it
- [ ] Add it to favorites
- [ ] Run `lsm` macro
- [ ] Execute `ascan` from favorites
- [ ] Run `lsmac` macro
- [ ] Execute `ascan` from history
- [ ] Edit `dscan` macro in spock yellow line and run it
- [ ] Restart macroexecutor application
- [ ] Run `lsm` from history
- [ ] Run `ascan` from favorites

#### sequencer
- [ ] Add `ascan` macro to the sequence
- [ ] Add `lsct` macro as a `post-acq` hook of `ascan`
- [ ] Add `dscan` macro to the sequence
- [ ] Run the sequence
- [ ] Save sequence to a file
- [ ] Start new sequence
- [ ] Load sequence from a files
- [ ] Run the loaded sequence

#### sardanaeditor
**Note:** There are known bugs on CentOS and Windows
- [ ] Open sardanaeditor with macroserver name as argument.
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by teresanunez** [comment]
Hi, here the results of my tests (going on)

### Installation
- [ ] Install Sardana (on Linux from the tar.gz : `pip install <tarball_artifact_URL>`
  and on Windows from MSI)
  **Note:** On openSuse 11.1 there are problems with pip, try `python setup
  .py install`
Teresa: I did the installation with python setup.py, pip is also not working for me.

### Create testing environment and run testsuite
- [ x] Start Pool demo2. In a console do `Pool demo2`.
- [ x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [ x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `PyTango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows
- [ x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [ x] Create spock profile demo2. In another console do `spock --profile=demo2`
- [ x] In spock run `sar_demo` macro.
- [ x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
Teresa: done
- [ x] Run testsuite. In another console do `sardanatestsuite`
  **Note:** On openSuse 11.1 and Windows there are known problems with 
  testsuite. Check previous release comments.
Teresa: done. Result:

Ran 228 tests in 735.910s

OK (skipped=7, expected failures=1)

### Test Sardana using Spock and expconf
- [ ] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
  **Note**: On Windows there are known bugs. 
- [ ] Execute `umvr` macro and verify that the position updates arrives.
- [ ] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
- [ ] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [ ] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
- [ ] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
- [ ] Open online plot.
- [ ] Set JsonRecorder to true. In spock do `senv JsonRecorder True`
- [ ] Run step scan
- [ ] Verify that records appear in spock output.
- [ ] Verify that records were stored in scan files.
- [ ] Verify that records were plotted on the online plot
- [ ] Run `showscan` and access to the last scan data.
- [ ] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied.
- [ ] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows

### Test Sardana with TaurusGUI

- [ ] Create the GUI using this [guide](https://sourceforge.net/p/sardana/wiki/Howto-GUI_creation)

#### PMTV (PoolMotorTaurusValue)
- [ ] Move motors from the slit panel in absolute and relative modes.
- [ ] Show expert view.
- [ ] Show compact mode.

#### macroexecutor
- [ ] Execute `ascan` macro
- [ ] Pause it in the middel and resume
- [ ] Abort it
- [ ] Add it to favorites
- [ ] Run `lsm` macro
- [ ] Execute `ascan` from favorites
- [ ] Run `lsmac` macro
- [ ] Execute `ascan` from history
- [ ] Edit `dscan` macro in spock yellow line and run it
- [ ] Restart macroexecutor application
- [ ] Run `lsm` from history
- [ ] Run `ascan` from favorites

#### sequencer
- [ ] Add `ascan` macro to the sequence
- [ ] Add `lsct` macro as a `post-acq` hook of `ascan`
- [ ] Add `dscan` macro to the sequence
- [ ] Run the sequence
- [ ] Save sequence to a file
- [ ] Start new sequence
- [ ] Load sequence from a files
- [ ] Run the loaded sequence

#### sardanaeditor
**Note:** There are known bugs on CentOS and Windows
- [ ] Open sardanaeditor with macroserver name as argument.
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by teresanunez** [comment]
Hi, I have finished my tests in debian9, above my comments/found errors.

**Comment by reszelaz** [comment]
Thanks @teresanunez for your tests!

My replies to your comments:

> I did the installation with python setup.py, pip is also not working for me.

I've tried it on a fresh sardana-test docker image (Debian 9) and the installation using pip worked without problems:

```
root@sardana-test:/# pip install https://ci.appveyor.com/api/buildjobs/ctjrd4rso1xl814m/artifacts/dist%2Fsardana-2.7.0.tar.gz
Collecting https://ci.appveyor.com/api/buildjobs/ctjrd4rso1xl814m/artifacts/dist%2Fsardana-2.7.0.tar.gz
  Downloading https://ci.appveyor.com/api/buildjobs/ctjrd4rso1xl814m/artifacts/dist%2Fsardana-2.7.0.tar.gz (11.6MB)
    100% |████████████████████████████████| 11.6MB 137kB/s 
Requirement already satisfied: PyTango>=7.2.3 in /usr/lib/python2.7/dist-packages (from sardana==2.7.0)
Requirement already satisfied: itango>=0.0.1 in /usr/lib/python2.7/dist-packages (from sardana==2.7.0)
Requirement already satisfied: lxml>=2.1 in /usr/lib/python2.7/dist-packages (from sardana==2.7.0)
Requirement already satisfied: taurus!=4.0,!=4.1,!=4.3,!=4.4,>=3.10 in /usr/local/lib/python2.7/dist-packages (from sardana==2.7.0)
Requirement already satisfied: enum34; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from taurus!=4.0,!=4.1,!=4.3,!=4.4,>=3.10->sardana==2.7.0)
Requirement already satisfied: future in /usr/lib/python2.7/dist-packages (from taurus!=4.0,!=4.1,!=4.3,!=4.4,>=3.10->sardana==2.7.0)
Requirement already satisfied: numpy>=1.1 in /usr/lib/python2.7/dist-packages (from taurus!=4.0,!=4.1,!=4.3,!=4.4,>=3.10->sardana==2.7.0)
Requirement already satisfied: pint>=0.8 in /usr/local/lib/python2.7/dist-packages (from taurus!=4.0,!=4.1,!=4.3,!=4.4,>=3.10->sardana==2.7.0)
Requirement already satisfied: funcsigs; python_version == "2.7" in /usr/lib/python2.7/dist-packages (from pint>=0.8->taurus!=4.0,!=4.1,!=4.3,!=4.4,>=3.10->sardana==2.7.0)
Building wheels for collected packages: sardana
  Running setup.py bdist_wheel for sardana ... done
  Stored in directory: /root/.cache/pip/wheels/e8/8e/21/1fa71147abd9a4b366eb8b4d4a659e314b97b89b741da4f17d
Successfully built sardana
Installing collected packages: sardana
Successfully installed sardana-2.7.0
```

> * Open online plot.
  **Comment:** this already requests to set JsonRecorder to True, so the next step is done with this or before this, but not after.

I will update the how-to-release guide to make it more clear.

>  Run lsm from history
Error: 'SingleParamNode' object has not attribute '_type'
  Run ascan from favorites
Error: same as above

I used the same sardana-test docker container as explained above and I was **not able** to reproduce this problem. I did:
1. Start Pool demo1
2. Start MacroServer demo1
3. Open macroexecutor
4. Choose MacroServer and Door to connect to using the "Change Configuration" action (shortcut: F10)
5. Execute release manual tests corresponding to the macroexecutor application.

> * Create a new macro using template.
**Error**:  I think it is a known error, if I do not mistake I also saw it in the previous release. It is not possible to create new macros.

Yes, there are known errors, but AFAIR, one should be able to create a new macro function using sardanaeditor and execute it afterwards. There are some combination which does not work, #914 and #1015 explain something about this.
Anyway, sardanaeditor should not block the release. If you have new information about this behavior please add them to the above issues or create a new one.

**Comment by reszelaz** [comment]
@teresanunez I just recalled myself that there were some issues related to the tests on Debian. What do you think about my comments?

**Comment by teresanunez** [comment]
Hi @reszelaz,  I think we can go ahead with the release. Thanks.
