### ISSUE TITLE
Jan19 manual release tests: CentOS 7

### ISSUE THREAD

**Issue by daneos** [sardana-org/sardana#1057]
### Installation
- [x] Install Sardana (on Linux from the tar.gz : `pip install <tarball_artifact_URL>`
  and on Windows from MSI)
  **Note:** On openSuse 11.1 there are problems with pip, try `python setup
  .py install`

### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `PyTango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
- [x] In spock run `sar_demo` macro.
- [x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [x] Run testsuite. In another console do `sardanatestsuite`
  **Note:** On openSuse 11.1 and Windows there are known problems with 
  testsuite. Check previous release comments.

### Test Sardana using Spock and expconf
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
  **Note**: On Windows there are known bugs. 
- [x] Execute `umvr` macro and verify that the position updates arrives.
- [x] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
- [x] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [x] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
- [x] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
- [x] Open online plot.
- [x] Set JsonRecorder to true. In spock do `senv JsonRecorder True`
- [x] Run step scan
- [x] Verify that records appear in spock output.
- [x] Verify that records were stored in scan files.
- [x] Verify that records were plotted on the online plot
- [x] Run `showscan` and access to the last scan data.
- [x] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied.
- [x] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows

### Test Sardana with TaurusGUI

- [x] Create the GUI using this [guide](https://sourceforge.net/p/sardana/wiki/Howto-GUI_creation)

#### PMTV (PoolMotorTaurusValue)
- [x] Move motors from the slit panel in absolute and relative modes.
- [x] Show expert view.
- [x] Show compact mode.

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [ ] Start new sequence
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### sardanaeditor
**Note:** There are known bugs on CentOS and Windows
- [ ] Open sardanaeditor with macroserver name as argument.
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by daneos** [comment]
When running testsuite, many tests show this error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sardana/taurus/core/tango/sardana/test/test_pool.py", line 65, in setUp
    SarTestTestCase.setUp(self)
  File "/usr/lib/python2.7/site-packages/sardana/tango/pool/test/base_sartest.py", line 77, in setUp
    BasePoolTestCase.setUp(self)
  File "/usr/lib/python2.7/site-packages/sardana/tango/pool/test/base.py", line 64, in setUp
    self._starter.startDs()
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/starter.py", line 107, in startDs
    self.start()
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/starter.py", line 216, in start
    self.process = subprocess.Popen(args, stdout=dev_null, stderr=dev_null)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1224, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```
The memory usage never exceeds 25% of available for the VM, though.

**Comment by daneos** [comment]
New sequence button becomes inactive if the sequence is created manually. If it's read from a file, the button is enabled.

**Comment by reszelaz** [comment]
> New sequence button becomes inactive if the sequence is created manually. If it's read from a file, the button is enabled.

This is a known issue #305.

**Comment by daneos** [comment]
sardanaeditor doesn't work because of missing spyder 3 on CentOS (this is for sure a known issue).
