### ISSUE TITLE
Jan19 manual release tests: Windows 10

### ISSUE THREAD

**Issue by daneos** [sardana-org/sardana#1058]
### Installation
- [x] Install Sardana (on Linux from the tar.gz : `pip install <tarball_artifact_URL>`
  and on Windows from MSI)
  **Note:** On openSuse 11.1 there are problems with pip, try `python setup
  .py install`

### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `PyTango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
**- Problem1: traceback appearing when creating new spock profile:**
https://gist.github.com/mrosanes/e8473156e350ba2d2425a089d0d19f15
**Bug also existed in previous releases:** https://github.com/sardana-org/sardana/issues/536
**- Problem2: Traceback related to matplotlib and PyQt5 (even if PyQt5 is not installed)**
https://gist.github.com/mrosanes/e87b970edb6b6fac23384477a7773d24
**Similar bug existed in previous releases:** https://github.com/sardana-org/sardana/issues/536
**- Problem3: cannot exit spock doing 'exit()', even if after I use 'Ctrl+C'**

- [x] In spock run `sar_demo` macro.
- [x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [x] Run testsuite. In another console do `sardanatestsuite`
  **Note:** On openSuse 11.1 and Windows there are known problems with 
  testsuite. Check previous release comments.
```
Ran 228 tests in 1415.110s
FAILED (failures=1, skipped=7, expected failures=1)
```
[Full testsuite output](https://gist.github.com/mrosanes/05392d12e9c61bbc7364b6a12c3372ff)

### Test Sardana using Spock and expconf
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
  **Note**: On Windows there are known bugs:
https://github.com/sardana-org/sardana/issues/347
- [x] Execute `umvr` macro and verify that the position updates arrives.
- [x] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
- [x] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [x] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
- [x] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
- [x] Open online plot.
- [x] Set JsonRecorder to true. In spock do `senv JsonRecorder True`
- [x] Run step scan
- [x] Verify that records appear in spock output.
- [x] Verify that records were stored in scan files.
- [x] Verify that records were plotted on the online plot
- [x] Run `showscan` and access to the last scan data.
** %showscan: ImportError: No module named PyMca5.PyMcaGui.io.hdf5**
- [x] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied 
**interactive macros fail on windows**
- [x] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows

### Test Sardana with TaurusGUI

- [x] Create the GUI using this [guide](https://sourceforge.net/p/sardana/wiki/Howto-GUI_creation)

#### PMTV (PoolMotorTaurusValue)
- [x] Move motors from the slit panel in absolute and relative modes.
- [x] Show expert view.
- [x] Show compact mode.

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [x] Start new sequence
**Known bug #305: new sequences cannot always be created**
https://github.com/sardana-org/sardana/issues/305
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### sardanaeditor
**Note:** There are known bugs on CentOS and Windows
- [ ] Open sardanaeditor with macroserver name as argument.
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by mrosanes** [comment]
After launching again sardanatestsuite (without removing the problematic file macroserver.properties https://github.com/sardana-org/sardana/pull/1060), we detected many failures due to memory increase in Windows (even with a VM that has around 4Gb of memory)
Many Pools/MS of unittest are not deleted correctly and their Python processes remains active consuming memory.

**Comment by mrosanes** [comment]
sardanatestsuite in windows:

With PR https://github.com/sardana-org/sardana/pull/1075 , sardanatestsuite is executed with similar results (even better) as in the previous release (Jul18). 
However, during the execution of the testsuite, some popups of python errors appear, these popups have to be closed as they appear, in order to get the correct results during the execution of the testsuite. 

I would give for concluded the Windows tests.

**Comment by reszelaz** [comment]
I agree! Thanks for the tests @mrosanes !
