### ISSUE TITLE
Jupyter kernels

### ISSUE THREAD

**Issue by lorcat** [sardana-org/sardana#1063]
Hi! 
I may have a very stupid question. 
Has anyone tried to have a Jupyter configured to work with ipython spock kernel / profile? I am interested in the qtconsole + spock. It was working with ipython before the split.
Do you think it possible at all?

**Comment by cpascual** [comment]
It has certainly being tested. I just don't remember the outcome (I do remember that some initial test when ipython qtconsole came out were not satisfactory, but I do not know if the situation improved later on). 

Somewhat related: there was some attempt at MAX-IV at replacing the MacroServer by a custom ipython/jupyter kernel, but the effort was abandoned.

**Comment by reszelaz** [comment]
> there was some attempt at MAX-IV at replacing the MacroServer by a custom ipython/jupyter kernel, but the effort was abandoned.

On the last [follow-up meeting](https://github.com/sardana-org/sardana-followup/blob/master/20190214/MINUTES.md) we just said to retake this idea and start from evaluating what MAXIV did in the past. Hope to be able to advance this in the near future.

**Comment by teresanunez** [comment]
Hi, at one of the DESY beamlines spock is used with the qtconsole.I am trying to get some information
 from them and report it in the sardana follow-up meeting today.

**Comment by reszelaz** [comment]
Finally [QtSpock](https://sardana-controls.org/users/taurus/qtspock.html) is available in the develop branch and will be available in Sardana v3 which we expect to be released at the end of the week.
