### ISSUE TITLE
set the significant digits of a counter value

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1081]
Hej,

I was wondering how many significant digits sardana handles for counter values?
I am trying to store long integer into the .spec file and I miss the last three digits.
Is there a way how to adjust that?

Best

Daniel

**Comment by reszelaz** [comment]
Sorry for late reply @dschick!

First of all, I think there is no way to parametrize the way values are written by  SPEC recorder.

I still did not have time to try to reproduce this problem - I will try it next week.

I just quickly looked at the code and just in case you want to investigate on your own in parallel I think that this line https://github.com/sardana-org/sardana/blob/aac4c20090b350fe94f5a9563c4e21c262c7cbab/src/sardana/macroserver/recorders/storage.py#L476 is responsible for formatting the channel values.

**Comment by dschick** [comment]
Thanks  @reszelaz for the comment.

I am actually trying to save a timestamp of a 2d detector within the SPEC file as integer as some kind of option 3, see #991 .
So I am trying to do something like 20190326125038999 where the last three digits are the miliseconds of the timestamp. Unfortunately, these three last digits are cut off.

I guess I could change the `str(data)` to some kind of `"".format()` but this would only make sense with have some general parameter available to set the formatting in the spec file.

Best

Daniel

**Comment by reszelaz** [comment]
@dschick thanks for further details and the example!

To solve this problem, first, we need to remember that the counter/timer values are floats and not integers.
Second, we would need to find a way of printing this value with pure Python. I tried the following and we lose the miliseconds precission:

```python
In [15]: i = 20190326125038999.0
In [16]: "{:17.0f}".format(i)
Out[16]: '20190326125039000'
```

I'm a little bit busy these days so it would be great if you could investigate this.

Whenever we find a way of doing it with Python, you could use a custom recorder (inheriting from SPEC recorder) where you could implement this formatting change. Adding a parametrization to SPEC recorder is another option but will certainly require more work.

**Comment by reszelaz** [comment]
> To solve this problem, first, we need to remember that the counter/timer values are floats and not integers.

I completelly forgot about the possibility of [changing the default interface](https://sardana-controls.org/devel/howto_controllers/howto_controller.html#changing-default-interface).

So, you simply need to add this method in your counter/timer controller:

```python
    def GetAxisAttributes(self, axis):
        axis_attrs = CounterTimerController.GetAxisAttributes(self, axis)
        axis_attrs = dict(axis_attrs)
        axis_attrs['Value']['type'] = int
        return axis_attrs
```

If you have other axis in the controller where you would like to maintain the `float` attribute type, just condition this change of type based on the `axis` argument.

With this change I have found another problem, the `int` type attributes are mapped to Tango `DevLong` type. For your case we would need a `DevLong64` type. I will propose a PR changing this. Whenever this change gets accepted you will get something like this:

```
Door_zreszela_1 [1]: ct 0.1 ct01
Wed Mar 27 09:58:02 2019

  ct01  =  2019032612538999
```

Finally, you won't need a custom recorder cause `str` representation of a `long` number in python does not drop the last digits:

```
In [11]: i = 2019032612538999

In [12]: str(i)
Out [12]: '2019032612538999'
```

**Comment by reszelaz** [comment]
> With this change I have found another problem, the int type attributes are mapped to Tango DevLong type. For your case we would need a DevLong64 type. I will propose a PR changing this. 

@dschick the necessary changes are available in #1083 for try..

**Comment by dschick** [comment]
thanks I will try as soon as possible

**Comment by reszelaz** [comment]
@dschick after the review from @teresanunez we integrated #1083. I close this issue. Please re-open if you find any problems, doubts. Thanks!
