### ISSUE TITLE
Scan hangs on calculating motion of a pseudo

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1087]
This issue is for tracking investigation of a hung scan while calcluating motion of a pseudo motor.
It was explained in between these comments: https://github.com/sardana-org/sardana/issues/1023#issuecomment-476591091 and https://github.com/sardana-org/sardana/issues/1023#issuecomment-477932007.

**Comment by dschick** [comment]
this is the output from the last hanging:

```
SardanaTP.W004 OUTPUT   2019-03-29 23:48:20,206 Door/moke/1.Macro[ascan]:    76     -215.986  1.5539e+09  -8.91237e-07  4.58543e-06  3.80409e-06  4.55861e-06  4.69533e-06  -0.234284  1.05896 
SardanaTP.W004 DEBUG    2019-03-29 23:48:20,248 SScan: [START] motion
SardanaTP.W004 DEBUG    2019-03-29 23:48:20,248 pm/delayctrl/1: write_Position(-207.0)
SardanaTP.W004 DEBUG    2019-03-29 23:48:20,248 delay: start cal_all_physical
calcPhysical: -31.028519403
SardanaTP.W004 DEBUG    2019-03-29 23:48:20,248 delay: end cal_all_physical
SardanaTP.W004 DEBUG    2019-03-29 23:48:20,248 delay: start checking limits
SardanaTP.W004 DEBUG    2019-03-29 23:48:20,248 delay: before creating AttributeProxy
```

**Comment by reszelaz** [comment]
Thanks! So it is clear now. There is some problem with the proxy creation. 

You could fix it immediately commenting out the whole limit protection block.

For in deep fix, we will try to reproduce it here. Please tell me which versions of Tango, Pytango do you use? Do you use some public packages? What is your platform?

And then how frequently does it  preproduce? What scan parameters do you run?

**Comment by dschick** [comment]
hej,

tango is version 9.2.5 a from the debian repos.
pyTango is 9.2.2 also from the debian repos.
Platform is LinuxMint19

Roughly the problem appears for me every 10 scans having like 100 points per scan, e.g.:
`ascan delay -900.0 0.0 100 1.0`
where delay is my PM

I will try to comment the limit protection and run some more scans for debugging.

Thanks a lot so far

**Comment by dschick** [comment]
@reszelaz , could you please tell me what to comment exactely?

**Comment by reszelaz** [comment]
It was only a [part of the code to be commented](https://github.com/reszelaz/sardana/commit/91d8e00562338a2382dd8d894ccf36e6174ffabd) in between `start checking limits` and `end checking limits`. Please let us know if this improved the situation.

I will run stress tests ovrnight on my development system.

**Comment by dschick** [comment]
Hej @reszelaz ,

I did run two test on both my Sardana setups and the error with the pseudoMotor disappeared.
However, I got again a hanging. For one setup with this last logs:

```
SardanaTP.W006 DEBUG    2019-04-02 03:09:28,804 powermeter.Acquisition: start event with id: 0 received at: 2019-04-02 03:09:28.804159
SardanaTP.W006 DEBUG    2019-04-02 03:09:28,804 powermeter.Acquisition: active event with id: 0 received at: 2019-04-02 03:09:28.804794
SardanaTP.W006 DEBUG    2019-04-02 03:09:28,805 powermeter.Acquisition: Executing software acquisition.
SardanaTP.W006 DEBUG    2019-04-02 03:09:28,806 powermeter.Acquisition: Executing ZeroD acquisition.
SardanaTP.W010 DEBUG    2019-04-02 03:09:28,806 powermeter.Acquisition.SoftwareAcquisition: -> start_action
SardanaTP.W007 DEBUG    2019-04-02 03:09:28,808 powermeter.Acquisition.Synchronization: -> action_loop
SardanaTP.W010 WARNING  2019-04-02 03:09:28,810 powermeter.Acquisition.SoftwareAcquisition: LoadOne(axis, value, repetitions) is deprecated since version Jan18. Use LoadOne(axis, value, repetitions, latency_time) instead.
SardanaTP.W010 DEBUG    2019-04-02 03:09:28,827 powermeter.Acquisition.SoftwareAcquisition: <- start_action
SardanaTP.W010 DEBUG    2019-04-02 03:09:28,827 powermeter.Acquisition.SoftwareAcquisition: -> action_loop
SardanaTP.W006 DEBUG    2019-04-02 03:09:29,803 powermeter.Acquisition: passive event with id: 0 received at: 2019-04-02 03:09:29.803128
SardanaTP.W006 DEBUG    2019-04-02 03:09:29,803 powermeter.Acquisition: Stopping ZeroD acquisition.
SardanaTP.W006 DEBUG    2019-04-02 03:09:29,804 powermeter.Acquisition: end event with id: 0 received at: 2019-04-02 03:09:29.804167
SardanaTP.W007 DEBUG    2019-04-02 03:09:29,805 powermeter.Acquisition.Synchronization: <- action_loop
SardanaTP.W010 DEBUG    2019-04-02 03:09:29,831 powermeter.Acquisition.SoftwareAcquisition: <- action_loop
```
And for the other setup with these logs:
```
SardanaTP.W007 DEBUG    2019-04-02 01:32:24,134 SScan: [START] acquisition
SardanaTP.W005 DEBUG    2019-04-02 01:32:24,136 moke.Acquisition: start event with id: 0 received at: 2019-04-02 01:32:24.136154
SardanaTP.W005 DEBUG    2019-04-02 01:32:24,136 moke.Acquisition: active event with id: 0 received at: 2019-04-02 01:32:24.136297
SardanaTP.W005 DEBUG    2019-04-02 01:32:24,136 moke.Acquisition: Executing software acquisition.
SardanaTP.W005 DEBUG    2019-04-02 01:32:24,136 moke.Acquisition: Executing ZeroD acquisition.
SardanaTP.W006 DEBUG    2019-04-02 01:32:24,142 moke.Acquisition.SoftwareAcquisition: -> start_action
SardanaTP.W006 WARNING  2019-04-02 01:32:24,142 moke.Acquisition.SoftwareAcquisition: LoadOne(axis, value, repetitions) is deprecated since version Jan18. Use LoadOne(axis, value, repetitions, latency_time) instead.
SardanaTP.W006 WARNING  2019-04-02 01:32:24,143 moke.Acquisition.SoftwareAcquisition: LoadOne(axis, value, repetitions) is deprecated since version Jan18. Use LoadOne(axis, value, repetitions, latency_time) instead.
SardanaTP.W009 DEBUG    2019-04-02 01:32:24,149 moke.Acquisition.Synchronization: -> action_loop
SardanaTP.W005 DEBUG    2019-04-02 01:32:25,136 moke.Acquisition: passive event with id: 0 received at: 2019-04-02 01:32:25.136184
SardanaTP.W005 DEBUG    2019-04-02 01:32:25,136 moke.Acquisition: Stopping ZeroD acquisition.
SardanaTP.W005 DEBUG    2019-04-02 01:32:25,136 moke.Acquisition: end event with id: 0 received at: 2019-04-02 01:32:25.136584
SardanaTP.W009 DEBUG    2019-04-02 01:32:25,137 moke.Acquisition.Synchronization: <- action_loop
SardanaTP.W006 DEBUG    2019-04-02 01:32:25,158 moke.Acquisition.SoftwareAcquisition: <- start_action
SardanaTP.W006 DEBUG    2019-04-02 01:32:25,158 moke.Acquisition.SoftwareAcquisition: -> action_loop
SardanaTP.W006 DEBUG    2019-04-02 01:32:26,179 moke.Acquisition.SoftwareAcquisition: <- action_loop
```


Is this again linked to the #1023 issue?

**Comment by reszelaz** [comment]
> Is this again linked to the #1023 issue?

Yes, I think so. I have advanced a little bit with #1023 investigation. More details there...

Regarding your problems with `AttributeProxy` creation comming from limits protection I have done a lot of tests on my development machine without reproducing it.
I use:
* libtango9 9.2.5a with the following patches
  * [debian_patches_0004-Fix-tango-controls-cppTango-354.patch.txt](https://github.com/sardana-org/sardana/files/3034645/debian_patches_0004-Fix-tango-controls-cppTango-354.patch.txt)
  * [debian_patches_0005-Reduce-event-subscription-sleeps-cppTango-415.patch.txt](https://github.com/sardana-org/sardana/files/3034646/debian_patches_0005-Reduce-event-subscription-sleeps-cppTango-415.patch.txt)
  * [debian_patches_0006-Set-the-ZMQ-Receive-Buffer-High-Water-Mark-only-if-i.patch.txt](https://github.com/sardana-org/sardana/files/3034648/debian_patches_0006-Set-the-ZMQ-Receive-Buffer-High-Water-Mark-only-if-i.patch.txt)
* pytango 9.2.2

Up to my knowledge none of the libtango9 patches should be important here.

**Comment by dschick** [comment]
I just want to confirm again the problem with the pseudomotors also with the latest release of Sardana.
I am again testing with commenting out the limit checking

**Comment by reszelaz** [comment]
Finally the AttributeProxy creation&destruction was removed in https://github.com/sardana-org/sardana/pull/1302. The root cause of the problem is https://github.com/tango-controls/pytango/issues/315 and we need to wait until it is solved to re-introduce the check. I think we can close this issue now.

**Comment by reszelaz** [comment]
> re-introduce the check

This is not True. The check is there but without involving the AttributeProxy.
