### ISSUE TITLE
meas is not removed if applying local configuration from expconf 

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#1092]
Measurement group is not removed in the server if applying local configuration from expconf.

How to reproduce:
1- open expconf
2- create measurement group from spock
3- mark 'keep' when expconf popup appears (to keep the local configuration from expconf)
4- apply the expconf configuration
5- The measurement group (not present in the local expconf configuration) is not removed in the server (so the other clients still reports it as existing). It should be removed.
6- The experiment configuration popup of 'load/keep' is appearing again, and it shouldn't. 

----

The symmetric error exists also: a meas is not created in the server if applying local configuration from expconf:
How to reproduce:
1- open expconf
2- remove measurement group from spock
3- mark 'keep' when expconf popup appears (to keep the local configuration from expconf)
4- apply the expconf configuration
5- The measurement group (existing in the local expconf configuration) is not created in the server (so the other clients does not report it as existing). It should be created in the server.
6- The experiment configuration popup of 'load/keep' is appearing again, and it shouldn't.

**Comment by HEnquist** [comment]
We (@HEnquist, @cpascual) think that this is working as it should.
