### ISSUE TITLE
spock does not work without X

### ISSUE THREAD

**Issue by cmft** [sardana-org/sardana#1106]
```> spock 
MainThread     INFO     2019-05-14 16:45:43,514 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     WARNING  2019-05-14 16:45:43,617 TaurusRootLogger: Qt: : cannot connect to X server 
Spock 2.5.1-alpha -- An interactive laboratory application.

help      -> Spock's help system.
object?   -> Details about 'object'. ?object also works, ?? prints more.

IPython profile: spockdoor

Connected to Door_BL01_1
MainThread     WARNING  2019-05-14 16:45:44,061 TaurusRootLogger: Qt:  : cannot connect to X server 
```

**Comment by daneos** [comment]
This is actually a side effect of Spock using and requiring Qt.
You can work around it by creating a ssh connection with X forwarding.
If you then need to leave Spock session running (e.g. with `screen`) after logout, you can forcibly close X connection by pressing Ctrl+C after logging out (otherwise your ssh connection will be closed, but it will not drop you to your local terminal).
Spock session should survive this with only a warning about lost X connection.

I agree that Spock should be able to start without X, maybe with a message that not all features will be available.

**Comment by reszelaz** [comment]
Here we can simply check if the `DISPLAY` environment variable is exported as suggested in this [StackOverflow post](https://stackoverflow.com/questions/12122671/how-to-determine-from-a-python-application-if-x-server-x-forwarding-is-running).

**Comment by reszelaz** [comment]
Here we could try to reuse a similar check mechanism as implemented in https://github.com/sardana-org/sardana/pull/1463

**Comment by jangarrevoet** [comment]
'''
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/lib/python3/dist-packages/IPython/core/shellapp.py in <lambda>(key)
    198         shell = self.shell
    199         if self.pylab:
--> 200             enable = lambda key: shell.enable_pylab(key, import_all=self.pylab_import_all)
    201             key = self.pylab
    202         elif self.matplotlib:

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py in enable_pylab(self, gui, import_all, welcome_message)
   3003         from IPython.core.pylabtools import import_pylab
   3004 
-> 3005         gui, backend = self.enable_matplotlib(gui)
   3006 
   3007         # We want to prevent the loading of pylab to pollute the user's

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   2964                 gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
   2965 
-> 2966         pt.activate_matplotlib(backend)
   2967         pt.configure_inline_support(self, backend)
   2968 

/usr/lib/python3/dist-packages/IPython/core/pylabtools.py in activate_matplotlib(backend)
    313 
    314     import matplotlib.pyplot
--> 315     matplotlib.pyplot.switch_backend(backend)
    316 
    317     # This must be imported last in the matplotlib series, after

/usr/lib/python3/dist-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    220                 "Cannot load backend {!r} which requires the {!r} interactive "
    221                 "framework, as {!r} is currently running".format(
--> 222                     newbackend, required_framework, current_framework))
    223 
    224     rcParams['backend'] = rcParamsDefault['backend'] = newbackend

ImportError: Cannot load backend 'Qt5Agg' which requires the 'qt5' interactive framework, as 'headless' is currently running

'''
