### ISSUE TITLE
weakref error in regscan

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1114]
Hi all,

I have a error message 
`Error: 'weakref' object has no attribute 'info'`
when doing a `regscan`
I am currently working with the latest development branch. I could not find the origin of this error message at all.

Best

Daniel

**Comment by reszelaz** [comment]
@dschick thanks for the report!
I was able to reproduce it and proposed #1115 which for me fixes the problem. Whenever you confirm that I will merge it directly.

**Comment by dschick** [comment]
Confirmation!

Works perfectly well!
Thanks!
