### ISSUE TITLE
Basic tutorial for debugging MacroServer with rconsole

### ISSUE THREAD

**Issue by daneos** [sardana-org/sardana#1117]
Is there any tutorial on using rconsole for debugging?
In the documentation there is only a simple connection instruction and not much more.

**Comment by reszelaz** [comment]
With this [example](https://sardana-controls.org/users/configuration/macroserver.html) you get the the [MacroServer](https://sardana-controls.org/devel/api/sardana/macroserver/macroserver.html#sardana.macroserver.macroserver.MacroServer) object and then the idea is to explore it according to its API.
Do you need something specific? What type of problem are you debugging?

**Comment by daneos** [comment]
I have a problem with some macro sequences hanging the MacroServer. I'd like to see if there are some stuck operations, not finished threads or something like this.
Since I'm not getting any useful information in logs, I thought that probably exploring MacroServer internals will help to debug this problem.

**Comment by reszelaz** [comment]
You could also attach to a running process with gdb and check the backtrace of all threads. Maybe this will give you more details.

**Comment by reszelaz** [comment]
Could it be that you also hit #1080?

**Comment by reszelaz** [comment]
I think there is no `rfoo` module for python3. I'll propose a PR eliminating rfoo usage from Sardana code and docs.
