### ISSUE TITLE
sequencer could report detailed syntax error when importing spock files (SF#181)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#114]
The sequecer allows to import text files with the sequences programmed with spock syntax - one macro execution per one line.

When one makes a mistake in the file, the sequencer does not report in which line is the incorrect command. 
It would be nice to have this information, especially if someone works with big seqeuces. 

Reported by: reszelaz ( http://sf.net/u/zreszela )

Original Ticket: [sardana/tickets/181](https://sourceforge.net/p/sardana/tickets/181)

**Comment by mrosanes** [comment]
Pull request https://github.com/sardana-org/sardana/pull/552 deals with this issue.

**Comment by reszelaz** [comment]
PR #552 was merged into develop
