### ISSUE TITLE
Bug in PMTV apply button

### ISSUE THREAD

**Issue by cmft** [sardana-org/sardana#1145]
If you relative move a motor using PMTV (e.g. from 0 (current pos) to 1) and then press the apply button the motor are moved to the previous relative position (following the example, the motor will come back to 0)

**Comment by reszelaz** [comment]
Actually it goes to the absolute position set in the write widget of the absolute mode. This is the active pending operation and the apply button applies them.
IMHO when you are in the relative mode, the absolute pending operation should not be considered as pending. It should be reconsidered as pending when you come back to the absolute mode.
