### ISSUE TITLE
ValueBuffer Tango attribute of 0D exp. channels

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1147]
This issue is to coordinate one action item from the last [follow-up meeting](https://github.com/sardana-org/sardana-followup/blob/3a2ab2cb11cc4ead1bd578ab8532c284ee528bd4/20190516/MINUTES.md).

Are you aware of any usege in your custom plugins (controllers, macros, recorders, widgets, GUIs) of the `ValueBuffer` attribute of any 0D experimental channel?
This attribute stores the raw samples of the 0D acquisition. This attribute was deprecated in 2.3.0 (2017-08-11) and an equivalent attribute `AccumulationBuffer` was suggested.

We at Alba don't use it. @teresanunez , @amilan and @daneos how about your sites? Anyone using this attribute?

**Comment by teresanunez** [comment]
Hi @reszelaz, i have asked in our beamlines and it seems that nobody use the ValueBuffer attribute.

**Comment by reszelaz** [comment]
@amilan and @daneos could you please poll at your sites about this attribute? Thanks!

**Comment by reszelaz** [comment]
It looks like this attribute was not programatically used, at least there are no voices about this:) ...so let's include this change in the Jul19 release without bumping the major version number. I close this poll.
