### ISSUE TITLE
Jul19 manual release tests: CentOS 7

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana#1154]
This is an issue for checking the Jul19 release in CentOS7

### Installation
- [x] Install Sardana (on Linux from the tar.gz : `pip install <tarball_artifact_URL>`
  and on Windows from MSI)
  **Note:** On openSuse 11.1 there are problems with pip, try `python setup
  .py install`

### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `PyTango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
- [x] In spock run `sar_demo` macro.
- [x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [x] Run testsuite. In another console do `sardanatestsuite`
  **Note:** On openSuse 11.1 and Windows there are known problems with 
  testsuite. Check previous release comments.

### Test Sardana using Spock and expconf
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
  **Note**: On Windows there are known bugs. 
- [x] Execute `umvr` macro and verify that the position updates arrives.
- [x] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
- [x] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [x] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
- [x] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
- [x] Open online plot (This should ask to enable JsonRecorder, set it to true. Otherwise enable it in spock: `senv JsonRecorder True`).
- [x] Run step scan
- [x] Verify that records appear in spock output.
- [x] Verify that records were stored in scan files.
- [x] Verify that records were plotted on the online plot
- [ ] Run `showscan` and access to the last scan data.
- [x] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied.
- [x] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows

### Test Sardana with TaurusGUI

- [x] Create the GUI using this [guide](https://sourceforge.net/p/sardana/wiki/Howto-GUI_creation)

#### PMTV (PoolMotorTaurusValue)
- [x] Move motors from the slit panel in absolute and relative modes.
- [x] Show expert view.
- [x] Show compact mode.

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [x] Start new sequence
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### sardanaeditor
**Note:** There are known bugs on CentOS and Windows
- [ ] Open sardanaeditor with macroserver name as argument.
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by amilan** [comment]
Hi, 
I've run all the test except the ones for sardanaeditor.
So far I've found this errors after running sardanatestsuit:
https://gist.github.com/amilan/8e71aaaa2929ab2f7c855098399efef9 

And in showscan, the elements in the tree appear and you can navigate through them, but no info is displayed at the bottom of the GUI. The error shown is the following:
https://gist.github.com/amilan/58e909d466deebc6daabaa33b74fec75

Regarding the sardanaeditor, the main issue is to have installed a version of spyder bigger than 3.
I saw from the previous releases that @daneos also had issues with spyder, and I would like to ask if you are still suffering them.
(side note: At MAXIV we don't use the sardanaeditor)

Also, I saw an issue when creating new panels in a TaurusGUI, but that doesn't belong here. I will check a couple of things with my environment and if I don't fix it I will report it in the Taurus repository.

Cheers,
Antonio.

**Comment by daneos** [comment]
Hi, I tested with SOLARIS environment, and everything looks good.
I do not see the issues with the testsuite.
With `showscan` I have the following problem:
```
Door_demo2_1 [11]: ascan mot05 -10 10 10 0.1
Operation will be saved in /tmp/scans/scan.h5 (HDF5::NXscan from NXscanH5_FileRecorder)
Scan #12 started at Wed Jun 26 12:27:24 2019. It will take at least 0:00:06.364911
 #Pt No    mot05      ct29      ct30      ct31      ct32       dt   
   0        -10       0.1       0.2       0.3       0.4     1.31674 
   1         -8       0.1       0.2       0.3       0.4     2.25073 
   2         -6       0.1       0.2       0.3       0.4      2.877  
   3         -4       0.1       0.2       0.3       0.4     3.44444 
   4         -2       0.1       0.2       0.3       0.4     4.04547 
   5         0        0.1       0.2       0.3       0.4     4.68771 
   6         2        0.1       0.2       0.3       0.4     5.24003 
   7         4        0.1       0.2       0.3       0.4     5.82019 
   8         6        0.1       0.2       0.3       0.4     6.40304 
   9         8        0.1       0.2       0.3       0.4     7.00574 
   10        10       0.1       0.2       0.3       0.4      7.5777 
Operation saved in /tmp/scans/scan.h5 (HDF5::NXscan)
Scan #12 ended at Wed Jun 26 12:27:31 2019, taking 0:00:07.732456. Dead time 85.8% (motion dead time 77.8%)

Door_demo2_1 [12]: showscan
Cannot plot scan:
It only works with HDF5 files.
```
And the `sardanaeditor` still doesn't work with Spyder 3 (tested with 3.3.3).

**Comment by reszelaz** [comment]
Thanks for the tests @amilan and @daneos !

Regarding the testsuite problems reported by @amilan: could you please run these tests manually? Do they also fail there?
What you report is strange since the testsuite works correctly on Travis-CI (Debian 9) and also @daneos reports that it works for him in Centos 7.

And regarding the `showscan`, @daneos could you please debug this code:
https://github.com/sardana-org/sardana/blob/4b24003ebbb7ecedaaefb2b857b81330bfcd755c/src/sardana/spock/spockms.py#L89
From your output it looks like you are using the H5 recorder but it somehow fails to recognize the file as HDF5 file.

**Comment by daneos** [comment]
After restarting the VMs showscan is able to open the file, it was probably a problem with NFS connection or so. Now I observe the same behaviour as @amilan.

**Comment by amilan** [comment]
Hi again,

On Friday I repeated the sardanatestsuite and I saw that my main issue was that some of the temporal elements that the test suite creates were not removed, probably due to some unexpected error in a previous execution of the test suite.
I just cleaned the tango database manually and then the test passes without errors.

Regarding the showscan issue, I didn't have time to investigate it, but for me it's OK if we open an issue for it and continue with the release.

What do you think @teresanunez, @daneos and @reszelaz?

**Comment by teresanunez** [comment]
Hi, for me it is also fine if we continue with the release and create an issue for showscan.

**Comment by amilan** [comment]
As agreed in #1150, we can considered this tests done and new issues will be opened for Showscan.

**Comment by reszelaz** [comment]
> Regarding the showscan issue, I didn't have time to investigate it, but for me it's OK if we open an issue for it and continue with the release.

Isn't it this one: #910?
