### ISSUE TITLE
Jul19 manual release tests: openSuse 11.1

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana#1156]
This issue is created for reporting the results of the manual tests for Jul18 release on debian-stretch.
Tested on openSuse 11.1.

### Installation
- [x] Install Sardana (on Linux from the tar.gz : `pip install <tarball_artifact_URL>`
  and on Windows from MSI)
  **Note:** On openSuse 11.1 there are problems with pip, try `python setup
  .py install`

### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
**Note**: Must remove lxml >=2.1 dependency
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `PyTango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
- [x] In spock run `sar_demo` macro.
**Note**. Must rename the module demo.py to demo_macros.py
- [x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
**Note**: Must be change on server and client side openSuse 11.1 and 12.1
- [ ] Run testsuite. In another console do `sardanatestsuite`
  **Note:** On openSuse 11.1 and Windows there are known problems with 
  testsuite. Check previous release comments. 
  **Does not work**: Test must be run on openSuse121. It happened the same error with demo module and report macro. And the bug of unsubscripted https://sourceforge.net/p/tango-cs/bugs/659/

### Test Sardana using Spock and expconf
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
  **Note**: On Windows there are known bugs. 
- [x] Execute `umvr` macro and verify that the position updates arrives.
- [x] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
- [x] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [x] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
- [x] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
- [x] Open online plot (This should ask to enable JsonRecorder, set it to true. Otherwise enable it in spock: `senv JsonRecorder True`).
- [x] Run step scan
- [x] Verify that records appear in spock output.
**Note**: I should change the h5 to use: NXscan_FileRecorder
- [x] Verify that records were stored in scan files.
- [x] Verify that records were plotted on the online plot
- [x] Run `showscan` and access to the last scan data.
- [x] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied.
- [x] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows

### Test Sardana with TaurusGUI

- [x] Create the GUI using this [guide](https://sourceforge.net/p/sardana/wiki/Howto-GUI_creation)

#### PMTV (PoolMotorTaurusValue)
- [x] Move motors from the slit panel in absolute and relative modes.
- [x] Show expert view.
- [x] Show compact mode.

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [x] Start new sequence
**Note**: The button does not work
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### sardanaeditor
**Note**: There is not spyder3 for OpenSuse11.1
**Note:** There are known bugs on CentOS and Windows
- [ ] Open sardanaeditor with macroserver name as argument.
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by rhomspuron** [comment]
Sometimes the tests fail with a segmentation fault:
```
Testing lsm with macro_runs() ... ok
test_lsm_macro_runs_2 (sardana.macroserver.macros.test.test_list.LsmTest)
Testing lsm with macro_runs(macro_params=['l.*']) ... ok
test_lsmac_macro_runs (sardana.macroserver.macros.test.test_list.LsmacTest)
Testing lsmac with macro_runs(macro_params=['w.*']) ... ok
test_lsmac_macro_runs_2 (sardana.macroserver.macros.test.test_list.LsmacTest)
Testing lsmac with macro_runs() ... TimerLoop 1    ERROR    2019-06-27 10:27:47,088 TaurusPollingTimer[3000]: poll_reply error
TimerLoop 1    ERROR    2019-06-27 10:27:47,320 TaurusPollingTimer[3000]: poll_reply error
TimerLoop 1    ERROR    2019-06-27 10:27:47,325 TaurusPollingTimer[3000]: poll_reply error
FAIL
Segmentation fault

```

**Comment by rhomspuron** [comment]
The error happens more frequently: 
```
Testing lsctrl with macro_runs() ... ok
test_lsctrllib_macro_runs (sardana.macroserver.macros.test.test_list.LsctrllibTest)
Testing lsctrllib with macro_runs(macro_params=['Dummy.*']) ... ok
test_lsctrllib_macro_runs_2 (sardana.macroserver.macros.test.test_list.LsctrllibTest)
Testing lsctrllib with macro_runs() ... ok
test_lsdef_macro_runs (sardana.macroserver.macros.test.test_list.LsdefTest)
Testing lsdef with macro_runs(macro_params=['w.*']) ... ok
test_lsdef_macro_runs_2 (sardana.macroserver.macros.test.test_list.LsdefTest)
Testing lsdef with macro_runs() ... FAIL
Segmentation fault

```

**Comment by rhomspuron** [comment]
Add snapshot do not activate the button apply on expconf. If we do more change: change filename and add snapshot, after to applied them, the expconf shows a pop-up with external changes, the snapshot value was not applied.

**Comment by rhomspuron** [comment]
Expconf snapshot but solved on taurus last commit

**Comment by reszelaz** [comment]
> Expconf snapshot bug solved on taurus last commit

Good to hear that!

Thanks for all the tests @rhomspuron !

Regarding the seg faults when executing testsuite, you must be hitting this [Pytango 7 bug](https://sourceforge.net/p/tango-cs/bugs/659/). We already observed that in some previous releases.

With all this IMHO the openSuse tests gets "checked".
