### ISSUE TITLE
Jul19 manual release tests: Win10

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana#1157]
This is an issue for checking the Jul19 release in Windows 10

### Installation
- [x] Install Sardana (on Linux from the tar.gz : `pip install <tarball_artifact_URL>`
  and on Windows from MSI)
  **Note:** On openSuse 11.1 there are problems with pip, try `python setup
  .py install`
  **Comment:** When installing with MSI I had to manually specify where Python is, otherwise it the installer was not able to find it. IIRC this was not necessary before.

### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `PyTango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
  **- Problem1: traceback appearing when creating new spock profile:**
  The same as traceback from the last release tests: 
  https://gist.github.com/mrosanes/e8473156e350ba2d2425a089d0d19f15
  **Bug also existed in previous releases:** https://github.com/sardana-org/sardana/issues/536
  **- Problem2: Traceback related to matplotlib and PyQt5 (even if PyQt5 is not installed)**
  The same as traceback from the last release tests: 
  https://gist.github.com/mrosanes/e87b970edb6b6fac23384477a7773d24
  **Similar bug existed in previous releases:** https://github.com/sardana-org/sardana/issues/536
**- Problem3: cannot exit spock doing 'exit()', even if after I use 'Ctrl+C'**
- [x] In spock run `sar_demo` macro.
- [x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [x] Run testsuite. In another console do `sardanatestsuite`
  **Note:** On openSuse 11.1 and Windows there are known problems with 
  testsuite. Check previous release comments.
  **Comment:** 
  ```
  ----------------------------------------------------------------------
  Ran 251 tests in 1332.891s

  FAILED (failures=4, errors=6, skipped=8, expected failures=1)
  ```  
  However all, but one test
  (sardana.macroserver.test.test_msrecordermanager.RecorderManagerTest.test_getRecorderPath_3), 
  which was already known, work when executed manually - see [output](https://gist.github.com/reszelaz/d4e0a708756ad4fbacd3cc8489facaeb).
  This kind of behavior was already observed in the previous releases. Sometimes the tests fail on 
  Windows when executed within testsuite.
### Test Sardana using Spock and expconf
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
  **Comment:** There are just a couple RuntimeWarnings printed about a difference between the stdin 
  and stdout encodings.
- [ ] Execute `umvr` macro and verify that the position updates arrives.
  **Bug:** Fix spock's output block on windows #1160
- [x] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
- [x] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [x] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
- [x] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
- [x] Open online plot (This should ask to enable JsonRecorder, set it to true. Otherwise enable it in spock: `senv JsonRecorder True`).
- [x] Run step scan
- [x] Verify that records appear in spock output.
- [x] Verify that records were stored in scan files.
- [x] Verify that records were plotted on the online plot
- [ ] Run `showscan` and access to the last scan data.
  No PyMCA for 32 bits: `ImportError: No module named PyMca5.PyMcaGui.io.hdf5`
- [x] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied.
  **Comment:** RuntimeWarnings are printed about a difference between the stdin and stdout 
  encodings.
- [x] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows

### Test Sardana with TaurusGUI

- [x] Create the GUI using this [guide](https://sourceforge.net/p/sardana/wiki/Howto-GUI_creation)

#### PMTV (PoolMotorTaurusValue)
- [x] Move motors from the slit panel in absolute and relative modes.
- [x] Show expert view.
- [x] Show compact mode.

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [x] Start new sequence
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### sardanaeditor
**Note:** There are known bugs on CentOS and Windows
**Bug:** Can not be tested due to: "Sardanaeditor does not work with latest spyder" #909
- [ ] Open sardanaeditor with macroserver name as argument.
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by reszelaz** [comment]
The test results are very similar to the ones from the previous release: #1058.
