### ISSUE TITLE
Install Sardana on Raspi

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1163]
Hej,

does anyone has experience with installing Sardana on a Raspi with Rasperian?
We currently have Tango running on some Pis without any Problems.
I was just wondering if I could run spock as well in order to connect to the according Door as a rather cheap and locally flexible client.

Best

Daniel

**Comment by cpascual** [comment]
I've run tango + taurus guis on a raspbian (stretch) without problems. 
I am not sure if I also tested sardana though... but I see no reason for it to 
be an issue.

**Comment by dschick** [comment]
works like charme!
Looking forward to the #1109 features and hopefully python3sardana will run on the raspi as well with all its dependencies.
