### ISSUE TITLE
Update when environment variable has changed

### ISSUE THREAD

**Issue by stanislaw55** [sardana-org/sardana#1165]
Hi,
is there any notification fired (event or anything else) in case of Sardana environment variable change? For example in QDoor device or in some ExpConf?

**Comment by reszelaz** [comment]
There is a Tango change event on the Environment attribute of the MacroServer.
I think there should be environmentChange Qt signal on both QDoor and QMacroServer.
Also the expconf widget reacts on some environment variables changes e.g. ActiveMntGrp, ScanFile, ScanDir, etc.

**Comment by stanislaw55** [comment]
Thanks for rapid reply!
I have some problems with connecting slot to this signal but will definitely test it.

**Comment by stanislaw55** [comment]
Hi @reszelaz 
Looking at code, it seems that QMacroServer can emit `environmentChanged` signal, but QDoor cannot since it does not execute `environmentChanged.emit` anywhere in its code. However, I'm not 100% sure about that. Could you confirm?

**Comment by reszelaz** [comment]
Sorry for the late reply!

I quickly reviewed the code and I also can´t see that we emit this signal. It could be some unfinished implementation. 
We are currently migrating Sardana to Py3, I would prefer to come back to this issue when the Py3 work is done. Can you wait? Meanwhile can you use the MacroServer signal? I think that `QDoor` should have some easy access to the macroserver, maybe `QDoor.macro_server` property or something like that?

**Comment by stanislaw55** [comment]
Hi @reszelaz 
Yes, no need to rush, I just used `evironmentChanged` signal from`QMacroServer` (which is available as `macro_serever` in `QDoor` as you said). However, it would be nice to emit this signal anyway

**Comment by reszelaz** [comment]
I propose to close this one, since as @stanislaw55 confirms it is possible to connect to this signal with the reference to the macro_server:
```
door = taurus.Device(<door_name>)
door.macro_server.environmentChanged.connect(slot)
```
