### ISSUE TITLE
Automatic release to PyPI does not work

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1166]
The automatic release to PyPI introduced in #1113 does not work correclty.
It only uploads the egg file and not the source distribution.

According to the [documentation](https://docs.travis-ci.com/user/deployment/pypi/#uploading-different-distributions) it should by default also upload the source distribution.

Not sure if the source distribution does not need to be created in the script part, like for example in [PAScual](https://github.com/cpascual/PAScual/blob/master/.travis.yml) project.

In the investigation we could run a test with a PR which modifies the `.travis.yml` (remove the condition) and upload to PyPI to see if it works.

**Comment by cpascual** [comment]
I fixed a similar issue in Taurus. See:
https://github.com/taurus-org/taurus/pull/990/commits/45e5e90363fda19b06e483588e2c2b576f236df8

In the case of sardana, the call to sdist can probably be done from from the host itself (for example in the "doc" environment)

**Comment by reszelaz** [comment]
Fixed by #1408
