### ISSUE TITLE
Py3: manual tests on Debian 9

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1175]
This issue is for running manual tests of #1173 on Debian 9. While testing I will try to extend the manual test scenarios.

### Installation
- [x] Install Sardana (on Linux from the tar.gz : `pip install <tarball_artifact_URL>`
  and on Windows from MSI)

### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `PyTango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
- [x] In spock run `sar_demo` macro.
- [x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [x] Run testsuite. In another console do `sardanatestsuite`

### Test Sardana using Spock and expconf
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
- [x] Execute `umvr` macro and verify that the position updates arrives.
- [x] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
- [ ] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [x] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
~BUG: Drag and drop does not work. One needs to input the attributes manually (remember to use complete URIs)~
- [x] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
~BUG: Pop-up with the following changes is raised and should not be - #1176 (already present in develop)~
- [ ] Open online plot (This should ask to enable JsonRecorder, set it to true. Otherwise enable it in spock: `senv JsonRecorder True`).
- [x] Run step scan
- [x] Verify that records appear in spock output.
- [x] Verify that records were stored in scan files.
- [ ] Verify that records were plotted on the online plot
- [ ] Run `showscan` and access to the last scan data.
**BUG**: most probably due to bug (bytes-string conversion) in PyMCA. Present in PyMCA 5.1.3 but according to @cmft not in PyMCA 5.5. See [exception](https://gist.github.com/reszelaz/de7cd7e80e07edd0df854462866e10d2)
- [x] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied.
~BUG: edmac does not appear due to lack of bytes-string conversion~

- [x] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.

### Test Sardana with TaurusGUI

- [x] Create the GUI using this [guide](https://sourceforge.net/p/sardana/wiki/Howto-GUI_creation)
  * Pool name will be: `Pool_demo2_1`
  * Your element names may be different (depending on free aliases in your Tango database)

#### PMTV (PoolMotorTaurusValue)
- [x] Move motors from the slit panel in absolute and relative modes.
- [x] Show expert view.
- [x] Show compact mode.

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [x] Start new sequence
  **Note:** new sequences cannot always be created #305
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### sardanaeditor
**Note:** There are known bugs on CentOS and Windows
- [x] Open sardanaeditor with macroserver name as argument.
- [x] Browse macro libraries and open an existing macro.
- [x] Edit existing macro and save & apply chaneges.
- [x] Execute macro to see if changes were aplied.
- [x] Create a new macro using template.
- [x] Execute the newly created macro.

#### MacroButton

- [x] Start macrobutton:
     ```console
     python3 -m sardana.taurus.qt.qtgui.extra_macroexecutor.macrobutton door_demo2_1
     ```
- [x] Execute `lsmac` macro with default parameter value for filter (`.*`).
- [x] Execute `ascanct` macro.
- [x] Execute `ascan` macro and stop it with the macrobutton (after prior pausing and confirming stopping in the pop-up).

**Comment by cmft** [comment]
>  **BUG:** Drag and drop does not work. One needs to input the attributes manually (remember to use complete URIs)

Fixed

**Comment by cmft** [comment]
> With edmac modify existing macro: ask_peak and run it to verify that the change
> was applied.
> ...
> TypeError: a bytes-like object is required, not 'str'

Fixed

**Comment by reszelaz** [comment]
The manual tests on Debian 9 are done now. Few issues were discovered and were already fixed by @cmft, thanks!

I have also extended the manual test guide with some tests of MacroButton.

There are the following known issues:
1. online plot does not work - Qwt5 is not ported to python 3
2. `showscan` does not work with PyMCA 5.1.3 (default package on Debian 9), one needs to install PyMCA 5.5.
3. In order to make the MacroServer environment work properly I was forced to use the `gdbm` backend of shelve instead of the `ndbm`. This requires installation of `python3-gdbm` package.

IMO the tests are satisfactory.
