### ISSUE TITLE
sardana-scada domain still points to RTD 

### ISSUE THREAD

**Issue by cpascual** [sardana-org/sardana#1183]
The official http://sardana-controls.org correctly points to the travis-generated docs (hosted in gh pages), but the secondary domain http://sardana-scada.org is still pointing to the readthedocs outdated pages.

This can create confusion if someone accidentally lands in the -scada page.

IMHO, the -scada domain should point to the -controls one (or just be removed)

**Comment by reszelaz** [comment]
Fixed. Both domains now point to github pages.
