### ISSUE TITLE
Motor widget expert view issue in SetOn/SetOff

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#1194]
In BL09 Beamline controls GUI ctbl09, we have observed an issue with the expert view of a motor widget. It is not clear to me if this problem comes from Sardana or from Taurus.

In some BL09 panels of the GUI ctbl09 (eg: M4 panel, XS panel), the motors associated with M4 and XS were ON, but the expert view was showing **SetOn** (as if the motors were Off, which was not the case). Tried to touch the button to see if the icepap motors associated with M4 and XS could be turned ON/OFF from this SetOn/SetOff expert view button, but it did not work.

We kind of solved temporarily this problem by restarting the GUI ctbl09... but something was not working till the restart of the GUI.

**Comment by reszelaz** [comment]
Hi @gjover,
Could you tell me if this isssue is still happening in ctbl09?
Thanks!

**Comment by HEnquist** [comment]
This is probably obsolete and can't be reliably reproduced. Please reopen if more information becomes available.
