### ISSUE TITLE
Sardana 2.8.1 not installable

### ISSUE THREAD

**Issue by stanislaw55** [sardana-org/sardana#1204]
Hello Sardana community,
Sardana version 2.8.1 is not installable from `pip`.
When searching, pip shows version 2.8.1, but when trying to install, it installs version 2.8.0.
Maybe it is caused by package format (2.8.1 - egg, 2.8.0 - wheel and tar.gz)

Apart from that, versions 2.8.2 and 2.8.3 are not present in pip at all. However, I do not know if it was intended or not.

**Comment by reszelaz** [comment]
Thanks @stanislaw55 for pointing this out!
2.8.1 was not correctly uploaded since we suffer #1166. I tried to fix it in #1189 and failed. I decided to postpone the fix it until the next official release (Jan20).
Meanwhile I uploaded the 2.8.1 and 2.8.3 manually.
Sorry about the inconveniences!
