### ISSUE TITLE
Update of elements in instrument (SF#218)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#122]
Hi,
       I create a ticket for this bug adding the information from my first mail about this subject and the answer from Zibi:

--> Mail reporting:

   I was trying to work with the Instruments from the Pool
   and what I have observed is that if I define an element as
   belonging to one Instrument the Pool only realizes that this
   element belongs to the Instrument if I stop the Pool and
   start it again. Before stoping it the behaviours that one
   would expect from an element of one Instrument like:

   -> if the element is in the active measurement group when I save
   the scan data in a nexus file the data from this element has a
   link with a path given by the Instrument name, or

   -> when I  display the data from this element in a Taurus
   GUI the whole Instrument would be displayed

   are not there. One has to Stop the Pool after assotiating
   the Element to the Instrument, and then after starting again
   everything works as expected.
   Have you also observed that?. I would say that this is
   a bug, and the restarting of the Pool should not be
   necessary.

--> Zibi checks:
   I had a quick look into this topic, and it looks that you found a bug.
   I have just checked the first part of your problem - the link in the 
   nexus file.
   I made it working without the need to restart the Pool, however it only
   works for the new measurement groups, or for channels added to the
   existing measurement groups.
   For the already existing measurement groups one needs to restart the Pool.
   Rewriting of their configuration ("Apply" button in the expconf) does
   not help.
   As a workaround one could remove the channel from the MG and add it again)
   Soon I will also check it for the panels in the GUI

                         Regards,
                                      Teresa

Reported by: teresanunez ( http://sf.net/u/tere29 )

Original Ticket: [sardana/tickets/218](https://sourceforge.net/p/sardana/tickets/218)

**Comment by reszelaz** [comment]
As stated in https://github.com/sardana-org/sardana/pull/612#issuecomment-332769467 this issue should be fixed now.
