### ISSUE TITLE
auto match measurement groups for soft- and hardware triggers

### ISSUE THREAD

**Issue by kklmn** [sardana-org/sardana#1224]
Hello,

In our usual beamline operation, we need both step- and fly scans, correspondingly with soft- and hardware triggers. To do so, we have to frequently switch measurement groups. This is always manual, not well understandable by users and often forgotten. The measurement groups differ only by the Synchronizer column. 

How can it be automatized? Can `ascanct` be forced to override this column value from `Software` to a specific hardware trigger?

Thank you in advance!

**Comment by reszelaz** [comment]
Many thanks Konstantin for raising this issue. I think this is a very common use case.

One possibility would be to try to use the [General Hooks](https://sardana-controls.org/users/macro_hooks.html#general-hooks) for that. I have made a simple example of a macro which would do what you need. Note that this macro can be more sophisticated, for example, change the synchronizer only on certain controllers:

```python
import copy

from sardana.macroserver.macro import Macro, Type

class set_synchronizer(Macro):
    """This macro demonstrates how to set synchronizer for all controllers
    present in the active measurement group.

    Measurement Group on which it applies can be limited by meas_grps
    repeat parameters.
    """

    param_def = [
        ["synchronizer", Type.String, None, "Synchronizer to be set"],
        ["meas_grps",[["meas_grp", Type.MeasurementGroup, None, "Measurement Group"], {"min":0}],
         None, "Measurement Groups on which apply the synchronizer"],
    ]

    def run(self, synchronizer, meas_grps):
        if self.getParentMacro().name != "a1scanct":
            return
        active_mnt_grp = self.getEnv("ActiveMntGrp")
        if len(meas_grps) > 0:
            meas_grps_names = [meas_grp.name for meas_grp in meas_grps]
            if active_mnt_grp not in meas_grps_names:
                return
        meas_grp = self.getMeasurementGroup(active_mnt_grp)
        conf = copy.deepcopy(meas_grp.getConfiguration().raw_data)
        for _, ctrl in conf["controllers"].items():
            ctrl["synchronizer"] = synchronizer
        meas_grp.setConfiguration(conf)
```

Then we just need to set it as a general hook for `pre-scan` and `post-scan` hook places:

```
Door_zreszela_1 [62]: defgh "set_synchronizer software" post-scan
Defining general hook
set_synchronizer software

Door_zreszela_1 [63]: defgh "set_synchronizer tg01" pre-scan
Defining general hook
set_synchronizer tg01

Door_zreszela_1 [64]: lsgh
   Hook place                     Hook(s)
 ------------ ---------------------------
     pre-scan       set_synchronizer tg01
    post-scan   set_synchronizer software
```

On the other hand some of ALBA beamlines have a dedicated macros for executing experiments, these internally call the `ascanct`, and in some cases also set a specific measurement group.

**Comment by kklmn** [comment]
Hi Zibi,
We've just implemented and it works! Now our operation will be much more user-friendly!
Thanks a lot!

**Comment by reszelaz** [comment]
That's great!
Hopefully soon we will integrate #867 so you could use a nice API to change configuration of measurement groups. Then instead of programming:

```python
conf = copy.deepcopy(meas_grp.getConfiguration().raw_data)
for _, ctrl in conf["controllers"].items():
    ctrl["synchronizer"] = synchronizer
meas_grp.setConfiguration(conf)
```

you would just need to:

```python
mnt_grp.set_synchronizer(synchronizer)
```

Also I think it has some sense to set _General Hooks_ for specific macros, then you won't need to check the parent macro at the beginning:

```python
if self.getParentMacro().name != "a1scanct":
    return
```
And BTW I don't like the fact that the single motor scan macros are called: `a1scanct` or `a1scan`.

**Comment by kklmn** [comment]
Hi Zibi,

What is the expected behavior of the hook when the scan is aborted? I guess the post-scan hook does not run then.
I would always make the post-scan set the software synchronizer. Can I get it?

**Comment by reszelaz** [comment]
Currently the post-scan hooks are not executed when the macro was stopped or aborted by the user.
I do not have a very strong opinion about it but I'm rather in favor of executing them. This is because:
* there may be scans programmed with an infinite generator where the user is supposed to stop them. Ideally our `timescan` should allow this use case - https://github.com/sardana-org/sardana/issues/555.
* the hook itself can implement a conditional behavior based on the parent macro state (whether the parent macro was stopped or aborted).

What is the opinion of others?

**Comment by teresanunez** [comment]
I have nothing against and I would prefer if it would be possible to set the conditional behaviour. The point to have into account is that they are macros, and macros can not be executed after ctrl-C and they could call macros inside arising the same problem (but well, solving the first one would solve the second).
 We have at DESY a general on-stop function that is called when a scan is aborted, but it is not 'standard' Sardana up to now and in any case it would imply that one should implement what is in the post-scan hook also there.

**Comment by reszelaz** [comment]
Yes, as Tereas says, the implementation won't be trivial:)

**Comment by kklmn** [comment]
**Note 1:**

We define the hooks like this:
````
defgh "set_synchronizer pandabox_tg" pre-scan 
defgh "set_synchronizer software" post-scan
````
where `set_synchronizer` macro is defined here: 
[1574092024-BalderSynchronizer.py.txt](https://github.com/sardana-org/sardana/files/4224769/1574092024-BalderSynchronizer.py.txt)

The post-scan hook is actually not needed, as the synchronizer will be re-defined by the next scan's pre-scan hook anyways. This is a kind of clean-up. In abortion, the post-scan hook will not be executed, and this is not critical at all.

**Note 2:**

The `defgh` commands must be executed in a terminal spock. The gui spock corrupts the string:

![image](https://user-images.githubusercontent.com/17322580/74828670-cd2b4000-530f-11ea-9c10-e3f3229ecb97.png)

**Comment by reszelaz** [comment]
Regardint Note 1.

I still don't get it how it works. You define a hook to set synchronizer in pre-scan to `pandabox_tg`. Then if you are not executing `aXscanct` macros you don't do anything. But if you are executing `aXscanct` then you effectivelly set the synchronizer configuration to `pandabox_tg` in the active measurement group. Who then sets it back to `software`? If one run `aXscanct` macro before and then wan'ts to run a step scan the synchronizer stays as `pandabox_tg` right?

Regarding Note 2.

I'm just creating a bug report for that.

**Comment by kklmn** [comment]
You're right, sorry, wrong version. Here is the correct one, it analyzes the scan type: with or without trailing 'ct', and sets the specified synchronizer or 'software', correspondingly.
[BalderSynchronizer.py.txt](https://github.com/sardana-org/sardana/files/4225219/BalderSynchronizer.py.txt)

**Comment by reszelaz** [comment]
Ok, now I get it. With this macro it should work also in the case of the scan abort. Simply bacause it always sets the correct synchronization. Thanks for this feedback!
