### ISSUE TITLE
dead links in docs

### ISSUE THREAD

**Issue by kklmn** [sardana-org/sardana#1228]
Hello,

I am interested in running sardana macros (scans) from a Qt widget.
"How to call procedures?" [here](https://sardana-controls.org/users/faq.html#how-to-call-procedures) probably answers this, just the links are dead. The "search docs" line doesn't help either.

Can you please point to an alive page? 
Thanks!

**Comment by reszelaz** [comment]
Konstantin, sorry about the poor state of the documentation. We recently made quite a lot of improvements in this aspect but as you have noticed there are still places with outdated information, like these broken links.

I have created a #1233 which adds some missing parts of the Taurus extensions to the API documentation and also fixes these broken links. Hope we will have it online soon.

Whenever it gets online you will probably notice that the majority of methods/classes miss docstings. So, whenever you miss some information just ask and we then we will add the docs gradually.

**Comment by reszelaz** [comment]
The new version of docs is already online.
