### ISSUE TITLE
device attribute listener doesn't listen in standalone applications

### ISSUE THREAD

**Issue by kklmn** [sardana-org/sardana#1230]
Hello,

Starting from one of the recent updates, after the summer, don't know of what, standalone GUI applications stopped receiving listener events from taurus attributes. Only if I embed them into a taurus gui, the listeners work. How can I bring the listeners back? This would be very convenient for test purposes, otherwise during development/testing I have to frequently restart the GUI, which wastes time.

An application example is attached.

Another strange difference between standalone and embedded cases:
- when standalone: door.runMacro requires a list,
- when embedded: door.runMacro requires a string.
It looks as if the door object (=taurus.Device('Balder/Door/01')) is different in these two cases.

[TuneDCM.txt](https://github.com/sardana-org/sardana/files/3835784/TuneDCM.txt)

Thank you in advance for commenting on it!

Currenly: sradana 2.8.1, taurus 4.5.1

**Comment by kklmn** [comment]
What I've found: if I instantiate TaurusApplication(), not QtGui.QApplication(), the standalone applications work as the embedded ones.
May be the taurus wrap was supposed to be a must, just I didn't have to use it before, now I do.

**Comment by kklmn** [comment]
This issue should have been posted to taurus.

**Comment by reszelaz** [comment]
Konstantin, I don't know if you were aware of the [Taurus extensions to Sardana devices](https://sardana-controls.org/devel/api/sardana/taurus/qt/qtcore/tango/sardana.html).

So, when you use `TaurusApplication` you get these enriched `taurus.Device` objects, but when you use `QApplication` you don't. This should explain the `door.runMacro` API differences. The standard `taurus.Device` just exposes the `RunMacro` Tango command which expects list of strings as argin. The _Taurus extension to Sardana devices_ `taurus.Device` object has an enriched method to execute macros, which in this case uses the same name `door.runMacro`. I think if you use `door.RunMacro` you will always refer to the Tango command.

I still don't understand well your problem. What do you mean that your GUI stopped receiving listener events?
Does it happen from the application start moment, or it happens at some random moment at runtime?

**Comment by kklmn** [comment]
Thank you Zibi for the explanation! This is what I suspected that now TaurusApplication does something additional.
And the problem was (not anymore if with TaurusApplication) that the listener events did not come to the listener, right from the start.

**Comment by reszelaz** [comment]
> And the problem was (not anymore if with TaurusApplication) that the listener events did not come to the listener, right from the start.

Ok, now after taking a look on your application and correlating it with the fact that you have upgraded some software it starts to ring a bell... Could you try to keep the reference to the door's state attribute?:

```python
def __init__(self, isTest=False):
        QtCore.QObject.__init__(self)
        self.door = taurus.Device('Balder/Door/01')
        self.dp = taurus.Attribute('Balder/Door/01/State')
        self.dp.addListener(self.listener)
```

Recently Taurus had improved a lot cleanup of its internals. And it is highly probable that this attribute was simple garbage collected and that's why you were not receiving events. So, please go back to your initial version (I think that before you was just using the `QApplication`) and try it with the above suggestion?

**Comment by kklmn** [comment]
I've just tried it (with `self.`), same behavior.

**Comment by cmft** [comment]
Hi @kklmn ,
It is not the TaurusApplication in fact, as Zibi said is the sardana extencion (although taurus GUI activate the sardana extencion when you use sardana widgets). You can use this extension in your application.

**Comment by reszelaz** [comment]
Hi Konstantin,

I confirm your bug with the taurus & sardana versions that you use. However I'm not able to reproduce it with the latest develop branches of these both projects. @cmft will also try to reproduce it on a different PC with the latest develop branches. If this is no more reproducible, I would consider this bug as solved and propose you to upgrade your software.

Taking a look on your widget I think that [`MacroButton`](https://sardana-controls.org/users/taurus/macrobutton.html) widget and the [`QDoor`](https://sardana-controls.org/devel/api/sardana/taurus/qt/qtcore/tango/sardana/macroserver.html#sardana.taurus.qt.qtcore.tango.sardana.macroserver.QDoor) class (and expecially the [macroStatusUpdated] Qt signal) may be interesting to you. As you can see the documentation of the QDoor class is not really helping:) Just let us know if you have doubts and we will gradually add info in the docs.
