### ISSUE TITLE
asyncio error on spock startup

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1250]
whenever I start spock with latest sardana develop I get the following error:

```
MainThread     ERROR    2019-12-10 15:56:34,922 asyncio: Task was destroyed but it is pending!
task: <Task pending coro=<History._start_loading() running at /home/labuser/.local/lib/python3.6/site-packages/prompt_toolkit/history.py:40>>
MainThread     ERROR    2019-12-10 15:56:34,923 asyncio: Task was destroyed but it is pending!
task: <Task pending coro=<History._start_loading() running at /home/labuser/.local/lib/python3.6/site-packages/prompt_toolkit/history.py:40>>
MainThread     ERROR    2019-12-10 15:56:34,923 asyncio: Task was destroyed but it is pending!
task: <Task pending coro=<History._start_loading() running at /home/labuser/.local/lib/python3.6/site-packages/prompt_toolkit/history.py:40>>
/home/labuser/.local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py:717: RuntimeWarning: coroutine 'History._start_loading' was never awaited
  return self.content.preferred_height(width, max_available_height)
/usr/lib/python3.6/asyncio/base_events.py:509: RuntimeWarning: coroutine 'History._start_loading' was never awaited
  self._ready.clear()
```

**Comment by reszelaz** [comment]
We have never seen this issue before. At ALBA we use Sardana with Python 3.5 (Debian 9). We have also made some extensive tests with Python 3.7 (Debian 10). I see that you use Python 3.6, which distro is it? How do you install the whole stack?
Meanwhile, have you also tried with a different versionso fo the prompt_toolkit? The erros seems to come from there?

**Comment by dschick** [comment]
I am using Linux Mint 19.2 which is based on Ubuntu bionic.
Python 3.6 is the default python3 distro.
I installed the whole stack via pip3 into my user directory.

prompt_toolkit has version 3.0.0 which is still beta.

downgrading to prompt_toolkit 2.0.10 solves the error messages
upgrading to prompt_toolkit 3.0.2 solves the issue as well

I guess I can close this issue, since it seems to be related to prompt_toolkit

**Comment by reszelaz** [comment]
Thanks for this investigation! I think it is fine to close this issue. We won't do anything to fix it here then.
