### ISSUE TITLE
advertise newfile macro when no datafile is set

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1254]
when there is no datafile configured, spocks prints:

`ScanDir is not defined. This operation will not be stored persistently. Use Use "expconf" (or "senv ScanDir <abs directory>") to enable it`

I guess, this should also state the `newfile` macro as an alternative to `senv ScanDir`

**Comment by reszelaz** [comment]
I agree, would you be so kind to make a PR, please?

A question to all, what do you think about the following message:
`ScanDir is not defined. This operation will not be stored persistently. Use "expconf" or "newfile" to configure data storage (or eventually "senv ScanDir <abs directory>")`

**Comment by dschick** [comment]
I can try to handle that in the next days.
I am fine with your suggestion
