### ISSUE TITLE
remove storage configuration in expconf does not undefine env variables

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1259]
When one remove strogate configuration in expconf (leave empty text fields for File name(s) or Path in the Storage tab) then the environment variables stays configured:
```
Door_zreszela_1 [8]: lsenv
                  Name                                                          Value   Type
 --------------------- -------------------------------------------------------------- ------
               ScanDir                                                                   str
              ScanFile                                                           ['']   list
```

This prevents to print the warning/hint message as described in #1254.
There are two options:
* unset environment variables from expconf
* improve gscan to consider these values as unset

The second one seems to be more robust (also for cases when someone configured it like this from other macros.

**Comment by teresanunez** [comment]
Hi @reszelaz, I also think that the second option is more robust, the environment could be set to
empty values from other places different than expconf and in all cases the Warning about 'not
saved data' should be displayed. What I wonder is if in that cases it would be possible to put
in the Warning that they are set to empty values. To avoid people getting confuse if they see that
the variables are actually in the environment and they do not realize (or do so) that they are
empty.

**Comment by reszelaz** [comment]
Thanks for the feedback!
Let's then do it this way - improving the gscan.
On the other proposal I think it should be possible to add this information.
