### ISSUE TITLE
subfolders in PoolPath and MacroPath

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1261]
Following the discussion in https://github.com/sardana-org/sardana/pull/726 I was trying to add a Macro and Pool Path to my Door that each contain subfolders, which include the actual controller and macro files - let's say because I want to use git submodules.
If I did nothing wrong, then the subfolders are not accessible by Sardana, right?

Then there are two options: 

1. either add the functionallity to access subfolders of the Macro and Pool Path when adding a controller/macro lib.

2. add each subfolder as Pool/MacroPath to the door.

The later can be done programatically and I guess there should be no problem in having tens of Pool and Macro paths, right?

**Comment by reszelaz** [comment]
Hi @dschick,
Sorry for so long silence on this issue.

Here, I would not go for point 1. I think this won't be necessary when we finish [SEP19](https://github.com/sardana-org/sardana/pull/1328) (hopefully this year). With _setuptools entry points_, these will be the plugins distributions that will register into the Sardana, and it won't be necessary to define the `PoolPath` and `MacroPath` properties. We plan to keep the current plugin mechanism for backwards compatibility but I would not add features to it.

So, for the moment the recommendation is to use point 2. We are not aware on the limitation of the number of paths.

Hope this helps! I'll proceed to close this issue, feel free to re-open.
