### ISSUE TITLE
AddDevice of pseudo elements (pseudomotor and pseudocounter)

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1272]
This is a very old question (2016) comming from @jairomoldes, Jairo if you still remember, if would be nice if you could place here the whole context.

It looks like PseudoMotor does not support the "AddDevice" feature that other  controllers do (e.g. Motor, 0D). Is there any technical reason for this? If not, I think it would interesting to implement.

**Comment by jairomoldes** [comment]
I found a use case in BL29MaresSampleDetector. This is a specific pseudomotor for BL29 which could provide a number of pseudo motors which it would be useful not to define in advance (maybe user would not need all them). I solved the problem by forcing the controller to define a fixed number of pseudos (10 in this case) which mostly are not used.

The code of this controller can be found here:
https://sourceforge.net/p/sardana/controllers.git/ci/master/tree/python/pseudomotor/ALBA_BL29_BOREAS/BL29PseudoMotorCtrls.py

**Comment by reszelaz** [comment]
Thanks @jairomoldes! When working on #1273 I have check this. The AddDevice and DeleteDevice methods are called also for the pseudo elements. So, I'm closing this issue. The question of dynamic roles of pseudo elements is treated in https://github.com/sardana-org/sardana/issues/86.
