### ISSUE TITLE
Remote recoder

### ISSUE THREAD

**Issue by stanislaw55** [sardana-org/sardana#1274]
Hello Sardana community
First of all, I am not Sardana expert and my question may be obvious but I want to be sure.
I am aware of Sardana recorders feature which allow to save data from scans in various forms. IS there any already functioning recorder which allows sending this data to remote server? 

Use case: company has strong policy about not storing any data on application servers. Any data must be stored on special storage servers. Sardana will run on application server but its data must somehow appear on storage server.

Thanks

**Comment by cpascual** [comment]
Have you considered a remote FS?
Any of the file recorders combined with e.g. nfs, may be enough (that's how we use it at ALBA)

**Comment by stanislaw55** [comment]
Hi @cpascual 
Yes, I've considered that but wanted to now if there's some recorder which already sends data somewhere, without the need for NFS

**Comment by cpascual** [comment]
I see... 
AFAIK, the closest thing would be the  `JsonRecorder` for working with streams. Maybe you can implement something for whatever storage backend you have in mind inspired on that.

Disclaimer: I am also not an expert on existing recorders, so there may be something already done of which I am not aware.

**Comment by stanislaw55** [comment]
Thank you @cpascual, I will look into `JsonRecorder`

**Comment by reszelaz** [comment]
Hi, I think that MaxIV made some recorder to sent data to some remote service for storing the metadata, was it Apache Kafka? 
Maybe @julianofjm could comment here?

**Comment by aureocarneiro** [comment]
@reszelaz was Apache Kafka, we just made a prototype and it is not in production. Here, we save the data directly to the storage cluster. We mount the storage on the sardana server computer.

@stanislaw55 here is a very simple example:

```python

"""This is the macroserver Kafka Recorder"""

__all__ = ["KafkaRecorder"]

__docformat__ = 'restructuredtext'

from uuid import uuid4
import requests
from sardana.macroserver.scan.recorder import DataRecorder


class KafkaRecorder(DataRecorder):

    def _startRecordList(self, recordlist):
        """
        Method to start the record.

        :param recordlist: Set of Records
        :type recordlist: RecordList
        """
        pass

    def _writeRecord(self, record):
        """
        Method executed while recording.
        
        :param record: Set of values measured at the same time.
        :type: Record
        """
        pass

    def _endRecordList(self, recordlist):
        """
        Method to execute when finishing the record.

        :param recordlist: Set of Records
        :type recordlist: RecordList
        """
        ###env = recordlist.getEnviron()
        # In .h5 file this scan will be called entry{serialno}
        # This will be useful when there is many scans in one .h5 file
        kafkaurl = recordlist.getEnvironValue('kafkaurl')

        uuid = str(uuid4())
        serialno = recordlist.getEnvironValue('serialno')
        scandir = recordlist.getEnvironValue('ScanDir')
        scanfile = recordlist.getEnvironValue('ScanFile') # This might be a list
        measgroup = recordlist.getEnvironValue('ActiveMntGrp') # This should be a string
        starttime = recordlist.getEnvironValue('starttime').ctime()
        endtime = recordlist.getEnvironValue('endtime').ctime()

        beamline = 'anymax'
        proposal = '20180316'

        data = {'uuid': uuid,
                'beamline': beamline,
                'proposal': proposal,
                'serialno': serialno,
                'directory': scandir,
                'files': scanfile,
                'measurementgroup': measgroup,
                'starttime': starttime,
                'endtime': endtime
               }

        r = requests.post(kafkaurl, json=data)

        if r.status_code != 200:
            pass


```

**Comment by stanislaw55** [comment]
Hi @aureocarneiro 
Thanks for example! I was thinking about something similar but with `requests.Session` persistence during scan for sending each point in separate request. However, this is definitely easier to implement.

**Comment by cpascual** [comment]
Hi @aureocarneiro , I may be missing something... but as far as I understand it, this `KafkaRecorder` only stores metadata of the scan, not the actual data, right?

**Comment by 13bscsaamjad** [comment]
we have found that if you put multiple `ScanFile` and `ScanRecorder`, sardana passes uses them all sequentially. the catch is to have same number of `ScanFile` as `ScanRecorder`. we only tested with two though. embedding the example config.
```
senv ScanFile "['test1', 'test2']" 
senv ScanRecorder "['Scicatrecorder', 'H5Recorder']"
```

**Comment by reszelaz** [comment]
I think this question can be closed because here we can see an example of a remote recorder. Please re-open if there are still some doubts.
