### ISSUE TITLE
MacroServer environment upgrade

### ISSUE THREAD

**Issue by taurel** [sardana-org/sardana#1282]
At ESRF, we are using the MacroServer since several years with Python 2. We are now using python3 and Zibi gives us the advice to use the **upgrade_env.py** script to update our environment. This script assumes that the environment is contained within a single file.
This is not the case for us. We have 3 files (xxx.bak, xxx.dir and xxx.dat). The script is not able to
work in such a case. 
If we start a MacroServer with no environment defined (deleted EnvironmentDb tango device prop),
it creates a new one with again 3 files.
We are using python installed with miniconda3 (python 3.7.3) running on Debian 9 OS.

Cheers

**Comment by reszelaz** [comment]
@taurel many thanks for creating the issue. After migrating many Sardana systems at different sites, we have not seen this problem anywhere else. Always the environment was stored in one file. I imagine that your Python 2 by default was using the `dumb` shelve backend, at least in Python 3 it is generating three files - see https://github.com/sardana-org/sardana/pull/1514#issuecomment-796688074. I propose to close it as won't fix, cause you already migrated your system and AFAIK, no one else hit this problem.
