### ISSUE TITLE
showscan fails to refresh (SF#235)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#129]
A refresh action should be added to the TaurusNexusBrowser.

The showscan magic command launches a TaurusNeXusBrowser with the current scan file as its parameter.

Scans executed after showscan has been launched are stored in the h5 file (checked with an external viewer), but the nexus browser widget is not updated and there is no way to force a refresh. Even closing the widget and launching showscan again fails to refresh (maybe "closing" is just hiding the widget?)

At least a refresh action should be added to the Taurus Nexus browser

Reported by: cpascual ( http://sf.net/u/cpascual )

Original Ticket: [sardana/tickets/235](https://sourceforge.net/p/sardana/tickets/235)

**Comment by reszelaz** [comment]
Moved to Taurus:https://github.com/taurus-org/taurus/issues/429
