### ISSUE TITLE
memorize ctrl_attributes

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1297]
I have a ctrl_attributes of a pseudoCounterController which I would like to memorize.

```
ctrl_attributes = {
    "rois" : {
            Type         : (int,),
            Description  : "List of ROIs",
            Access : DataAccess.ReadWrite,
            DefaultValue : [0, -1, 0, -1],
            Memorized: Memorize,
        },
    }
```

However, this seems not to work as expected.

Daniel

**Comment by reszelaz** [comment]
Sorry for late answer. We had a busy shutdown week at ALBA.
I'm afraid it won't work for attr types different than scalars: https://tango-controls.readthedocs.io/en/latest/development/device-api/memorized-attribute.html
May by try scalar string with the repr of the list and then evaluate it in the ctrl code?

**Comment by dschick** [comment]
okay, I will try converting the list to a str and back and check if memorizing works.

Thanks

Daniel

**Comment by reszelaz** [comment]
Hi Daniel, please reopen if we could still help somehow.

**Comment by dschick** [comment]
yep, thanks. we are actually fine with the current situation.
