### ISSUE TITLE
Macro hooks question

### ISSUE THREAD

**Issue by cpt-majkel** [sardana-org/sardana#1304]
Hi,
I have a question about macro hooks. 
I am working on the mechanism of making scans dependent on beam quality. At the moment I was thinking about creating a pre-acq general hook that would check for a certain condition. I wonder what would be the best way to pause the scan depending on that condition (e.g flag from facade), and then resume it as it becomes true.

Michal

**Comment by teresanunez** [comment]
Hi Michal,
                    we have a implementation for that at DESY, using what we call the 'general condition'
feature', and at Alba they have also done something similar. There is a ticket about that. With the general hooks you can not get the same ... but perhaps you can live with that, it depends on
 what you exactly want.

                                   Regards,
                                                      Teresa

**Comment by cpt-majkel** [comment]
Hi Teresa,

Thanks for your fast reply!

I do not know, however, if I understood correctly, where can I find this ticket you mentioned?

**Comment by reszelaz** [comment]
> I wonder what would be the best way to pause the scan depending on that condition (e.g flag from facade), and then resume it as it becomes true.

For pausing and resuming I think that [hooks](https://sardana-controls.org/users/macro_hooks.html) would be enough.

Teresa refers to _general condition_ concept, but I think this is for repeating the scan points. More details on it in https://github.com/sardana-org/sardana/issues/201.

**Comment by cpt-majkel** [comment]
Ok, I will test hooks then. Is there any "Sardana" way to pause the macro and wait for the condition to change and then resume (i guess it means to stay in that hook for a certain time, but making loop is not the best idea)?

**Comment by reszelaz** [comment]
As you say I think you will just need to stay in the hook. Then it depends on what the condition is. ..

If for example you have a Tango attribute which will send you an event that the condition is ok to continue, then you just need to listen on that event. You could use some threading primitive e.g. `thrending.Event` and wait on it in the hook and in the event callback set it.

If your Tango attribute don't push events then someone (most probably your hook) would need to evaluate the condition periodically and continue when the condition is met.

Note that you may use Tango polling on the server to get events from attributes.

The thing would get complicated if your condition depends on multiple attributes...

You may also consider using Panic (PyAlarm) for evaluating alarms and assign actions to the alarms e.g. call PauseMacro command on the Door. But I think in this case you loose some control which you have when you use hooks. 

Hope I have clarified and not confused you more :)

**Comment by cpt-majkel** [comment]
Hi,
Thanks for the suggestions! Sorry for the delay in answering but due to the COVID-19 situation we had some urgent things to do and this task has gone down the line. 

Now I've returned to the topic from my home office. 

I've tried `threading.Event` as you described (waiting in the hook and setting from callback) but without any loop-kind solution in this thread, Sardana comes out of the hook and the functionality is not met (maybe I'm doing something wrong). 

I am currently testing an implementation based on periodic condition evaluation and this condition is set to true in callback (basically I'm waiting for Tango event). It looks like it works.

I wish you and your families to stay healthy!

**Comment by reszelaz** [comment]
Hi Michal,

Regarding using `threading.Event` you could try something like this:

```python
import threading
import functools
import tango
from sardana.macroserver.macro import macro

TIMEOUT = 60


@macro()
def are_you_ready(self):
    """Testing are_you_ready macro"""

    def cb(ready, event):
        if not event.err:
            state = event.attr_value.value
            if state == tango.DevState.RUNNING:
                ready.set()

    self.print("In are_you_ready")
    ready = threading.Event()
    dev = tango.DeviceProxy("sys/tg_test/1")
    cb = functools.partial(cb, ready)
    id_ = dev.subscribe_event("state", tango.EventType.CHANGE_EVENT, cb)
    self.print("Waiting for being ready...")
    ready.wait(TIMEOUT)
    self.print("We are ready, let's go!")
    dev.unsubscribe_event(id_)
```

To test it I set 3 s polling on `State` command of the `sys/tg_test/1` and then used `SwitchState` command of the same device to change the state from `RUNNING` to `FAULT`. Then I set it as pre-acq general hook and it worked for me.

Note, maybe even creating a `Macro` class would simplify it a little bit..
