### ISSUE TITLE
Remove deprecated features in Sardana 3

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1315]
Since we are approaching a major version number release we would like to remove some features deprecated long time ago.

This issue is to discuss if we all agree on it.

I have reviewed the whole code and found the following features marked as deprecated.
I think we can remove all of them since the deprecation period is very long.
The _data source_ deprecations (32-37) are maybe too early to be removed - only one release of deprecation warning. But if no one comments here I would remove them as well.

|Number | Deprecated | Deprecated since | Sugested substitute |
|---|---|---|---|
| 1 | sardana.release.version_info | 2.2.0 | sardana.release.version |
| 2 | sardana.release.revision | 2.2.0| sardana.release.version |
| 3 | sardana.release.revision | 2.2.0| sardana.release.version |
| 4 | ParamRepeat | 2011| param_def in lists |
| 5 | GSF generator yields hooks | 2011| GSF generator yields specific hooks e.g. post-acq-hooks|
| 6 | pre-start hook place in ascanct scans | 2018| pre-acq hook place in ascacnt scans|
| 7 | FileRecorder macro hints | Jan16 | ScanRecorder environment variable |
| 8 | Controller.class_prop | 1.0 | Controller.ctrl_properties |
| 9 | Controller.ctrl_extra_attributes | 1.0 | Controller.axis_attributes |
| 10 | Controller.inst_name | 1.0 | Controller.GetName |
| 11 | Controller.SetPar | 1.0 | Controller.SetAxisPar |
| 12 | Controller.GetPar | 1.0 | Controller.GetAxisPar |
| 13 | Controller.GetExtraAttributePar | 1.0 | Controller.GetAxisExtraPar |
| 14 | Controller.SetExtraAttributePar | 1.0 | Controller.SetAxisExtraPar |
| 15 | CounterTimerController._trigger_type | Jan17 (SEP6) | CounterTimerController._synchronizarion |
| 16 | CounterTimerController.PreStartAllCT | 1.0 | CounterTimerController.PreStartAll |
| 17 | CounterTimerController.PreStartOneCT | 1.0 | CounterTimerController.PreStartOne |
| 18 | CounterTimerController.StartAllCT | 1.0 | CounterTimerController.PreStartAll |
| 19 | CounterTimerController.PreStartOneCT | 1.0 | CounterTimerController.PreStartOne |
| 20 | PseudoMotorController.calc_all_pseudo | 1.0 | PseudoMotorController.CalcAllPseudo |
| 21 | PseudoMotorController.calc_all_physical | 1.0 | PseudoMotorController.CalcAllPhysical |
| 22 | PseudoMotorController.calc_pseudo | 1.0 | PseudoMotorController.CalcPseudo |
| 23 | PseudoMotorController.calc_physical | 1.0 | PseudoMotorController.CalcPhysical |
| 24 | PseudoCounterController.calc | 1.0 | PseudoCounterController.Calc |
| 25 | IORegisterController.predefined_values | 1.0 | IORegisterController.axis_attributes |
| 26 | *Timerable*Controller.PreLoadOne(value) | 2.3.0 | *Timerable*Controller.PreLoadOne(value, repetitions, latency) |
| 27 | *Timerable*Controller.LoadOne(value) | 2.3.0 | *Timerable*Controller.LoadOne(value, repetitions, latency) |
| 28 | MeasurementGroup.Configuration with non URI element/controller names | Jan19 | set configuration or recreate measurement group |
| 29 | MeasurementGroup.Configuration with trigger_type parameter | Jan18 | use synchronization parameter |
| 30 | MeasurementGroup.Start without prior Prepare | Jan18 | Prepare and then Start |
| 31 | Controller.ctrl_properties with "Descritpion" | Jul18 | Controller.ctrl_properties with sardana.pool.controller.Description |
| 32 | OneDController data_source axis par | Jul19 | Inherit from Referable class|
| 33 | TwoDController data_source axis par | Jul19 | Inherit from Referable class|
| 34 | OneDExpChannel DataSource attribute | Jul19 | ValueRef attribute |
| 35 | TwoDExpChannel DataSource attribute | Jul19 | ValueRef attribute |
| 36 | Pool1DExpChannel data_source property | Jul19 | value_ref property|
| 37 | Pool2DExpChannel data_source property | Jul19 | value_ref property|
| 38 | DiscretePseudMotor Label and Calibration axis attributes | 2.5.0 | Configuration axis attribute|
| 39 | sardana.spock.release module | Jul17 | sardana.release module |
| 40 | IPython < 1.0 genutils | 2.8.0 | Upgrade to IPython > 1.0 and Python 3 |
| 41 | Door Abort command | 2012 | Door StopMacro or AbortMacro command |
| 42 | Controller.getUsedAxis (taurus) | 2.5.0 | Controller.getUsedAxes |
| 43 | DoorAttrListener class (previously used in DoorOutput widgets)| 2.5.1 | QDoor |
| 44 | MacroButton.updateMacroArgumentFromSignal | 2014 |   |
| 45 | MacroButton.connectArgEditors | 2014 | pyqtSignal objects |
| 46 | MacroButton.toggleProgress | 2014 | MacroButton.showProgress |
| 47 | PoolMotorSlim widget | 2.5.0 | PoolMotorTaurusValue |
| 48 | *Timerable*Controller.PreLoadOne(value, repetitions) | 2.7.0 | *Timerable*Controller.PreLoadOne(value, repetitions, latency) |
| 49 | *Timerable*Controller.LoadOne(value, repetitions) | 2.7.0 | *Timerable*Controller.LoadOne(value, repetitions, latency) |

Please raise your hand if you really need them and can not move forward to the suggested substitutes.

**Comment by teresanunez** [comment]
Hi Zibi,
              we are actually using the data_source attribute in the 1D/2D controllers at DESY.
 I don't know how much work would be to change this for us, but well, in any case we are
 not going to change now to the last Release. We also use some other deprecated functions,
 we have to check and change that, we should have already done it.

                                          Regards,
                                                            Teresa

**Comment by reszelaz** [comment]
Hi Teresa,
Yes, I completely forgot that when discussing SEP2 you explicitly said that you use the _data source_.
I think to remove its usage you would need to:
* inherit your controller from `Referable` class
* implement in your controller `RefOne` method that would return the same as your data_source axis par readout
* use `ValueRef` Tango attribute wherever you used `DataSource` Tango attribute

But we can leave this still deprecated without removing it. The argument is that it is deprecated only since the last release.

**Comment by reszelaz** [comment]
Reminder:) @aureocarneiro, @teresanunez, @daneos for now we are only considering leaving the _data source_ deprecations (32-37). The rest are to be removed. Do you agree?

**Comment by teresanunez** [comment]
Hi Zibi, I agree, thanks

**Comment by reszelaz** [comment]
I just realized that in the initial discussion I forgot to include the `LoadOne(value, repetitions)` which were deprecated in version 2.7. I added them as points 48 and 49. Hope there are no inconeniences to remove these as proposed in #1370.

**Comment by reszelaz** [comment]
All the deprecated features were removed in the above mentioned PRs. The CI shows green now and I don't expect that these PRs will break anything. Since we agreed on removing them I would go for integrating them myself but @sardana-org/integrators feel free to review, comment, etc. Many thanks!

**Comment by reszelaz** [comment]
I'm proceeding with the merges.
