### ISSUE TITLE
Problem with Sardana server start

### ISSUE THREAD

**Issue by Val7** [sardana-org/sardana#1318]
![image](https://user-images.githubusercontent.com/20576174/78133835-d556bf00-7427-11ea-9e75-df8ba51ddea6.png)
![image](https://user-images.githubusercontent.com/20576174/78133886-e9022580-7427-11ea-9b62-034058e087f4.png)
Problem with starting Sardana server on Python 3.7.6 64 bit, Windows 10. It seems everything needed has been installed, but i cant run Sardana server.

**Comment by rhomspuron** [comment]
Hi @Val7, 

We created a conda package that is under testing from the develop branch. Maybe it can help you to see the environment created with all packages. Could you try to install it on a new environment?

> conda create -n test_sardana -c alba-controls -c tango-controls -c conda-forge sardana python=3

**Comment by reszelaz** [comment]
Hi,
From the packages that you list it looks like you have sardana 2.8.3 which is not Python3 compatible.
Only the develop branch is Python3 compatible. Currently are preparing an official release.
You may try what Roberto says in the previous comment or install it in conda environment using pip from the develop branch.
Cheers

**Comment by Val7** [comment]
Thanks for answers!
