### ISSUE TITLE
Scan start time taken too late

### ISSUE THREAD

**Issue by tiagocoutinho** [sardana-org/sardana#1321]
When a scan starts the following actions are done in sequence:

- construct GScan
  - _setupEnvironment()
    - prepare header (serialno, user, title, etc)
    - prepare columns
    - **takeSnapshot**
    - prepare directories (ScanDir & ScanFile)
- Gscan.scan()
  - start()
    - set header *start time*
    - scan loop
    - end

Take note that some actions, like takeSnapshot, may take some time. This not only because it is done sequentially but also because there might be some timeouts.

I would expect that it reflects the time when the scan macro was started. This is the first thing that appears in a scan header in a spec file for example so I would say it what the users would expect also.

But since the start time is taken only when the scan loop starts, it might be several seconds off the actual scan operation started.
(the method name `start()`  misleads us as it is intended to state the start of the scan loop and not the start of the scan)

Therefore, I propose that *start_time* be moved to the initial region when the serialno, user and title are set.

**Comment by HEnquist** [comment]
This leads to the question what the start_time in nexus means, the macro start or the scan start. I have sent a question on the nexus mailing list.
