### ISSUE TITLE
MacroButton and Running 2 Macros in parallel 

### ISSUE THREAD

**Issue by marouanebj** [sardana-org/sardana#1323]
Hi,
In my GUI I would like to use MacroButton but when I looked at the code I see:
```python
class MacroButton ...
    def stop(self):
        '''stop the macro.'''
        if self.door is None:
            return
        self.door.PauseMacro()
```
That suggest I can run only one macro at a time.
In my GUI I want to powerUp some generator that can take minutes, and so in the same time I want to adjust my sample positioning.
I think of 2 possibilities:
1/ I use Macros:
      I want to use 2 macros in parallel (maybe more in the future) but how can I do that ?
2/ I use QThread and no macro.

Extra question:
I like the idea of macros because 
I do not know how to do: ` moveable.move(prevPosition + nextMove)` In my GUI how to get the moveable.
Can you write me the code to get a Moveable from a `m = taurushelper.Device(motorModel)` please ?

Thanks for all the nice work.

**Comment by reszelaz** [comment]
Hi Marouane,

You can run multiple macros at the same time. You will need to define additional door devices for that. For the moment there is no user-friendly way to do so. I think the easiest would be to follow this https://github.com/sardana-org/sardana/issues/110#issuecomment-616172452.

The [Sardana-Taurus extension API]( https://sardana-controls.org/devel/api/sardana/taurus/core/tango/sardana.html#module-sardana.taurus.core.tango.sardana), the one that adds the `move` method and is enabled in the macros can be enabled in your application as well. But if you use Qt application you may be also interested in the [Sardana-Taurus Qt extension API](https://sardana-controls.org/devel/api/sardana/taurus/qt/qtcore/tango/sardana.html). BTW I think we need to add direct links to these APIs to [Developers Guide -> API](https://sardana-controls.org/devel/api/api_sardana.html) and some introduction also to [Users Guide -> Sardana-Taurus widgets](https://sardana-controls.org/users/taurus/index.html).

Hope this helps!

**Comment by reszelaz** [comment]
Hi Marouane,
I'm closing this one. Please re-open if you have more doubts on it.
Thanks!
