### ISSUE TITLE
energy motor

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1334]
Hi all,

we are just preparing another Sardana setup (total of 7 now) for a synchrotron experiment at PETRA III and I was wondering how we should implement the photon energy of the beamline as motor in Sardana?

We will be able to set the energy directly via a socket connection, so we do not have to take care of any synchronization of undulator and monochromator.

My question more related to diffractometer related issues.
As I know from `SPEC` the energy is no typical motor, as it also changes the wavelength and all calculations for the `hkl-macros`.

Are there any blueprint for the energy or should we just implement it as a normal motor?

Best

Daniel

**Comment by teresanunez** [comment]
Hi Daniel,
               the energy is moved as a motor in all Petra beamlines,
Also the diffractometer is moved as a motor.

                       Best Regards,
                                            Teresa

**Comment by dschick** [comment]
Thanks Teresa,

Okay, so nothing special to take care for - sounds good.
Is there a template available?
We need to use a `ComServer `as interface to the beamline and cannot access the TANGO attributes directly. I do not know if this server has a generic interface.

**Comment by teresanunez** [comment]
Hi Daniel,
                 our energy devices are simply integrated in sardana as motors, so there is no
template or anything need. But it depends of course on how you talk to your hardware. There
is where it has to be implemented in the right way.

                                  Regards,
                                                 Teresa

**Comment by dschick** [comment]
okay, thanks.

**Comment by jangarrevoet** [comment]
Hi Daniel,
Teresa is talking for the tango cases, which is the default. I assume you come to P04 or alike, where users bring their own instrument. There you use a secondary server, which you can also wrap in a tango server and let it act like a motor.
Greetings,
Jan

**Comment by teresanunez** [comment]
In any case, Daniel, we are always here to help. Just tell us when you are here or before
you come if you already know the details and we can take care of the integration and use
in sardana as a motor, no problem.

**Comment by dschick** [comment]
okay, the inital question was only related to Sardana - if one should meet any internal requriements for the energy.
Regarding the Tango/Beamline connection we will come back to you.
Many thanks in advance!

**Comment by reszelaz** [comment]
Hi Daniel and all,

> we are just preparing another Sardana setup (total of 7 now) for a synchrotron experiment at PETRA III and I was wondering how we should implement the photon energy of the beamline as motor in Sardana?

Great news that Sardana is helpful and you keep using it! Do you already run the Python 3 version from develop or you are on 2.8.*? 

Regarding the control of the BL energy we at ALBA use pseudo motors, which are usually based on the physical motor of the monochromator angle. Recently @gjover and @tiagocoutinho created a repo with a generic controller for the energy, we should add it to the plugin catalogue soon so you could take a look. But if you have a direct control over the energy of the BL, if its via Tango, then you could use a TangoAttrMotorController, and if not, then a normal motor controller will work for you.

I think what concerns you is the energy connection with the diffractomer control, then according to the [documentation](https://sardana-controls.org/users/diffractometer.html):
> The wavelength used for the diffractometer can be automatically updated setting the attribute AutoEnergyUpdate to 1 and the name of the Tango Device controlling the beam energy in the attribute EnergyDevice. The energy is read from the attribute Position of the EnergyDevice device, in eV, every time motor or pseudomotor positions are read.

In any case, you are in good hands, for sure Teresa - she is the diffractomerts expert, Jan and their colleagues will give you a great support on site.

Cheers!

**Comment by dschick** [comment]
@reszelaz thanks for this additional information!

> Great news that Sardana is helpful and you keep using it! Do you already run the Python 3 version from develop or you are on 2.8.*?

We are actually doing both. So with our first two setups we are staying with 2.8.* and Python2 for now. All new setups are directly using Python3 and Sardana >= 3.0

> I think what concerns you is the energy connection with the diffractomer control, then according to the documentation:

That was exactely what I was looking for :)

> In any case, you are in good hands, for sure Teresa - she is the diffractomerts expert, Jan and their colleagues will give you a great support on site.

Yes I know. We already received a great deal of support from DESY IT group for Sardana and Tango
