### ISSUE TITLE
Use Tango Events to read/update in MotorController

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1343]
I was wondering if it is possible to use events instead of polling in Sardana MotorControllers to update/read the position & state of a Motor?

In the current situation, we have a pyhsical motor controller, which is exposed as a TangoDS: https://github.com/dschick/pytango-PhytronMCC2

The Sardana MotorController simply reads the position and state of the according TangoDS and polls them accordingly:
https://github.com/dschick/sardana-MbiTangoMotorController

Best

Daniel

**Comment by reszelaz** [comment]
Hi Daniel,

This is not yet possible, but again it is a very interesting feature request. The notifcation of the position/state/... updates fom the plugin (controller) to the core (action) could be even considered as another capability similar to the ones we talk in #1344. However in this case the implementation would be more difficult (actions are quite complicated part of Sardana).

We quickly discussed it on the last follow-up meeting and found that the polling machanism from the action to the controller would still be needed in the cases whe underneeth Tango DS does not exist or the SDK does not support the notification callbacks.

If you still want to use events, as a workaround, you can subscribe to the events in the controller and in the `StateOne` and `ReadOne` return the cached in the event callback value.

Cheers,

**Comment by dschick** [comment]
thanks for the response.
I might try the workaround, but I close the issue for now.

Best

Daniel
