### ISSUE TITLE
fuzziness calculation could implement filter of the error types feature (SF#244)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#135]
fuzziness calculation could implement filter of the error types feature.

When looking for the number of times that a test shall be executed without fail, to have a certain probability (eg 99%) that the bug has been solved, it should be interesting that we can explicitly define which kind of exception/error we want to study in the fuzziness. If the error indicated in such a filter is detected, the given test will be failed (+1 failed for calculating the statistics of fuzziness); however if another error that is not the specified one is present the test will not count as failed for the statistics of the fuzziness. 

This will be really useful to study a given fail; (for instance it could be interesting to determine if we have solved a bug of a given timeout in the Sardana Stop command of the measurement group, without taking into account if there are timeouts in the Sardana Start command of the same measurement group: like  that we could focus in a certain kind of error).

Reported by: sagiss ( http://sf.net/u/mrosanes )

Original Ticket: [sardana/tickets/244](https://sourceforge.net/p/sardana/tickets/244)

**Comment by reszelaz** [comment]
Moved to: https://github.com/taurus-org/taurus/issues/432
