### ISSUE TITLE
loopTest function should be refactored to make use of unittest.TestSuite() (SF#248)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#139]
loopTest function, is a function developed for the Sardana Testing Framework. This function allow to execute many times a given test. loopTest() should be refactored to be developed using the class TestSuite from unittest (unittest.TestSuite())

The documentation of the class unittest.TestSuite(tests=()) can be found here:
https://docs.python.org/2/library/unittest.html#unittest.TestSuite

Reported by: sagiss ( http://sf.net/u/mrosanes )

Original Ticket: [sardana/tickets/248](https://sourceforge.net/p/sardana/tickets/248)

**Comment by reszelaz** [comment]
Moved to Taurus:
https://github.com/taurus-org/taurus/issues/431
