### ISSUE TITLE
Jul20 manual release tests: Win10

### ISSUE THREAD

**Issue by aureocarneiro** [sardana-org/sardana#1391]
This is an issue for checking the Jul20 release in Windows 10

### Installation
- [x] Install Sardana
  According to the previous test instructions the installation was from the MSI file. Since now we use conda, the installation is using pip from the artifact URL in the conda environment.
  The tests are run using taurus-vagrant project (internal to ALBA). The Vagrant file was pasted in https://github.com/taurus-org/taurus/issues/1134 and the conda environment configuration used is the following:
  ```
  (base) C:\Users\IEUser>conda config --add channels conda-forge
  (base) C:\Users\IEUser>conda config --add channels tango-controls
  conda create -n py3qt5 python=3 pyqt=5 pytango lxml future guidata guiqwt ipython pillow pint ply pyqtgraph pythonqwt 
  numpy scipy pymca click
  conda activate py3qt5
  pip install taurus taurus_pyqtgraph
  pip install https://ci.appveyor.com/api/buildjobs/s65v35bj40aucg0m/artifacts/dist%2Fsardana-3.0.2.tar.gz
  conda install matplotlib
  conda install pytest
  conda install spyder
  ```

### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
`PyTango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
  **- Problem1: traceback appearing when creating new spock profile. This bug also existed in previous releases:** https://github.com/sardana-org/sardana/issues/536
  **- Problem2: cannot exit spock doing 'exit()', even if after I use 'Ctrl+C'. This bug also existed in previous releases:** https://github.com/sardana-org/sardana/issues/724
- [x] In spock run `sar_demo` macro.
- [ ] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [ ] Run testsuite. In another console do `sardanatestsuite`
  **Problem:** execution of tests starts promissing, however after receiving the _python crashed_ pop-ups the tests are not able to continue. Similar issues were already existing in previous release tests: #540, but the testsuite was able to continue if one was closing the pop-up windows. What has changed now is that we are using the pytest instead of the unittest.
### Test Sardana using Spock and expconf
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
- [x] Execute `umvr` macro and verify that the position updates arrives.
- [x] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
- [x] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [x] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
- [x] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
- [x] Open online plot (This should ask to enable JsonRecorder, set it to true. Otherwise enable it in spock: `senv JsonRecorder True`).
- [x] Run step scan
- [x] Verify that records appear in spock output.
- [x] Verify that records were stored in scan files.
- [x] Verify that records were plotted on the online plot
- [x] Run `showscan` and access to the last scan data.
  **- Problem: traceback appearing when opening showscan. This bug also existed in previous releases:** https://github.com/sardana-org/sardana/issues/910
- [x] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied.
  **Note:** It is `MacroPath` sensitive. Use `\` as path separator.
- [x] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.
  **Note:** It is `MacroPath` sensitive. Use `\` as path separator.
### Test Sardana with TaurusGUI
- [x] Create a new GUI from scratch using TaurusGUI: `$ taurus newgui`
  - project page: directory = "/home/<user>/mygui"
  - general settings page: GUI Name = "MyGui"
  - custom logo: NEXT
  - synoptics page: NEXT
  - MacroServer Info page: Enable sardana Communication and select `demo2` MS and Door name
  - Instruments from Pool page: Yes
  - the rest of the pages, NEXT...NEXT...NEXT...FINISH
  - note the message about installing the GUI!
- [x] install the GUI
- [x] launch the GUI: `$ MyGui`
- [x] say yes to enable json
- [x] set a nice panel layout

#### PMTV (PoolMotorTaurusValue)
- [x] Open a `taurus form` with all slit related motors
- [x] Activate compact mode
  - Move all motors with absolute and relative mode
  - Stop a motor in the middle of it's movement with the stop button
- [x] Activate normal mode (deactivate compact)
  - Move all motors with absolute and relative mode
  - Stop a motor in the middle of it's movement with the stop button
- [x] Activate expert mode
  - Define slit motors limits while the form is open. Expert mode buttons and limit indicators should switch from grey to active colors
  - Check every motor limit with expert buttons
    **Problem: limit tooltip is not visible when limit is active - more details in:**
    https://github.com/sardana-org/sardana/issues/1404
- [x] Move a few motors using absolute and the apply button
- [x] Reset absolute blue values

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [ ] Start new sequence
  **Note:** new sequences cannot always be created #305
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### MacroButton

- [x] Start macrobutton:
     ```console
     python3 -m sardana.taurus.qt.qtgui.extra_macroexecutor.macrobutton door_demo2_1
     ```
- [x] Execute `lsmac` macro with default parameter value for filter (`.*`).
- [x] Execute `ascanct` macro.
- [x] Execute `ascan` macro and stop it with the macrobutton (after prior pausing and confirming stopping in the pop-up).

#### sardanaeditor
**Note:** There are known bugs on CentOS and Windows
**Problem: sardanaeditor does not work with the latest spyder:** #909
- [ ] Open sardanaeditor with macroserver name as argument.
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by reszelaz** [comment]
I have finished the tests. IMO the results are satisfactory. There is only one thing which got worse with respect to the previous releases. Now we are not able to execute the tests - these crash the pytest process as soon as we run tests which start and stop Tango DS. This was already problematic when running tests with unittest - see #540. I would not try to fix it now. The idea is to use the PyTango `MultiDeviceTestContext` soon.
