### ISSUE TITLE
Jul20 manual release tests: Debian 9

### ISSUE THREAD

**Issue by aureocarneiro** [sardana-org/sardana#1392]
This is an issue for checking the Jul20 release in debian 9

### Installation
- [ ] Install Sardana (on Linux from the tar.gz : `pip install <tarball_artifact_URL>`
  and on Windows from MSI)
  **Comment:** i did the installation using setup.py:
    python3  setup.py install --user
### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `tango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
  **Note:** Remember to use OS path separator e.g. `/` on Linux and `\` on 
  Windows
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
- [x] In spock run `sar_demo` macro.
- [x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [ ] Run testsuite. In another console do `sardanatestsuite`
  **Note:** On openSuse 11.1 and Windows there are known problems with 
  testsuite. Check previous release comments.
  **Comment:** I get the message:
  sardanatestsuite was removed in Sardana 3.0.2. Use pytest to run tests.

### Test Sardana using Spock and expconf
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
  **Note**: On Windows there is printed RuntimeWarning about difference between
  stdin and stdout encoding.
- [x] Execute `umvr` macro and verify that the position updates arrives.
- [x] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
- [x] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [x] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
- [x] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
- [x] Open online plot: `showscan online` (This should ask to enable JsonRecorder, set it to true. Otherwise enable it in spock: `senv JsonRecorder True`).
- [x] Run step scan
- [x] Verify that records appear in spock output.
- [x] Verify that records were stored in scan files.
- [x] Verify that records were plotted on the online plot
- [ ] Run `showscan` and access to the last scan data.
  **Comment:**  I get the error:
  Trying to open local scan file /tmp/demo1.h5...
  AttributeError: 'str' object has no attribute 'decode'
  (For more detailed information type: python_error)
  
  With hdfview I can open the nexus file and it looks like fine

- [x] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied.
- [x] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows

### Test Sardana with TaurusGUI
- [x] Create a new GUI from scratch using TaurusGUI: `$ taurus newgui`
  - project page: directory = "/home/<user>/mygui"
  - general settings page: GUI Name = "MyGui"
  - custom logo: NEXT
  - synoptics page: NEXT
  - MacroServer Info page: Enable sardana Communication and select `demo2` MS and Door name
  - Instruments from Pool page: Yes
  - the rest of the pages, NEXT...NEXT...NEXT...FINISH
  - note the message about installing the GUI!
- [x] install the GUI with pip
  **Comment:** I have to use pip3, since in my computer pip is for python2. 
  pip3 install --no-deps .
  from the directory where my_gui was created.

- [x] launch the GUI: `$ MyGui`
- [x] say yes to enable json (if not done yet)
- [x] set a nice panel layout

#### PMTV (PoolMotorTaurusValue)
- [x] Open a `taurus form` with all slit related motors
- [x] Activate compact mode
  - Move all motors with absolute and relative mode
  - Stop a motor in the middle of it's movement with the stop button 
- [x] Activate normal mode (deactivate compact)
  - Move all motors with absolute and relative mode
  - Stop a motor in the middle of it's movement with the stop button
- [x] Activate expert mode
  - Define slit motors limits while the form is open. Expert mode buttons and limit indicators should switch from grey to active colors
  - Check every motor limit with expert buttons
- [x] Move a few motors using absolute and the apply button
- [x] Reset absolute blue values

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [x] Start new sequence
  **Note:** new sequences cannot always be created #305
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### MacroButton

- [x] Start macrobutton:
     ```console
     python3 -m sardana.taurus.qt.qtgui.extra_macroexecutor.macrobutton door_demo2_1
     ```
- [x] Execute `lsmac` macro with default parameter value for filter (`.*`).
- [x] Execute `ascanct` macro.
- [x] Execute `ascan` macro and stop it with the macrobutton (after prior pausing and confirming stopping in the pop-up).

#### sardanaeditor
**Note:** There are known bugs on CentOS and Windows
- [ ] Open sardanaeditor with macroserver name as argument.
  **Comment:** I get the error:
  MainThread     INFO     2020-09-04 13:39:49,461 TaurusRootLogger: Using PyQt4 (v4.11.4 with Qt 4.8.7   and Python 3.5.3)
MainThread     INFO     2020-09-04 13:39:49,549 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /home/tnunez/.local/lib/python3.5/site-packages/taurus-4.6.1-py3.5.egg/taurus/qt/qtgui/icon/)
Traceback (most recent call last):
  File "sardana_jul20/src/sardana/taurus/qt/qtgui/extra_sardana/sardanaeditor.py", line 47, in <module>
    from .macrotree import MacroSelectionDialog
SystemError: Parent module '' not loaded, cannot perform relative import

- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by teresanunez** [comment]
I have done the tests. I think the problems are related to possible conflicts between my python2 and
python3 installations.

**Comment by reszelaz** [comment]
Thanks @teresanunez for performing the release tests. I think that the results that you've got are satisfactory. Let me comment on the points that you have not "checked":
* executing the automatic tests is not mandatory for Debian 9 - we run them on Travis and are greeen
* I confirm the error that you got for showscan with the PyMca5 from the Debian 9 repos. One needs to go for newer version of PyMca to avoid this error. I managed to get it work with version 5.5.5
* issues sardanaeditor is not release blocking, it is known that it does not work with the latest

**Comment by dschick** [comment]
Hi, I just tested the latest release with one of our systems (Mint 19.3) and python 3.6.
I encountered issues when running the `ct` macro.
If I use the `dummycounter` everything is fine, but e.g the `TangoAttrZeroDController` does not return any results and more importantly our [epoch](https://github.com/MBI-Div-B/sardana-EpochCounterTimerController) counter throws an error

```
Thu Sep 10 13:59:59 2020

Elements ended acquisition with:
epoch:
       State: On (14:00:01.214492)
      Status: epoch is On
              Counter is stopped (14:00:01.235806)
An error occurred while running ct:
ValueError: Acquisition ended with Unknown
Hint: in Spock execute `www`to get more details
```

and 

```
SardanaTP.W005 ERROR    2020-09-10 14:00:00,156 SardanaTP.SardanaTP.W005: Uncaught exception running job 'run' called from thread SardanaTP.W003:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/labuser/Repos/sardana/src/sardana/sardanathreadpool.py", line 64, in run
    Worker.run(self)
  File "/home/labuser/.local/lib/python3.6/site-packages/taurus/core/util/threadpool.py", line 147, in run
    cmd(*args, **kw)
  File "/home/labuser/Repos/sardana/src/sardana/util/funcgenerator.py", line 194, in run
    self.fire_active()
  File "/home/labuser/Repos/sardana/src/sardana/util/funcgenerator.py", line 259, in fire_active
    self.fire_event(EventType("active"), self._id)
  File "/home/labuser/Repos/sardana/src/sardana/sardanaevent.py", line 110, in fire_event
    self._fire_event(event_type, event_value, listeners=listeners)
  File "/home/labuser/Repos/sardana/src/sardana/sardanaevent.py", line 130, in _fire_event
    real_listener.event_received(self, event_type, event_value)
  File "/home/labuser/Repos/sardana/src/sardana/pool/poolacquisition.py", line 359, in event_received
    **self._sw_acq_args.kwargs)
Traceback (most recent call last):
  File "/home/labuser/.local/lib/python3.6/site-packages/taurus/core/util/threadpool.py", line 145, in run
    callback(cmd(*args, **kw))
  File "/home/labuser/Repos/sardana/src/sardana/pool/poolaction.py", line 342, in run
    self.start_action(*args, **kwargs)
  File "/home/labuser/Repos/sardana/src/sardana/pool/poolacquisition.py", line 1145, in start_action
    nb_states_per_value, **kwargs)
  File "/home/labuser/.local/lib/python3.6/site-packages/taurus/core/util/log.py", line 196, in wrapper
    ret = f(*args, **kwargs)
  File "/home/labuser/Repos/sardana/src/sardana/pool/poolacquisition.py", line 901, in start_action
    load(ctrl.timer, value, repetitions, latency)
  File "/home/labuser/Repos/sardana/src/sardana/pool/poolacquisition.py", line 894, in load
    ctrl.LoadOne(axis, value, repetitions, latency)
TypeError: LoadOne() takes 4 positional arguments but 5 were given
SardanaTP.W002 ERROR    2020-09-10 14:00:01,238 Door/scattering/1: An error occurred while running ct:
ValueError: Acquisition ended with Unknown
```
Best

Daniel

**Comment by reszelaz** [comment]
Hi Daniel,
Many thanks for testing the release.
You will need to adapt the [epoch's controller LoadOne()](https://github.com/MBI-Div-B/sardana-EpochCounterTimerController/blob/4550154152d6c670d353e429e31e91c2c829b63e/EpochCounterTimerController.py#L45) to the new `LoadOne()` API.

There are quite few [deprecated features removed](https://sardana-controls.org/devel/guide_migration/2to3.html#other-non-python-3-related-incompatibilities) in Sardana v3.

`TangoAttrZeroDController` still needs to be adapted to Sardana v3. Similar changes were done for the rest of the Tango controllers in: https://github.com/ALBA-Synchrotron/sardana-tango/pull/1 and https://github.com/ALBA-Synchrotron/sardana-tango/pull/2

**Comment by dschick** [comment]
@reszelaz many thanks,
the `epoch` controller is working correctly now.
I will try upgrading the `TangoAttrZeroDController` accordingly

**Comment by reszelaz** [comment]
Many thanks to you!
