### ISSUE TITLE
Jul20 manual release tests: CentOS 7

### ISSUE THREAD

**Issue by aureocarneiro** [sardana-org/sardana#1393]
This is an issue for checking the Jul20 release in CentOS 7

### Installation
- [x] Install Sardana (on Linux from the tar.gz : `pip install <tarball_artifact_URL>`
  and on Windows from MSI)

### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `tango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
  **Note:** Remember to use OS path separator e.g. `/` on Linux and `\` on 
  Windows
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
- [x] In spock run `sar_demo` macro.
- [x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [x] Run testsuite. In another console do `sardanatestsuite`
  **Note:** On openSuse 11.1 and Windows there are known problems with 
  testsuite. Check previous release comments.

### Test Sardana using Spock and expconf
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
  **Note**: On Windows there is printed RuntimeWarning about difference between
  stdin and stdout encoding.
- [x] Execute `umvr` macro and verify that the position updates arrives.
- [x] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
- [x] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [x] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
- [x] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
- [x] Open online plot: `showscan online` (This should ask to enable JsonRecorder, set it to true. Otherwise enable it in spock: `senv JsonRecorder True`).
- [x] Run step scan
- [x] Verify that records appear in spock output.
- [x] Verify that records were stored in scan files.
- [x] Verify that records were plotted on the online plot
- [x] Run `showscan` and access to the last scan data.
- [x] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied.
- [x] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows

### Test Sardana with TaurusGUI
- [x] Create a new GUI from scratch using TaurusGUI: `$ taurus newgui`
  - project page: directory = "/home/<user>/mygui"
  - general settings page: GUI Name = "MyGui"
  - custom logo: NEXT
  - synoptics page: NEXT
  - MacroServer Info page: Enable sardana Communication and select `demo2` MS and Door name
  - Instruments from Pool page: Yes
  - the rest of the pages, NEXT...NEXT...NEXT...FINISH
  - note the message about installing the GUI!
- [x] install the GUI with pip
- [x] launch the GUI: `$ MyGui`
- [x] say yes to enable json (if not done yet)
- [x] set a nice panel layout

#### PMTV (PoolMotorTaurusValue)
- [x] Open a `taurus form` with all slit related motors
- [x] Activate compact mode
  - Move all motors with absolute and relative mode
  - Stop a motor in the middle of it's movement with the stop button
- [x] Activate normal mode (deactivate compact)
  - Move all motors with absolute and relative mode
  - Stop a motor in the middle of it's movement with the stop button
- [x] Activate expert mode
  - Define slit motors limits while the form is open. Expert mode buttons and limit indicators should switch from grey to active colors
  - Check every motor limit with expert buttons
- [x] Move a few motors using absolute and the apply button
- [x] Reset absolute blue values

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [x] Start new sequence
  **Note:** new sequences cannot always be created #305
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### MacroButton

- [x] Start macrobutton:
     ```console
     python3 -m sardana.taurus.qt.qtgui.extra_macroexecutor.macrobutton door_demo2_1
     ```
- [x] Execute `lsmac` macro with default parameter value for filter (`.*`).
- [x] Execute `ascanct` macro.
- [x] Execute `ascan` macro and stop it with the macrobutton (after prior pausing and confirming stopping in the pop-up).

#### sardanaeditor
**Note:** There are known bugs on CentOS and Windows
- [ ] Open sardanaeditor with macroserver name as argument.
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by aureocarneiro** [comment]
`sardanaeditor` step can't be executed because of spyder.

**Comment by aureocarneiro** [comment]
`MacroButton` macros has been executed through the interface but the results were not been displayed in the interface.

**Comment by reszelaz** [comment]
> `sardanaeditor` step can't be executed because of spyder.

That's a known problem. It does not work with the recent spyder releases.

**Comment by reszelaz** [comment]
> `MacroButton` macros has been executed through the interface but the results were not been displayed in the interface.

Yeap, `MacroButton` does not print the macro output/result. It just changes the frame colour indicating that the macro is beeing executed, or an error occured.

**Comment by aureocarneiro** [comment]
I used `pytest` to run the unittest

**Comment by reszelaz** [comment]
> I used `pytest` to run the unittest

Exactly, `pytest` is the way to [execute Sardana tests](https://sardana-controls.org/devel/howto_test/test_run_commands.html#run-test-suite) now.

**Comment by aureocarneiro** [comment]
Done! Looks great apart from sardanaeditor which I couldn't test.

Using singularity running on CentOS 7.7:

Dockerfile:

```docker
FROM continuumio/miniconda3:4.8.2

RUN apt-get update && apt-get install -y libgl1-mesa-dev libxi6 libnvidia-egl-wayland-dev mesa-utils libxft-dev libglew-dev libglfw3-dev

RUN conda install -c tango-controls pytango==9.3.2 itango==0.1.7

RUN conda install -c conda-forge qt pyqt libxcb pytest h5py matplotlib libxkbcommon spyder bitshuffle guiqwt pyqtgraph wget libiconv

RUN git clone https://github.com/ALBA-Synchrotron/pyIcePAP.git && cd pyIcePAP && git checkout 3.2.1 && pip install .

RUN wget https://ci.appveyor.com/api/buildjobs/vqem1va2472dceys/artifacts/dist%2Fsardana-3.0.3.tar.gz && tar -xvzf dist%2Fsardana-3.0.3.tar.gz && cd sardana-3.0.3 && pip install .

ENV HDF5_PLUGIN_PATH /opt/conda/lib/python3.7/site-packages/hdf5plugin/plugins
ENV QT_XKB_CONFIG_ROOT /usr/share/X11/xkb
```

Singularity file:

```def
BootStrap: docker-daemon
From: docker.maxiv.lu.se/sardana:3.0.3

%runscript
exec echo "Run with --app Pool/MacroServer/spock"

%apprun Pool
exec Pool "$@"

%apprun MacroServer
exec MacroServer "$@"

%apprun spock
exec spock "$@"

%labels
    Author KITS - MAXIV
```
How to:
compile singularity: `singularity build sardana-3.0.3.sif sardana-3.0.3.def`
run Pool: `singularity run --env-file /etc/tangorc --app Pool sardana-3.0.3.sif demo2 --log-level=debug`
run MacroServer: `singularity run --env-file /etc/tangorc --app MacroServer sardana-3.0.3.sif demo2 --log-level=debug`
run spock: `singularity run --app spock --bind /run/user/$UID:/run/user/$UID --env-file /etc/tangorc sardana-3.0.3.sif --profile=demo2`

**Comment by reszelaz** [comment]
Many thanks Aureo!
I mark it as done in the release check boxes.
