### ISSUE TITLE
PySpectra from hasyweb.desy.de

### ISSUE THREAD

**Issue by TacHuynh** [sardana-org/sardana#1419]
I am interest in the GUI interface to Sardana.
Reading these documents:
http://hasyweb.desy.de/services/computing/Spock/Spock.html
http://hasyweb.desy.de/services/computing/Spock/node134.html
Is this PySpectra package available from outside of hasyweb.desy.de?
Thanks,
Tac.

**Comment by teresanunez** [comment]
Hello,
           PySpectra is a DESY development, it is not the GUI interface to Sardana.
Sardana GUI interface is based on Taurus. You can find documentation
in the Sardana and Taurus documentations.

                      Regards,
                                    Teresa

**Comment by TacHuynh** [comment]
Thanks for answering my questions.
Is this PySpectra package available from outside of hasyweb.desy.de?

**Comment by teresanunez** [comment]
No, it is not.
