### ISSUE TITLE
Pause macro interface with trigger gate controller for continuous scan

### ISSUE THREAD

**Issue by aureocarneiro** [sardana-org/sardana#1423]
Hej all,

I am using one equipment called PandaBox and it is responsible for timing system at the beamline.
For continuous scan, we implemented one way to stop / resume the triggers from this equipment in order to use sardana macro pause feature.
But what is the right way to use the sardana pause functionality inside my sardana controller? Is it using isPaused() method and call it periodically ?
Do we have a place to add a hook which I can call to pause the triggers on my equipment when the user request macro pause and then resume it ? If we have it, where should I configure the hook?

Cheers,

/Aureo

**Comment by reszelaz** [comment]
Hi Aureo,

This sounds like a very interesting use case for continuous scans.
I have two questions:
1. What kind of scan do you want to pause? Does it involve a moveable or it is a timescan only?
2. Does the measurement group contain only hardware synchronized channels or also software synchronized?

Unfortunatelly, when implementing SEP6 we did not have in mind this use case. Actually I did not know that there is a hardware which allows this feature - good to know that PandaBox supports it. But, don't worry I think it won't be so difficult to add this feature to Sardana.

So, if I understand well, you would like that the user (or some external software client), in the middle of the scan calls `PauseMacro` command on the `Door` and then after an arbitrary amount of time call the `ResumeMacro` command. Here, for the moment I focus on scans which do not involve moveable - then we would just need to pause the measurement group. Hence, we would need to add two new commands to the measurment group `Pause` and `Resume`.
If you don't need software synchronizers, this would just need to call a sequence of _pause methods_ on the _pauseable_ controllers. For the moment I would just add the `Pausable` interface with `PauseOne` method. The `TriggerGate` controller could then inherit from it.

I'm very curious how had you implemented it so far, can you explaind it?

Thanks!

**Comment by aureocarneiro** [comment]
Hej @reszelaz thanks for your comment.

1 - Based on the specification of this project, they should be able to pause any type of scan.
2 - The measurement group contains only hw sync elements.

Yes we could implement this feature at PandaBox, I am very happy using it and this is different than all the similar hw available in the market, it is really good and an open source project 👍 

I like this solution, PauseOne method will solve all the problems. My initial idea, for now, is to create an attribute to monitor the door and check if it is paused, then react on this. I didn't implemented yet, for sure I will need to configure polling for this attribute and the polling frequency must to be faster than integration time in order to not unused triggers.. This will be the most trick part.. I need to make sure that the triggers which has been sent by pandabox are sync with number of points before pause etc, also tango timeouts must to be configured in other devices ..

I will keep you informed!

**Comment by reszelaz** [comment]
> 1 - Based on the specification of this project, they should be able to pause any type of scan.

What would be the expected behavior in the case of pausing a scan which involves a moveable? The motor can continue movement? What if the triggers were configured in the position domain? Then some of them could be missed. 

In any case, either if you go and implement your plan or go for adding this features to Sardana, then the _pause points_ would need to be added to the scan classes from the GSF. Otherwise you won't be able to pause the scan.

**Comment by reszelaz** [comment]
Hi @aureocarneiro,
I was just reviewing all question issues. I wonder if go should keep this issue in the backlog? Or maybe we could close it?
Many thanks!

**Comment by aureocarneiro** [comment]
Yes, we can close it :) Thanks
