### ISSUE TITLE
Acquisition in pre-acq hook fails due to MeasurementGroup not prepared after updating to Sardana 3.0.3

### ISSUE THREAD

**Issue by tox1c90** [sardana-org/sardana#1426]
Hi!
I was using the "hack" described in #812 to duplicate my counters after toggling a motor at every scan point (magnetic field for XMCD measurements).
Therefore a second acquisition at every point of the scan is implemented as a 'pre-acq' hook in the following way:

```
if altOn:
        magnet.move(-1*ampl)
        magnetState.magnet = -1*ampl
        
        parent = self.getParentMacro()
        if parent:
            integ_time  = parent.integ_time
            mnt_grp     = self.getObj(self.getEnv('ActiveMntGrp'), type_class=Type.MeasurementGroup)
            state, data = mnt_grp.count(integ_time)
                       
        magnet.move(+1*ampl)
        magnetState.magnet = +1*ampl
```

After updating to Sardana 3.0.3, running a scan now fails with the following error:

> An error occurred while running ascan:
PyDs_PythonError: RuntimeError: prepare is mandatory before starting acquisition

I understand that it's now necessary to explicitly prepare the measurement group before acquisition. However, simply calling `mnt_grp.prepare()` before the `mnt_grp.count(integ_time)` in my example does not help and the acquisition within the hook still throws the same error. Is there anything else I have to do?

**Comment by reszelaz** [comment]
Hi Martin,

Many thanks for this report.

> After updating to Sardana 3.0.3, running a scan now fails with the following error:

Yes, as part of #1315 we made it mandatory to execute `Prepare` Tango command before the measurement. But the [`MeasurementGroup.count()`](https://sardana-controls.org/devel/api/sardana/taurus/core/tango/sardana/pool.html#sardana.taurus.core.tango.sardana.pool.MeasurementGroup.count) already calls it. Note the difference with [`MeasurementGroup.count_raw()`](https://sardana-controls.org/devel/api/sardana/taurus/core/tango/sardana/pool.html#sardana.taurus.core.tango.sardana.pool.MeasurementGroup.count_raw).

When adding the [deterministic scan optimization](https://sardana-controls.org/devel/howto_macros/scan_framework.html#deterministic-scans) as part of SEP18 we forgot about your particuar use case, sorry.

In #1427 I introduce a programmatic API to disable the optimization. Would it be enough for you?

Or you need a user interface e.g. an environment variable? I would try to avoid adding new macro parameters (if eventually we go for a [pythonic syntax to run macros](https://github.com/sardana-org/sardana-questionnaire/blob/fb741a05f11e4eb287a23ba42defaf6672ed2e83/questionnaire.gs#L107) then of course having `deterministic_scan` kwarg would be perfectly fine).

Also, do you need a hotfix release or push to develop would be enough for you?

Sorry about the inconveniences!

**Comment by tox1c90** [comment]
Hi @reszelaz , thank you for implementing this property! Push to develop would be enough.

Looking at your example, I assume it will be necessary then to wrap the standard scan macros like `ascan` in a custom scan in order to be able to set `my_scan._gScan.deterministic_scan = False` before it actually gets executed, is that correct?

Is it possible to do this within a `pre_scan` hook as well? We are using an environment variable `altOn` which we set when we want to scan in this mode. It would be great if we could determine in a `pre_scan` hook if the variable is set, and if yes, proceed with running the standard scan macros in `deterministic_scan = False` mode.

**Comment by reszelaz** [comment]
> Push to develop would be enough.

Great, let's make it this way then. 

> Looking at your example, I assume it will be necessary then to wrap the standard scan macros like `ascan` in a custom scan in order to be able to set `my_scan._gScan.deterministic_scan = False` before it actually gets executed, is that correct?

Yes, this was my idea behind the programmatic API. But, what you say in continuation should also work.

> Is it possible to do this within a `pre_scan` hook as well? We are using an environment variable `altOn` which we set when we want to scan in this mode. It would be great if we could determine in a `pre_scan` hook if the variable is set, and if yes, proceed with running the standard scan macros in `deterministic_scan = False` mode.

Yes, I think it should work! But it would be nice if you could try it and post back a feedback in the the PR. I was also thinking in adding an environemnt variable e.g. `DeterministicScan` which could be then consulted in the `deterministic_scan` property getter. But for your case it would require setting two environment variables every time `altOn` and `DeterministicScan`. So, if you are fine with defining another *GeneralHook* for the `pre-scan` hook place, let's forget about the new environment variable for the moment.
