### ISSUE TITLE
PrepareOne for TriggerGateController

### ISSUE THREAD

**Issue by 13bscsaamjad** [sardana-org/sardana#1432]
A use case appeared at MAX IV when users want to trigger a laser on alternate steps in a step scan. Since the axis methods do not have access to the current step, it is perhaps a good idea to have a `PrepareOne` method for `TriggerGateController` as well to be able to prepare variables that can be used for different logics throughout the scan.

**Comment by reszelaz** [comment]
Yes, It makes sense to me to make preparation on the trigger/gate axes. What information do you think should go there? Just `nb_starts` ? Here, similar doubt raises to me as we discuss with @jkotan on #1430. I would have different signatures for `PrepareOne()` method of an experimental channel and different one for the trigger/gate.

**Comment by 13bscsaamjad** [comment]
I think that only `nb_starts` is relevant for TG!

**Comment by reszelaz** [comment]
I also think that `nb_starts` would be enough. Any other opinions?

Roughly speaking, the implementation would consist of:
* Adding `PrepareOne(self, nb_starts)` method to the `TriggerGateController` class with default implemntation which does just `pass`
* Calling this method on all enabled TriggerGate controllers in `PoolAcquisition.prepare()` method
* Updating the [How to write a trigger/gate controller](https://sardana-controls.org/devel/howto_controllers/howto_triggergatecontroller.html) guide

Do you feel like MaxIV could make a PR with this? If you want we can schedule a pair-programming session. I heared that Visual Studio Code allows remote pair-programming. Personally I have never tried it but it may be fun:)

**Comment by 13bscsaamjad** [comment]
Pair-programming will be great :)
