### ISSUE TITLE
Travis is discontinuing the unlimited CI service for OSS projects

### ISSUE THREAD

**Issue by cpascual** [sardana-org/sardana#1433]
In case you didn't know, have a look at https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

More specifically:

> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
(...)
When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.
We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment.

As a guide, consider that a typical sardana run uses ~25' (so the "trial" allotment will only last ~40builds)

Fortunately, there are good alternatives:
- move to github actions
- move to gitlab-ci

See:
- https://github.com/taurus-org/taurus/issues/1139  (regarding github actions)
- https://github.com/taurus-org/taurus/issues/761 (regarding gitlab-ci)
- https://github.com/taurus-org/taurus_pyqtgraph/pull/60 (regarding an already completed migration to github actions)

**Comment by reszelaz** [comment]
Thanks for sharing - I was not aware of this.
For the moment GH actions wins as an alternative - we already use them for publishing on PyPI:)

**Comment by reszelaz** [comment]
For the moment I'm closing this one. Whenever we run out minutes necessary for building the docs on travis we will come back to this issue.
