### ISSUE TITLE
Allow for single file per scan (how to sync large hdf5 files)

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1452]
Hi all,

we are currently progressing with integrating 2D detectors into our setups and into Sardana.
We pretty much like saving all acquired images in one hdf5 file together with the scan data as it makes evaluation very easy.

However, we encounter some issues when trying to sync the hdf5 files after each scan.
It seems that there is no way to do an incremental backup of hdf5 files, e.g. using `rsync` (https://forum.hdfgroup.org/t/hdf5-files-backup-solutions-rsync-etc/4187)
This means that we would always need to sync the whole hdf5 file, which can be several GB, and is not feasable.

Of course we could avoid these large files by using references in the hdf5 file as introduced in SEP2.
However, since the original files are usually stored on a differnent machine in non hdf5 format, this would mean a lot of extra layers to make this working in a user-friendly way.

Another option would be a hdf5 recorder which creates individual files per scan. Does anyone already did something like that? I think I once read about it, but could not find it here ...

I would also appreciate any other concept of solving the general issue of hdf5 syncing :)

**Comment by teresanunez** [comment]
Hi @dschick,
                    we saved our 2D data during the scan synchronized to the different scan
points. We did it before the SEP2, but it works, so it should be possible to do it.

                        Best Regards,
                                                    Teresa

**Comment by dschick** [comment]
hi @teresanunez thanks for the quick reply.

I am not sure if we talk about the same thing.
We do get the images into our h5 file in sardana. this syncs perfectly fine.
I am talking about syncing the whole scan file after the scan to some external location as backup.

We usually have a `post-scan` macro like `sync_data` which is does the job but takes to much time for large hdf5 files.

D

**Comment by teresanunez** [comment]
Hi @dschick,
                       we don't use the h5 implementation from Sardana, we have
one implementation in DESY.

                        Best Regards,
                                                  Teresa

**Comment by dschick** [comment]
is it available somewhere so I can have a look at it?

**Comment by reszelaz** [comment]
Hi all,
Just a quick comment.

@dschick, for sure you must have tried it already, but what about automatically changing the `ScanFile` in pre-scan or post-scan hook? What problems have you found with it?

The recorders that @teresanunez talks about must be the same ones as described in https://github.com/sardana-org/sardana/issues/1124#issuecomment-498052469.
BTW, it would be nice to have them listed in the plugins catalogue, and the lavue tool as well.

Thank you!

**Comment by teresanunez** [comment]
Hi @reszelaz, yes, thanks, this is the recorder I meant ... but I think it is in Sardana, and the
needed Tango Servers in the tango repository ... @jkotan, is that right?.  
Best Regards,
                       Teresa

**Comment by jkotan** [comment]
Hi, 
in principle it is possible to run our **NXS_FileRecorder**  in a limited version without additional tango servers but you have to set a lot of additional  environment variables so it is not so convenient. 

- It is good to set at least the **NXSRecSelector** server which takes care of additional configuration information not included in measurement groups. 
- **NXSDataWriter** server is user to write nexus files from a xml configuration. It can be used as a python module but if you want to have its non-standard configuration (kept in tango properties, i.e. SWMR mode) or write data on a different host it is better to use the NXSDataWriter server which is running on dedicated host.
- **NXSConfigServer** server is a front end to the nxsconfig database in mysql. It provides access to the xml configuration for the recorder (You cannot define everything in real time in MG). Similarly you can use is in the python module version but if you want to have its additional properties or you have the mysql database on a different host it is better to install the tango server.    

If you have more question just let me know.

**Comment by dschick** [comment]
thanks a lot for the detailed answers.
I hope we will have time to test the NXS Recorder as sounds very promising.
Up to then, we will test @reszelaz suggestions to change the scan_file in the pre-scan hook (I have not thought about that so far ;)
I will close the issue and reopen it, if necessary.
