### ISSUE TITLE
Storing data in Columns in Scan Macro pre-acq or post-acq Hook

### ISSUE THREAD

**Issue by marouanebj** [sardana-org/sardana#1454]
Hi,

I use the mesh Macro to scan on an x y grid.
I have a laser distance mesure in the z axis and a Zmotor.
I have a macro that adjust Zmotor according to a reference laser distance, lets call it adjustZ
I set adjustZ as a pre-acq Hook.

This works fine.

I want to store the position of the Zmotor for each acquisition (exactly like the Xmotor and Ymotor).

First/
I looked through the examples with "extrainfodesc"
https://sardana-controls.org/devel/examples/macro_scans_examples.html?highlight=hdf
I manage to declare the columns (I "modified" the mesh.prepare method) but 
But I did not find out how to fill the step from the adjustZ macro.

Second/
A also saw that `GScan` has a `_getExtraColumns` which uses `cols = self.macro.getEnv('ExtraColumns')`
Third/
A also saw `getStepExtraInfo` methode called somewhere

Can you help me to store the position of the Zmotor for each acquisition (exactly like the Xmotor and Ymotor)?
Thanks

**Comment by reszelaz** [comment]
Hi @marouanebj,
You simply need to add the `Zmotor/position` Tango attribute to the [Measurement Group](https://sardana-controls.org/devel/overview/overview_measurementgroup.html).
You can do it in the [expconf](https://sardana-controls.org/users/taurus/experimentconfiguration.html) widget (_Click on the "Add channel" button_ -> _Select "Other" from the drop down list_ -> _Select attribute from the Tango DB_) or directly when you create the measurement group in Spock using `defmeas` macro e.g.
```
defmeas my_meas ct01 Zmotor/position
```
I think this is not very clear in the documentation. Sorry about that.
Cheers!

**Comment by marouanebj** [comment]
Thanks
