### ISSUE TITLE
Use Recorders to store scan data in a Nexus files with grid positioning

### ISSUE THREAD

**Issue by marouanebj** [sardana-org/sardana#1467]
Hi, Happy new Year,

I'm running a mesh macro:
mesh mottrx 1.0 2.0 1 mottry 1.0 2.0 1 1.0 True

in x direction I have 1 interval so 2 points
in y direction I have 1 interval so 2 points also

the measurementgroup contains a onedamptekdp5 that reads 2048 int64.

All is working and I have in my output tests.h5 file my data.
I think that it is the h5storage.NXscanH5_FileRecorder that is the used recorder.

The problem is that the data are stored as a list not as a grid:
current format
```
measurement       NXcollection
  Pt_No          Dataset         4             int64
  mottrx         Dataset         4             float64
  mottry         Dataset         4             float64
  ...
  onedamptekdp5  Dataset         4 x 2018      int64
  ...
```

And I would like to have something like:
wanted format
```
measurement       NXcollection
  Pt_No          Dataset         4                 int64
  mottrx         Dataset         2 x 2             float64
  mottry         Dataset         2 x 2             float64
  ...
  onedamptekdp5  Dataset         2 x 2 x 2018      int64
  ...
```

Explanation:
There are 2 problems here.
First I would like to have my onedamptekdp5 Dataset stored as `2 x 2` grid (also same for all other Dataset except maybe Pt_No).
Second the mesh macro is doing a path in a S walk:
 0 -> 1
 3 <- 2
 and I would like this to be correct in my 2x2 grid Dataset.

So my question:
Is there a way to have my wanted format with a proper configuration (expconf) ?
Is there a way to have my wanted format with some env settings or other ?
Will I have to code a recorder inspired by NXscanH5_FileRecorder myself ?
Do you have another idea ?

Thanks,
Marouane

**Comment by cpascual** [comment]
Hi, 
I may be wrong but, AFAIK, there is no configuration option for doing what you want, and your only option is to use a custom recorder.

That said, I would suggest to investigate if in such custom recorder you can actually keep the original data conforming to the NXscan standard and just add new datasets with the desired structure. Maybe it is even possible to make use of some advanced hdf5 feature (virtual datasets, or even the VOL api) to just add a "2D view" to the existing datasets in order to avoid data duplication and still maintain NXscan compatibility.

I hope it helps

On January 7, 2021 4:32:55 PM GMT+00:00, marouanebj <notifications@github.com> wrote:
>Hi, Happy new Year,
>
>I'm running a mesh macro:
>mesh mottrx 1.0 2.0 1 mottry 1.0 2.0 1 1.0 True
>
>in x direction I have 1 interval so 2 points
>in y direction I have 1 interval so 2 points also
>
>the measurementgroup contains a onedamptekdp5 that reads 2048 int64.
>
>All is working and I have in my output tests.h5 file my data.
>I think that it is the h5storage.NXscanH5_FileRecorder that is the used
>recorder.
>
>The problem is that the data are stored as a list not as a grid:
>current format
>```
>measurement       NXcollection
>  Pt_No          Dataset         4             int64
>  mottrx         Dataset         4             float64
>  mottry         Dataset         4             float64
>  ...
>  onedamptekdp5  Dataset         4 x 2018      int64
>  ...
>```
>
>And I would like to have something like:
>wanted format
>```
>measurement       NXcollection
>  Pt_No          Dataset         4                 int64
>  mottrx         Dataset         2 x 2             float64
>  mottry         Dataset         2 x 2             float64
>  ...
>  onedamptekdp5  Dataset         2 x 2 x 2018      int64
>  ...
>```
>
>Explanation:
>There are 2 problems here.
>First I would like to have my onedamptekdp5 Dataset stored as `2 x 2`
>grid (also same for all other Dataset except maybe Pt_No).
>Second the mesh macro is doing a path in a S walk:
> 0 -> 1
> 3 <- 2
> and I would like this to be correct in my 2x2 grid Dataset.
>
>So my question:
>Is there a way to have my wanted format with a proper configuration
>(expconf) ?
>Is there a way to have my wanted format with some env settings or other
>?
>Will I have to code a recorder inspired by NXscanH5_FileRecorder myself
>?
>Do you have another idea ?
>
>Thanks,
>Marouane
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sardana-org/sardana/issues/1467

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by reszelaz** [comment]
Hi all,
Thanks, and happy New Year too!

As @cpascual suggests the best would be to aviod data duplication. I have never tried it for your use case but, if it helps, in Sardana we [use virtual data sets for 1D and 2D value references](https://github.com/sardana-org/sardana/blob/caeddcbe2cfe90efa4b8a19bcf6be17b085b3157/src/sardana/macroserver/recorders/h5storage.py#L362).
If you don't manage to avoid data duplication in your custom recorder, and you still want the NXscan definition, then you may completelly change the approach and  avoid using a custom recorder and just add a post-scan hook to the mesh macro in which you could create an additional dataset using `addCustomData()` as in this [example](https://github.com/sardana-org/sardana/blob/caeddcbe2cfe90efa4b8a19bcf6be17b085b3157/src/sardana/macroserver/macros/examples/scans.py#L623).

Also, for others, only interested in visualizng the mesh scalar channels in a grid format, you can use silx directly with the Sardana mesh data:

![image](https://user-images.githubusercontent.com/6735649/104180834-1398fa00-540e-11eb-9ad5-1b4b8e1e2188.png)

In any case, @marouanebj please share with us your final solution. It will be very usefull for other users facing the same problem!

**Comment by marouanebj** [comment]
Thanks,
I will try not to duplicate data, I will tell you when I get a solution.

**Comment by marouanebj** [comment]
Hi,
I did a Macro that rearrange my data by coping in the same hdf5 file. I just created a group "measurementGrid".
I'm trying to recode the Macro that rearrange my data by referencing in the same hdf5 file.
I'm not really satisfied because the visualization with PyMCA and Silx of my data is not easy.

I thought my view was simple. I have 2 motors one x the other y, and for each couple I have an array of 2048 ints.
I like to see points like I see here in Silx:
![Capture Silx du 2021-02-03 14-32-51](https://user-images.githubusercontent.com/1905891/106754856-c0d9e900-662d-11eb-8004-9a1e901794ae.png)
But I need something to see 2048 ints but I can't see it in Silx:
![Capture Slix du 2021-02-03 14-30-55](https://user-images.githubusercontent.com/1905891/106755125-08607500-662e-11eb-8acf-e0a6b63a33ca.png)
So I would like to know if there is a way to see the curve with the Pt_No of the first screenshot and the MCA curves in a second graph for each point (with the color of the point).
I know this might be a question that goes somewhere else but if some of you know Silx or PyMCA or who to ask ?

I keep you informed

**Comment by vasole** [comment]
What you want is to visualize 1D data at the grid positions?

You have to use the Mask Scatter View plugin of the PyMca ROI Imaging tool.

For automatic loading of the motor positions, the key point is to have a group named positioners containing all your motors in the NXinstrument group. If they are named x and y they will be assigned. If they have other names, they can be assigned by the user in the same Mask Scatter View.

You might also use your current data. There is a ROI imaging tool plugin accessible as "Load positioners from file". If with your current files you already have the motor positions in a group, you can manually select it

![image](https://user-images.githubusercontent.com/5636251/106763278-f2a37d80-6636-11eb-9e92-fd51690152fa.png)

**Comment by marouanebj** [comment]
Thanks, I will look into that

**Comment by marouanebj** [comment]
Hi The users a happy with the data I display after transforming in 2D. So we can close this.
