### ISSUE TITLE
Publish sardana to conda-forge

### ISSUE THREAD

**Issue by beenje** [sardana-org/sardana#1487]
`pytango` and `taurus` have been recently published on conda-forge.
I think it'd be nice to have `sardana` available on conda-forge as well. I can volunteer to prepare a PR if it's OK.
If it's yes, is anyone interested to be listed as a maintainer?

**Comment by cpascual** [comment]
I am only partially involved in the sardana maintainance, but if no one else from @sardana-org/integrators  wants to be involved with the conda-forge package maintainance of sardana, I don't mind doing it (I am already there for taurus)

**Comment by reszelaz** [comment]
Thnaks @beenje for this initiative and count with me as the maintainer.

**Comment by beenje** [comment]
Thanks to both of you! PR created: https://github.com/conda-forge/staged-recipes/pull/13840

**Comment by reszelaz** [comment]
Hi @beenje,

I have tried to build it from the `meta.yaml` locally and install afterwards and it works perfectly!

I'm just curious about the requirement of python>=3.6. Sardana still supports python 3.5 and will do it for quite a lot of time - we at ALBA need it since our default OS is Debian 9 which comes with python 3.5. I wonder if it make sense to also specify the same for the conda package. What do you think?

Thanks a lot!

**Comment by beenje** [comment]
conda-forge only supports Python >= 3.6, this is why I took this version. But I think it's fine to specify 3.5 as minimum version so it does represent what the package really supports. I'll update the recipe.
Note that it might not be possible to install Sardana with Python 3.5 using conda as some dependencies might require >= 3.6 in conda-forge. 

Could you please confirm you want to be listed as maintainer in a comment of the https://github.com/conda-forge/staged-recipes/pull/13840 PR? This is required in the conda-forge check-list. Thanks!

**Comment by reszelaz** [comment]
> conda-forge only supports Python >= 3.6, this is why I took this version.

Thanks for the clarification.

> Could you please confirm you want to be listed as maintainer in a comment of the [conda-forge/staged-recipes#13840](https://github.com/conda-forge/staged-recipes/pull/13840) PR? This is required in the conda-forge check-list.

Sure, I've just done it.

**Comment by cpascual** [comment]
> conda-forge only supports Python >= 3.6, this is why I took this version.

I had the same question in the case of taurus (which also supports 3.5), but I opted to not support 3.5 *in the conda package* because it implied having to take care of many small differences with the handling of dependencies that are available from conda-forge only for py>=3.6

**Comment by reszelaz** [comment]
Sardana is already on conda-forge so I'm closing this ticket. Thanks @beenje for all your work!
