### ISSUE TITLE
Log changes of position related attributes

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1508]
In older Tango versions we were relying on the history of the attribute properties used by memorized attributes, like offset, sign and step_per_unit to keep track of the changes. This however was romoved after this [poll](https://lists.tango-controls.org/wws/arc/info/2015-07/msg00008.html). At ALBA, we plan to use the HDB++ (extended with archiving on change events) for this purposes, but this won't come shortly.

Meanwhile,  with @jordiandreu we were thinking that simply logging the changes in the usual server log files would be of great help in tracking the changes. Hence we propose to add logs like:

- sign set to -1
- offset set to -2.34
- step_per_unit set to 567

For the moment I would start with the debug log level.

With this, at least, we will gain access to the history of changes limited by the numer and size of log files which are configurable with the [`sardanacustomsettings`](https://sardana-controls.org/users/configuration/sardanacustomsettings.html#sardana-custom-settings) module. Also, the ones using elastic, or similar tools, could easily gain unlimited history.

Note that on the server startup, when restoring the memorized values, this may repeat the last setting in the log but it won't be harmfull and after implementing https://github.com/sardana-org/sardana/issues/1458 this repeated log could be removed.

Thanks in advace for your feedback!

**Comment by teresanunez** [comment]
Hi Zibi, we have motor log files for our motors and since all our changes in Sardana go through or to our
Tango motors we already keep track of the changes we are interested in.

**Comment by reszelaz** [comment]
@jordiandreu FYI this feature is already in the develop branch. Cheers!
