### ISSUE TITLE
How to define Doors and/or Pools to have 2 totally independant environements on one computer

### ISSUE THREAD

**Issue by marouanebj** [sardana-org/sardana#1511]
Hi,
I'm working on 2 different projects (ipadiffx and ipatomo), on the same computer.
For the moment I have all the Controllers in the same Door and same Pool.
I do not remember how I created those but I have "Door_ipadiffx_1" and "Pool_ipadiffx_1".

To Start Sardana I type: Sardana ipadiffx
Di it created the "Door_ipadiffx_1" and "Pool_ipadiffx_1" the first time I started it ?
is there somewhere (an environement or something) other than the tangoDB(MariaDB.tango) that store this infos ?

I would like to totally separate the projects:

One reason is because I will have a problem with defining PoolPath, MacroPath, PythonPath
```python
Door_ipadiffx_1 [1]: Pool_ipadiffx_1.put_property({"PoolPath":poolPathList})
Door_ipadiffx_1 [1]: _MACRO_SERVER.put_property({"MacroPath":macroPathList})
Door_ipadiffx_1 [1]: _MACRO_SERVER.put_property({"PythonPath":pythonPathList})
```

And for infos this is how I create my GUI with Taurus (Only for the first project for the moment)
```python
if __name__ == "__main__":
    registerExtensions()
    app = TaurusApplication(sys.argv, cmd_line_parser=None,)

    app.setOrganizationName(IpanemaSettings.organizationName)
    app.setOrganizationDomain(IpanemaSettings.organizationDomain)
    app.setApplicationName(IpanemaSettings.applicationNameScanXGUI)
    app.setApplicationVersion(IpanemaSettings.applicationVersion)

    mainWindow = MainWindow()

    sys.exit(app.exec_())
```

Question 1: should I have 2 Doors, 2 Pools something else ?
Option A: 
      - I have 2 Doors(Is it possible) like "Door_ipadiffx_1" and "Door_ipatomo_1" with one Pool in each Door.
      - I think this will solve the "PoolPath" because it looks like I can have 2 PoolPaths.
      - What about _MACRO_SERVER , do we have one per Door ?
      - Should I put the Door information or Pool somewhere in my code for the GUI ?

Option B: 
      - I have 1 Doors(Is it possible) like "Door_ipanema_1" and 2 Pools "Pool_ipadiffx_1" and "Pool_ipatomo_1"
      - I think this will solve the "PoolPath" because it looks like I can have 2 PoolPaths.
      - What about _MACRO_SERVER , do we have one per Pool ?
      - Should I put the Door information or Pool somewhere in my code for the GUI ?

The 'Option A' I prefer because then i will not to have to rename my "Door_ipadiffx_1" but just to add the other,
and also because when we start Spock we work on a Door so it might have sens.

Question 2: how to create 2 Doors (or 2 Pool) and how to define a Controller (defctrl) in only one of the Door (or Pool)

Thanks in advance for the Help.
Marouane

**Comment by HEnquist** [comment]
I would say that using two completely separate Sardana instances would be the easiest. They can coexist in the same tangoDB without problems.
When you run Sardana with an instance name that doesn't exist in the tangoDB, it will ask if you want to create it. SO if you run "Sardana the_other_project" it will say something like: "the_other_project" isn't defined in the database, do you want to create it?
If you answer yes, then it will create a new Pool, MacroServer and Door for you.
Then you create a new spock profile "spock --profile=some_new_name", and connect it to the new Door. Then when you do defctrl that will go in the new Pool.
For Taurus apps you should not need to do anything special, just connect to the devices exported by the Pool you want to work with.

**Comment by reszelaz** [comment]
Hi all,

Yes, having in mind your description: "2 different projects" I would go the way that @HEnquist proposes.
I think for sure you would need two doors - one door can run only one macro at the same time.
If these are two independent setups and you create two TaurusGUIs then each one will be connected to a different Door and could generate you Pool instruments panels from different setups.

I think this does not apply to you, but:
If there are some elements which would be shared between these two systems you could consider having: one Pool and one MacroServer and two Doors (or eventually two MacroDervers and two Doors connected to the same Pool - but I do not recall anyone using this architecture).

Also, I think there were several issues addressing similar/related problems e.g. https://github.com/sardana-org/sardana/issues/1289, https://github.com/sardana-org/sardana/issues/51, ...

**Comment by marouanebj** [comment]
First Thanks for the very fast replies.

So I created a new Door "Door_ipatomo_1" and here the resumé, with some questions:

1/ MACRO SERVER
Configuring the MACRO_SERVER WAS STRANGE for MacroPath and PythonPath
   ` _MACRO_SERVER.put_property` HAS disapeared, I guess it is Obsolete. Is it ?
So I tryed Doing this IT DID NOT WORK :
    `_MACRO_SERVER.putEnvironment("MacroPath", ["/home/marouane/ipa-ohw/thorlabs_tango/ipanematomo/sardana/macros"])`
    `_MACRO_SERVER.putEnvironment("PythonPath", ["/home/marouane/ipa-ohw/thorlabs_tango"])`
    => It setted something somewhere (NOT IN THE Database tango), the getEnvironment() returned my set, but I did not understand and it did not work (=Macros not available).
I looked in the MariaDB and comparing with "ipadiffx" (and having found a /tmp/tango/Sardana/ipatomo/macroserver.properties file), I DID THIS.
```
INSERT INTO property_device (device, name, count, value) VALUES ("MacroServer/ipatomo/1", "EnvironementDb", 1, "/tmp/tango/Sardana/ipatomo/macroserver.properties");
INSERT INTO property_device (device, name, count, value) VALUES ("macroServer/ipatomo/1", "MacroPath", 1, "/home/marouane/ipa-ohw/thorlabs_tango/ipanematomo/sardana/macros");
INSERT INTO property_device (device, name, count, value) VALUES ("macroServer/ipatomo/1", "PythonPath", 1, "/home/marouane/ipa-ohw/thorlabs_tango");

```    
   My Macros are working NOW.

Is the "/tmp/tango/Sardana/ipatomo/macroserver.properties" still used in the last version of sardana ?
Is the "EnvironementDb" still used in the last version of Sardana ? Can I delete Those from my MariaDB ?

2/ CONTROLLERS
undefine of elements and controllers for "ipadiffx" and defining for "ipatomo":
a/ With spock --profile=ipadiffx
        I did :
```
Door_ipadiffx_1 [6]: udefelem motmirrorx
Door_ipadiffx_1 [7]: udefelem motmirrorz
Door_ipadiffx_1 [8]: udefelem motmirrorxz
Door_ipadiffx_1 [9]: udefctrl mirrorctrl
```
b/ Then with spock --profile=ipatomo
        I did :
 ```
Door_ipatomo_1 [6]: defctrl MirrorKDC101MotorController mirrorctrl serialNumber1 27505047 serialNumber2 27505012 serialNumber3 27505089
Door_ipatomo_1 [7]: defelem motmirrorx mirrorctrl 1
Door_ipatomo_1 [8]: defelem motmirrorz mirrorctrl 2
Door_ipatomo_1 [9]: defelem motmirrorxz mirrorctrl 3
```

All is working I have the correct access to my motors and list of motors(lsm) with spock in both "ipadiffx" and "ipatomo".
But here is What I have in the MariaDB tango.
```
MariaDB [tango]> select device, name,count,value from property_device where device like "%ipadiffx%" order by 1,2,3,4;
+----------------------------------------+---------------+-------+---------------------------------------------------------------+
| device                                 | name          | count | value                                                         |
+----------------------------------------+---------------+-------+---------------------------------------------------------------+
| Door/ipadiffx/1                        | Id            |     1 | 1                                                             |
| dserver/Sardana/ipadiffx               | __SubDevices  |     1 | tango://bantam.ipanema.cnrs.fr:10000/dserver/sardana/ipadiffx |
| dserver/Sardana/ipadiffx               | __SubDevices  |     2 | tango://bantam.ipanema.cnrs.fr:10000/motor/minskvmactrl/1     |
| dserver/Sardana/ipadiffx               | __SubDevices  |     3 | tango://bantam.ipanema.cnrs.fr:10000/motor/minskvmactrl/2     |
| dserver/Sardana/ipadiffx <= NOT ipatomo| __SubDevices  |     4 | tango://bantam.ipanema.cnrs.fr:10000/motor/mirrorctrl/1       |
| dserver/Sardana/ipadiffx <= NOT ipatomo| __SubDevices  |     5 | tango://bantam.ipanema.cnrs.fr:10000/motor/mirrorctrl/3       |
| dserver/Sardana/ipadiffx <= NOT ipatomo| __SubDevices  |     6 | tango://bantam.ipanema.cnrs.fr:10000/motor/mirrorctrl/2       |
| dserver/Sardana/ipadiffx               | __SubDevices  |     7 | tango://bantam.ipanema.cnrs.fr:10000/motor/hydraxyzoctrl/4    |
| dserver/Sardana/ipadiffx               | __SubDevices  |     8 | tango://bantam.ipanema.cnrs.fr:10000/motor/hydraxyzoctrl/1    |
| dserver/Sardana/ipadiffx               | __SubDevices  |     9 | tango://bantam.ipanema.cnrs.fr:10000/motor/hydraxyzoctrl/2    |
| dserver/Sardana/ipadiffx               | __SubDevices  |    10 | tango://bantam.ipanema.cnrs.fr:10000/motor/hydraxyzoctrl/3    |
| dserver/Sardana/ipadiffx               | __SubDevices  |    11 | tango://bantam.ipanema.cnrs.fr:10000/motor/zaberxlsmctrl/1    |
| MacroServer/ipadiffx/1                 | EnvironmentDb |     1 | /tmp/tmpnjogp687/Sardana/ipadiffx/macroserver.properties      |
| macroserver/ipadiffx/1                 | MacroPath     |     1 | /home/marouane/instrum-x/sardana/macrosFAKE                   |
| MacroServer/ipadiffx/1                 | PoolNames     |     1 | pool/ipadiffx/1                                               |
| macroserver/ipadiffx/1                 | PythonPath    |     1 | /home/marouane/instrum-x/taurus/gui/src                       |
| macroserver/ipadiffx/1                 | __SubDevices  |     1 | tango://bantam.ipanema.cnrs.fr:10000/pool/ipadiffx/1          |
| macroserver/ipadiffx/1                 | __SubDevices  |     2 | tango://bantam.ipanema.cnrs.fr:10000/dserver/sardana/ipadiffx |
| mg/pool_ipadiffx_1/_mg_ms_10693_1      | elements      |     1 | 18                                                            |
....
| mntgrp/pool_ipadiffx_1/mntgrpsdd       | id            |     1 | 45                                                            |
| pool/ipadiffx/1                        | PoolPath      |     1 | /home/marouane/instrum-x/sardana/controllersFAKE              |
+----------------------------------------+---------------+-------+---------------------------------------------------------------+
```


```
MariaDB [tango]> select device, name,count,value from property_device where device like "%ipatomo%" order by 1,2,3,4;
+-----------------------+----------------+-------+-----------------------------------------------------------------------+
| device                | name           | count | value                                                                 |
+-----------------------+----------------+-------+-----------------------------------------------------------------------+
| Door/ipatomo/1        | Id             |     1 | 1                                                                     |
| MacroServer/ipatomo/1 | EnvironementDb |     1 | /tmp/tango/Sardana/ipatomo/macroserver.properties                     |
| macroServer/ipatomo/1 | MacroPath      |     1 | /home/marouane/ipa-ohw/thorlabs_tango/ipanematomo/sardana/macros      |
| MacroServer/ipatomo/1 | PoolNames      |     1 | pool/ipatomo/1                                                        |
| macroServer/ipatomo/1 | PythonPath     |     1 | /home/marouane/ipa-ohw/thorlabs_tango/                                |
| pool/ipatomo/1        | PoolPath       |     1 | /home/marouane/ipa-ohw/thorlabs_tango/ipanematomo/sardana/controllers |
+-----------------------+----------------+-------+-----------------------------------------------------------------------+
```

The stange lines are marked with "<= NOT ipatomo" Because I defined them in spock --profile=ipatomo. I do no tunderstand why ?

The other stange one is "EnvironementDb" containing "/tmp/tmpnjogp687/Sardana/ipadiffx/macroserver.properties" BUT THIS IS BECAUSE I HAD Problemes with migration.

Thanks

**Comment by marouanebj** [comment]
HI read this before previous:
About "<= NOT ipatomo" What I have in the MariaDB tango is OK NOW
```
| dserver/Sardana/ipatomo | __SubDevices   |     1 | tango://bantam.ipanema.cnrs.fr:10000/motor/mirrorctrl/1                                |
| dserver/Sardana/ipatomo | __SubDevices   |     2 | tango://bantam.ipanema.cnrs.fr:10000/dserver/sardana/ipatomo                           |
| dserver/Sardana/ipatomo | __SubDevices   |     3 | tango://bantam.ipanema.cnrs.fr:10000/motor/mirrorctrl/3                                |
| dserver/Sardana/ipatomo | __SubDevices   |     4 | tango://bantam.ipanema.cnrs.fr:10000/motor/mirrorctrl/2                                |
| dserver/Sardana/ipatomo | __SubDevices   |     5 | tango://bantam.ipanema.cnrs.fr:10000/controller/mirrorkdc101motorcontroller/mirrorctrl |
```

**Comment by reszelaz** [comment]
> So I created a new Door "Door_ipatomo_1" 

IMPORTANT: Could you clarify if you created only a new Door device within the same Sardana server? Or you created a separate Sardana server instance?

From this https://github.com/sardana-org/sardana/issues/1511#issuecomment-788038963 I think that you have created a new Sardana server, which also implies a new Door.

> ` _MACRO_SERVER.put_property` HAS disapeared, I guess it is Obsolete. Is it ?

No, it is not obsolete. It does not appear in the spock's Tab completion, but if you execute this method it will actually put the property on the Tango DB. After doing so, please remember to restart the Sardana (or MacroServer) server:

```
Door_zreszela_1 [9]: _MACRO_SERVER.put_property({"MacroPath": ['/homelocal/zreszela/workspace/sardana/src/sardana/macroserver/macros/examples', '/homelocal/zreszela/workspace/macros']})

Door_zreszela_1 [10]: _MACRO_SERVER.get_property("MacroPath")
        Result [10]: {'MacroPath': ['/homelocal/zreszela/workspace/sardana/src/sardana/macroserver/macros/examples', '/homelocal/zreszela/workspace/macros']}
```


> So I tryed Doing this IT DID NOT WORK :
> `_MACRO_SERVER.putEnvironment("MacroPath", ["/home/marouane/ipa-ohw/thorlabs_tango/ipanematomo/sardana/macros"])`
> `_MACRO_SERVER.putEnvironment("PythonPath", ["/home/marouane/ipa-ohw/thorlabs_tango"])`
> => It setted something somewhere (NOT IN THE Database tango), the getEnvironment() returned my set, but I did not understand and it did not work (=Macros not available).

This is not the way to configure it. MacroPath is not intended to be stored as an environment variable. It worked, cause you can create an environment variable with this name, but the MacroServer will not consider it to look for macros.

> I looked in the MariaDB and comparing with "ipadiffx" (and having found a /tmp/tango/Sardana/ipatomo/macroserver.properties file), I DID THIS.
> 
> ```
> INSERT INTO property_device (device, name, count, value) VALUES ("MacroServer/ipatomo/1", "EnvironementDb", 1, "/tmp/tango/Sardana/ipatomo/macroserver.properties");
> INSERT INTO property_device (device, name, count, value) VALUES ("macroServer/ipatomo/1", "MacroPath", 1, "/home/marouane/ipa-ohw/thorlabs_tango/ipanematomo/sardana/macros");
> INSERT INTO property_device (device, name, count, value) VALUES ("macroServer/ipatomo/1", "PythonPath", 1, "/home/marouane/ipa-ohw/thorlabs_tango");
> ```
> 
> My Macros are working NOW.

Yes, this works. But this is a very low level of setting properties. I would not recommend it. Better use `put_property` method.
> 
> Is the "/tmp/tango/Sardana/ipatomo/macroserver.properties" still used in the last version of sardana ?
> Is the "EnvironementDb" still used in the last version of Sardana ? Can I delete Those from my MariaDB ?

Yes, it is used. `EnvironmentDb` property makes sense only if you change the default location. The location that you pasted above looks like a default one.

> 
> 2/ CONTROLLERS
> undefine of elements and controllers for "ipadiffx" and defining for "ipatomo":
> a/ With spock --profile=ipadiffx
> I did :
> 
> ```
> Door_ipadiffx_1 [6]: udefelem motmirrorx
> Door_ipadiffx_1 [7]: udefelem motmirrorz
> Door_ipadiffx_1 [8]: udefelem motmirrorxz
> Door_ipadiffx_1 [9]: udefctrl mirrorctrl
> ```
> 
> b/ Then with spock --profile=ipatomo
> I did :
> 
> ```
> Door_ipatomo_1 [6]: defctrl MirrorKDC101MotorController mirrorctrl serialNumber1 27505047 serialNumber2 27505012 serialNumber3 27505089
> Door_ipatomo_1 [7]: defelem motmirrorx mirrorctrl 1
> Door_ipatomo_1 [8]: defelem motmirrorz mirrorctrl 2
> Door_ipatomo_1 [9]: defelem motmirrorxz mirrorctrl 3
> ```

If for the IMPORTANT question you answer that you created a new Sardana server then it looks OK.

> The other stange one is "EnvironementDb" containing "/tmp/tmpnjogp687/Sardana/ipadiffx/macroserver.properties" BUT THIS IS BECAUSE I HAD Problemes with migration.

Yes, I remember that you had problems then. If you want, you can fix it by moving the files `/tmp/tmpnjogp687/Sardana/ipadiffx/*` inside of `/tmp/tango/Sardana/ipadiffx` and then remove this property.

**Comment by marouanebj** [comment]
>     So I created a new Door "Door_ipatomo_1"
> 
> IMPORTANT: Could you clarify if you created only a new Door device within the same Sardana server? Or you created a separate Sardana server instance?
> 

Here is what I did:

```shell
marouane@gaston:~/ipa-ohw/thorlabs_tango$ Sardana ipatomo --log-level=debug
   it asks: Do you wish to create a new one (Y/n) ?
```
I answered YES so know I have my Door_ipatomo_1 and Pool_ipatomo_1  in the database.
I think it created only a new Door within the same Sardana server.
Is there a query I can type in tango database to know if I have 2 Doors only or 2 Sardana instances.

**Comment by reszelaz** [comment]
Thanks for the clarification. What you have done is explained in this chapeter of the documentation: [Running Sardana as a tango server](https://sardana-controls.org/users/getting_started/running_server.html#running-sardana-as-a-tango-server).

This Sardana server, at the creation time, it is populated with one Pool device, one MacroServer device and one Door device. Then continue reading about [Running the client](https://sardana-controls.org/users/getting_started/running_cli.html#sardana-getting-started-running-cli) to know how Spock connects the the Door device.

> I think it created only a new Door within the same Sardana server.

What you have done is that you have created a new Sardana server `ipatomo` (with its Door) completelly independent from your initial Sardana server `ipadiffx` (which has its own Door). I think this is what you needed.

> Is there a query I can type in tango database to know if I have 2 Doors only or 2 Sardana instances.

Yes, in [Using spock as a Tango console](https://sardana-controls.org/users/spock.html#using-spock-as-a-tango-console) you will find a link to ITango. You can use it to make queries directly in Spock, take a look on this examples:

1. List Sardana servers:

```
Door_zreszela_1 [1]: lsserv Sardana
Sardana/zreszela               Sardana/vds
```

2. List Door devices:
```
Door_zreszela_1 [2]: lsdev Door
Device                                   Alias                     Server                    Class               
---------------------------------------- ------------------------- ------------------------- --------------------
Door/bl29/1                              Door_bl29_1               MacroServer/bl29          Door                
door/demo1/1                                                       MacroServer/unittest1_1   Door                
Door/id/1                                Door_id_1                 MacroServer/id            Door                
Door/test/1                              Door_test_1               MacroServer/test          Door                
Door/vds/1                               Door_vds_1                Sardana/vds               Door                
Door/zreszela/1                          Door_zreszela_1           Sardana/zreszela          Door
```

Note that here I have some Door devices which belong to a MacroServer server. This is a different architecture of using Sardana, with separate Pool and MacroServer servers as explained in: [Running Pool and MacroServer tango servers separately](https://sardana-controls.org/users/getting_started/running_server.html#running-pool-and-macroserver-tango-servers-separately).

Hope I have clarified something and not made it more complicated :)

**Comment by marouanebj** [comment]
I read the doc specially "Running Pool and MacroServer tango servers separately" 
So some questions:
1/ When we run "Sardana ipadiffx" is it equals to running both "Pool ipadiffx" and "MacroServer ipadiffx"?

for Doors i'm not completely clear but I let that for futur.

**Comment by reszelaz** [comment]
> 1/ When we run "Sardana ipadiffx" is it equals to running both "Pool ipadiffx" and "MacroServer ipadiffx"?

Yes, in some sense you can call it _equal_. There is just this difference that when you run Sardana, you have the whole server side (Pool, MacroServer, Door(s), and then all your elements that you will create with `defelem` macro) in one Python process.

In contrary, when you run separatelly Pool and MacroServer servers, you would end up with two Python processes: in one process Pool with all your elements that you will create with `defelem` macro and in the other one MacroServer and Door(s).
