### ISSUE TITLE
Recovering and resetting Last DialPosition to my Motor

### ISSUE THREAD

**Issue by marouanebj** [sardana-org/sardana#1513]
Hi,

I have a Motor where I can tell it is at a certain position (=setPosition) this means it will not move but it will reset itself to say it is its position now.
I can also Home that Motor, and that will move it to home position and setPosition to 0.

When I use my motor through sardana I have in the tangoDB my last DialPosition.
My first approach:
I would like to propose through my GUI options of Homing and/or Initializing the motor.
OR Home the motor
OR Home the motor then move it to last DialPosition
OR setPosition to be DialPosition
OR setPosition to be whatever he wants (the move to that position to save the DialPosition in the tangoDB).

Q1: I would like to know how can I get the DialPosition of my motor from the tangoDB ?

My second approach:
Q2: I found some code in Motor.py:
```
def init_device(self): 
    ...
    if self.in_constructor:
                try:
                    w_pos, w_ts = self.get_write_dial_position_from_db()
                    self.in_write_position = True
                    try:
                        motor.set_write_position(w_pos, timestamp=w_ts)
                    finally:
                        self.in_write_position = False
                except KeyError:
                    pass
    ...
```
And I would like to know If I can execute something in my MotorController when `motor.set_write_position(w_pos, timestamp=w_ts)` is called?

Thanks

**Comment by marouanebj** [comment]
I could recover the DialPosition of my motmirrorx with the code here after.
```
import tango
db = db = tango.Database()
p = db.get_device_attribute_property(motmirrorx.name(), "DialPosition")["DialPosition"]
dialPos = float(p["__value"][0])
```
Is it a good way?

**Comment by reszelaz** [comment]
Hi @marouanebj,

First of all, sorry for the late answer. 

> When I use my motor through sardana I have in the tangoDB my last DialPosition.

Exactly, it stores the last requested dial position (but the request is for the Position attribute and DialPosition is read only) i.e. the last move target.

> Q1: I would like to know how can I get the DialPosition of my motor from the tangoDB ?

Your answer from https://github.com/sardana-org/sardana/issues/1513#issuecomment-792655535 should do the job.
You could also use:

```python
float(tango.AttributeProxy("mot01/dialposition").get_property("__value")["__value"][0])
```

> Q2: I found some code in Motor.py:
[...]
And I would like to know If I can execute something in my MotorController when motor.set_write_position(w_pos, timestamp=w_ts) is called?

IIRC this is executed only at the server startup and is there for the [pseudo motor's drift correction](https://sardana-controls.org/devel/api/api_pseudomotor.html#drift-section) feature to work. I think there is no way to realize about it in the controller (plugin).

Some ideas that may be helpful to you:
- What about always keeping in the controller's cache the dial position setpoint (this is `StartOne()` argument) and exposing it as an extra axis attribute e.g. DialPositionSetpoint
- Please remember that the Position attribute, as any other writable Tango attribute, has its `w_value`.

Related to your problems: [Define a position chapter from the How to write a motor controller](https://sardana-controls.org/devel/howto_controllers/howto_motorcontroller.html#define-a-position).

Sorry if my replies are not very helpful, but maybe I have not understood well your needs.

**Comment by marouanebj** [comment]
Thanks it is more clear.
