### ISSUE TITLE
TriggerGateController in StepScans

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1525]
Hi all,

I am currently implementing a hardware gate generator (DESY PiLC) in order to gate most of my detectors (CCD, Keithley, etc ...).
In addition I also have ZeroDCounters which must be software-gated (this can be nicely configured in the measurement group).
I am not working with continous scan but for now only with step scans.

So in general I would like to implement the DESY PiLC as a `triggerGateController`.
In this scenario I cannot use it as timer/monitor right?
So if I use any Timerable element as timer I do get the following error after a ct:
```
Door_scattering_1 [142]: ct                                                                                           
Wed Mar 17 09:28:17 2021

Elements ended acquisition with:
epoch:
       State: On (09:27:25.839462)
      Status: epoch is On
              Counter is stopped (09:28:17.473397)
tcryo:
       State: On (08:55:30.562803)
      Status: tcryo is On
              Always ON, just reading external Tango Attribute (09:28:17.473570)
pilc_tg:
       State: On (09:27:25.931278)
      Status: pilc_tg is On
              Stopped (09:28:17.490598)
An error occurred while running ct:
PyDs_PythonError: Exception: The synchronization description group has not been initialized

Hint: in Spock execute `www`to get more details
```

In https://sardana-controls.org/devel/howto_controllers/howto_triggergatecontroller.html it is shown how to define the missing synchronization description but I have currently no idea how to provide that to the TriggerGateController?
Have I missed the relevant documentation?

Best

Daniel

**Comment by 13bscsaamjad** [comment]
Hi,

The synchronization description is populated by sardana based on the scan macro (or ct) and its parameters which can be used in the `TriggerGateController` `SynchOne` method to configure the trigger gate hardware. As an example, for step scans `SynchOne` gets called before each step with `SynchParam.Repeats` 1 and for continuous scans it gets value of n based on number of points in the params.

**Comment by dschick** [comment]
many thanks for your quick answer. I already though so.
So maybe I found a bug, since when I create a new measurement group using my `TriggerGateController` and do a `ct` before running any scans, I get the above error.
So the `ct` seem not to populate the synchronization description?

**Comment by dschick** [comment]
after doing at least one scan, I do not get the error due to the missing synchronization description.

However, I am not sure if I got the concept correctly:
I hust have one `CounterTimer` in my current measurement group which is synchronized by my `TriggerGate`.
Following the logs, the gate is correctly started and Sardana recognizes that the gate has finished via the `State` of the `TriggerGateController`.

However, I do not get any output from the timerable going in its `StateOne` method and this is why a simple `ct` hangs, because the timerable never finishes.

**Comment by reszelaz** [comment]
Thanks @dschick for raising this interesting thread and @13bscsaamjad for joining it!

In the case of the step scans, the two concepts: synchronizer and timer overlap a little bit. The timer concept was in Sardana from the very beginning and then with the SEP6 we introduced the synchronizer concept which in my opinion is more general. It may be that for your needs you could use either of them.

BTW, I see in the plugins-catalogue the PiLCTimer and IIRC, @teresanunez was working at some point on the PiLC `TiggerGateController` plugin.

> So maybe I found a bug, since when I create a new measurement group using my TriggerGateController and do a ct before running any scans, I get the above error.

From your description it could be that you are hitting #1473, I remember that @cpt-majkel suffered this bug when his counter/timer controllers were not returning `latency_time` correctly. See the _Warning_ section from [Multiple acquisitions chapter of the How to write counter/timer controller](https://sardana-controls.org/devel/howto_controllers/howto_countertimercontroller.html#multiple-acquisitions)

> However, I do not get any output from the timerable going in its StateOne method and this is why a simple ct hangs, because the timerable never finishes.

Do you also configure the synchronization type in the counter/timer controller? See the [Sychronization type chapter of the How to write counter/timer controller](https://sardana-controls.org/devel/howto_controllers/howto_countertimercontroller.html#synchronization-type)

**Comment by dschick** [comment]
thanks for making this clear.
I made it a least once to make a `ct` work with my `TriggerGateController` but I would then stay with my `Timer` instead.

However, I would need to make sure that my master timer is always started as the last one, I guess you are discussing this just in #1516 ?

**Comment by reszelaz** [comment]
> However, I would need to make sure that my master timer is always started as the last one, I guess you are discussing this just in #1516 ?

Simply putting it at the very top in the `expconf` should be enough to start it as the last one. Then keep using _software trigger_ in the Synchronizer and Synchronization columns.  Let us know if it does not work.

**Comment by dschick** [comment]
okay, thank you so far. I will reopen it, if I encounter any issues.
However, it was a bit tricky to find all the information in the docs, which are a bit clattered around the SEPs and controller docs.
Maybe it is worth updating the docs for the Acquisition with details about the Synchronization.

Thanks again for your help
