### ISSUE TITLE
move regscan from examples to scans

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1537]
Hi, we are heavily using the great `regscan` macro.
But currently it is only located in the `macro/examples` folder instead of in the `macro/scans.py`.

if there no argument against moving it I would prepare a PR.

**Comment by reszelaz** [comment]
I see it as a very good idea. At ALBA several times our users complained that these macros were not available because we (controls) forgot to add the path to the examples to the `MacroPath`. 

If we agree to move `regscan` there, I would move in one bunch `reg2scan` and `reg3scan`.

**Comment by dschick** [comment]
sure, I am just wondering if they should also inherit from `aNscan` as well in order to solve #891 ?

**Comment by reszelaz** [comment]
I think it won't be easy to make the `regscan` inherit from `aNscan`. 
I would go for:
> make the motors a standard member of all macros having the said hook places.

from https://github.com/sardana-org/sardana/issues/1472#issuecomment-763148599, so add `motors` to `regscan`.

**Comment by reszelaz** [comment]
Done in #1540
