### ISSUE TITLE
Since the code moved to Gitlab can I still Ask questoins here

### ISSUE THREAD

**Issue by marouanebj** [sardana-org/sardana#1542]
Hello,
Since the code moved to Gitlab can I still Ask questions here ?

**Comment by reszelaz** [comment]
Hi @marouanebj,
For the moment only the [Taurus](https://gitlab.com/taurus-org/taurus) project was moved to Gitlab. Today, on the follow-up meeting, we will discuss if to do the same for Sardana.
So, as of today, here is the correct place to ask questions.
Cheers!
