### ISSUE TITLE
Jan21 manual release tests: Debian 9

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1548]
This is an issue for checking the Jan21 release in Debian 9

This is a check-list of manual tests. It is just orientative. Expand it
at will. This list assumes a clean environment with all Sardana dependencies
already installed and access to a Tango system with the TangoTest DS running.

Hint: this list can be used as a template to be copy-pasted on a release manual test issues

### Installation
- [x] Install Sardana (on Linux from the tar.gz : `pip3 install <tarball_artifact_URL>` (in conda use `pip`) 
  and on Windows from MSI)

### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `tango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
  **Note:** Remember to use OS path separator e.g. `/` on Linux and `\` on 
  Windows
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
- [x] In spock run `sar_demo` macro.
- [x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [x] Run testsuite. In another console do `pytest <path_to_sardana_installation_dir>`
  **Note:** On openSuse 11.1 and Windows there are known problems with 
  testsuite. Check previous release comments.

### Test Sardana using Spock and expconf
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
  **Note**: On Windows there is printed RuntimeWarning about difference between
  stdin and stdout encoding.
- [x] Execute `umvr` macro and verify that the position updates arrives.
- [x] In expconf configure scan files by setting ScanDir to: `/tmp/` on Linux
  `C:\Users\<username>\tmp` on Windows and ScanFile to: `demo1.h5, demo1.dat`.
- [x] Configure online plot to show counters: On expconf GUI select for all
  the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
- [x] Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
  attribute.
- [x] Add the `sys/tg_test/1/double_scalar` attribute to the measurement
  group.
- [x] Open online plot: `showscan online` (This should ask to enable JsonRecorder, set it to true. Otherwise enable it in spock: `senv JsonRecorder True`).
- [x] Run step scan
- [x] Verify that records appear in spock output.
- [x] Verify that records were stored in scan files.
- [x] Verify that records were plotted on the online plot
- [ ] Run `showscan` and access to the last scan data.
**I get an error coming from HDF5Widget**
- [x] With `edmac` modify existing macro: `ask_peak` and run it to verify that the change
  was applied.
- [x] With `edmac` create a new macro in a new macro library:
  `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py`
  and run it.
  **Note:** Remember to use OS path separator e.g. '/' on Linux and '\' on 
  Windows

### Test Sardana with TaurusGUI
- [x] Create a new GUI from scratch using TaurusGUI: `$ taurus newgui`
  - project page: directory = "/home/<user>/mygui"
  - general settings page: GUI Name = "MyGui"
  - custom logo: NEXT
  - synoptics page: NEXT
  - MacroServer Info page: Enable sardana Communication and select `demo2` MS and Door name
  - Instruments from Pool page: Yes
  - the rest of the pages, NEXT...NEXT...NEXT...FINISH
  - note the message about installing the GUI!
- [x] install the GUI with pip
- [x] launch the GUI: `$ MyGui`
- [x] say yes to enable json (if not done yet)
- [x] set a nice panel layout

#### PMTV (PoolMotorTaurusValue)
- [x] Open a `taurus form` with all slit related motors
- [x] Activate compact mode
  - Move all motors with absolute and relative mode
  - Stop a motor in the middle of it's movement with the stop button
- [x] Activate normal mode (deactivate compact)
  - Move all motors with absolute and relative mode
  - Stop a motor in the middle of it's movement with the stop button
- [x] Activate expert mode
  - Define slit motors limits while the form is open. Expert mode buttons and limit indicators should switch from grey to active colors
  - Check every motor limit with expert buttons
- [x] Move a few motors using absolute and the apply button
- [x] Reset absolute blue values

#### PCTV (PoolChannelTaurusValue)
- [x] Open a `taurus form` with a counter, 1D and 2D experimental channels

For each of the channels repeat the following:
  - [x] For 1D and 2D set a timer: "__self" using the "Tango attributes" form (opened from the context menu on the channel's label)
  - [x] Set integration time e.g. 1, and press return
  - [x] Start acquisition
  - [x] Show value (2nd show does not work)

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [x] Start new sequence
  **Note:** new sequences cannot always be created #305
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### MacroButton

- [x] Start macrobutton:
     ```console
     python3 -m sardana.taurus.qt.qtgui.extra_macroexecutor.macrobutton door_demo2_1
     ```
- [x] Execute `lsmac` macro with default parameter value for filter (`.*`).
- [x] Execute `ascanct` macro.
- [x] Execute `ascan` macro and stop it with the macrobutton (after prior pausing and confirming stopping in the pop-up).

#### QtSpock

- [x] Create default Spock profile (QtSpock requires it): `spock` and connect to `Door_demo2_1`.
- [x] Open QtSpock: `python -m sardana.taurus.qt.qtgui.extra_sardana.qtspock`
- [x] Execute `lsm`
- [x] Execute a ascan
- [x] Stop scan execution with Ctrl+C
- [x] Execute plotting macro examples e.g. `J0_plot` (it's buggy and appears twice, once in the qtconsole, and once in the pop-up dialog)

#### sardanaeditor
**Note:** There are known bugs on CentOS and Windows
- [ ] Open sardanaeditor with macroserver name as argument.
     ```
     python3 -m sardana.taurus.qt.qtgui.extra_sardana.sardanaeditor MS_demo2_1
     ```
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by catunlock** [comment]
Seems that in QtSpock with matplotlib 3.0.3 (that is the latest version available for Python 3.5) after repeating the plotting, J0_plot appears with a remaining image buffer in the background.

![](https://i.imgur.com/aYW6WAw.png)

**Comment by catunlock** [comment]
We found that when doing the PCTV, 2D plot this messages were output in the terminal:

````
MainThread     WARNING  2021-04-28 11:59:04,668 DefaultReadWidgetLabel.tango://sardana-test:10000/expchan/twodctrl02/1/ValueBuffer: Error formatting display (ValueError("Single '}' encountered in format str
ing",)). Reverting to raw string                                                                                                                                                                              
MainThread     WARNING  2021-04-28 11:59:05,987 DefaultReadWidgetLabel.tango://sardana-test:10000/expchan/twodctrl02/1/ValueBuffer: Error formatting display (ValueError("Single '}' encountered in format str
ing",)). Reverting to raw string                                                                                                                                                                              
MainThread     WARNING  2021-04-28 11:59:06,787 DefaultReadWidgetLabel.tango://sardana-test:10000/expchan/twodctrl02/1/ValueBuffer: Error formatting display (ValueError("Single '}' encountered in format str
ing",)). Reverting to raw string                                                                                                                                                                              
MainThread     WARNING  2021-04-28 11:59:07,505 DefaultReadWidgetLabel.tango://sardana-test:10000/expchan/twodctrl02/1/ValueBuffer: Error formatting display (ValueError("Single '}' encountered in format str
ing",)). Reverting to raw string      
````

**Comment by catunlock** [comment]
I would recommend enabling "Single Writer Multiple Reader (SWMR)"  in all the H5 files by default.

**Comment by catunlock** [comment]
We found that depending on the version of python3-pyqtgraph  `showscan online` can fail to plot 

```
Door_demo2_1 [1]: ascan mot06 0 10 10 0.1                                                                                                                                                                                       
Operation will be saved in /tmp/demo1.h5 (HDF5::NXscan from NXscanH5_FileRecorder)                                                                                                                                              
Operation will be saved in /tmp/demo1.dat (Spec from SPEC_FileRecorder)                                                                                                                                                         
Scan #17 started at Tue Apr 27 11:56:38 2021. It will take at least 0:00:04.822854                                                                                                                                              
                                                                 sys                                                                                                                                                            
                                                               tg_test                                                                                                                                                          
                                                                  1                                                                                                                                                             
 #Pt No    mot06      ct05      ct06      ct07      ct08    double_scalar     dt                                                                                                                                                
   0         0        0.1       0.2       0.3       0.4        -167.952    0.945649                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                                                              
  File "/usr/local/lib/python3.5/dist-packages/sardana/taurus/qt/qtgui/macrolistener/macrolistener.py", line 168, in do_update                                                                                                  
    curve_item.setData(x_data.contents(), y_data.contents())                                                                                                                                                                    
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 533, in setData                                                                                                                   
    self.updateItems()                                                                                                                                                                                                          
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 569, in updateItems                                                                                                               
    self.scatter.setData(x=x, y=y, **scatterArgs)                                                                                                                                                                               
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 469, in setData                                                                                                                
    self.addPoints(*args, **kargs)                                                                                                                                                                                              
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 575, in addPoints                                                                                                              
    setMethod(kargs[k], update=False, dataSet=newData, mask=kargs.get('mask', None))                                                                                                                                            
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 636, in setPen                                                                                                                 
    dataSet['sourceRect'] = 0                                                                                                                                                                                                   
TypeError: a bytes-like object is required, not 'int'                                                                                                                                                                           
Traceback (most recent call last):                                                                                                                                                                                              
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 785, in viewRangeChanged                                                                                                          
    self.updateItems()                                                                                                                                                                                                          
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 569, in updateItems                                                                                                               
    self.scatter.setData(x=x, y=y, **scatterArgs)                                                                                                                                                                               
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 469, in setData                                                                                                                
    self.addPoints(*args, **kargs)                           
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 575, in addPoints
    setMethod(kargs[k], update=False, dataSet=newData, mask=kargs.get('mask', None))       
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 636, in setPen
    dataSet['sourceRect'] = 0                                                          
TypeError: a bytes-like object is required, not 'int'
[11:56:39]  Ignored exception:                                                            
                                                         
    |==============================>>                                                    
    |  Traceback (most recent call last):  
    |    File "/usr/local/bin/showscan", line 11, in <module>                                                                    
    |      sys.exit(main())  
    |    File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 829, in __call__                                
    |      return self.main(*args, **kwargs)           
    |    File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 782, in main                          
    |      rv = self.invoke(ctx)                          
    |    File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    |      return ctx.invoke(self.callback, **ctx.params)

[11:56:39]  Ignored exception:

    |==============================>>
    |  Traceback (most recent call last):
    |    File "/usr/local/bin/showscan", line 11, in <module>
    |      sys.exit(main())
    |    File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 829, in __call__
    |      return self.main(*args, **kwargs)
    |    File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 782, in main
    |      rv = self.invoke(ctx)
    |    File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    |      return ctx.invoke(self.callback, **ctx.params)
    |    File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 610, in invoke
    |      return callback(*args, **kwargs)
    |    File "/usr/local/lib/python3.5/dist-packages/sardana/taurus/qt/qtgui/extra_sardana/showscanonline.py", line 320, in main
    |      return app.exec_()
    |    File "/usr/local/lib/python3.5/dist-packages/taurus/qt/qtgui/application/taurusapplication.py", line 358, in exec_
    |      ret = Qt.QApplication.exec_(*args, **kwargs)
    |    File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/widgets/GraphicsView.py", line 161, in paintEvent
    |      return QtGui.QGraphicsView.paintEvent(self, ev)
    |    File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/debug.py", line 93, in w
    |      printExc('Ignored exception:')
    |    --- exception caught here ---
    |    File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/debug.py", line 91, in w
    |      func(*args, **kwds)
    |    File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 1069, in paint
    |      self.data['sourceQRect'][viewMask].tolist()))
    |  TypeError: arguments did not match any overloaded call:
    |    drawPixmap(self, QRectF, QPixmap, QRectF): argument 3 has unexpected type 'NoneType'
    |    drawPixmap(self, QRect, QPixmap, QRect): argument 1 has unexpected type 'QRectF'
    |    drawPixmap(self, Union[QPointF, QPoint], QPixmap): argument 1 has unexpected type 'QRectF'
    |    drawPixmap(self, QPoint, QPixmap): argument 1 has unexpected type 'QRectF'
    |    drawPixmap(self, QRect, QPixmap): argument 1 has unexpected type 'QRectF'
    |    drawPixmap(self, int, int, QPixmap): argument 1 has unexpected type 'QRectF'
    |    drawPixmap(self, int, int, int, int, QPixmap): argument 1 has unexpected type 'QRectF'
    |    drawPixmap(self, int, int, int, int, QPixmap, int, int, int, int): argument 1 has unexpected type 'QRectF'
    |    drawPixmap(self, int, int, QPixmap, int, int, int, int): argument 1 has unexpected type 'QRectF'
    |    drawPixmap(self, Union[QPointF, QPoint], QPixmap, QRectF): argument 1 has unexpected type 'QRectF'
    |    drawPixmap(self, QPoint, QPixmap, QRect): argument 1 has unexpected type 'QRectF'
    |==============================<<
```

**Comment by catunlock** [comment]
Did you found some of these "issues" in the tests that you did on Debian 10  @teresanunez ?

**Comment by teresanunez** [comment]
Actually not, I am not aware of any of them.

**Comment by jangarrevoet** [comment]
> I would recommend enabling "Single Writer Multiple Reader (SWMR)" in all the H5 files by default.

Be aware that as far as I remember correctly, Matlab is compiled with HDF5 v.1.8 so it does not support SWMR. If your users thus want to have a look at the data you will have to convert the files.

**Comment by reszelaz** [comment]
@catunlock many thanks for performing the tests and @jangarrevoet and @teresanunez for your comments!

Regarding https://github.com/sardana-org/sardana/issues/1548#issuecomment-828532341, I would not bother about it for the moment cause the feature is still usable with some inconveniences. We at ALBA are the only ones stick to Debian 9, and AFAIK QtSpock is not used yet at our beamlines. If our users complain about it we could come back to this issue and maybe then it would be even possible to move to Debian 10 or even 11. In other words, as a solution to this problem, I would recommend updating matplotlib.

Regarding https://github.com/sardana-org/sardana/issues/1548#issuecomment-829285337, I would not bother about it for the moment cause the feature is still usable with some inconveniences. We at ALBA are the only ones stick to Debian 9, and AFAIK PCTV is not used yet at our beamlines. If our users complain about it we could come back to this issue and maybe then it would be even possible to move to Debian 10 or even 11. In other words, as a solution to this problem, I would recommend updating to the newer versions of dependencies, since this issue does not happen on Debian 10 or in the recent conda-forge/pip stack.

> We found that depending on the version of python3-pyqtgraph showscan online can fail to plot

Yes, this happens with the pyqtqraph which comes with Debian 9. However, ALBA has backported the version which fixes this problem.

> > I would recommend enabling "Single Writer Multiple Reader (SWMR)" in all the H5 files by default.

> Be aware that as far as I remember correctly, Matlab is compiled with HDF5 v.1.8 so it does not support SWMR. If your users thus want to have a look at the data you will have to convert the files.

I think here @catunlock refers to using the [_h5 write session_](https://sardana-controls.org/users/scan.html#nxscanh5-filerecorder) always whenever possible.
Probably, as @jangarrevoet points out, there would be an issue with opening these files with Matlab, but AFAIK at ALBA's beamlines users do not use Matlab. I assume that the issue affects only while the writer (recorder) maintains the file opened in the SWMR mode? As soon as the file is closed by the writer then the Matlab could read the file correctly, right?

With all this feedback I consider the Jan21 artifacts passed the release tests on Debian 9.
