### ISSUE TITLE
Shape not updated in h5recorder 

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana#1560]
Hello,
            we have a problem storing OneD data with the h5 recorder (I would say that
the same problem will happen with TwoD data).
We are using sardana with the new implementation of OneD and TwoD controllers in
which one has to specify the shape (data length).
If we change the length of the oned spectrum and we start an scan saving data in
h5 format, we get an  mismatch between the length that h5 expects (the old one) and the real length. 
A second scan without changing the length will work. I have seen in the h5storage.py file that
the shape is read from the env["datadesc"] during the preparation of the file. The env does not
update the shape that is changed in the controller, but contains the old one. At least this is
what is observed. Have somebody tried this with sucess?. Many thanks.

                    Best Regards,
                                             Teresa

**Comment by reszelaz** [comment]
Hi @teresanunez,
I just checked it using a dummy 1D and it worked for me:

```
Door_zreszela_1 [4]: ascan mot01 0 1 1 0.1
Operation will be saved in /tmp/foo.h5 (HDF5::NXscan from NXscanH5_FileRecorder)
Scan #1 started at Thu Apr 15 23:05:02 2021. It will take at least 0:00:01.094427
 #Pt No    mot01      ct01     oned01      dt   
   0         0        0.1     (1024,)   0.0794532
   1         1        0.1     (1024,)   2.42222 
Operation saved in /tmp/foo.h5 (HDF5::NXscan)
Scan #1 ended at Thu Apr 15 23:05:05 2021, taking 0:00:02.559187. Dead time 92.2% (motion dead time 87.0%)

Door_zreszela_1 [5]: oned01.RoI = [10, 20]

Door_zreszela_1 [6]: ascan mot01 0 1 1 0.1
Operation will be saved in /tmp/foo.h5 (HDF5::NXscan from NXscanH5_FileRecorder)
Scan #2 started at Thu Apr 15 23:06:04 2021. It will take at least 0:00:01.988854
 #Pt No    mot01      ct01     oned01      dt   
   0         0        0.1      (10,)    0.946305
   1         1        0.1      (10,)    3.27678 
Operation saved in /tmp/foo.h5 (HDF5::NXscan)
Scan #2 ended at Thu Apr 15 23:06:07 2021, taking 0:00:03.406464. Dead time 94.1% (motion dead time 91.7%)
```

I tried it with a debugger and https://github.com/sardana-org/sardana/blob/5ddbf01cd44b570f11eaf2601e30b0c716d82028/src/sardana/macroserver/scan/gscan.py#L717 is called at each scan.

**Comment by teresanunez** [comment]
Hi Zibi, with the dummy also works for me ... I have to investigate what is going on with ours.

**Comment by teresanunez** [comment]
Hi Zibi,
               I have now checked with the debugger. The difference that I see is that in the function
_get_shape from gscan.py for the DummyOneD controller channel.shape has the updated value,
but for my controller the value that channel.shape gives is the old one. The second time that the
scan run (without changing the shape between both) channel.shape returns the right value. I can 
not see any difference between the implementation of shape in the dummy und in my controller.
Do you have any hint where I could look at?. Many thanks.

                       Best Regards,
                                                 Teresa

**Comment by teresanunez** [comment]
I see now the problem. The function getAxisPar implementing the readout of the shape in my the controller is never called.
Instead of that I get the warning telling that the not implementation of shape is deprecated. But it is implemented !.
Is it not enough adding this to the controller:

    def GetAxisPar(self, axis, par):
        if par == "shape":
            return [self.proxy[ind-1].read_attribute("samples_per_record").value]
 

Many thanks and sorry for the problem.

**Comment by reszelaz** [comment]
At the first sight your code looks ok. Maybe try if the Pool uses this code by placing a log in the constructor. On Monday I could help you more when I'll be on my PC again.

**Comment by teresanunez** [comment]
Hi Zibi,
            thanks, yes, I have already checked that this code is used ... and it is.

**Comment by teresanunez** [comment]
Hi Zibi, sorry, it was actually a stupid typo in the code of the controller. It is solved now. Many thanks.
