### ISSUE TITLE
How to define Pools, MacroServer and Doors to have an integrated environment with SardanaControllers on 2 computers.

### ISSUE THREAD

**Issue by marouanebj** [sardana-org/sardana#1565]
Hello,

Pre subject: Starting a Pool with Pool cmd that has been created running Sardana cmd and not by Pool cmd.

I runned and got no problems with a Sardana server running:
> Sardana ipatomo

As I understand from the doc it starts a server serving both a 'pool' and a 'macroserver'
I guess it created all those the first time I started it.
Here is the content of my db:
MariaDB [tango]> select alias, name,host from device where name like "%ipatomo%";
+----------------+-------------------------+------------------------+
| alias          | name                    | host                   |
+----------------+-------------------------+------------------------+
| Pool_ipatomo_1 | pool/ipatomo/1          | bantam.ipanema.cnrs.fr |
| MS_ipatomo_1   | MacroServer/ipatomo/1   | bantam.ipanema.cnrs.fr |
| NULL           | dserver/Sardana/ipatomo | bantam.ipanema.cnrs.fr |
| Door_ipatomo_1 | Door/ipatomo/1          | bantam.ipanema.cnrs.fr |
+----------------+-------------------------+------------------------+

Now after stopping the Sardana server I want to launch just the Pool.
so I tryed all these.
marouane@bantam:~/ipa-ohw/thorlabs_tango/ipanematomo$ Pool ipatomo
ipatomo does not exist. Do you wish to create a new one (Y/n) ? n
Pool startup aborted
marouane@bantam:~/ipa-ohw/thorlabs_tango/ipanematomo$ Pool Pool_ipatomo
pool_ipatomo does not exist. Do you wish to create a new one (Y/n) ? n
Pool startup aborted
marouane@bantam:~/ipa-ohw/thorlabs_tango/ipanematomo$ Pool Pool_ipatomo_1
pool_ipatomo_1 does not exist. Do you wish to create a new one (Y/n) ? n
Pool startup aborted

So here is the base questions:
Can I start the 'Pool of ipatomo' just with the Pool command ?
Will I be able to connect that pool to another MacroServer than the one created by Sardana cmd ?

My goal at the end:

How to define Pools, MacroServer and Doors to have an integrated environment with SardanaControllers on 2 computers.
related question https://github.com/sardana-org/sardana/issues/1511

Here is the configuration that I would like to deploy.
2 machines (TomoPC, CommonPC, GuiPC), TomoPC and CommonPC controls different motors.
And a GuiPC to run spock have my PyQTGui, and be able to run macros that handle motors from both sides.

My current view:
Pool_ipatomo_1 with 2 MirrorMotorController (motmirrorx and motmirrorz)
Pool_ipacommon_1 with 1 IpaTestMotorController (motipatestx)

I start on TomoPC the Pool ipatomo: Pool ipatomo
I declare some controllers and elem there.
Question will this create a Door just for that Pool ?

I start on CommonPC the Pool ipacommon: Pool ipacommon
I declare other controllers and elem there.

I want to run a macro that needs all motors accessible so I guess I have to run a MacroServer (msipa),
and I understand that I can connect it to both pools (Pool_ipatomo_1, Pool_ipacommon_1), is this OK ?

When Using spock I need to pick only 1 Door.
So What about the Door:
 Should I create a Door connected to both Pools and the MacroSever ?
 If yes how ?

Thanks,

**Comment by reszelaz** [comment]
> Can I start the 'Pool of ipatomo' just with the Pool command?

Yes, but it is not so straightforward. You will need to make some reconfigurations (shutdown the Sardana Tango device server first).
I think the easiest would be to:
1. Rename the "Sardana/ipatomo" Tango device server to "Pool/ipatomo" Tango device server (this will re-assign all the Tango devices from one Tango device server, which BTW will disappear, to another one):
   ```python
   import tango

   db = tango.Database()
   db.rename_server('Sardana/ipatomo', 'Pool/ipatomo')
   ```
2. Create a new Tango device server "MacroServer/ipatomo" with two Tango devices: macroserver/ipatomo/1 and door/ipatomo/1. (this will automatically remove these devices from the "Pool/ipatomo" Tango device server created in step 1 at the same time maintaining their Tango properties e.g. PoolNames of the MacroServer Tango device):
   ```python
   import tango
   from tango import DbDevInfo
   
   db = tango.Database()
   
   ms_info = DbDevInfo()
   ms_info.name = "macroserver/ipatomo/1"
   ms_info._class = "MacroServer"
   ms_info.server = "MacroServer/ipatomo"
   
   door_info = DbDevInfo()
   door_info.name = "door/ipatomo/1"
   door_info._class = "Door"
   door_info.server = "Door/ipatomo"
   
   db.add_server("MacroServer/ipatomo", (ms_info, door_info))
   ```


> Will I be able to connect that pool to another MacroServer than the one created by Sardana cmd ?

You mean the other way around: to connect that MacroSerever to another Pool, right? - it works this way.
Yes, you can connect your MacroServer to any Pool at any time.

> 2 machines (TomoPC, CommonPC, GuiPC), TomoPC and CommonPC controls different motors.

Here you mean 3 machines, right?

> Question will this create a Door just for that Pool ?

No, by creating a Pool Tango device server you don't create a Door Tango device. You need to create, either a MacroServer Tango device server or the Sardana Tango device server to create a Door device. Note, a Door device must be always in a Tango device server together with a MacroServer device. There may be many Door devices in such a server.

> I guess I have to run a MacroServer (msipa),
and I understand that I can connect it to both pools (Pool_ipatomo_1, Pool_ipacommon_1), is this OK

Exactly!

> So What about the Door:
Should I create a Door connected to both Pools and the MacroSever ?

When you create the MacroServer/msipa Tango device server it will create you a door Tagno device called door/msipa/1. So, in principle, you just need to connect Spock to that Door.

Hope this helps!

**Comment by dschick** [comment]
I also encountered a similar issue, when I wanted to group some shared hardware in a deticated `Pool` in order to use it in with two `Doors`, see #1289.

I kept starting the shared `Pool` with the `Sardana` command and also created a _unused_ `MacroServer`, since I was not aware of the rename procedure that @reszelaz just described.

However, there was another issue when adding hardware to the `Pool`s (I cannot find the issue for that):
If you `MacroServer` is connected to multiple `Pool`s and you add new hardware e.g. via `defctrl` one cannot specifiy the target `Pool` which should host the hardware.

So in general using multiple `Pool`s is a great concept but it seems rather hacky in reality to me for now.

**Comment by marouanebj** [comment]
Hi,
Here I propose a procedure:
- create PoolA on machine A
- create PoolB on machine B
- create MacroSevrerOnlyA connected to PoolA (creates a DoorOnlyA) => to make the defctrl for PoolA
- create MacroSevrerOnlyB connected to PoolB (creates a DoorOnlyB) => to make the defctrl for PoolB
- create MacroServerAB connected to PoolA and PoolB (creates DoorAB) => Here I can make my macros mixing both pools.
@reszelaz does this work ?

**Comment by dschick** [comment]
this is essentially how I do it, whereas I do not have DoorAB but use DoorB to also connect to A. but this is up to you.

**Comment by marouanebj** [comment]
> this is essentially how I do it, whereas I do not have DoorAB but use DoorB to also connect to A. but this is up to you.

It's not clear for me, I do not have of any DoorB in my procedure.
Do you mean that you have DoorOnlyA, and DoorAB ? But the how do you make defctrl for PoolB ?

**Comment by dschick** [comment]
so DoorB == DoorOnlyB 



> But the how do you make defctrl for PoolB ?

I was refering to this problem, in my former comment.
So in MacroSevrerOnlyB, when it is also connected to PoolA, all `defctrl` will endup in the first Pool of this Door, which will be PoolB (PoolA is added manually as second in my configuration).
In order to add elements to PoolA you need to use MacroServerA.

There has been already a discussion about that (which I cannot find right now) and maybe it will be possible to add a Pool parameter to all `def* ` macros.

**Comment by reszelaz** [comment]
Many thanks @marouanebj and @dschick for proposing this procedure: https://github.com/sardana-org/sardana/issues/1565#issuecomment-823095254. IMO it should work.

The issue that @dschick is referring to is this one: https://github.com/sardana-org/sardana/issues/589.
