### ISSUE TITLE
update py2 -> py3 plotting example

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#1573]
The plotting example 

  https://sardana-controls.org/devel/howto_macros/macros_general.html#plotting

gives the bug reported in

  issue  #1570

To fix it one need to change

```    
y1 = map(j0i, x1)
```     

to 
```    
y1 = list(map(j0i, x1))
```

**Comment by reszelaz** [comment]
@jkotan, thanks for pointing this out. I fixed it 0c12cfc and pushed it directly to develop branch.

BTW, it would be better to insert code inline in the docs from the `sardana.macroserver.macros.example.plotting`. There it was already fixed.
