### ISSUE TITLE
PoolAcquisition keeps polling the state of channels even after aborting the acquisition

### ISSUE THREAD

**Issue by 13bscsaamjad** [sardana-org/sardana#1581]
It is a side-effect of poorly-implemented controller and/or the underlying device of the controller. But it renders Pool process useless until restarted.

### Steps to reproduce
- make experimental channel always return Moving in State calls.
- run any scan and then abort it.
- the pool will still be polling on the channel state and will never recover even after abort because its doing so in wild loop

### Suggested solution
exit condition from state polling based on the scan abortion

**Comment by reszelaz** [comment]
This should be solved by #1582
