### ISSUE TITLE
udef checks dependencies

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1586]
Hi,

we just somehow crashed our Sardana configuration and it was somehow due to the deletion of a motor that was required for several pseudo motors to work and was included in `motor groups`

For the later issue I already opened #1059 

For the first problem I suppose to add a dependency check to the `udefelem` and `udefctrl` macros in order to check if the according element has any dependencies within the connected Pools.

Do you think this is possible?

Best

Daniel

**Comment by reszelaz** [comment]
Hi Daniel,

First of all, sorry for the late reply and thanks for raising this very important issue.
I think it should not be so difficult to implement this check. Here are my first thoughts:

1. It is better to implement this check in [`Pool.delete_element()`](https://github.com/sardana-org/sardana/blob/6952e6c106f47c1dd601401ef335a2f174b07219/src/sardana/pool/pool.py#L550). As you can see in the code, there are other similar checks already present there. This way other clients, not only `udefelem` macro, could make a profit from this check.
2. Currently all the Pool elements are indirectly inheriting from [`EventGenerator`](https://github.com/sardana-org/sardana/blob/6952e6c106f47c1dd601401ef335a2f174b07219/src/sardana/sardanaevent.py#L51) which maintains a list of _listeners_.
3. All Pool elements contain a list of _listeners_ which will react on the `state` attribute change. So, for example,
  - pseudo motor is a listener of motor
  - pseudo counter is a listener of experimental channel
  - motor group is a listener of motor
  - pseudo motor can be a listener of another pseudo motor
  - measurement group is a listener of experimental channel or trigger/gate
  - etc...
4. I think it would be enough to check in the `Pool.delete_element()` if the element being deleted contains listeners of type `PoolBaseElement`. If yes, we should abort the deletion saying that first the listeners should be deleted. (Note, that we may need to add some public API to make this check more clear).

Is anyone volunteering to work on this issue?:) I could help with review/suggestions/pair-programming... I think fixing this issue will be a great improvement for all!

Many thanks!

**Comment by catunlock** [comment]
I'm volunteering to work on this issue

**Comment by dschick** [comment]
many thanks for the propsal.
I would help in testing the changes.

**Comment by catunlock** [comment]
@reszelaz and I are still working on it, we already solved the problem for all types of elements except for the pseudocounters. We are having some trouble deleting them, someone is keeping a reference to them, but we expect to solve this soon.
