### ISSUE TITLE
editing macro parameters in macroexecutor in random order does not work (SF#15)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#16]
Editing macro parameters from graphical parameter editor in random order does not work - value gets reset to the default one - None. One must edit them in order they are listed. This is probably caused by the validation done by spock line.

Reported by: reszelaz ( http://sf.net/u/zreszela )

Original Ticket: [sardana/tickets/15](https://sourceforge.net/p/sardana/tickets/15)

**Comment by mrosanes** [comment]
I could not reproduce this error. I think this ticket can be closed. For macroexecutor and macrosequencer it seems that now the parameters can be edited in random order without problems.

**Comment by reszelaz** [comment]
Yes, this bug is no more reproducible with the latest develop on debian 9. I'm closing it.
