### ISSUE TITLE
PoolMotorTV display value

### ISSUE THREAD

**Issue by kklmn** [sardana-org/sardana#1600]
Hello,

Half of our displayed set values in PoolMotorTV elements are always blue, signalling a recent change:
![image](https://user-images.githubusercontent.com/17322580/120201325-9d166080-c225-11eb-89dc-78176e0b65b3.png)

If you look closer to the bottom of the tooltip, you see that this is actually untrue.
I guess that if this color signaling is considered useful, the comparison should be made not straightly as == but within the machine precision (math.isclose() or numpy.isclose()).

Thank you!

**Comment by reszelaz** [comment]
Hi @kklmn,
I briefly talked about this with @cpascual and we agreed that this is a bug.

I was going to work on this and propose a PR to Taurus (this is actually already a bug in Taurus, and Sardana PMTV widget suffers from it, like any other TaurusValue widget). It would actually speed up the whole process if you propose a PR directly - you already have an idea on how to fix it. I would start with trying to apply changes in [`taurus.core.taurusattribute.TaurusAttribute.areStrValuesEqual()`](https://gitlab.com/taurus-org/taurus/-/blob/develop/lib/taurus/core/taurusattribute.py#L167).

Thanks a lot in advance!

**Comment by HEnquist** [comment]
A fix was already merged in Taurus (https://gitlab.com/taurus-org/taurus/-/merge_requests/1195 ), will be included in the next release.

**Comment by reszelaz** [comment]
I think we can already close this issue. It was actually an enhacement to taurus and it is already implemented. One could start using it with the Taurus develop branch.
