### ISSUE TITLE
pre-scan general hooks block ctrl-c

### ISSUE THREAD

**Issue by HEnquist** [sardana-org/sardana#1603]
If a general hook is placed in the pre-scan position, then it's not possible to stop for example an ascan with ctrl-c. It seems to go completely ignored.

To reproduce, define anything as a pre-scan hook:
```
Door_B304A [17]: defgh lsenv pre-scan
Defining general hook
lsenv

Door_B304A [18]: lsgh
   Hook place   Hook(s)
 ------------ ---------
     pre-scan     lsenv
```
Then run some scan, an ascan or dscan with dummy motors is enough, and try stoppning it with ctrl-c.
Removing the hook makes it work normally again.
Edit: this seems to affect sardana 3.1.0 only, in 3.0.3 it works.

**Comment by 13bscsaamjad** [comment]
Reproduced it. Even after `ctrl-c` 5 times and releasing done, the door keeps on with the scan and outputting to spock!

**Comment by reszelaz** [comment]
Hi @HEnquist and @13bscsaamjad,
This regression was introduced in #1559. Reverting it fixes the problem. I will see if I can fix it with the revert.
Sorry about the inconvenience.

**Comment by dschick** [comment]
Hi I encounter the same problem but I am already on the latest development branch.
I also checked out the hotfix-3.1.1 branch but there is still this problem for me.

I tested it with `sar_demo` and a `wu` hooked to the `pre-scan` hook place.
