### ISSUE TITLE
Interactive question in macro freezes spock when timed out

### ISSUE THREAD

**Issue by jairomoldes** [sardana-org/sardana#1613]
The macro defined below ask for input from user. If user answers before time out then it works just fine. But if you allow the question to time out then spock gets freezed when prompt is returned.

The problem can be reproduced with python3, sardana 3.0.4 in debian9.

```python
#!/usr/bin/env python


from sardana.macroserver.macro import Macro


class question(Macro):

    interactive = True

    def run(self, *args, **kwargs):
        answer = ''
        while not answer.lower() in ('y', 'n'):
            answer = self.input('Answer (y/n)', timeout=10, default_value='y')
        self.output('User answered: %s' % answer)

```

**Comment by reszelaz** [comment]
Thanks for the report @jairomoldes. I confirm this issue. Will make a quick attempt to fix it.
