### ISSUE TITLE
creating a Sardana server programmatically

### ISSUE THREAD

**Issue by marouanebj** [sardana-org/sardana#1617]
Hello,
currently to create a new server I do like this
```
marouane@bantam:~$ Sardana myNewServer
mynewserver does not exist. Do you wish to create a new one (Y/n) ?
```
I'm making a python script of "install" of my several controller and so on so I want to create the Sardana server using python3.
I found how to create the controller and all the rest but not how to create a Sardana server (I want to replicate what does the code here before if user answer Y)

Thanks,

**Comment by reszelaz** [comment]
Hi @marouanebj,
I think you will need to execute a combination of `tango.Database.add_server()` and `tango.Database.db.add_device()` in order to create a Sardana device server with 3 devices: Pool, MacroServer and Door. I have not tested this snippet, but more or less you will need:

```python
from tango import Database, DbDevInfo

db = Database()

# create Sardana device server with Pool device
dev_info = DbDevInfo()
dev_info.name = 'Pool/zreszela/1'
dev_info._class = 'Pool'
dev_info.server = 'Sardana/zreszela'
db.add_server(dev_info.server, dev_info, with_dserver=True)

# create MacroServer device
dev_info = DbDevInfo()
dev_info.name = 'MacroServer/zreszela/1'
dev_info._class = 'MacroServer'
dev_info.server = 'Sardana/zreszela'
db.add_device(dev_info)

# create Door device
dev_info = DbDevInfo()
dev_info.name = 'Door/zreszela/1'
dev_info._class = 'Door'
dev_info.server = 'Sardana/zreszela'
db.add_device(dev_info)
# define a consecutive Id value
db.put_device_property('Door/zreszela/1', {"Id": 1})
```
Hope this helps! Just let us know the working version of the snippet.

**Comment by reszelaz** [comment]
@marouanebj, I have just updated the above comment, cause initially, I forgot to add the `PoolNames` property to the MacroServer.

**Comment by reszelaz** [comment]
@marouanebj I will proceed to close this issue. If you come back to this in the future, let us know if the above script worked. Many thanks!
