### ISSUE TITLE
Error running AbortMacro command

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana#1619]
AbortMacro gives problems if it is not run just after StopMacro.
Running AbortMacro not direct after StopMacro gives the error:

DevFailed: DevFailed[
DevError[
     desc = AttributeError: 'NoneType' object has no attribute 'ident'

   origin = Traceback (most recent call last):
   File
"/homelocal/zreszela/workspace/sardana/src/sardana/tango/macroserver/Door.py",
line 362, in AbortMacro
     self.macro_executor.abort()
   File
"/homelocal/zreszela/workspace/sardana/src/sardana/macroserver/msmacromanager.py",
line 1499, in abort
     raise_in_thread(ReleaseException, self._stop_thread)
   File
"/homelocal/zreszela/workspace/sardana/src/sardana/util/thread.py", line
82, in raise_in_thread
     th_id = ctypes.c_long(thread.ident)
AttributeError: 'NoneType' object has no attribute 'ident'

   reason = PyDs_PythonError
severity = ERR]

DevError[
     desc = Failed to execute command_inout on device door/zreszela/1,
command AbortMacro
   origin = Connection::command_inout()
   reason = API_CommandFailed
severity = ERR]
]

If after that StopMacro is called from a Client different from Spock the prompt in Spock never comes,
one need to restart the MacroServer.

**Comment by johanfforsberg** [comment]
Looks like the same behavior as #919 ?
