### ISSUE TITLE
[Doubt] Is this line necessary?

### ISSUE THREAD

**Issue by marc2332** [sardana-org/sardana#1665]
Hello,

I wanted to use `BaseDoor` class with a custom output, but, I found out that its `write()` function overwrites the _output_stream property for no apparent reason:

https://github.com/sardana-org/sardana/blob/3eb154ccc4b25001925c4a48ce060d7cfda7e496/src/sardana/taurus/core/tango/sardana/macroserver.py#L763

Is it ok? I tried removing that line and it worked as I wanted.

Thanks 👍🏻

**Comment by reszelaz** [comment]
Thanks for the report @marc2332 ! For me it looks like we don't need this like. It would be great if you could provide a PR. Thanks!
