### ISSUE TITLE
mca_start macro (SF#301)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#168]
Hi,
    in the src/sardana/macroserver/macros directory there is a file called 
 mca.py with the macros mca_start and mca_stop. The macro mca_start is calling
 the function Start from the 1D experimental channels, but this gives an
 error since the experimental channels in general (at least up to now) can 
 not be started outside the measurement group. mca_stop works because the
 function Stop of the experimental channels can be called outside a measurement
 group. I would say that either one allows the experimental channels to be
 started outside the MG (that I think it would be important to have) or one
 has to change the implementation of the macro, well or simply remove it.
 I will implement something for our users, since they need it and it is 
 confusing for them to have it there and get an error every time they try to 
 use it.
 What do you think?. Many thanks.

                       Regards,
                                  Teresa

                       

Reported by: teresanunez ( http://sf.net/u/tere29 )

Original Ticket: [sardana/tickets/301](https://sourceforge.net/p/sardana/tickets/301)

**Comment by reszelaz** [comment]
Hi @teresanunez,

Coming back to this very old issue, what is the solution that you implemented? I imagine that the experimental channel acquisition (without the measurement group) as we have it now is not exactly what one would like here. With MCA one would like to start the accumulation and then stop it at some point, right? So the integration time is not known beforehand, right?

Thanks!

**Comment by teresanunez** [comment]
Hi Zibi,
            it is not an issue any more, we go to our underlying Tango Device if needed.
Many thanks.

**Comment by reszelaz** [comment]
> Hi Zibi,
> it is not an issue any more, we go to our underlying Tango Device if needed.
> Many thanks.

Then I think the best would be to remove this macro. Do you agree? If yes, @teresanunez could you please provide a PR? Many thanks!

**Comment by teresanunez** [comment]
Hi Zibi, the macros work now (since the implementation of the possible single channel acquisition).
I close the issue.
