### ISSUE TITLE
Question: is it possible to define measurement data form a remote host

### ISSUE THREAD

**Issue by TacHuynh** [sardana-org/sardana#1680]
I got an error get using fully qualify device attribute. Is it not support?

Door_sardana1_1 [42]: %defmeas meas_TemperatureA ct01,tango://192.168.30.210:10000/sys/Fluke917x_DryWells/9173_COM1/controlsetpoint
An error occurred while running Macro 'defmeas(meas_TemperatureA, ['ct01,tango://192.168.30.210:10000/sys/Fluke917x_DryWells/9173_COM1/controlsetpoint']) -> 227db278-fbce-11eb-a624-08002727781d':
'NoneType' object has no attribute 'getPoolObj'

**Comment by TacHuynh** [comment]
Use TangoAttrZeroDCtrl from https://github.com/ALBA-Synchrotron/sardana-tango
then with spock:
defctrl TangoAttrZeroDController anyAttributeFromTangoDevice
%defelem readAnAttribute anyAttributeFromTangoDevice 1
readAnAttribute = 'tango://192.168.30.210:10000/sys/Fluke917x_DryWells/9173_COM1/controlsetpoint''

**Comment by reszelaz** [comment]
Hi @TacHuynh,
Using `TangoAttrZeroDCtrl` is a valid option as you discovered, but you should be able to use directly an attribute.
In your attempt, you wrongly specified a list of channels separated by a comma `,`. You must use a space ` ` as a separator:
```
Door/zreszela/1 [8]: defmeas baz ct01 tango://controls05.cells.es:10000/sys/tg_test/1/ampli
Created baz

Door/zreszela/1 [9]: set_meas baz

Door/zreszela/1 [10]: ct
Tue Aug 31 11:32:49 2021

                 ct01  =         1.0
  sys/tg_test/1/ampli  =         0.0
```

**Comment by reszelaz** [comment]
Of course, using an _external attribute e.g. Tango_ is not the same as using a [0D](https://sardana-controls.org/devel/overview/overview_0D.html#d-channel-overview). The second one gives you the benefit of performing multiple readouts during the integration time. These readouts are then filling a buffer and finally a calculation on the buffer e.g. an average or a sum is returned as a result of the acquisition. _External attribute e.g. Tango_ is simply read once at the end of the integration time.
