### ISSUE TITLE
Bug in mv and scan macros with PseudoMotors

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana#1686]
We have observed that trying two move two or more PseudoMotors depending on same physical motors 
only the first of the pseudomotors is moved, for the other(s) one(s) even the new position is not set.
For example, if one tries:

mv gap 2 offset 3

only the gap is moved to 2.
The same happens with a2scan, a3scan ...

**Comment by reszelaz** [comment]
Many thanks @teresanunez for the bug report. 
Have you tried it with the develop branch or some of the previous versions: 3.0.3, 3.1.2? I'm almost sure it used to work, it would be nice to know when we introduced this regression.

**Comment by teresanunez** [comment]
We are not using the develop branch, it is a previous one. Perhaps @jkotan knows at which point we take it.

**Comment by teresanunez** [comment]
For us is quite urgent because our hkl scans are not working.

**Comment by reszelaz** [comment]
With @teresanunez we found that the regression was accidentally introduced in https://github.com/sardana-org/sardana/pull/1302. The following lines were wrongly introduced in `sardana.pool.poolmotorgroup`:

![image](https://user-images.githubusercontent.com/6735649/132671804-d70be2d2-d058-4415-84a3-e8836f0fb1d7.png)

@teresanunez will try to provide a hotfix release. Many thanks!

**Comment by reszelaz** [comment]
Fixed in 3.1.3 and latest develop.
