### ISSUE TITLE
Precision display by umv macro (SF#320)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#176]
Hello,
      the macro umv shows the position during the movement with format %*.4f.
Our users complain because for some of the motors they need more precision in
 the displayed position. I think that it is also not convenient to have a much
 more precision in general for all the motors. Could be it possible to set it
 somehow (spock environment, for example. Perhaps the PosFormat
 ViewOption could be also used for that). Many thanks.

                  Regards,
                              Teresa

Reported by: teresanunez ( http://sf.net/u/tere29 )

Original Ticket: [sardana/tickets/320](https://sourceforge.net/p/sardana/tickets/320)

**Comment by reszelaz** [comment]
Sorry for the late reply. I think this is the role of the PosFormat ViewOption. @teresanunez do you feel like working on that and proposing a PR? Many thanks!

**Comment by teresanunez** [comment]
Hi Zibi, for this release I will for sure not manage ... I don´t know in any case if this is still an issue, but I will have a look.

**Comment by teresanunez** [comment]
Hi Zibi, I have just now implemented, tomorrow I send the PR, so it could be included in this release.

**Comment by reszelaz** [comment]
My fault, I should have said that it was not urgent. I was looking for another issue and came across this one and wanted to reply with the hint. But if the fix is ready and the review is quick then of course it can be included in the release. Please remember then to create a PR against the release-Jan21 branch. Many thanks!

**Comment by reszelaz** [comment]
Implemented in #1555.
