### ISSUE TITLE
Remove the TangoAttribute Controllers from Sardana (SF#327)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#181]
Feature proposal to integrate the TangoAttribute Controllers inside Sardana.
This is a task that was begun on 2012 with the creation of pool/poolcontroller/TangoController.py. 

Apparently TangoController.py seems to be broken, thus the first thing to be done is to remove TangoController.py to be replaced by a non broken code. Is somebody using the module sardana.pool.poolcontrollers.TangoController.py today?

There exists 4 controllers present in the third party controllers 'sardana-controllers' that should be integrated in Sardana.
Controllers that shall be integrated in sardana.pool.poolcontrollers are:
- sardana-controllers/python/countertimer/TangoAttrCTCtrl.py
- sardana-controllers/python/ioregister/TangoAttrIORCtrl.py
- sardana-controllers/python/motor/TangoAttrMotorCtrl.py
- sardana-controllers/python/zerod/TangoAttrZeroDCtrl.py

For integrating these controllers inisde sardana.pool.poolcontrollers we propose to follow the convention stated [in this mail][1]. 
[1]: https://sourceforge.net/p/sardana/mailman/message/31315637/

For this reason the name of the modules while they will be migrated in Sardana will be:
sardana.pool.poolcontrollers.TangoAttrCounterTimerController.py
sardana.pool.poolcontrollers.TangoAttrIORController.py
sardana.pool.poolcontrollers.TangoAttrMotorController.py
sardana.pool.poolcontrollers.TangoAttrZeroDController.py

--

We got a feedback from Guifré for this ticket pointing that this integration inside Sardana is maybe a not so good idea:

A motor ctrl should implement the acceleration and the velocity because some macros are using it, but TangoAttrMotorCtrl.py only does a write of the Position when we want to move the motor somewhere, and a read when we want to read the positions, ignoring the limits.

The controller of counter-timer is maybe worst, because the pool would wait that the controller transfers the value of loadOne(x) and it should have no sense with an attribute from tango/taurus.

The zerod could be maybe an accepted option, because it is simply a continued buffer and the controller only needs a readone().

The ioregisters are even more complicated to implement with the TangoAttrIORController.py and are possibly not usable in a generic way.

After assessing these comments we will take the decision if we close the ticket.  

Anyway the currently present code inside Sardana from pool/poolcontroller/TangoController.py should be removed because it seems to be a broken code.

Reported by: sagiss ( http://sf.net/u/mrosanes )

Original Ticket: [sardana/tickets/327](https://sourceforge.net/p/sardana/tickets/327)

**Comment by reszelaz** [comment]
As issues were raised by @guifrecuni in https://github.com/sardana-org/sardana/issues/181#issue-191720313 and we have now [sardana-tango](https://github.com/ALBA-Synchrotron/sardana-tango) repo nicelly listed in the [sardana-plugins](https://github.com/sardana-org/sardana-plugins/blob/master/software.md) catalogue the current idea is to remove this never working code from Sardana.
So, I rename the issue subject from: "Integrate the TangoAttribute Controllers inside Sardana (SF#327)" to "Remove TangoAttribute Controllers from Sardana (SF#327)".
