### ISSUE TITLE
Independent acquisition of timerable channels (SF#332)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#185]
Hi,

I've just noticed that during starting a timer I get 

Description - AttributeError: 'PoolCounterTimer' object has no attribute 'get_write_value'

from

Origin -   File "/usr/lib/python2.7/dist-packages/sardana/tango/pool/CTExpChannel.py", line 198, in Start
    self.ct.start_acquisition()
  File "/usr/lib/python2.7/dist-packages/sardana/pool/poolbasechannel.py", line 163, in start_acquisition
    value = self.get_write_value()

That causes that from time to time on our beamlines ascan command get stack.

Bests,
Jan

Reported by: jkotan ( http://sf.net/u/jkotan )

Original Ticket: [sardana/tickets/332](https://sourceforge.net/p/sardana/tickets/332)

**Comment by reszelaz** [comment]
This feature will be very helpful when working on SEP2. Furthermore, SEP18 makes it very easy to implement this. I propose the following...

# Idea

Allow single and independent (without the need to define a measurement group) measurement of experimental channels. This measurement is composed from just one acquisition of one channel synchronized by software.
Implement the said measurement on example of timerable channels and leave 0D and pseudo counters to be implemented in the future.

# Specification

There are three different types of experimental channels.
1. timerable (counter/timer, 1D, 2D)
2. 0D
3. psuedo counter

One part of the specification, more preciselly, the one concerning the integration time is common to all types of experimental channels. However, the rest of the specification has some particularities which will be explained later. To make it easier to follow to necessary changes these are written in **bold**.

## Integration time configuration

**Add attribute `integration_time` (core) and `IntegrationTime` (Tango) to experimental channels.** It accepts the integration time in seconds (`float`) and it is a pure configuration attribute - it does not set anything to the hardware.

## Timerable

Timerable experimental channels characterize themself by the involvement of a timer in the channel's acquisition. For this reason a configuration parameter is necessary to specify which channel should be used as the timer.
When a measurement group is involved its configuration comprises information which channel has the timer role in each controller. For the single channel's measurement the timer is configured in the following way.

### Timer configuration

**Add attribute `timer` (core) and `Timer` (Tango) to timerable experiemental chnnels.** It accepts a name or a full name of one of the channels belonging to the same controller as the channel under concern e.g. `ct01` or `tango://localhost:10000/counter/ctctrl01/1`. Two special values are possible: `None` and `__default`. It is a pure configuration attribute - it does not set anything to the hardware. When set to `None` single acquisition won't be possible. When set to `__default`  it resets the timer to the controller's default timer (see next paragraph for explanation).

### Controller's default timer

**Controller (plugin) may define its default timer axis by adding a class member: `default_timer`** with the axis number of the default timer e.g `1`. If the element belonging to this axis is not defined in the controller, resetting the controller's timer to the default one raises an exception.

### Acquisition

Each timerable channel agregates an instance of the acquisition action. **Change its class from `CTAcquisition` to `PoolAcquisitionSoftware`.** This action is employed on Tango `Start` command or channel's `start_acquisition` method call. **Change the Tango `Start` command - remove its argument integration time.** The acquisiton action will set the synchronization to software trigger.

## 0D

### Acquisition

`Pool0DAcquisition` is assigned to 0D experimental channels and it will be employed on Tango `Start` command or on channel's `start_acquisition` call - there are no changes with respect to that. **The acquisition will be controlled by software synchronizer which will stop it when the integration time elapses.**

## Psuedo counter

### Acquisition

**`PoolAcquisition` is assigned to pseudo counter experimental channels.** It involves all the physical channels belonging to this pseudo countee. This action is employed on Tango `Start` command or channel's `start_acquisition` method call. The acquisiton action will set the synchronization to software trigger.

@teresanunez could you please comment if this satisfies the DESY needs.

**Comment by teresanunez** [comment]
HI @reszelaz, many thanks. I have read it and I do not agree with the part of the timer, it should be
 possible to make an acquisition without having to specify a timer, so if one writes None, simply make
 the acquisition, like we do in our timers/counters outside of sardana.

**Comment by teresanunez** [comment]
Thanks, I think it is fine if you add the new keyword and keep None for disabling.

**Comment by teresanunez** [comment]
The attribute Timer is a memorized attribute. If never set the default value is __default.

**Comment by reszelaz** [comment]
Solved in #997.
