### ISSUE TITLE
'Single counter' plots during the scan (SF#334)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#186]
Summary of previous exchange information in sardana-devel list:

Request from Teresa:

Our beamline scientist do not like to display all the
counters in the same plot during the scan. 
They want to have them in separated plots.

Suggestion from Carlos:

I think this is a nice feature to have, and not a very difficult one to 
implement, since the expconf widget is already creating separated plots 
when you assign different "x" variables to the plots of different channels 
(so it is just a matter of deciding a way to present this option to the 
user and then doing some minor changes in the way the plots are 
internally initialized).

Reported by: teresanunez ( http://sf.net/u/tere29 )

Original Ticket: [sardana/tickets/334](https://sourceforge.net/p/sardana/tickets/334)

**Comment by reszelaz** [comment]
I think this should be already solved by https://github.com/sardana-org/sardana/pull/1285. Teresa could you please check if this is ehough?

**Comment by teresanunez** [comment]
Yes, it should be, at least contains what the user asked at that point for. I close it. Many thanks.
