### ISSUE TITLE
Problem with the Spec File (SF#351)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#197]
The spec file generated by Sardana is not compatible with the spec python library
(https://github.com/specpython/filespec). 

filespec.FileSpec() is not able to read files since the command:
#N number_of_counters

Reported by: rhomspuron ( http://sf.net/u/rhomspuron )

Original Ticket: [sardana/tickets/351](https://sourceforge.net/p/sardana/tickets/351)

**Comment by rhomspuron** [comment]
The new version of the spec library supports the spec file generated by sardana.
