### ISSUE TITLE
Removing of qt4 in Debian/Ubuntu  (SF#352)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#198]
Hello guyes.

Just to tell you that the next Debian Distribution will get rid of qt4.
so it seems to be the right time to work on the qt4 -> qt5 migration :)

Cheers

Fred

here the debian message

Hi! As you might know we the Qt/KDE team are preparing to remove Qt4's WebKit
as announced in [announce]. Your package seems to be using it via PyQt4's
QtWebKit module.

[announce] https://lists.debian.org/debian-devel-announce/2015/05/msg00001.html

Basically we are about to get the last Qt4 point release and upstream is
migrating from WebKit to Blink in the Qt5 series, so we won't have much upstream
support for maintaining Qt4's WebKit (Qt5's WebKit is expected to stay supported
until Qt6).

In order to make this move, all packages directly or indirectly depending on
the Qt4's WebKit library have to either get ported to Qt5 or eventually get
removed from the Debian repositories.

Therefore, please take the time and:
- contact your upstream (if existing) and ask about the state of a Qt5
port of your application
- if there are no activities regarding porting, investigate whether there are
suitable alternatives for your users
- if there is a Qt5/PyQt5 port that is not yet packaged, consider packaging it
- if both the Qt4 and the Qt5 versions already coexist in the Debian
archives, consider removing the Qt4 version

= Porting =

Some of us where involved in various Qt4 to Qt5 migrations [migration] and we
know for sure that porting stuff from Qt4 to Qt5 is much much easier and less
painful than it was from Qt3 to Qt4.

We also understand that there is still a lot of software still using Qt4. In
order to ease the transition time we have provided Wheezy backports for Qt5.

Don't forget to take a look at the C++ API changes page [apichanges] and the
PyQt4 vs PyQt5 differences page [pyqtchanges] whenever you start porting
your application.

[migration] http://pkg-kde.alioth.debian.org/packagingqtstuff.html
[apichanges] http://doc.qt.io/qt-5/sourcebreaks.html
[pyqtchanges] http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html

For any questions and issues, do not hesitate to contact the Debian Qt/KDE
team at debian-qt-kde@lists.debian.org.

--
Dmitry Shachnev,
on behalf of the Qt4 and PyQt4 maintainers

Reported by: picca ( http://sf.net/u/piccaf )

Original Ticket: [sardana/tickets/352](https://sourceforge.net/p/sardana/tickets/352)

**Comment by reszelaz** [comment]
Support to Qt5 was added in #1009 .
