### ISSUE TITLE
pymca problem with spec files (generated by sardana) (SF#360)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#206]
Hi, 
   we have a problem with the spec file generated by the sardana
 scans when we try to open them with pymca. The problem is in
 fact related with the ticket 304, there it was written that an
 extra line at the beginning of the spec file was not compatible
 with pymca. For us it is the contrary: without the extra line
 (it can be empty or contain anything arbitrary) pymca crashes trying
 to open the file. This happens only if in the file there is only
 one scan, if we record two or more scans in the same file the problem
 is not there any more.
 For being more explicit:

 -> this works

------------

#S 18 ascan exp_dmy01 1.0 10.0 4 1.0
#U tnunez
#D 1434618538.0
#C Acquisition started at Thu Jun 18 11:08:58 2015
#N 6
#L Pt_No  exp_dmy01  timer1  oms_acceleration  oms_baserate  dt
0 1.0 1.0 0.0 0.0 0.596115112305
1 3.25 1.0 0.0 0.0 2.22683000565
2 5.5 1.0 0.0 0.0 4.22746801376
3 7.75 1.0 0.0 0.0 6.20940113068
4 10.0 1.0 0.0 0.0 8.2477991581
#C Acquisition ended at Thu Jun 18 11:09:08 2015
---------------

-> this does not work:

---------------
#S 18 ascan exp_dmy01 1.0 10.0 4 1.0
#U tnunez
#D 1434618538.0
#C Acquisition started at Thu Jun 18 11:08:58 2015
#N 6
#L Pt_No  exp_dmy01  timer1  oms_acceleration  oms_baserate  dt
0 1.0 1.0 0.0 0.0 0.596115112305
1 3.25 1.0 0.0 0.0 2.22683000565
2 5.5 1.0 0.0 0.0 4.22746801376
3 7.75 1.0 0.0 0.0 6.20940113068
4 10.0 1.0 0.0 0.0 8.2477991581
#C Acquisition ended at Thu Jun 18 11:09:08 2015
---------------

-> and this works:

---------------
#S 18 ascan exp_dmy01 1.0 10.0 4 1.0
#U tnunez
#D 1434618538.0
#C Acquisition started at Thu Jun 18 11:08:58 2015
#N 6
#L Pt_No  exp_dmy01  timer1  oms_acceleration  oms_baserate  dt
0 1.0 1.0 0.0 0.0 0.596115112305
1 3.25 1.0 0.0 0.0 2.22683000565
2 5.5 1.0 0.0 0.0 4.22746801376
3 7.75 1.0 0.0 0.0 6.20940113068
4 10.0 1.0 0.0 0.0 8.2477991581
#C Acquisition ended at Thu Jun 18 11:09:08 2015
#S 19 ascan exp_dmy01 1.0 10.0 4 1.0
#U tnunez
#D 1434618538.0
#C Acquisition started at Thu Jun 18 11:08:58 2015
#N 6
#L Pt_No  exp_dmy01  timer1  oms_acceleration  oms_baserate  dt
0 1.0 1.0 0.0 0.0 0.596115112305
1 3.25 1.0 0.0 0.0 2.22683000565
2 5.5 1.0 0.0 0.0 4.22746801376
3 7.75 1.0 0.0 0.0 6.20940113068
4 10.0 1.0 0.0 0.0 8.2477991581
#C Acquisition ended at Thu Jun 18 11:09:08 2015
----------------------

We checked with different versions from pymca,included the last
 code taken directly from Armando's repository and the effect
 is always the same.

                      Regards,
                                  Teresa

Reported by: teresanunez ( http://sf.net/u/tere29 )

Original Ticket: [sardana/tickets/360](https://sourceforge.net/p/sardana/tickets/360)

**Comment by cpascual** [comment]
Hi, 

I just checked and PyMca 5.1.3 (the one currently in debian stretch) seems not to have this problem anymore.

Also, the following command can be used to "fix" the problematic files for older PyMca versions:
```
sed -i '1s/^/\n/' yourfile.dat
```

Since this seems to be fixed in PyMca5.1.3 and there is a workaround for older PyMca, I am closing this issue

**Comment by LJBD** [comment]
Just to clarify things: this "bug" was present in PyMca <= 5.1.1 - it crashed with a segmentation fault when given a SPEC file for Sardana. I've filed a bug to Armando Sole and he solved it in May last year.
His original response regarding the workaround was:

> The original SPEC file Sardana is trying to replicate contains a file header (starting by #F) separated from the first scan by a newline character. It is true that the program should not segfault, but the problem is that *always* there must be a newline character (\n) prior to the starting a scan (#S).
Just starting the file with a newline character instead of by #S and everything works.

**Comment by dschick** [comment]
I just encountered a similar problem using Sardana under Win7.
Here Sardana seems to adds a CR+LF which is not acknowledged by PyMCA 5.3
When I manually change this to only LF it works again in PyMCA.

**Comment by cpascual** [comment]
Ok, this should be easy to fix by forcing  LF in Sardana's SpecRecorder regardless of the platform.
The only thing is to clarify whether this is a bug in sardana or in pymca (i.e. whether the spec standard allows CR+LF or only LF)

**Comment by dschick** [comment]
thanks, that works. I changed the SPEC_FileRecorder to

 self.fd = io.open(self.filename, 'a', newline='\n')

but the one has to unicode() all write calls.

As I was always generating SPEC files from a linux machine and reading it with PyMCA from Linux and Windows I guess both SPEC and PyMCA expect only \n as line endings.
I cannot find anything about the line endings in the SPEC manual: https://certif.com/spec_manual/mac_3_13.html

Best

Daniel

**Comment by cpascual** [comment]
@vrey: do you know if spec mandates one type or another of newline characters (i.e. LF or CRLF)?

**Comment by cpascual** [comment]
@dschick : would you mind creating a PR with the required changes?

**Comment by dschick** [comment]
I can do that with in the next days.
These changes are only limited to the SPEC_FileRecorder, because for the FIO_FileRecorder the OS convention for line breaks might be fine, I guess?

**Comment by cpascual** [comment]
For the FIO recorder, the authority would be @teresanunez ...

**Comment by teresanunez** [comment]
Hi @dschick, yes, please, make only the change for the SPEC_FileRecorder. Thanks.
