### ISSUE TITLE
IORegister devices do not send State events, and Value does not have the 'CHANGING' quality (SF#21)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#21]
Hi, I've detected that Pool's ioregister devices do not send events of State and the 'Value' does not have the quality to 'CHANGING' when the controller is reporting 'MOVING'.

Reported by: guifrecuni ( http://sf.net/u/guifre )

Original Ticket: [sardana/tickets/21](https://sourceforge.net/p/sardana/tickets/21)

**Comment by reszelaz** [comment]
We have talked about this internally at Alba with @jordiandreu and @rhomspuron, below our conclusions.

Most probably the original request was motivated by the lack of feedback when using the [TangoAttrIORController](https://sourceforge.net/p/sardana/controllers.git/ci/master/tree/python/ioregister/TangoAttrIORCtrl.py) to move motors to discrete positions. This is a misuse of IOR elements. The recommended way to do this is to use the [DiscretePseudoMotorController](https://github.com/sardana-org/sardana/blob/develop/src/sardana/pool/poolcontrollers/DiscretePseudoMotorController.py).

Write of the IOR value is an instant operation, hece there is no need to implement changing quality nor MOVING state.

If you all agree I will add this information to the [I/O register overview](http://www.sardana-controls.org/en/latest/devel/overview/overview_IOR.html).

**Comment by reszelaz** [comment]
Since there are no opinions against this I'll proceed to add this information to the docs and close this issue.

**Comment by reszelaz** [comment]
Done in 205162b.
