### ISSUE TITLE
Bug in polling of the Encoder attribute (PMTV) (SF#365)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#211]
The taurus polling of the Encoder attribute (PMTV) remains active, even if the widget is invisible (window minimized or panel closed). 

Could be easily seen when the Pool is down and taurus-log-level=debug

<pre>
taurusform mot20 --taurus-log-level=debug

...  AFTER KILL POOL ...

TimerLoop 1    DEBUG    2014-11-04 16:01:59,567 controls01:10000.mot20.Encoder: Error polling: encoder attribute not found
TimerLoop 1    DEBUG    2014-11-04 16:02:02,573 controls01:10000.mot20.Position: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
TimerLoop 1    DEBUG    2014-11-04 16:02:02,574 controls01:10000.mot20.Encoder: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
TimerLoop 1    DEBUG    2014-11-04 16:02:05,580 controls01:10000.mot20.Position: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
TimerLoop 1    DEBUG    2014-11-04 16:02:08,586 controls01:10000.mot20.Position: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
TimerLoop 1    DEBUG    2014-11-04 16:02:11,592 controls01:10000.mot20.Position: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
TimerLoop 1    DEBUG    2014-11-04 16:02:14,598 controls01:10000.mot20.Position: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
Dummy-1        INFO     2014-11-04 16:02:15,263 controls01:10000.mot20.Limit_Switches: Activating polling. Reason: API_EventTimeout
Dummy-1        INFO     2014-11-04 16:02:15,264 controls01:10000.mot20.state: Activating polling. Reason: API_EventTimeout
TaurusTP.W004  DEBUG    2014-11-04 16:02:15,264 controls01:10000.mot20.Limit_Switches: [Tango] read failed (API_CantConnectToDevice): Failed to connect to device motor/motctrl05/4
The connection request was delayed.
The last connection request was done less than 1000 ms ago
TaurusTP.W004  DEBUG    2014-11-04 16:02:15,265 controls01:10000.mot20.Limit_Switches: Error polling: Failed to connect to device motor/motctrl05/4
The connection request was delayed.
The last connection request was done less than 1000 ms ago
Dummy-1        INFO     2014-11-04 16:02:15,265 controls01:10000.mot20.Status: Activating polling. Reason: API_EventTimeout
TaurusTP.W005  DEBUG    2014-11-04 16:02:15,265 controls01:10000.mot20.state: [Tango] read failed (API_CantConnectToDevice): Failed to connect to device motor/motctrl05/4
The connection request was delayed.
The last connection request was done less than 1000 ms ago
TaurusTP.W005  DEBUG    2014-11-04 16:02:15,266 controls01:10000.mot20.state: Error polling: Failed to connect to device motor/motctrl05/4
The connection request was delayed.
The last connection request was done less than 1000 ms ago
TaurusTP.W005  DEBUG    2014-11-04 16:02:15,266 controls01:10000.mot20: SW Device State changed Running -> Uninitialized
TaurusTP.W001  DEBUG    2014-11-04 16:02:15,266 controls01:10000.mot20.Status: [Tango] read failed (API_CantConnectToDevice): Failed to connect to device motor/motctrl05/4
The connection request was delayed.
The last connection request was done less than 1000 ms ago
TaurusTP.W001  DEBUG    2014-11-04 16:02:15,267 controls01:10000.mot20.Status: Error polling: Failed to connect to device motor/motctrl05/4
The connection request was delayed.
The last connection request was done less than 1000 ms ago
TimerLoop 1    DEBUG    2014-11-04 16:02:17,604 controls01:10000.mot20.Status: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
TimerLoop 1    DEBUG    2014-11-04 16:02:17,604 controls01:10000.mot20.Position: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
TimerLoop 1    DEBUG    2014-11-04 16:02:17,605 controls01:10000.mot20.Limit_Switches: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
TimerLoop 1    DEBUG    2014-11-04 16:02:17,606 controls01:10000.mot20.state: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
TimerLoop 1    DEBUG    2014-11-04 16:02:20,611 controls01:10000.mot20.Status: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
TimerLoop 1    DEBUG    2014-11-04 16:02:20,612 controls01:10000.mot20.Position: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
TimerLoop 1    DEBUG    2014-11-04 16:02:20,613 controls01:10000.mot20.Limit_Switches: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
TimerLoop 1    DEBUG    2014-11-04 16:02:20,613 controls01:10000.mot20.state: Error polling: Device motor/motctrl05/4 is not exported (hint: try starting the device server)
Dummy-2        DEBUG    2014-11-04 16:02:21,886 controls01:10000.mot20.Position: Failed: Failed to disconnect from event!
Error while trying to unsubscribe the heartbeat ZMQ socket from the channel heartbeat publisher
ZMQ message: Resource temporarily unavailable
Dummy-2        DEBUG    2014-11-04 16:02:21,887 controls01:10000.mot20.Limit_Switches: Failed: Failed to disconnect from event!
Error while trying to unsubscribe the heartbeat ZMQ socket from the channel heartbeat publisher
ZMQ message: Resource temporarily unavailable
Dummy-2        DEBUG    2014-11-04 16:02:21,888 controls01:10000.mot20.state: Failed: Failed to disconnect from event!
Error while trying to unsubscribe the heartbeat ZMQ socket from the channel heartbeat publisher
ZMQ message: Resource temporarily unavailable
Dummy-2        DEBUG    2014-11-04 16:02:21,888 TaurusPollingTimer[3000].Timer on _pollAttributes: Timer::stop()
Dummy-2        DEBUG    2014-11-04 16:02:21,888 controls01:10000.mot20.Position.configuration: Exception trying to unsubscribe configuration events
Dummy-2        DEBUG    2014-11-04 16:02:21,888 controls01:10000.mot20.state.configuration: Exception trying to unsubscribe configuration events

</pre>

Reported by: cmft ( http://sf.net/u/cmft )

Original Ticket: [sardana/tickets/365](https://sourceforge.net/p/sardana/tickets/365)

**Comment by reszelaz** [comment]
I think this is actually a limitation in Taurus. minimized windows or hidden panels are not disabling Taurus polling of the models. @cpascual could you confirm, please? Meanwhile, I'm closing.

**Comment by cpascual** [comment]
Yes, this is a design decision in taurus. 

In very old versions of taurus (or Tau, I don't remember) an attempt was made for not polling on models that were not visible, but this introduced many more issues (e.g. having to deal with the same attribute shown in different widgets, or distinguishing between "snapshot" widgets such as a label and "logging" widgets such as a trend).That is why it was decided **not** to disable the polling depending on visibility
