### ISSUE TITLE
Documentation about macro stop/abort is missing (SF#366)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#212]
The guide "Writing macro" misses information about stopping/aborting of the macros. This should include information about macro API methods checking for the user aborts e.g. checkPoint and the automatic stop/abort of the reserved objects.

Reported by: reszelaz ( http://sf.net/u/zreszela )

Original Ticket: [sardana/tickets/366](https://sourceforge.net/p/sardana/tickets/366)

**Comment by daneos** [comment]
Brainstorming notes:
This should be added to the Writing macros section
* Difference between stop and abort
* How to deal with stops and aborts
