### ISSUE TITLE
New argument for Calc(All)Pseudo: indicator read/write values in physical_pos (SF#367)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#213]
Hi,
    we need to have a new argument in the Calc(All)Pseudo function
 of the PseudoMotors for indicating if the positions in the physical_pos
 argument correspond to the write or the read values of the motor positions. 
 Calc(All)Pseudo is called always twice: the first time physical_pos are
 the read values of the positions and the second one are the write ones.
 If the values in physical_pos are sent to any library for further calculations
 the results of the calculations will correspond to the write values, not
 to the read (the actual positions) ones, so they are wrong in case write
 and read values differs. The problem have been seen in the PseudoMotor 
 controller for the diffractometer.

                            Regards,
                                        Teresa

Reported by: teresanunez ( http://sf.net/u/tere29 )

Original Ticket: [sardana/tickets/367](https://sourceforge.net/p/sardana/tickets/367)

**Comment by teresanunez** [comment]
I have in fact implemented the diffractometer controller with a work around. This is not relevant for that controller.

**Comment by reszelaz** [comment]
Maybe then we could close it? If you agree, it would be interesting to explain the workaround here for the future needs.

**Comment by teresanunez** [comment]
Hi Zibi, thanks, I will close it them. I do not actually remember what I did. I will try to figure it out and add it at some point.
