### ISSUE TITLE
Simplify MG configuration by removing the units (SF#372)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#218]
MG dictionary (measurement groups dictionary) contains unnecessary complexity. In order to simplify it, we propose to go without the concept of 'units'. Actually the 'units' concept is not used. We are not sure about its original purpose, it could be one of these:

Handle complex controllers:
example 1:
Controllers like the MUSST counter card, which are programmable to work in several "units". For example, one could load the controller with program "tomo", in this way the controller would work under unit 0 with several counters. Loading with program "fluorescence" the controller would work under unit 1 with potentially other counters.

example 2:
Controllers like the complex DAQ crates with multiple units e. g. multiple ADC cards.

----------------------------

The current structure of the MG dictionary is the following:

<pre>
#----------------------------------------------
# Measurement Group (MG) Configuration information
#----------------------------------------------
# dict <str, obj> with (at least) keys:
#    - 'timer' : the MG master timer channel name / master timer channel id
#    - 'monitor' : the MG master monitor channel name / master monitor channel id
#    - 'controllers' : dict <Controller, dict> with one entry per controller:
#        - ctrl_object : dict<str, dict> with (at least) keys:
#            - 'units' : dict <str, dict> with with one entry per unit:
#                - unit_id : dict<str, obj> with (at least) keys:
#                    - 'id' : the unit ID inside the controller
#                    - 'timer' : the timer channel name / timer channel id
#                    - 'monitor' : the monitor channel name / monitor channel id
#                    - 'trigger_type' : 'Gate'/'Software'
#                    - 'channels' where value is a dict<str, obj>
#                          - ...
#    - 'label' : measurement group label (defaults to measurement group name)
#    - 'description' : measurement group description
</pre>

We propose to simplify the MG dictionary by removing the 'units' concept. This would result on a MG dictionary with the following shape:

<pre>
#----------------------------------------------
# Measurement Group (MG) Configuration information
#----------------------------------------------
# dict <str, obj> with (at least) keys:
#    - 'timer' : the MG master timer channel name / master timer channel id
#    - 'monitor' : the MG master monitor channel name / master monitor channel id
#    - 'controllers' : dict <Controller, dict> with one entry per controller:
#        - ctrl_object : dict<str, dict> with (at least) keys:
#            - 'timer' : the timer channel name / timer channel id
#            - 'monitor' : the monitor channel name / monitor channel id
#            - 'trigger_type' : 'Gate'/'Software'
#            - 'channels' where value is a dict<str, obj> with (at least) keys:
#                - ...      
#    optional keys:
#    - 'label' : measurement group label (defaults to measurement group name)
#    - 'description' : measurement group description
</pre>

**Note:** Code related with MG configuration dictionaries can be found in modules: sardana/pool/poolmeasurementgroup.py
sardana/pool/poolelement.py
sardana/pool/poolacquisition.py
sardana/taurus/qt/qtgui/extra_sardana/measurementgroup.py
sardana/taurus/core/tango/sardana/pool.py 

Reported by: sagiss ( http://sf.net/u/mrosanes )

Original Ticket: [sardana/tickets/372](https://sourceforge.net/p/sardana/tickets/372)

**Comment by reszelaz** [comment]
Implemented in SEP6 and already part of develop.
