### ISSUE TITLE
warnings in sphinx build (SF#373)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#219]
After fixing [#358], I get about 100 warnings when building sphinx docs in a simulated RTD environment (a virtualenv with READTHEDOCS=True envvar and only a few packages installed).

The warnings are all similar to the following one (but for different docstrings):

```
(rtd)cpascual@pc218:~/src/sardana(bug-358)$ sphinx-build -b html ./doc/source/  /tmp/_build/sdn_html 
Running Sphinx v1.3.1
(...)
writing output... [100%] users/standard_macro_catalog
(...)
docstring of sardana.macroserver.macro.Macro.execMacroObj:None: WARNING: more than one target found for cross-reference u'str': sardana.sardanabase.SardanaBaseObject.str, sardana.sardanameta.SardanaLibrary.str, sardana.sardanameta.SardanaClass.str
(...)
build succeeded, 100 warnings.
```

In this case, the docstring looks like:

```
def execMacroObj(self, name, *args, **kwargs):
        """**Macro API**. Execute a macro in this macro. The method only returns
        after the macro is completed or an exception is thrown. This is a
        higher level version of runMacro method. It is the same as::

            macro = self.prepareMacroObjs(name, *args, **kwargs)
            self.runMacro(macro)
            return macro

        :param name: name of the macro to be prepared
        :type name: str
        :param args: list of parameter objects
        :param kwargs: list of keyword parameters

        :return: a macro object"""
```

The problem comes from the line that says:

```
:type name: str
```

For some reason, the builtin symbol "str" is not picked for the reference, and class members are tried (and then it finds several, hence the warning). Consequently, in the generated docs, the str reference is made to sardana.sardanabase.SardanaBaseObject.str (not the builtin)

But note that, according to http://sphinx-doc.org/domains.html, sphinx should select the builtin str reference instead of trying to check a class member "str" reference:

    Normally, names in these roles are searched first without any further 
    qualification, then with the current module name prepended, then with the 
    current module and class name (if any) prepended.

Can somebody else confirm this problem?
Maybe it is a sphinx issue?

Reported by: cpascual ( http://sf.net/u/cpascual )

Original Ticket: [sardana/tickets/373](https://sourceforge.net/p/sardana/tickets/373)

**Comment by cpascual** [comment]
PR #859 fixes all warnings and is ready for review
