### ISSUE TITLE
Arguments for software continuous scans macros (SF#374)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#220]
Hello,
      our beamline scientist want to have the number of
 points as an argument for the macros doing software
 continuous scans. Just now the arguments are:

 start position, final position, integration time, [slow down factor]

 They do not want the slow down factor (just now optional) but
 a fixed number of points, and with the given arguments the macro
 should compute and set the velocity of the motor during the scan,
 if this is smaller than the base rate or bigger than the Velocity
 set originally in the motor, the macro should throw an error message
 and the scan will not be performed.
 I have just now thought about it, and how we can keep both set
 of arguments. The idea that comes to my mind is to use the current last
 argument (slow_down) as slow_down if it is between 0 and 1 and as
 number of points if it is above one (hopefully nobody will want a 
 continuous scan with only one point ;)), the macro should check the
 value (if given) and use it accordingly. Do you agree with something
 like this?. I could try to implement it and send a patch, not problem.

                      Regards,
                                   Teresa

Reported by: teresanunez ( http://sf.net/u/tere29 )

Original Ticket: [sardana/tickets/374](https://sourceforge.net/p/sardana/tickets/374)

**Comment by reszelaz** [comment]
Software continuous scan with a fixed number of points are possible after accepting SEP6. I think that we can close this ticket now.

At some point we will get to the point of merging the `ascanc` and `ascanct` into one macro. Then we will think on how to maintain the backwards compatibility and @teresanunez ideas about the `slow_down` and `nr_of_points` parameters will be helpfull.
