### ISSUE TITLE
Alphabetical order when presenting Doors, in new spock profile creation (SF#375)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#221]
When creating a new spock profile, the Door to be connected to, has to be chosen.
The Doors are presented without any coherent order.

This feature request proposes to present the Doors in alphabetical order. By first presenting in alphabetical order the Doors which have an alias associated; and then presenting in alphabetical order the Doors which does not have an alias associated.

Reported by: sagiss ( http://sf.net/u/mrosanes )

Original Ticket: [sardana/tickets/375](https://sourceforge.net/p/sardana/tickets/375)

**Comment by mrosanes** [comment]
Pull request https://github.com/sardana-org/sardana/pull/558 is dealing with this issue.
