### ISSUE TITLE
fscan macro (SF#377)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#223]
Hello,

I recently tried to use the fscan macro (src/sardana/macroserver/macros/scan.py), and it seems that this macro does not work. (I found a ticket about this problem : https://sourceforge.net/p/sardana/tickets/84/ ). I feel that this macro is an unused macro.

The function needs parameters : {'indepvars', Type.String} , { 'motor_funcs', ParamRepeat[ {'motor, Type.Moveable} , {'func', Type.String}]} , {'integ_time', Type.String}

I tried the exemple  : 
fscan x=[1,3,5,7,9],y=arange(5)  motor1 x^2 motor2 sqrt(yx-3) 0.1 

But i had an error like "Error: Moveable with name 0.1 does not exist". The last parameter integ_time is evaluated as a Moveable due to the ParamRepeat.

I switched this two arguments in the macro declaration and i saw some troubles in fscan.prepare. This methode use SafeEvaluator, which is not import; there some mistake in the way to format and use inputs arguments.

If you want to have a look, I fixed problems in the linked patch.
(git apply --ignore-space-change --ignore-whitespace patch.diff)

Thanks
Antoine

Reported by: adupre ( http://sf.net/u/adupre )

Original Ticket: [sardana/tickets/377](https://sourceforge.net/p/sardana/tickets/377)

**Comment by dschick** [comment]
I just tried the fscan macro and it works for:
`fscan x=arange(5) 1 motor x`
but
`fscan x=[1,2,3,4] 1 motor x`
fails with
`ValueError: Only members of repeat parameter allow list values`

This seems to be still a limitation of parameter parsing, right?

**Comment by teresanunez** [comment]
Hi Daniel,
                 we have probably not check it when we introduce the new
  implementation for ParamRepeat. We could discuss about changing this 
in the
  code, but a solution that works is:

|fscan "x=[1,2,3,4]" 1 motor x|

  The argument has to be passed as a string, like this it will not see 
it as a list.


                           Regards,
                                           Teresa

**Comment by dschick** [comment]
¡Gracias!
