### ISSUE TITLE
Document usage of specific macro environment variables (SF#383)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#229]
Information of specific macro environment variables ScanDir/ScanFile referring to specific macros is not documented in ReadTheDocs.

Document it.

Reported by: sagiss ( http://sf.net/u/mrosanes )

Original Ticket: [sardana/tickets/383](https://sourceforge.net/p/sardana/tickets/383)

**Comment by daneos** [comment]
Brainstorming notes:
* Description of the environment concept
* Variable scope explanation
* Link to the environment variables catalog

**Comment by reszelaz** [comment]
@teresanunez gathered some [information](https://github.com/sardana-org/sardana-followup/blob/master/20180710-Barcelona/MacroServerEnvironment.draft) when working on #803.
