### ISSUE TITLE
ZeroD vs OneD vs CounterTimer Controllers (SF#392) [Teresa]

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#238]
Hello,
             I wanted to create a Sardana Controller for creating RoIs
 from 1d detectors. My idea was to use the ZeroDController class,
 adding as extra attributes the limits of the RoI, read the spectrum
 once and compute using the limits the corresponding value for
 each axis of this controller.
 I tried it with a 1D detector for which I already have a OneDController
 working properly. However one I transformed this to ZeroD I found
 several problems:
 
 1. The ZeroDController class is neither Startable nor Loadable (see
 file controller.py in sardana/pool directory), so I can not give an
 exposure time to the controller and I also can not start my detector.

 2. The function reading the value (ReadAll/ReadOne) for the ZeroDController
 class is called continuously during the acquisition and not only at
 the end of the acquisition time, like is the case for the OneDController
 class. This has to consecuencies: a) I will be reading the spectrum also
 during the movement of the motors, what is not convenient,
 b) my detector has to be stopped calling a function 'Stop' at the end of
 the acquisition time. In the OneDController I make this call in the PreRead
 function, that is called only after the acquisition time, here I can not
 use this because the PreRead function is constantly called.

 Using a CounterTimerController instead of a ZeroDController solves the
 problem 1, but not the 2.
 I would like to know if there is any reason for the different implementation
 of the ZeroD and the OneD/TwoD, conceptually, I mean. I would say that
 the only difference should be the dimension size of the output and could
 be some implication due to the different time consuming readout time or
 load of the system, but I don't see any reason for the point 1 (only perhaps
 that you want to make them different to CounterTimers) or the 2 (the
 behaivour for 1D and 2D is perfect like it is, so that the readout is only
 once ... even if actually they are usually not readout, but why for
 ZeroD different?).
 I have implemeted the RoIs in a different way, so I am not in a hurry just
 now, but in any case I think it is worth to know and understand the reasons,
 and if possible change the implementation.

                                       Regards,
                                                       Teresa

Reported by: teresanunez ( http://sf.net/u/tere29 )

Original Ticket: [sardana/tickets/392](https://sourceforge.net/p/sardana/tickets/392)

**Comment by reszelaz** [comment]
Brainstorming ideas:
* More details should be added to each element's overview (Developers Guide -> Overview)
* Add a question to FAQ "What is the difference between C/T and 0D"
