### ISSUE TITLE
os.environ.get ('TANGO_HOST') should not be used (SF#393)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#239]
See ticket: https://sourceforge.net/p/tauruslib/tickets/80/

Files affected: 
sardanaConfig/src/wizards/new_sardana_wizard.py
sardanaConfig/src/wizards/tango_host_page.py
sardanaConfig/src/wizards/tango_host_page.py
scripts/upgrade/upgradeGUI.py

Reported by: rhomspuron ( http://sf.net/u/rhomspuron )

Original Ticket: [sardana/tickets/393](https://sourceforge.net/p/sardana/tickets/393)

**Comment by reszelaz** [comment]
These code is not part of Sardana. Most probably it will be removed at some point. IMO there is no sense to keep this issue opened.
