### ISSUE TITLE
document and distribute the ...config/sardana.py script (SF#395)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#241]
According to this email thread [https://sourceforge.net/p/sardana/mailman/message/34604990/], the script `src/sardana/tools/config/sardana.py` can be used to configure a new sardana system by parsing a spreadsheet doc.

In order to help newcomers, it would be nice if we:

- write the instructions (even if just copying what has been said in the thread) somewhere in the "getting started" section of the sardana docs. Adding the simple and complete example files would also be nice.

- Move the script to `<sdnroot>/scripts/` (and possibly rename it to something such as "sardanaconfig.py" (to avoid confusion with the Sardana DS), patch it with maxIV patches, and make sure that it is included in the list of installable scripts of `setup.py`

Reported by: cpascual ( http://sf.net/u/cpascual )

Original Ticket: [sardana/tickets/395](https://sourceforge.net/p/sardana/tickets/395)

**Comment by teresanunez** [comment]
I think this issue is obsolete and can be closed.

**Comment by reszelaz** [comment]
Thanks @teresanunez. I agree,
