### ISSUE TITLE
Document role and use of the instruments (SF#396)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#242]
The Instrument concept is not documented in the official documentation.

The general role of the instrument is to group the related sardana elements e.g. motors, counters.
In most cases this relation reflects the element association to a laboratory instrument.

Two features uses this information: nexus data storage and the TaurusGUI panel population.

An example on how to configure Instruments is presented in [Howto-GUI_creation].

There are some known issues related to the Instrument use. See: [#218], [#388].

I propose to document it in Developer's Guide -> Overview -> Instrument.

Reported by: reszelaz ( http://sf.net/u/zreszela )

Original Ticket: [sardana/tickets/396](https://sourceforge.net/p/sardana/tickets/396)

**Comment by teresanunez** [comment]
PR created
