### ISSUE TITLE
spock matplotlib bug for OS suse-leap421 (SF#400)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#245]
Detected bug in spock for OS suse-leap421. It seems related with matplotlib (and/or IPython version 3.2.2):

<pre>
Door_demo1_1 [1]: exit()
ERROR: Invalid alias: The name mv can't be aliased because it is another magic command.
sicilia@ct64suse421:/siciliarep/projects/ctgensoft/rcs> spock --profile=demo1
MainThread     INFO     2015-11-18 14:36:46,073 TaurusRootLogger: Using "PyQt4" for Qt
Spock 1.6.1 -- An interactive laboratory application.

help      -> Spock's help system.
object?   -> Details about 'object'. ?object also works, ?? prints more.

IPython profile: demo1

Connected to Door_demo1_1
[TerminalIPythonApp] WARNING | Eventloop or matplotlib integration failed. Is matplotlib installed?
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/lib/python2.7/site-packages/IPython/core/shellapp.pyc in <lambda>(key)
    216         shell = self.shell
    217         if self.pylab:
--> 218             enable = lambda key: shell.enable_pylab(key, import_all=self.pylab_import_all)
    219             key = self.pylab
    220         elif self.matplotlib:

/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in enable_pylab(self, gui, import_all, welcome_message)
   3138         from IPython.core.pylabtools import import_pylab
   3139 
-> 3140         gui, backend = self.enable_matplotlib(gui)
   3141 
   3142         # We want to prevent the loading of pylab to pollute the user's

/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in enable_matplotlib(self, gui)
   3099                 gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
   3100 
-> 3101         pt.activate_matplotlib(backend)
   3102         pt.configure_inline_support(self, backend)
   3103 

/usr/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in activate_matplotlib(backend)
    272     matplotlib.rcParams['backend'] = backend
    273 
--> 274     import matplotlib.pyplot
    275     matplotlib.pyplot.switch_backend(backend)
    276 

/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py in <module>()
    107 
    108 from matplotlib.backends import pylab_setup
--> 109 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    110 
    111 

/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.pyc in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

ImportError: No module named backend_qt4agg
</pre>

Maybe related with this error, plot macros does not work:
- mandelbrot
- J0_plot

Reported by: sagiss ( http://sf.net/u/mrosanes )

Original Ticket: [sardana/tickets/400](https://sourceforge.net/p/sardana/tickets/400)

**Comment by reszelaz** [comment]
We at ALBA don't use this platform anymore and as far as I'm aware noone else is suffering this problem.
So, I'm closing as won't fix. Feel free to reopen.
