### ISSUE TITLE
problem with sar_demo (SF#32)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#28]
Hello, I am playing with the sar_demo

to reproduce this bug,

you need to register in Sardana a motctrl01

then when you try to run the sar_demo you get this kind of problem

```
MainThread     DEBUG    2013-08-26 17:38:36,914 MS_test_1: Creating pool pool/test/1
MainThread     DEBUG    2013-08-26 17:38:37,018 Door/test/1: -> init_device
MainThread     DEBUG    2013-08-26 17:38:37,024 Door/test/1: <- init_device
MainThread     INFO     2013-08-26 17:38:37,030 TaurusRootLogger: Ready to accept request in 0:00:02.376888
SardanaTP.W001 DEBUG    2013-08-26 17:38:44,713 Door/test/1.MacroExecutor: [START] runMacro Macro 'sar_demo()'
SardanaTP.W001 OUTPUT   2013-08-26 17:38:44,800 Door/test/1.Macro[sar_demo]: Creating motor controller motctrl04 ...
SardanaTP.W001 DEBUG    2013-08-26 17:38:44,804 Door/test/1.Macro[sar_demo]: Executing macro: defctrl
SardanaTP.W001 DEBUG    2013-08-26 17:38:44,870 Door/test/1.MacroExecutor: [START] runMacro Macro 'defctrl(DummyMotorController, motctrl04) -> [<built-in function id>]'
SardanaTP.W001 DEBUG    2013-08-26 17:38:44,938 controller/dummymotorcontroller/motctrl04: -> init_device
SardanaTP.W001 DEBUG    2013-08-26 17:38:44,961 controller/dummymotorcontroller/motctrl04: <- init_device
SardanaTP.W001 INFO     2013-08-26 17:38:45,483 mordor:10000.Pool_test_1: Timed out waiting for 'motctrl04' in container
SardanaTP.W001 OUTPUT   2013-08-26 17:38:45,484 Door/test/1.Macro[sar_demo].Macro[defctrl]: Created None
SardanaTP.W001 DEBUG    2013-08-26 17:38:45,490 Door/test/1.MacroExecutor: [ END ] runMacro Macro 'defctrl(DummyMotorController, motctrl04) -> [<built-in function id>]'
SardanaTP.W001 OUTPUT   2013-08-26 17:38:45,493 Door/test/1.Macro[sar_demo]: Creating motor mot01 ...
SardanaTP.W001 DEBUG    2013-08-26 17:38:45,496 Door/test/1.Macro[sar_demo]: Executing macro: defelem
SardanaTP.W001 DEBUG    2013-08-26 17:38:45,504 Door/test/1.MacroExecutor: Sending exception event
SardanaTP.W001 DEBUG    2013-08-26 17:38:45,509 Door/test/1.MacroExecutor: [ENDEX] (WrongParam) runMacro sar_demo
SardanaTP.W001 DEBUG    2013-08-26 17:38:45,512 Door/test/1: Traceback (most recent call last):
  File "/home/picca/Projets/sardana/u-tere29-sardana/src/sardana/macroserver/msmacromanager.py", line 1131, in runMacro
    for step in macro_obj.exec_():
  File "/home/picca/Projets/sardana/u-tere29-sardana/src/sardana/macroserver/macro.py", line 2143, in exec_
    res = self.run(*self._in_pars)
  File "/home/picca/Projets/sardana/u-tere29-sardana/src/sardana/macroserver/macro.py", line 2310, in run
    return self._function(self, *args)
  File "/home/picca/Projets/sardana/u-tere29-sardana/src/sardana/macroserver/macros/demo.py", line 119, in sar_demo
    self.defelem(motor_name , mot_ctrl_name, axis)
  File "/home/picca/Projets/sardana/u-tere29-sardana/src/sardana/macroserver/macro.py", line 2280, in f
    return self.execMacro(*eargs, **kwargs)
  File "/home/picca/Projets/sardana/u-tere29-sardana/src/sardana/macroserver/macro.py", line 304, in new_fn
    ret = fn(*args, **kwargs)
  File "/home/picca/Projets/sardana/u-tere29-sardana/src/sardana/macroserver/macro.py", line 1195, in execMacro
    macro_obj, prepare_result = self.prepareMacro(*args, **kwargs)
  File "/home/picca/Projets/sardana/u-tere29-sardana/src/sardana/macroserver/macro.py", line 304, in new_fn
    ret = fn(*args, **kwargs)
```

Cheers

Reported by: picca ( http://sf.net/u/piccaf )

Original Ticket: [sardana/tickets/32](https://sourceforge.net/p/sardana/tickets/32)

**Comment by jkotan** [comment]
Hi,

On stretch with sardana 2.3.3 and taurus 4.3 when I try to run `sar_demo` I get

    Door_stretch-jk_1 [1]: sar_demo
    Creating motor controller motctrl08 ...
    Created None
    Creating motor mot13 ...
    An error occurred while running Macro 'sar_demo() -> ce78ca8c-17bf-11e8-a4a2-525400b8e442':
    Either of: Controller with name motctrl08 does not exist or Controller with name motctrl08 does not exist made it impossible to decode parameters

and in MacroServer log I get

    SardanaTP.W001 DEBUG    2018-02-22 12:02:01,126 Door/stretch-jk/1.MacroExecutor: Sending exception event
    SardanaTP.W001 DEBUG    2018-02-22 12:02:01,127 Door/stretch-jk/1.MacroExecutor: [ENDEX] (WrongParam) runMacro sar_demo
    SardanaTP.W001 DEBUG    2018-02-22 12:02:01,128 Door/stretch-jk/1: Traceback (most recent call last):
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.3.3a0-py2.7.egg/sardana/macroserver/msmacromanager.py", line 1462, in runMacro
	for step in macro_obj.exec_():
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.3.3a0-py2.7.egg/sardana/macroserver/macro.py", line 2309, in exec_
	res = self.run(*self._in_pars)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.3.3a0-py2.7.egg/sardana/macroserver/macro.py", line 2481, in run
	return self._function(self, *args)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.3.3a0-py2.7.egg/sardana/macroserver/macros/demo.py", line 138, in sar_demo
	self.defelem(motor_name, mot_ctrl_name, axis)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.3.3a0-py2.7.egg/sardana/macroserver/macro.py", line 2451, in f
	return self.execMacro(*eargs, **kwargs)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.3.3a0-py2.7.egg/sardana/macroserver/macro.py", line 352, in new_fn
	ret = fn(*args, **kwargs)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.3.3a0-py2.7.egg/sardana/macroserver/macro.py", line 1325, in execMacro
	macro_obj, _ = self.prepareMacro(*args, **kwargs)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.3.3a0-py2.7.egg/sardana/macroserver/macro.py", line 352, in new_fn
	ret = fn(*args, **kwargs)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.3.3a0-py2.7.egg/sardana/macroserver/macro.py", line 1220, in prepareMacro
	return self.executor.prepareMacro(args, init_opts, kwargs)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.3.3a0-py2.7.egg/sardana/macroserver/msmacromanager.py", line 1241, in prepareMacro
	meta_macro, _, macro_params = self._decodeMacroParameters(pars)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.3.3a0-py2.7.egg/sardana/macroserver/msmacromanager.py", line 1090, in _decodeMacroParameters
	return self.macro_manager.decodeMacroParameters(self.door, params)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.3.3a0-py2.7.egg/sardana/macroserver/msmacromanager.py", line 758, in decodeMacroParameters
	raise WrongParam, msg
    WrongParam: Either of: Controller with name motctrl08 does not exist or Controller with name motctrl08 does not exist made it impossible to decode parameters

    SardanaTP.W001 ERROR    2018-02-22 12:02:01,132 Door/stretch-jk/1: An error occurred while running Macro 'sar_demo() -> ce78ca8c-17bf-11e8-a4a2-525400b8e442':
    Either of: Controller with name motctrl08 does not exist or Controller with name motctrl08 does not exist made it impossible to decode parameters
    SardanaTP.W001 DEBUG    2018-02-22 12:02:01,135 Door/stretch-jk/1.MacroExecutor: Job ended (stopped=False, aborted=False)

Is it the same error?

Bests,
Jan

**Comment by teresanunez** [comment]
The problem above happens because doesn't see the controller or any other device created in the Pool until the Macroserver is restarted.

**Comment by reszelaz** [comment]
This is an old ticket so I'm not sure if this is the same problem.

The Pool notifies the MacroServer about the newly created elements via Tango events. For me it looks like the event does not reach the MacroServer. Could you please check if the event system works? For example by emitting events from the `TangoTest` server and subscribing with a DeviceProxy in ipython at the same machine where your Pool and MacroServer runs?

**Comment by teresanunez** [comment]
Thanks Zibi, I want to do that check .

**Comment by teresanunez** [comment]
I have subscribed to CHANGE_EVENT from a TangoTest attribute and it works and I receive the events.

**Comment by teresanunez** [comment]
Could be related to the use of the cache ?, but in any case should not be different than in debian8

**Comment by reszelaz** [comment]
I think I know where the problem is, could you try with `TANGO_HOST` environment variable set. I mean, apart of setting in `/etc/tangorc`?

**Comment by teresanunez** [comment]
Do you mean with:

export TANGO_HOST=hasp029rack:10000

in the windows where Pool, MS and spock run?.
I have just tried that and I see not changes.

**Comment by reszelaz** [comment]
Yes I was thinking about this. That's strange that it does not help in your case.

If the events work with PyTango, could you now try with taurus? Something like this:
```
import taurus

def cb(*args, **kwargs):
    print args
    pring kwargs

attr = taurus.Attribute("sys/tg_test/1/double_scalar")
attr.addListener(cb)
```
Does it work as well?

**Comment by teresanunez** [comment]
I tried now what you wrote:

import taurus

def cb(*args, **kwargs):
    print args
    print kwargs

attr = taurus.Attribute("sys/tg_test/1/long_scalar")
attr.addListener(cb)

And I get:

p06user:~$ python test_events.py 
(TangoAttribute(tango://hasp029rack.desy.de:10000/sys/tg_test/1/long_scalar), 0, TangoAttrValue{'wvalue': <Quantity(0, 'dimensionless')>, '_attrRef': <weakproxy at 0x7fd2fd39cc58 to TangoAttribute at 0x7fd2fd389d10>, 'rvalue': <Quantity(237, 'dimensionless')>, '_pytango_dev_attr': DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'long_scalar', nb_read = 1, nb_written = 1, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1519375040, tv_usec = 370712), type = tango._tango.CmdArgType.DevLong, value = 237, w_dim_x = 1, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 1, dim_y = 0), w_value = 0), 'time': TimeVal(tv_nsec = 0, tv_sec = 1519375040, tv_usec = 370712), 'error': None, 'config': <weakproxy at 0x7fd2fd39cc58 to TangoAttribute at 0x7fd2fd389d10>, 'quality': <AttrQuality.ATTR_VALID: 0>})
{}
p06user:~$ 

It is fine, isn't it?

**Comment by reszelaz** [comment]
The problem reported in https://github.com/sardana-org/sardana/issues/28#issuecomment-367664234, seems to be related to https://github.com/taurus-org/taurus/pull/692. Sardana works correctly with Taurus commit ` 180d5b6`.

**Comment by cmft** [comment]
Hi @reszelaz ,
The #taurus-org/taurus#692  fix a  persistence bug, so before these changes, any Tango attribute that were not reference did not disappear ([taurus/issue-511](https://github.com/taurus-org/taurus/issues/511)) and the listeners that pointing to it still receiving its events  ([taurus/issue-512](https://github.com/taurus-org/taurus/issues/512)) . 

Now the factory does not keep the reference of the "delete" attributes. So, IMHO taurus works as expected and the bugs are in Sardana.

Adding these lines  in the sequencer main code you can see this behavior:
```
import taurus
print len(taurus.Factory().tango_attrs), taurus.Factory().tango_attrs.keys()
``` 

Output with #taurus-org/taurus#692 
``` 
8 
['tango://controls01.cells.es:10000/macroserver/cfalcon/1/state',
'tango://controls01.cells.es:10000/door/cfalcon/1/error',
'tango://controls01.cells.es:10000/door/cfalcon/1/result',
'tango://controls01.cells.es:10000/door/cfalcon/1/debug',
'tango://controls01.cells.es:10000/door/cfalcon/1/info',
'tango://controls01.cells.es:10000/door/cfalcon/1/output',
'tango://controls01.cells.es:10000/door/cfalcon/1/state',
'tango://controls01.cells.es:10000/door/cfalcon/1/warning']
```

Output with commit `180d5b6`

```
13
[ 'tango://controls01.cells.es:10000/macroserver/cfalcon/1/state', 
'tango://controls01.cells.es:10000/door/cfalcon/1/error', 
'tango://controls01.cells.es:10000/door/cfalcon/1/result',
'tango://controls01.cells.es:10000/door/cfalcon/1/debug',
'tango://controls01.cells.es:10000/door/cfalcon/1/info', 
'tango://controls01.cells.es:10000/door/cfalcon/1/output', 
'tango://controls01.cells.es:10000/door/cfalcon/1/state', 
'tango://controls01.cells.es:10000/door/cfalcon/1/warning']
## Attributes that seems to be not references after #taurus-org/taurus#692 
'tango://controls01.cells.es:10000/macroserver/cfalcon/1/elements', 
'tango://controls01.cells.es:10000/macroserver/cfalcon/1/environment',
'tango://controls01.cells.es:10000/door/cfalcon/1/macrostatus',
'tango://controls01.cells.es:10000/door/cfalcon/1/input', 
'tango://controls01.cells.es:10000/door/cfalcon/1/recorddata',
```

**Comment by cmft** [comment]
Hi @jkotan, @teresanunez ,
PR #710 should fix the troubles with missing events. Can you test it?

**Comment by teresanunez** [comment]
HI @cmft, many thanks, I have just tested it and the problem with running sar_demo due to
the missing events is not there any more.

**Comment by reszelaz** [comment]
I have directly pushed 67a159b that should fix most of the problems. #84 will deal with the consequences of the eventual other problems.
