### ISSUE TITLE
macroexecutor exception if macro in history no longer exists (SF#50)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#35]
Steps to reproduce:

1) Define a useless macro (i.e. "useless_macro" in the attached "useless.py")
2) Restart macroserver
3) run macroexecutor and execute 3 macros in this order:
    a) execute any valid macro (i.e. ascan dummy_motor)
    b) execute the useless_macro
    c) execute any valid macro (i.e. ascan dummy_motor)
4) quit macroexecutor
5) kill macroserver
6) remove the file in which the useless macro is defined (i.e. "useless.py")
7) start macroserver
8) run macroexecutor
9) go to "History viewer" tab and click on an entry below the no longer existing "useless_macro". You will see that an exception is raised in the console and that the macro is not correctly loaded in yellow the command line widget of the window.

Reported by: jairomoldes ( http://sf.net/u/jairomoldes )

Original Ticket: [sardana/tickets/50](https://sourceforge.net/p/sardana/tickets/50)

**Comment by reszelaz** [comment]
I'm closing this as duplicate because #18 is a more general ticket that treats the same bug.
