### ISSUE TITLE
Bug on relmaclib

### ISSUE THREAD

**Issue by rhomspuron** [sardana-org/sardana#377]
It you try to reload a library of macros and there is a macro with a wrong definition of the parameters, the macro relmaclib does not show the error, but on the MacroServer log you can see it. 

Macro code:
<pre>
class dynaGO(Macro):
       param_def = [
      ['temperature', Type.Float,None,],
      ['temperature_old', Type.Float,None,]
        ]

     def run(self, temperature, temperature_old):
       temp = temperature
       self.execMacro('dynRamp %f' %temp)
     ...
</pre>

MacroServer Log:
<pre>
SardanaTP.W005 DEBUG    2016-12-01 16:50:11,880 MS_BL22.MacroManager: Adding macro class dynaGO
SardanaTP.W005 ERROR    2016-12-01 16:50:11,882 MS_BL22.MacroManager: Error adding macro dynaGO
SardanaTP.W005 DEBUG    2016-12-01 16:50:11,882 MS_BL22.MacroManager: Details:
Traceback (most recent call last):
  File "/homelocal/sicilia/lib/python/site-packages/sardana/macroserver/msmacromanager.py", line 502, in reloadMacroLib
    self.addMacro(macro_lib, macro)
  File "/homelocal/sicilia/lib/python/site-packages/sardana/macroserver/msmacromanager.py", line 514, in addMacro
    return add(macro_lib, macro)
  File "/homelocal/sicilia/lib/python/site-packages/sardana/macroserver/msmacromanager.py", line 523, in addMacroClass
    macro_class = MacroClass(**params)
  File "/homelocal/sicilia/lib/python/site-packages/sardana/macroserver/msmetamacro.py", line 238, in __init__
    Parameterizable.__init__(self)
  File "/homelocal/sicilia/lib/python/site-packages/sardana/macroserver/msmetamacro.py", line 118, in __init__
    self._parameter = self.build_parameter()
  File "/homelocal/sicilia/lib/python/site-packages/sardana/macroserver/msmetamacro.py", line 137, in build_parameter
    return self._build_parameter(self.get_parameter_definition())
  File "/homelocal/sicilia/lib/python/site-packages/sardana/macroserver/msmetamacro.py", line 168, in _build_parameter
    ret_p['description'] = p[3]
IndexError: list index out of range
SardanaTP.W005 DEBUG    2016-12-01 16:50:11,882 MS_BL22.MacroManager: Adding macro class dynaVtuneClaess
SardanaTP.W005 DEBUG    2016-12-01 16:50:11,884 MS_BL22.MacroManager: Adding macro class energy2K
SardanaTP.W005 DEBUG    2016-12-01 16:50:11,884 MS_BL22.MacroManager: Adding macro class hecryo
SardanaTP.W005 DEBUG    2016-12-01 16:50:11,885 MS_BL22.MacroManager: Adding macro class mono_change
SardanaTP.W005 DEBUG    2016-12-01 16:50:11,887 MS_BL22.MacroManager: Adding macro class rcs
SardanaTP.W005 DEBUG    2016-12-01 16:50:11,888 MS_BL22.MacroManager: Adding macro class set_rcs
SardanaTP.W005 DEBUG    2016-12-01 16:50:11,888 MS_BL22.MacroManager: Adding macro class time_constKscan
SardanaTP.W005 OUTPUT   2016-12-01 16:50:11,891 BL22/DOOR/01.Macro[relmaclib]: claess_utils successfully (re)loaded (found 16 macros)
SardanaTP.W005 DEBUG    2016-12-01 16:50:11,892 BL22/DOOR/01.MacroExecutor: [ END ] runMacro Macro 'relmaclib(claess_utils) -> d7d229d6-b7dd-11e6-a884-001999eaf6e9'
SardanaTP.W005 DEBUG    2016-12-01 16:50:11,892 BL22/DOOR/01.MacroExecutor: Job ended (stopped=False, aborted=False)
/tmp/tango-sicilia/MacroServer/bl22/log.txt lines 59870-59902/59902 (END)
</pre>

**Comment by mrosanes** [comment]
A new pull request has been opened to deal with this issue:
https://github.com/sardana-org/sardana/pull/642

**Comment by reszelaz** [comment]
@rhomspuron the PR that was dealing with this issue is now integrated. I'll close the issue. If the solution is not satisfactory, please reopen it.

**Comment by rhomspuron** [comment]
Thanks!
