### ISSUE TITLE
Error reading/writing ZeroD accumulation type

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana#385]
Hi,
          I was working with zeroD experimental channels and I have seen that one can neither read nor 
write the CumulationType attribute of the devices of the ZeroDExpChannel class. The reason is:
the function for reading/writing it is definde with the name get/set_accumulation_type in the file  pool/poolzerodexpchannel.py, but the file tango/pool/ZeroDExpChannel.py calls the function
get/set_cumulation_type for reading/writing the attribute, and this function does not exit. The correction
is trivial ... but which name do you want to keep for the function ?, using accumulation or using
 cumulation?. I can create the PR once this is decided. Thanks.
                         Regards,
                                       Teresa

**Comment by reszelaz** [comment]
Some issues with 0D were already reported in: https://github.com/sardana-org/sardana/issues/258 and https://github.com/sardana-org/sardana/issues/257. Now I don't remember the conclusions that we got into at that time. Maybe @sagiss remembers? Otherwise I will take a look into it the next week.

**Comment by reszelaz** [comment]
I think that the easiest will be to rename the Tango attribute to `AccumulationType` instead of `CumulationType`. This is because in the core everywhere is used "accumulation".
I consider it as not breaking the API, because it was not working before and no one had reported it.

**Comment by teresanunez** [comment]
Hi Zibi, I agree with you. Should I proceed with the change?.

**Comment by reszelaz** [comment]
It would be great if you could make the changes and create a PR.

**Comment by teresanunez** [comment]
I have just sent a PR
