### ISSUE TITLE
Controller axis attributes write method not found (SF#61)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#39]
This is a bug already reported in old sardana repository (https://sourceforge.net/p/tango-cs/bugs/618/), but maybe it was lost on the migration to git.

It looks like the pool is somehow mixing and/or incorrectly setting the read and write methods for axis attributes.
You can reproduce the problem using the BL29EnergyMono controller, available in:
sardana-controllers.git/python/pseudomotor/ALBA_BL29_BOREAS

If you try to write the axis attribute "heg_sm2_offset" you get the following exception:
DevFailed: DevFailed
DevError[
desc = write_ranges method not found for heg_sm2_offset
origin = PyTango::Attr::write
reason = PyTango_WriteAttributeMethodNotFound
severity = ERR

DevError
desc = Failed to write_attribute on device pm/energy_mono_ctrl/1, attribute heg_sm2_offset
origin = DeviceProxy::write_attribute()
reason = API_AttributeFailed
severity = ERR
]

Note that the exception complains about that "write_ranges" method is not found, when this is another read only axis attribute. If you defined that attribute (the "ranges" axis attribute) as read/write, then the problem disappears.
I think that the problem may be in the "add_dynamic_attribute()" method of sardana "src/sardana/tango/pool/PoolDevice.py"

If this assigned to some member of Alba, I can lend you a already working setup for reproducing the problem.

Reported by: jairomoldes ( http://sf.net/u/jairomoldes )

Original Ticket: [sardana/tickets/61](https://sourceforge.net/p/sardana/tickets/61)

**Comment by reszelaz** [comment]
Hi @jairomoldes,
Finally we are getting back to this issue. Do you still have this issue reproducible?
What we are are seeing with @HEnquist is that the issue starts to appear if there are attributes  with the same name but different characteristic (type, writable, format) defined for different Sardana elements of the same Tango class. Here especially problematic is the writable characteristic. In your case you found it on pseudo motors. Do you use the same attribute name(s) with different characteristic in different axis/controllers of pseudo motors?

**Comment by reszelaz** [comment]
The same issue was reported recently in #1436. Since that new issue contains more information, I propose to close this one.
