### ISSUE TITLE
Macro mym2 present in macros module demo.py does not work

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#397]
mym2 macro does not work:

<pre>
Door_demo1_1 [8]: %mym2 mot54
An error occurred while running Macro 'mym2(mot54) -> 0d12fec4-c84e-11e6-a04c-001d0969db5b':
getMotorNames
</pre>

I think that this macro maybe a test that has been done in the past, but maybe is not a relevant macro and it could maybe be removed.

**Comment by reszelaz** [comment]
Yes, I agree. It could be removed if there are no references to it in the docs, or in the code.
