### ISSUE TITLE
h5 file is not saved in windows

### ISSUE THREAD

**Issue by sagiss** [sardana-org/sardana#400]
After indicating the ScanFile (demo1.h5) in Windows thanks to expconf, we performed a scan. When trying to execute 'showscan' the macro reported:

<pre>
Cannot plot scan:
Could not find demo1.h5 in any of the following locations:
C:\tmp
</pre>

The h5 file is not created.
(On the other hand the .dat (demo1.dat) is created correctly).

**Comment by reszelaz** [comment]
Could it be that you don't have nxs module installed? The NXscan_FileRecorder requires it:
https://github.com/sardana-org/sardana/blob/develop/src/sardana/macroserver/scan/recorder/storage.py#L88

**Comment by reszelaz** [comment]
@sagiss was it finally a missing `nxs` module? If so, could you close this issue?

**Comment by sagiss** [comment]
'nxs' module was missing; we close this ticket.
