### ISSUE TITLE
document online visualization of scans (SF#63)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#41]
The solutions mentioned in the following thread should be in the docs:
https://sourceforge.net/mailarchive/message.php?msg_id=31836161

Reported by: cpascual ( http://sf.net/u/cpascual )

Original Ticket: [sardana/tickets/63](https://sourceforge.net/p/sardana/tickets/63)

**Comment by cpascual** [comment]
Docs added in #853
