### ISSUE TITLE
Python splat operator does not work when calling macros

### ISSUE THREAD

**Issue by JeanLucPons** [sardana-org/sardana#417]
Hello,

We have moved from sardanna 1.5 to sardanna 2.1.1.

It seems that in 2.1.1, in the MacroServer, the python splat (unpack) operator does not work when calling a macro from an other macro. This worked fine in 1.5.

Ex:
attr_list = ( "RFAmplitude", "RFPhase","MagLoopGain")
self.macros.save_opfile(True, filename, comment, *self.attr_list)
is interpreted as
self.macros.save_opfile(True, filename, comment, self.attr_list) 
which means that the save_opfile macro receive a list instead of an expanded list of parameters.

I know that the 2.1.1 is not the last release. But I would like to know if this operator work in 2.2 or if not, if it can be fixed.
Thanks

Jean-Luc PONS

**Comment by teresanunez** [comment]
Hello Jean-Luc,
                           I suppose save_opfile is a macro with a ParamRepeat as last argument, isn't it?.
If this is the case ... the implementation of ParamRepeat has been changed, implying some 
changes in the way this arguments have to be provided. So it is normal that you have to change this.
Here the discussions about that:
https://sourceforge.net/p/sardana/tickets/3/

                              Regards,
                                               Teresa

**Comment by JeanLucPons** [comment]
OK, thanks. I wasn't aware of this breaking of backward compatibility.
