### ISSUE TITLE
Macrobutton fails to correctly parse string parameter with spaces

### ISSUE THREAD

**Issue by jordiandreu** [sardana-org/sardana#423]
The macro button does not correctly parse the string-type argument if it contains a space character. The parameter value is split at the space character position and the second part as the original value is taken as the value for the following argument (if it exist).

This can be easily tested by using the new macro button main application used for testing and proposed in PR #422.

**Comment by cmft** [comment]
I did a fix in my branch https://github.com/cmft/sardana/tree/fix_macrobutton . I test the implementation using PR #422. If you agree with the changes I will create a PR.

**Comment by reszelaz** [comment]
This bug was resolved in #425
