### ISSUE TITLE
Duplicate repeats in macroexecutor and sequencer

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#426]
Adding the possibility to duplicate an already defined repetition of a repeat parameter may save time to the users, especially when the repeat parameter is complex (contains nested repeat parameters or basically contains many simple parameters) and the difference between the repetitions is minor. With this feature the user could duplicate the already introduced repetition and just modify the differences.

In the future, similar feature could be added to the sequencer in order to duplicate macros.

**Comment by reszelaz** [comment]
If there are no other ideas on how to implement it we were thinking on:
* adding the "duplication" button to the parameters editor, just below the "move down" arrow
* prior to the duplication, the already existing repetition must be selected in the tree
* the duplicated repetition is appended at the end of the repetitions
* after duplication the selection must be maintained at the previously selected repetition

**Comment by sagiss** [comment]
This feature has been implemented in Sardana develop.

**Comment by reszelaz** [comment]
Implemented in #429.
