### ISSUE TITLE
strings are interpreted as sequences by macro parameter parser

### ISSUE THREAD

**Issue by cpascual** [sardana-org/sardana#437]
Consider the following macro:

```python
class pt16(Macro):
    param_def = [
        [ 'string_list1', [ [ 'pos', Type.String, None, 'value'] ], None, 'List of values'],
        [ 'string_list2', [ [ 'pos', Type.String, None, 'value'] ], None, 'List of values'],
    ]
    def run(self, *args, **kwargs):
        pass
```

Now, if in spock one does: `pt16 [foo] [bar]`, it works fine (the parser interprets it as `[['foo'], ['bar']]`), but if one does `pt16 [foo] bar`, (which should be rejected) the parser "swallows" it and returns  `[['foo'], ['b', 'a', 'r']]`

This is not a big deal, but it could cause difficult to debug problems in some situations.

**Comment by reszelaz** [comment]
I haven't debug it, but I have a feeling that it is not a problem with the parser but with the parameter decoder (this is already the server side). Probably there is somewhere missing a check if the value is a non string sequence.
