### ISSUE TITLE
spock ignores extra parameters 

### ISSUE THREAD

**Issue by cpascual** [sardana-org/sardana#438]
This is probably known, but IMHO it should be fixed.

Consider, e.g. the example macro `pt0`, which defines no parameters.

spock does not complain if one executes `pt0 foo bar 1 2 3 4`

Similarly, pt1 (which accepts a single parameter) would ignore all but the first parameter passed to it.

IMHO, the parser should complain and refuse to execute the macro.

**Comment by teresanunez** [comment]
Hi Carlos, yes, this is known. We (Zibi, Marc and myself) have discussed about this when we made
the new implementation for the ParamRepeat arguments. We keep it like it is because it is a general
issue, all macros work like this. But yes, I agree that it should be better to change the behaviour.

**Comment by reszelaz** [comment]
I agree. This can be easily fixed in the ParamDecoder and FlatParamDecoder classes. Parser does not know about the parameters definition.
