### ISSUE TITLE
missing code examples in online docs?

### ISSUE THREAD

**Issue by alexbjorling** [sardana-org/sardana#439]
Reading the [online documentation](http://sardana-controls.org/en/latest/users/overview.html), I get the feeling that there are code examples missing. For example, one paragraph ends "The following example shows the procedure to move a motor.", and the next one starts "As you can see in the example,". This happens here and there, something must be missing in between.

Thanks,
Alex

**Comment by alexbjorling** [comment]
After reading the rest of the docs I see that there are bigger gaps elsewhere, closing this...

**Comment by reszelaz** [comment]
I have added the missing example. I have pushed it directly since it was a copy&paste from the "Writing Macros" part.

Ususally the missing parts in the documentation are marked with the TODO box.
