### ISSUE TITLE
Problem in loading a favorite macro in macroexecutor

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#441]
When loading a macroexecutor previously saved favourite macro (with parameter values stored) in the same macroexecutor a bug appears.

And it does not let you to change the parameters of the recently loaded favourite macro.

<pre>
Traceback (most recent call last):
  File "/homenfs/mrosanes/PycharmProjects/sardana/src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroparameterseditor/model.py", line 63, in flags
    not node.type() in globals.EDITOR_NONEDITABLE_PARAMS):
  File "/homenfs/mrosanes/PycharmProjects/sardana/src/sardana/taurus/core/tango/sardana/macro.py", line 502, in type
    return self._type
AttributeError: 'SingleParamNode' object has no attribute '_type'
</pre>

**Comment by reszelaz** [comment]
What was the definition of the macro? Which parameters does it have? I remember this problem when between storing and restoring macro from the favorites list a parameter value e.g. motor, was eliminated from the Pool.

**Comment by sagiss** [comment]
Attached an image of the macro launched. They are the manytomos macros (a set of macros used for a specific beamline at ALBA synchrotron) which contains param repeats.

![macroexecutor](https://cloud.githubusercontent.com/assets/1327426/24551276/2a046686-1622-11e7-9125-80a47d3c71cd.jpeg)

**Comment by sagiss** [comment]
The problem of being unavailable to modify the parameters of the stored favorite macro is only happening when closing and opening again the macroexecutor after having stored the favorite macro. This does not happen with the macros in the 'history viewer': the parameters of the macros in the 'history viewer' can be modified without problem.

**Comment by sagiss** [comment]
The problem appears both with Taurus3 and with Taurus4.
