### ISSUE TITLE
backward comatibility problems of senv

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#442]
Hi,

Since #434 has been already closed I create another ticket for the bug, i.e.

    senv ScanFile "[\"file.nxs\",\"file.fio\"]"

no more works.

Bests,
Jan

**Comment by reszelaz** [comment]
I have an idea on how to fix it using a negative lookbehind assertion. I will try to propose a solution along the weekend.

**Comment by reszelaz** [comment]
@jkotan could you please try if #443 fixed it?

**Comment by jkotan** [comment]
Hi Zibi,

Great. Thanks. It looks like it solves the problem.

Cheers,
Jan
