### ISSUE TITLE
Problems with setting a timer of 0DChannels in expconf with SEP6

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#448]
Hi,

I've just noticed when I create a new measurement group in expconf firstly adding exp_adc01 (0DChannel) and then exp_t01 (Timer) and press apply I get the following error:

    p09/door/haso228k.01 [8]: MainThread     INFO     2017-04-11 09:08:53,896 TaurusRootLogger: Using "PyQt4" for Qt
    MainThread     ERROR    2017-04-11 09:09:20,415 TaurusRootLogger: Could not create/delete/modify Measurement group "mtest2": DevFailed(args = (DevError(desc = "KeyError: ('timer',)\n", origin = '  File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/tango/pool/MeasurementGroup.py", line 216, in write_Configuration\n    self.measurement_group.set_configuration_from_user(cfg)\n  File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/pool/poolmeasurementgroup.py", line 451, in set_configuration_from_user\n    self.set_configuration(config, propagate=propagate)\n  File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/pool/poolmeasurementgroup.py", line 355, in set_configuration\n    if timer_ctrl_data[\'timer\'] != g_timer:\n', reason = 'PyDs_PythonError', severity = tango._tango.ErrSeverity.ERR), DevError(desc = 'Failed to write_attribute on device mntgrp/pool_haso228k/mtest2, attribute configuration', origin = 'DeviceProxy::write_attribute()', reason = 'API_AttributeFailed', severity = tango._tango.ErrSeverity.ERR)))

Moreover, if I try to set in expconf a timer of exp_adc01 I get 

    Traceback (most recent call last):
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/taurus/qt/qtgui/extra_sardana/measurementgroup.py", line 782, in setEditorData
	editor.addItem(channel['name'], Qt.QVariant(channel['full_name']))
    TypeError: string indices must be integers, not str

Bests,
Jan

**Comment by teresanunez** [comment]
Hi Jan, I can not reproduce this. It happens the same for you if you use a  counter instead of a 0D?.
 For me it works.

**Comment by jkotan** [comment]
Hi Teresa. No with counter everything is fine (except #445 ).

**Comment by teresanunez** [comment]
So I think you should better change the title of the issue.

**Comment by reszelaz** [comment]
Does it happen if you add them in the reversed order? First a counter/timer and then a 0d?

**Comment by jkotan** [comment]
In reverse order the first step is OK by when I try to change the timer od exp_adc01 I get again

     Traceback (most recent call last):
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/taurus/qt/qtgui/extra_sardana/measurementgroup.py", line 782, in setEditorData
    editor.addItem(channel['name'], Qt.QVariant(channel['full_name']))
    TypeError: string indices must be integers, not str

**Comment by reszelaz** [comment]
This bug was introduced in #218. Comming back to previous implementation avoids this exception. Could you confirm that by trying #451?

**Comment by jkotan** [comment]
Hi Zibi,

I'm just on one week vacations. In case this is argent can some one try it instead of me ?

Bests,
Jan

**Comment by reszelaz** [comment]
No worries! I think this can wait, but if there is anyone else willing to try it, please go ahead.

Have a good holidays!

**Comment by teresanunez** [comment]
I will try if I have a moment.

**Comment by teresanunez** [comment]
Hi, I have tried and the error message does not appear. I can close the issue and accept the PR.
