### ISSUE TITLE
Improve travis-ci output readability when flake8 check fails

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#452]
Travis always executes 2 main checks - flake8 and sardanatestsuite. It is difficult to figure out which of these two was the reason of failure. One of the possibilities of the improvement would be to use the configuration matix as explained in this https://github.com/sardana-org/sardana/pull/450#issuecomment-293496858.

**Comment by cpascual** [comment]
Seeing how frustrating the experience was for a seasoned developer such as @teresanunez in #462, I think we should try to implement this kind of urgently (or risk losing some contributions).

Another related improvement, could be to make the flake8_diff.sh script to echo the following:

- a suggested autopep8 command that would fix the issues 
- the command that the user can run locally to check before pushing 

or alternatively,...
- write a generic version of the above instructions in the CONTRIBUTING.md file and let the flake8_diff.sh point to it.

**Comment by teresanunez** [comment]
Many thanks @cpascual, I think these are the main points ... Once you got the error after your first attempt (in case, you were not aware of checking your code locally before making the PR),
it shoud be pointed out how the code could be checked before pushing again and the output of this check should be a command for fixing the issues. I think this would help a lot. I would show the information compact and clear (for the specific case) in the PR itself.

**Comment by reszelaz** [comment]
First of all sorry about the inconveniences. I totally agree on the relevance of this issue. But this week I won't have time to improve it, I could start from the next weekend.

**Comment by cpascual** [comment]
Fixed by #470
