### ISSUE TITLE
Close file on stopping the scan

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#455]
Hi,

our user often stop the scan. Therefore, it would be good if recorders have a possibility to close properly their files. It could be done by calling endRecordList() on StopException.
(I've not found anything like this).

For some complicated file formats data without closing the file can be corrupted.
In principle recorders could close their files on their next start but this solution is unsafe:
recorder may not be called again or file may be already moved.

Is there any mechanism to prevent against such data corruption?

Best regards,
Jan

**Comment by reszelaz** [comment]
Sorry, I'm a little bit limited with the access to the computer right now so I haven't looked into the code yet... Just to clarify, in case the scan ends correcty i.e. it is not aborted by the user, the behavior already satisfies you. It is just for the special case of the abort?

**Comment by jkotan** [comment]
yes. It is only the case when someone stop the scan.

**Comment by reszelaz** [comment]
At first glance it makes sense to treat the files exactly the same in both these cases.

**Comment by reszelaz** [comment]
And what about the accidental exceptions during the scan e.g. a timeout, or a motor trying to move out of the limit. Is the `endRecordList` called then?

**Comment by jkotan** [comment]
To my knowledge after  accidental exceptions during the scan the |endRecordList| is not called.

**Comment by reszelaz** [comment]
Thanks for investigating it. I would say that we should treat all the 3 cases in the same way:
- normal end
- user abort
- unhandled exception

Maybe we would need to add this information (how the scan ended) to the environment so the recorder could write a more explicative message. 

Unfortunatelly I can't work on it at least for the following 2 months. But if you propose a PR I will try to  comment on it.

**Comment by teresanunez** [comment]
If you want I can try to work on that.

**Comment by jkotan** [comment]
Thanks Teresa. If you need a help let me know.

**Comment by jkotan** [comment]
Hi Teresa and Zibi,

It looks like this issue is related to #202 . Recorder's calls are usually inside macros. The question if we want to provide such mechanism   only for recorders of for all macros.

Bests,
Jan

**Comment by teresanunez** [comment]
Hi Jan,
 I do not really see a direct relation. The issue #202 is already implemented (not in the official sardana but at DESY) and running in our beamlines. It is about actions that the users what to do when an scan is aborted, but we don't want the users to have to put there the close of the files ...

**Comment by jkotan** [comment]
Hi Teresa,

Great. I didn't know. My idea was just  to add  the `endRecordList()` into `on_stop` of `ascan*`  macros.
Usually recorders are only used in built-in macros like ascan* so user don't have to add anything unless
she/he uses Recorders explicitly in her/his macros.

But since I've looked at the code in details I may be wrong.

Bests,
Jan

**Comment by jkotan** [comment]
If on_stop in not called on StopException  the above idea does not work.

**Comment by teresanunez** [comment]
Hi Jan, this issue has to be solved in the core of sardana, not in user defined functions.

**Comment by jkotan** [comment]
Ah, Ok. Thanks for info.  So in order to implement it simply we can use `on_abort()`  method of  ascan*(Macro).

**Comment by reszelaz** [comment]
I agree with @teresanunez , we should look for the correct place in the core to call indirectly (via `RecordList` and `DataHandler`) the `endRecordList` of the recorders. Ì think that this should be the GScan class. Maybe somewhere around [here](https://github.com/sardana-org/sardana/blob/develop/src/sardana/macroserver/scan/gscan.py#L875) ?
The `end` method is the one which does the job in case of normal end of the scan.

**Comment by teresanunez** [comment]
Hi Zibi, thanks for your comment. I have still not had time to look at this. I hope tomorrow or on Friday.

**Comment by jkotan** [comment]
Yes. I agree.  One can create the `end`-like method in `GScan`  and call it `on_abort`.

**Comment by teresanunez** [comment]
Hi Jan,
              I was interrupting scans with ctrl-C and saving data in spec and fio formats and I do
 not get any corrupted file. The files are correctly saved. Is there any way to reproduce the
 error you are talking about?. Thanks.

**Comment by jkotan** [comment]
Hi Teresa,

But do you get e.g. 'end time' saved into FIO file?

1) SPEC, and FIO formats are text format so it is not a big issue for them.  For binary formats, like nexus 
this 'end time' or similar information are more important in order properly interpret the data or even open the file in the viewer (so they are corrupted).

2) Moreover,  it is not good to left unclose the file for the system. Actually, the for FIO recorders and SPEC files are closed at the beginning of the next scan. 
But in the case of changing beamtime  we switch the hole filesystem so the file will be not closed and may be not flushed. In this situation (data is not flushed)  the operating system is not obligated to store all data from the cache in the file.

Therefore, It would be good to give possibility to a recorder developer to say his/her last word.
It can be call of endRecordList() but it would be good to pass to the recorder information that scan was stopped or aborted , e.g. additional parameter passed to recorder or call additional recorder method, i.r. abortRecordList(). Then the recorder has choice either to close the file doing nothing or store some additional info into file.

Bests,
Jan

**Comment by reszelaz** [comment]
I agree with @jkotan, the abort and exception cases deserve the same treatment that the normal end of the scan.

With the implementation I would not go for the `on_abort` method of the macros. I would try to keep it in the `GScan` class, maybe this could be implemented with handling of the `AbortException`/`StopExpceition` and any other exceptions? To pass the information to the recorder I would try to use the environment which already contains other metadata of the scan and I would use a dedicated enum for that e.g.
`ScanEnd(Normal, Stop, Abort, Exception)`. Just treat it as brainstorming ideas, I have not looked into the code carefully.

**Comment by reszelaz** [comment]
After merging #461 this issue should be already solved in develop. Thanks @jkotan and @teresanunez!
