### ISSUE TITLE
Improve generic scan with check of position limits when possible (SF#73)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#46]
When the user run an scan if the end position is out of range, the scan starts, and when the motor detect the limit the scan stops with an exception.

It is useful to check the limits of each motor before to run the scan.
 

Reported by: rhomspuron ( http://sf.net/u/rhomspuron )

Original Ticket: [sardana/tickets/73](https://sourceforge.net/p/sardana/tickets/73)

**Comment by daneos** [comment]
This is mostly fixed by #963, excluding pseudomotor hierarchy. I think that we need a more generic way (that is, the moveable should be able to check if given position exceeds its limits itself), see #974.

**Comment by reszelaz** [comment]
Fix in #963.
