### ISSUE TITLE
Use h5py insted of nxs in Sardana

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#460]
Nexus library and python-nxs are not maintained anymore. It is strongly recommended to use h5py instead of nxs:

(http://download.nexusformat.org/doc/html/napi.html#napi) :
"It is expected that most application developers will use standard HDF5 tools 
to read and write NeXus.(...) Therefore, the decision has been taken to freeze 
the NAPI. Maintenance is reduced to bug fixes."

Adapt Sardana code to use h5py instead of nxs.
nxs library is used by the Sardana recorders to store data in h5 file format.

--

Moreover, an error when storing h5 files using Sardana (which uses python-nxs) on debian9 stretch. 

How to reproduce the error:
- Set ScanDir and ScanFile (test.h5)
- Launch a scan

The error is coming from NeXus, not from Sardana:

<pre>
Door_1 [28]: ascan mot09 0 10 2 0.1
[START] runMacro Macro 'ascan(mot09, 0.0, 10.0, 2, 0.1) -> b0aa6134-3163-11e7-a4f8-484d7ed736dd'
Operation will be saved in /home/mrosanes/z/tmp/scanoutputdir/scan.h5 (w5)
Scan #10 started at Fri May  5 09:23:09 2017. It will take at least 0:00:02.243056
Moving to start positions...
 #Pt No    mot09      ct09      ct10      ct11      ct12 dt
Sending exception event
[ENDEX] (MacroServerException) runMacro ascan
Traceback (most recent call last):
  File "/homenfs/mrosanes/PycharmProjects/sardana/src/sardana/macroserver/msmacromanager.py", line 1232, in runMacro
    for step in macro_obj.exec_():
  File "/homenfs/mrosanes/PycharmProjects/sardana/src/sardana/macroserver/macro.py", line 2244, in exec_
    for i in it:
  File "/homenfs/mrosanes/PycharmProjects/sardana/src/sardana/macroserver/macros/scan.py", line 251, in run
    for step in self._gScan.step_scan():
  File "/homenfs/mrosanes/PycharmProjects/sardana/src/sardana/macroserver/scan/gscan.py", line 841, in step_scan
    self.start()
  File "/homenfs/mrosanes/PycharmProjects/sardana/src/sardana/macroserver/scan/gscan.py", line 797, in start
    self.data.start()
  File "/homenfs/mrosanes/PycharmProjects/sardana/src/sardana/macroserver/scan/scandata.py", line 259, in start
    self.datahandler.startRecordList(self)
  File "/homenfs/mrosanes/PycharmProjects/sardana/src/sardana/macroserver/scan/recorder/datarecorder.py", line 56, in startRecordList
    recorder.startRecordList(recordlist)
  File "/homenfs/mrosanes/PycharmProjects/sardana/src/sardana/macroserver/scan/recorder/datarecorder.py", line 113, in startRecordList
    self._startRecordList(recordlist)
  File "/homenfs/mrosanes/PycharmProjects/sardana/src/sardana/macroserver/recorders/storage.py", line 512, in _startRecordList
    self.fd = nxs.open(self.filename, nxfilemode)
  File "/usr/lib/python2.7/dist-packages/nxs/napi.py", line 273, in open
    return NeXus(filename, mode)
  File "/usr/lib/python2.7/dist-packages/nxs/napi.py", line 320, in __init__
    raise NeXusError, "Could not %s %s"%(op,filename)
NeXusError: Could not create /home/mrosanes/z/tmp/scanoutputdir/scan.h5

An error occurred while running Macro 'ascan(mot09, 0.0, 10.0, 2, 0.1) -> b0aa6134-3163-11e7-a4f8-484d7ed736dd':
Could not create /home/mrosanes/z/tmp/scanoutputdir/scan.h5
Job ended (stopped=False, aborted=False) 
</pre>

This error is present in debian9 (testing), but not in debian8 (stable)

**Comment by cpascual** [comment]
For the implementation, have a look at how to write nexus files with h5py: http://download.nexusformat.org/doc/html/examples/h5py/index.html

**Comment by cpascual** [comment]
Note: while this is an "enhancement" for sardana, it is a **serious** bug for debian since the pyhon-nxs package n which we currently depend may be dropped from debian9. See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861900.

**Comment by cpascual** [comment]
If anyone is interested in following the development efforts for getting rid of nxs in the NXScan recorder, see my WIP on this: https://github.com/cpascual/sardana/tree/bug-460

**Comment by cpascual** [comment]
The implementation in  https://github.com/cpascual/sardana/tree/bug-460 is closer to be finished after I fixed a few issues with the creation of the NXinstrument groups. 

Also note that, [as it is now](https://github.com/cpascual/sardana/commit/97e705149d871020d4b047b55f38125ef383f31b) the recorder is automatically used if the ScanFile has '.hdf5' extension (no need to modify the map in `sardanacustomsettings`). 

TODO : 

- We should decide what should we do regarding the '.h5' extension (either leave the nxs-based implementations as default, or using the h5py based one instead)   
- The "add custom data" feature. Still needs to be checked
- The compression behaviour needs to be checked too
- Help with testing would be appreciated, specially from @sardana-org/integrators

PD: I wrote [this basic nexus summary tool](https://gist.github.com/cpascual/342ca09e86d081ddaae1011cc96bbaf3) to check the generated files

**Comment by cpascual** [comment]
Note that I am not creating a PR yet, because the priority is to create a debian patch based on [version 2.2.2](https://github.com/sardana-org/sardana/tree/2.2.2) in order to save sardana from [getting dropped of debian9](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861900). 
Once that is done, I will adapt the commits to the "develop" branch and submit the PR.

**Comment by reszelaz** [comment]
> We should decide what should we do regarding the '.h5' extension (either leave the nxs-based implementations as default, or using the h5py based one instead)

If I understands well, the objective of this development is to provide a complete equivalent to the nxs-based recorder i.e. the files produced by both recorders should be the same, isn't it?
If this is true, I would make all the h5-like extension pointing to the new implementation. The old recorder could be still available if someone modifies the sardanacustomsetting map or select it explicitelly.

> Help with testing would be appreciated, specially from @sardana-org/integrators

Unfortunatelly I won't be able to help here. I have very limitted time these days.

**Comment by cpascual** [comment]
Hi @reszelaz 
> i.e. the files produced by both recorders should be the same, isn't it

... at least they should be *equivalent*. Definitely, we do not intend binary indentity. But at least, when open with libhdf5 (e.g., with h5py) they should return the same groups, datasets and attributes.

>  I would make all the h5-like extensions pointing to the new implementation

I would also vote for that. Make the new implementation the default one for '.h5' and leave the old one available

**Comment by cpascual** [comment]
Note: I got also confirmation that it works from @guifrecuni

**Comment by cpascual** [comment]
And I tested the  "add custom data" feature using the `ascan_with_addcustomdata` macro from the official examples and it works as expected

**Comment by teresanunez** [comment]
Hi, even if we have another nexus recorder at Desy, I have tested this and Iagree with the implementation. I also agree with your comments about leaving the old implementation as available but using the new one as default.

**Comment by cpascual** [comment]
Compression is now supported and tested (with [this commit](https://github.com/cpascual/sardana/commit/6c8e098e525d595dd249dab0068be3e33264877c)).

Note: the old recorder used LZW compression. But this is not available in h5py. For this recorder I default to 'gzip' [which is the recommended one for compatibility](http://docs.h5py.org/en/latest/high/dataset.html?highlight=create_dataset#lossless-compression-filters).

**Comment by cpascual** [comment]
[Last commit](https://github.com/cpascual/sardana/commit/86c04198a50a69e94b9020a0385b7651fd20e0a4) replaces NXscan_FileRecorder by NXscanH5_FileRecorder as the default recorder for `*.h5` files

With this, we will be creating a patch for debian.

**Comment by cpascual** [comment]
Patch for sardana 2.2.2 uploaded to:  https://github.com/cpascual/sardana/tree/debian-patch-nonxs

It was used to build this debian package: https://mentors.debian.net/package/sardana
