### ISSUE TITLE
"umv" macro keeps displaying position after being interrupted by an exception

### ISSUE THREAD

**Issue by LJBD** [sardana-org/sardana#464]
Hello!

There's an issue with `umv` macro: its displaying mechanism (I suppose it's a thread) is not closed properly when an exception happens during movement. Then, it keeps displaying changes indefinitely. What is more, the problem disappears only when the MacroServer is restarted: a simple restart of a spock session doesn't help.

Steps to reproduce:
I've created a simple controller to test it:
```python
rom sardana.pool.poolcontrollers.DummyMotorController import DummyMotorController
from tango import DevFailed
from time import sleep

class CrashCtrl(DummyMotorController):
    def StartOne(self, axis, pos):
        if pos == 9999:
            sleep(3)
        else:
            super(CrashCtrl, self).StartOne(axis, pos)
```

This way I will get a *TRANSIENT_CallTimeout* error when I try moving this motor to position 9999.

Here's a complete output from spock:
```python
Door_fresh-conda_1 [2]: wm crash_mot01
              crash_mot01
User               
 High                inf 
 Current            100.0
 Low                -inf 
Dial               
 High                inf 
 Current            100.0
 Low                -inf 

Door_fresh-conda_1 [3]: crash_mot01.write_attribute('Position', 150)

Door_fresh-conda_1 [4]: wm crash_mot01
              crash_mot01
User               
 High                inf 
 Current            150.0
 Low                -inf 
Dial               
 High                inf 
 Current            150.0
 Low                -inf 

Door_fresh-conda_1 [5]: umv crash_mot01 100
crash_mot01
  100.0000

Door_fresh-conda_1 [6]: umv crash_mot01 9999
An error occurred while running Macro 'umv([['crash_mot01', '9999.0']]) -> 296382ec-3eeb-11e7-83b7-000c295e4c94':
TRANSIENT CORBA system exception: TRANSIENT_CallTimedout
crash_mot01
  100.0000

Door_fresh-conda_1 [7]: crash_mot01.write_attribute('Position', 150)

crash_mot01
  150.0000
```
As you can see, after the first `write_attribute` I get no output - as it should be. After the second (and any subsequent ones, too), I get output from this unfinished displaying mechanism.
Here's a picture with that output, too:
![umv_output](https://cloud.githubusercontent.com/assets/9516795/26309397/2686eeda-3efd-11e7-8690-ea9be564b71e.jpg)

What is worse, if you restart the spock session and the attribute changes again (so a change event is pushed), the displaying mechanism will overwrite the last line of your input:
```python
Door_fresh-conda_1 [11]: crash_mot01.write_attribute('Position',
                         crash_mot01
  100.0000
```
While the complete input was, of course:
```python
Door_fresh-conda_1 [11]: crash_mot01.write_attribute('Position',
                         100)
```

We've also seen this behaviour for other types of exceptions. Most commonly, some exceptions from IcePAP not being able to move because of its inner alarms.

**Comment by reszelaz** [comment]
#465 should fix it, could you test it and feedback, please.

Some explanations:

> What is more, the problem disappears only when the MacroServer is restarted: a simple restart of a spock session doesn't help.

This is normal. The macros are executed within the MacroServer process. Hence the objects created by macros resides within the MacroServer. Restaring of the spock does not help here.

> What is worse, if you restart the spock session and the attribute changes again (so a change event is pushed), the displaying mechanism will overwrite the last line of your input.

This is also normal. The Motor's position event callback was incidentally left subscribed in the MacroServer process. This callback prints an output block, basically overrides the same line(s) in spock. The MacroServer communicates this requests via the Door's Output attribute. Restarting the spock session subscribes again to this attribute. So the next time you move the motor, after restarting the just the spock, and not the MacroServer, you will still receive the update.

**Comment by LJBD** [comment]
Yes, it works, thank you very much!
