### ISSUE TITLE
Allow measurementGroup as a parameter in 'ct' macro.

### ISSUE THREAD

**Issue by droldan** [sardana-org/sardana#473]
Following the [Issue-471](https://github.com/sardana-org/sardana/issues/471), we want to allow the measurement group as a optional parameter in 'ct' macro to enable acquire in a specific measurement group.
This will help to avoid change the 'ActiveMntGrp' environment variable in each ct measurement and make it more flexible

**Comment by reszelaz** [comment]
Solved with #940.
