### ISSUE TITLE
Avoid import OrderedDict from taurus

### ISSUE THREAD

**Issue by cmft** [sardana-org/sardana#481]
Sardana imports `OrderedDict` module from `taurus.external` and it will be dropped in the next release.
See taurus [#223](https://github.com/taurus-org/taurus/issues/223) 

All occurrences of `from taurus.external.ordereddict import OrderedDict` must be replaced.

e.g.
```
try:
    from collections import OrderedDict
except ImportError:
    # For Python < 2.7
    from ordereddict import OrderedDict
```

**Comment by jkotan** [comment]
Hi,

when I use new sardana with new taurus during start of macroserver I get two errors:

    MainThread     ERROR    2017-07-18 15:05:00,409 ModuleManager: Invalid module msmacromanager
    MainThread     DEBUG    2017-07-18 15:05:00,409 ModuleManager: Details:
    Traceback (most recent call last):
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/sardanamodulemanager.py", line 194, in isValidModule
	m = imp.load_module(fake_name, mfile, pathname, desc)
      File "/usr/lib/python2.7/dist-packages/sardana/macroserver/msmacromanager.py", line 45, in <module>
	from taurus.external.ordereddict import OrderedDict
    ImportError: No module named ordereddict
    MainThread     INFO     2017-07-18 15:05:00,410 ModuleManager: (re)loading module msrecordermanager...
    MainThread     ERROR    2017-07-18 15:05:00,410 ModuleManager: Invalid module msrecordermanager
    MainThread     DEBUG    2017-07-18 15:05:00,410 ModuleManager: Details:
    Traceback (most recent call last):
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.5_alpha-py2.7.egg/sardana/sardanamodulemanager.py", line 194, in isValidModule
	m = imp.load_module(fake_name, mfile, pathname, desc)
      File "/usr/lib/python2.7/dist-packages/sardana/macroserver/msrecordermanager.py", line 38, in <module>
	from taurus.external.ordereddict import OrderedDict
    ImportError: No module named ordereddict
    MainThread     INFO     2017-07-18 15:05:00,410 ModuleManager: (re)loading module msdoor...

Is it harmless?

Bests,
Jan

**Comment by jkotan** [comment]
It looks like ModuleManager found my old installation of sardana (in /usr/lib)  instead of use package from /home/jkotan/testsar/lib/python2.7

**Comment by jkotan** [comment]
Ok, the issue was caused by our default macro paths, i.e. someone added 
     /usr/lib/python2.7/dist-packages/sardana/macroserver
which is not correct.
