### ISSUE TITLE
Unexecuted macro shows results

### ISSUE THREAD

**Issue by cmft** [sardana-org/sardana#502]
The results (returned) data of a macro seems to be not reset between macro executions.
If the second macro could not be executed, spock shows the previous values.

See:

```
Door_cfalcon_1 [5]: %ret2parms
        Result [5]: (1, 2)

Door_cfalcon_1 [6]: ct 1
Error: The macro ct requires the following missing environment to be defined: ['ActiveMntGrp']
        Result [7]: (1, 2)
```

**Comment by mrosanes** [comment]
The incorrect 'result' appears on spock when it is called the self._push_change_event() method from the class _set_attribute_push() from the tango.core.SardanaDevice module.

**Comment by teresanunez** [comment]
I can not reproduce this error. Should this be closed?.

**Comment by reszelaz** [comment]
I also can not reproduce it. Closing.
