### ISSUE TITLE
Exception in PoolMotorTV (with Taurus4)

### ISSUE THREAD

**Issue by cpascual** [sardana-org/sardana#504]
This exception in a TaurusForm was reported by one of our users when testing A GUI with Taurus4 (internal ticket CS-14048 )

```
MainThread ERROR 2017-06-29 11:38:10,047 LogExceptHook: Unhandled exception:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py", line 1491, in updatePosition
self.updateLimits(limit_switches, position=position)
File "/usr/lib/python2.7/dist-packages/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py", line 1438, in updateLimits
self.readWidget(followCompact=True).btn_lim_pos.setStyleSheet(pos_btnstylesheet)
AttributeError: 'TaurusDevButton' object has no attribute 'btn_lim_pos'
MainThread ERROR 2017-06-29 11:38:10,053 LogExceptHook: Unhandled exception:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py", line 1468, in updatePowerOn
self.labelWidget().btn_poweron.setText(btn_text)
AttributeError: 'DefaultLabelWidget' object has no attribute 'btn_poweron'
```

The taurusform reverts to showing the motor as a generic device instead of using the PoolMotorTV widget.

Hint: before anything else, we should check if the problem is caused by old (taurus3) config file being loaded (the same GUI works ok with Taurus3)

**Comment by reszelaz** [comment]
The user checked the GUI in the --fail-proof mode and the problem disappeared. We relate it to the corrupted/incompatible settings file (ini) between Taurus3 and Taurus4. Since Taurus does not guarantee the backwards compatibility of the setting files I close this issue.
