### ISSUE TITLE
Sequencer: Create a way to define macros to be executed after sequence abort (SF#79)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#52]
When a sequence of macros is aborted, there should be a way to define a set of macros to be executed on abort. This feature is needed mainly to leave the system in a safe configuration after the abort.

F.Ex.: In a sequence as:
- Open shutter
- Start temperature ramp
- Take data
- Stop temperature ramp
- Close shutter

If the macro is aborted in any point, one need to define a way to stop the temperature ramp and close the shutter right after the abort.

Reported by: gjover ( http://sf.net/u/gjover )

Original Ticket: [sardana/tickets/79](https://sourceforge.net/p/sardana/tickets/79)

**Comment by reszelaz** [comment]
I wonder if this request still fits into the scope of the sequencer tool. Maybe for these cases, the recommendation should be to define a macro that executes other sub-macros? Also in the [comments about the sequencer](https://hackmd.io/@reszelaz/Bk53UScj_#/13/3) in the user's questionnaire this need was not mentioned. I let myself close this issue. Just re-open or comment if you think differently.
