### ISSUE TITLE
Spock issues at startup on Windows

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#536]
Bug present when launching spock:

![first_error](https://user-images.githubusercontent.com/1327426/29120725-f3f8c928-7d0b-11e7-98b6-19bfff2287f2.jpg)

However, it is possible to work with spock even with this bug present.
It does not seem a critical bug.

**Comment by mrosanes** [comment]
Testing Sardana 2.4.0 on Win7, a part from the logs above. We also get the following error logs when initiating spock:

<pre>
C:\Users\vagrant>spock --profile=demo2
MainThread     INFO     2018-03-05 07:16:45,638 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2018-03-05 07:16:45,802 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from C:\Python27\lib\site-packages\taurus\qt\qt
i\icon\)
Spock 2.4.0 -- An interactive laboratory application.

help      -> Spock's help system.
object?   -> Details about 'object'. ?object also works, ?? prints more.

IPython profile: demo2

Connected to Door_demo2_1
[TerminalIPythonApp] WARNING | Eventloop or matplotlib integration failed. Is matplotlib installed?
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
C:\Python27\lib\site-packages\IPython\core\shellapp.pyc in <lambda>(key)
    198         shell = self.shell
    199         if self.pylab:
--> 200             enable = lambda key: shell.enable_pylab(key, import_all=self.pylab_import_all)
    201             key = self.pylab
    202         elif self.matplotlib:

C:\Python27\lib\site-packages\IPython\core\interactiveshell.pyc in enable_pylab(self, gui, import_all, welcome_message)
   2987         from IPython.core.pylabtools import import_pylab
   2988
-> 2989         gui, backend = self.enable_matplotlib(gui)
   2990
   2991         # We want to prevent the loading of pylab to pollute the user's

C:\Python27\lib\site-packages\IPython\core\interactiveshell.pyc in enable_matplotlib(self, gui)
   2948                 gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
   2949
-> 2950         pt.activate_matplotlib(backend)
   2951         pt.configure_inline_support(self, backend)
   2952

C:\Python27\lib\site-packages\IPython\core\pylabtools.pyc in activate_matplotlib(backend)
    306     matplotlib.rcParams['backend'] = backend
    307
--> 308     import matplotlib.pyplot
    309     matplotlib.pyplot.switch_backend(backend)
    310

C:\Python27\lib\site-packages\matplotlib\pyplot.py in <module>()
    107
    108 from matplotlib.backends import pylab_setup
--> 109 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    110
    111

C:\Python27\lib\site-packages\matplotlib\backends\__init__.pyc in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33
     34     # Things we pull in from all backends

C:\Python27\lib\site-packages\matplotlib\backends\backend_qt5agg.py in <module>()
     16
     17 from .backend_agg import FigureCanvasAgg
---> 18 from .backend_qt5 import QtCore
     19 from .backend_qt5 import QtGui
     20 from .backend_qt5 import FigureManagerQT

C:\Python27\lib\site-packages\matplotlib\backends\backend_qt5.py in <module>()
     29     figureoptions = None
     30
---> 31 from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
     32 from matplotlib.backends.qt_editor.formsubplottool import UiSubplotTool
     33

C:\Python27\lib\site-packages\matplotlib\backends\qt_compat.py in <module>()
    109
    110     else:  # PyQt5 API
--> 111         from PyQt5 import QtCore, QtGui, QtWidgets
    112         _getSaveFileName = QtWidgets.QFileDialog.getSaveFileName
    113

C:\Python27\lib\site-packages\qtconsole\qt_loaders.pyc in load_module(self, fullname)
     61     Importing %s disabled by QtConsole, which has
     62     already imported an incompatible Qt Binding: %s
---> 63     """ % (fullname, loaded_api()))
     64
     65 ID = ImportDenier()

</pre>


However, it is possible to work with spock even with this bug present.
It does not seem a critical bug.

**Comment by dschick** [comment]
I can confirm the bug with the freeze_support() and that it seems not to be critical.
I run the test on Win10 with 
- tango 9.2.1
- taurus 4.3.1
- Sardana 2.4.0

Best 

Daniel

**Comment by mrosanes** [comment]
Bugs also present on Jan19 release: Sardana v2.7.0

**Comment by reszelaz** [comment]
While testing Jul20 release (3.0.2) the matplotlib errors disappeared.
Using:
- Python 3.7.8
- IPython 7.17.0
- matplotlib 3.3.1
The freeze_support() error is still present.
The current output (after previous creation of the profile) is as following:

```
(py3qt5) C:\Users\IEUser>spock --profile=demo1
MainThread     INFO     2020-08-26 03:36:34,995 TaurusRootLogger: Using PyQt5 (v5.12.3 with Qt 5.12.5 and Python 3.7.8)
c:\miniconda\envs\py3qt5\lib\site-packages\sardana\spock\ipython_01_00\genutils.py:1348: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  from IPython.utils.traitlets import Unicode
c:\miniconda\envs\py3qt5\lib\site-packages\IPython\qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated since IPython 4.0. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
MainThread     INFO     2020-08-26 03:36:35,261 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from c:\miniconda\envs\py3qt5\lib\site-packages\taurus\qt\qtgui\icon\)
MainThread     INFO     2020-08-26 03:36:35,261 TaurusRootLogger: Plugin "taurus_pyqtgraph" lazy-loaded as "taurus.qt.qtgui.tpg"
[TerminalIPythonApp] WARNING | Config option `deep_reload` not recognized by `TerminalInteractiveShell`.
Spock 3.0.2 -- An interactive laboratory application.

help      -> Spock's help system.
object?   -> Details about 'object'. ?object also works, ?? prints more.

IPython profile: demo1

Connected to Door_demo1_1
MainThread     INFO     2020-08-26 03:36:37,870 TaurusRootLogger: Using PyQt5 (v5.12.3 with Qt 5.12.5 and Python 3.7.8)
MainThread     INFO     2020-08-26 03:36:38,120 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from c:\miniconda\envs\py3qt5\lib\site-packages\taurus\qt\qtgui\icon\)
MainThread     INFO     2020-08-26 03:36:38,120 TaurusRootLogger: Plugin "taurus_pyqtgraph" lazy-loaded as "taurus.qt.qtgui.tpg"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\miniconda\envs\py3qt5\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "c:\miniconda\envs\py3qt5\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\util\singleton.py", line 81, in __new__
    cls._the_instance.init(*p, **k)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\sardana\spock\inputhandler.py", line 118, in init
    proc.start()
  File "c:\miniconda\envs\py3qt5\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\miniconda\envs\py3qt5\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\miniconda\envs\py3qt5\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\miniconda\envs\py3qt5\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\miniconda\envs\py3qt5\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "c:\miniconda\envs\py3qt5\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Door_demo1_1 [1]: 
```

**Comment by reszelaz** [comment]
We found it fixed during the Jan21 release tests. Using the following packages:

```
C:\Users\IEUser>pip freeze
atomicwrites==1.4.0
attrs==20.3.0
backcall==0.2.0
click==7.1.2
colorama==0.4.4
cycler==0.10.0
decorator==5.0.7
fisx==1.2.0
future==0.18.2
guidata==1.7.9
guiqwt==3.0.6
h5py==3.2.1
iniconfig==1.1.1
ipykernel==5.5.3
ipython==7.22.0
ipython-genutils==0.2.0
itango==0.1.8
jedi==0.18.0
jupyter-client==6.1.12
jupyter-core==4.7.1
kiwisolver==1.3.1
lxml==4.6.3
matplotlib==3.4.1
numpy==1.20.2
packaging==20.9
parso==0.8.2
pickleshare==0.7.5
Pillow==8.2.0
Pint==0.17
pluggy==0.13.1
ply==3.11
prompt-toolkit==3.0.18
py==1.10.0
Pygments==2.8.1
pymca==5.6.5
PyMca5==5.6.5
PyOpenGL==3.1.5
pyparsing==2.4.7
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.8.1
pyqtgraph==0.12.1
pytango==9.3.3
pytest==6.2.3
python-dateutil==2.8.1
PythonQwt==0.9.0
pywin32==300
pyzmq==22.0.3
qtconsole==5.0.3
QtPy==1.9.0
sardana @ https://ci.appveyor.com/api/buildjobs/ihe5ontu9a569y5y/artifacts/dist%2Fsardana-3.1.0.tar.gz
scipy==1.6.2
six==1.15.0
taurus==4.7.1
taurus-pyqtgraph==0.5.1
tgconf-MyGui @ file:///C:/Users/IEUser/mygui
toml==0.10.2
tornado==6.1
traitlets==5.0.5
wcwidth==0.2.5
```
