### ISSUE TITLE
Deprecation warnings due to Taurus4 (testing in win7 - Sardana 2.3.0)

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#537]
Deprecation warnings due to Taurus4 (testing in win7 - Sardana 2.3.0):

![second_error](https://user-images.githubusercontent.com/1327426/29120868-805c3580-7d0c-11e7-8d3e-4864ef2c6ebc.jpg)

**Comment by LJBD** [comment]
I do think that all platforms are affected my this.

**Comment by mrosanes** [comment]
This has been solved on pull request https://github.com/sardana-org/sardana/pull/550.
The deprecation warnings are correct, and the messages can be hidden using the mechanism of pull request 550.
