### ISSUE TITLE
Max recursion error visible in spock (testing Sardana 2.3.0 in Win7)

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#538]
Max recursion error visible in spock (testing Sardana 2.3.0 in Win7)

![third_error](https://user-images.githubusercontent.com/1327426/29120928-c1485434-7d0c-11e7-9ef7-99d293069db5.jpeg)

It does not seem a critical error, as it is possible to work in spock after having seen this error.

**Comment by LJBD** [comment]
AFAIK this was fixed in the newest Taurus version.

**Comment by mrosanes** [comment]
It is not exactly the error @LJBD is pointing out, because the problem found in 538 refers to tangodevice.py. 

However, I am not able to reproduce the error anymore. We close the ticket for the moment.
