### ISSUE TITLE
ElementList attribute from Door presents an error

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#556]
Trying to read the Tango attribute 'ElementList' from a 'Door' device, returns an error:

```
on sardana.tango.macroserver.Door in read_ElementList
element_list = self.macro_server_device.getElementList()
'MacroServer' object has no attribute 'getElementList'
```

The method getElementList() does not exist on the MacroServer Tango Device Server class.

**Comment by reszelaz** [comment]
ElementList attribute was removed in #653
