### ISSUE TITLE
Stop the FunctionGenerator when the motor ends the movement.

### ISSUE THREAD

**Issue by droldan** [sardana-org/sardana#583]
When the FunctionGenerator is configured as a Synch Domain Position there are problems when the motor does not reach the final position , the FunctionGenerator does not finish waiting for the last positions event and the scanning does not end.

This happens in ascanct 60 62 and the motor does not reach 62, ending the movement in 61.9995.

The idea is to also check the motor status, if the motor has finished the movement then the FunctionGenerator needs to be stopped

**Comment by reszelaz** [comment]
Closing this issue - see discussion in PR #584.
