### ISSUE TITLE
Syntax error in ALBA_BL22_CLAESS/Bl22DcmTurboPmacPositionTGCtrl.py controller

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#636]
Hi,

In Bl22DcmTurboPmacPositionTGCtrl.py controller there is a syntax error, i.e:

    diff --git a/python/triggergate/ALBA_BL22_CLAESS/Bl22DcmTurboPmacPositionTGCtrl.py b/python/triggergate/ALBA_BL22_CLAESS/Bl22DcmTurboPmacPositionTGCtrl.py
    index 832c422..f890aef 100755
    --- a/python/triggergate/ALBA_BL22_CLAESS/Bl22DcmTurboPmacPositionTGCtrl.py
    +++ b/python/triggergate/ALBA_BL22_CLAESS/Bl22DcmTurboPmacPositionTGCtrl.py
    @@ -1,9 +1,9 @@
     import PyTango
     
    -from sardana import State,
    +from sardana import State
     from sardana.pool.pooldefs import SynchDomain, SynchParam
     from sardana.pool.controller import TriggerGateController
    -from sardana.pool.controller import Type, Description,
    +from sardana.pool.controller import Type, Description
 
     from bl22dcmlib import energies4encoders
 
Bests,
Jan

**Comment by reszelaz** [comment]
Thanks for the report! I ping @rhomspuron who developed this controller so he is aware of this.

**Comment by rhomspuron** [comment]
Hi Jan, 

Thanks for the report! I fixed the error.

Cheers, 
Roberto

**Comment by reszelaz** [comment]
Thanks to both! I'm closing this issue...
