### ISSUE TITLE
Problem loading macros without arguments from a txt file

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana#641]
There is a problem loading macros that do not need arguments and are put in the text file without them. For example, a sequence with the macro lsm, if I put in the the text file to load:

mv mot01 10
lsm

the sequence is loaded but when I try to run it I get the error:

'nothing to repeat'

The right way to put it in the text file is:

lsm .*

but I don't think that this is easy to see for the user.
I would say that if the macro is loaded as:

lsm

it should run, and if it does not run an error should appear when loading ... but
indicating something about putting

lsm .*

in the text file, if not it could be difficult to figure out.

**Comment by mrosanes** [comment]
Just for completion: this issue is related with the 'sequencer' gui.

**Comment by reszelaz** [comment]
This is no more reproducible with the latest develop branch.
