### ISSUE TITLE
Allow string ParamRepeats on load Sequencer plain text. 

### ISSUE THREAD

**Issue by droldan** [sardana-org/sardana#645]
There are problems on try to load a plain text sequence that contains strings ParamRepeat on Sequencer.

**Comment by reszelaz** [comment]
@droldan please take a look on how was it solved in Spock. The parameter parser https://github.com/sardana-org/sardana/blob/01b154244c97e09b316be39fbf2e7a15d149e4f3/src/sardana/spock/parser.py#L61 together with https://github.com/sardana-org/sardana/blob/01b154244c97e09b316be39fbf2e7a15d149e4f3/src/sardana/taurus/core/tango/sardana/macro.py#L1188 should be very close to what you need.

**Comment by reszelaz** [comment]
Solved in #781
