### ISSUE TITLE
Add information to macrobutton tooltip

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#656]
As the result of the discussion in #322 it would would be nice to add more information to the macrobutton tooltip. The tooltip should say: "Run <macro_name> <macro_parameters>" when the door is in On or Alarm state and "Abort <macro_name> <macro_parameters>" when the door is in Running or Standby state.

**Comment by cpascual** [comment]
I would not make the tooltip dynamic. Instead I would give all the info all the time. Something like:

```
Run  <macro_name> <macro_parameters>
(uncheck to abort)
```

**Comment by reszelaz** [comment]
It is fine with me. ...but in #322 we already agreed to put a text on the button "Run/Abort <macro_name> <macro_buttons>". So for me the tooltip does not add more information here - it is already present in the button's text. If we change the tooltip dynamically, depending on the state of the door, the tooltip information is more precisse - it adds information.

**Comment by emiliojmorales** [comment]
First proposal: create a method to update tooltip depending on device state ready for review.
