### ISSUE TITLE
Add information about continuous scan parameters in ascanct macros 

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#692]
This request comes from Francois Fault from ALBA.

It would be nice to give a message to the user about some of the scan parameters e.g. motor velocity, 
acceleration, deceleration, maybe the actual motion range (pre-start and post-end positions). And at the end of the scan about the reestablished parameters e.g. motor velocity, acceleration and deceleration.

**Comment by cpascual** [comment]
I assume that the implementation just involves deciding which info and printing it to the the macro output... if it instead involves defining a new API for accessing this info, I would change the size to M or L

**Comment by reszelaz** [comment]
This does not involve any new API.

**Comment by HEnquist** [comment]
I'm increasing the impact of this to medium. We are using the continuous scans more and more, and there has been many occasions lately where this would really have helped.

**Comment by cpascual** [comment]
>I'm increasing the impact of this to medium.

Agreed!
