### ISSUE TITLE
spock commands not visable with bright background

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#706]
Hi,

I've just tested spock with taurus 4.3 and sardana 2.3.3 an I noticed that for themes with a  bright background terminal I do not see command I type. Probably it can be change somewhere but by default I assume that command in spock should be visible in all themes. i.e. take from the system.

Best regards,
Jan

**Comment by jkotan** [comment]
I see it on hasp029rack or my stretch VM which is standard stretch installation with gnome classic (independent of  hasp029rack).

**Comment by jkotan** [comment]
Hi,

I looks like it is an issue with `colors=linux` on ipython (5?) https://github.com/ipython/ipython/pull/9655

If I type `%colors lightbg` in `spock` my commands start to be visible. If I type `%colors linux` command colors are again not visible. 
Shall we switch default from `linux` to `lightbg`?

Bests,
Jan

**Comment by teresanunez** [comment]
All the other possibilities work: Neutral, NoColors or LightBG

**Comment by jkotan** [comment]
I think the default in jessie is `Neutral`. It looks like it was switched to `Linux`.

**Comment by cmft** [comment]
Hi @jkotan and @teresanunez ,
Many thanks to debug it. spock uses Linux as default colors. I agree to change it for ipython v5 but with which command do you see the problems?

**Comment by teresanunez** [comment]
Hi @cpascual, typing any macro in spock, we can not see what we type.

**Comment by jkotan** [comment]
It is like at

https://cloud.githubusercontent.com/assets/335567/16320907/1ec4a034-394f-11e6-9a37-184614adbb67.gif

line 4

**Comment by cmft** [comment]
Hi @jkotan and @teresanunez 
The #712 PR should fix this problem. Can you test it?

**Comment by jkotan** [comment]
Thanks! For me it works.

**Comment by teresanunez** [comment]
For me also, many thanks.
