### ISSUE TITLE
Event channel is not responding anymore, maybe the server or event system is down

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#713]
Hi,

I've just wanted to test release taurus/sardana version on my stretch box with pytango 9.2.2. With
sardana 2.2.2-3 and taurus 4.0.3 I do not get any errors (i.e. I can ran sar_demo) but when I try to 
do it with sardana 2.4.0 release and taurus 4.3.0 release it does not work.
Firstly, I get after starting MacroServer:

    MainThread     DEBUG    2018-02-28 22:38:37,893 MS_stretch_1: Creating pool Pool_stretch_1
    MainThread     WARNING  2018-02-28 22:38:37,987 TaurusRootLogger: /home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/taurus/core/tango/sardana/pool.py:1954: DeprecationWarning: _get_value is deprecated since 4.0. Use .rvalue instead
      elems = CodecFactory().decode(evt_value.value, ensure_ascii=True)

    MainThread     DEBUG    2018-02-28 22:38:38,030 Door/stretch/1: -> init_device
    MainThread     DEBUG    2018-02-28 22:38:38,033 Door/stretch/1: <- init_device
    MainThread     INFO     2018-02-28 22:38:38,037 TaurusRootLogger: Ready to accept request in 0:00:01.298683
    Dummy-1        WARNING  2018-02-28 22:38:49,933 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: Received elements error event API_EventTimeout: Event channel is not responding anymore, maybe the server or event system is down
    Dummy-1        DEBUG    2018-02-28 22:38:49,933 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: DevFailed[
    DevError[
	desc = Event channel is not responding anymore, maybe the server or event system is down
      origin = EventConsumer::KeepAliveThread()
      reason = API_EventTimeout
    severity = ERR]
    ]
    Dummy-1        INFO     2018-02-28 22:38:49,935 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1.Elements: Activating polling. Reason: API_EventTimeout
    Dummy-1        DEBUG    2018-02-28 22:38:49,961 TaurusPollingTimer[3000].Timer on _pollAttributes: Timer::stop()
    Dummy-1        WARNING  2018-02-28 22:38:59,982 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: Received elements error event API_EventTimeout: Event channel is not responding anymore, maybe the server or event system is down
    Dummy-1        DEBUG    2018-02-28 22:38:59,982 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: DevFailed[
    DevError[
	desc = Event channel is not responding anymore, maybe the server or event system is down
      origin = EventConsumer::KeepAliveThread()
      reason = API_EventTimeout
    severity = ERR]
    ]
    Dummy-1        INFO     2018-02-28 22:38:59,984 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1.Elements: Activating polling. Reason: API_EventTimeout
    Dummy-1        DEBUG    2018-02-28 22:39:00,003 TaurusPollingTimer[3000].Timer on _pollAttributes: Timer::stop()
    Dummy-1        WARNING  2018-02-28 22:39:10,025 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: Received elements error event API_EventTimeout: Event channel is not responding anymore, maybe the server or event system is down
    Dummy-1        DEBUG    2018-02-28 22:39:10,026 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: DevFailed[
    DevError[
	desc = Event channel is not responding anymore, maybe the server or event system is down
      origin = EventConsumer::KeepAliveThread()
      reason = API_EventTimeout
    severity = ERR]

which where absent in the first case and then after `sar_demo`  in spock I get

    Spock 2.4.0 -- An interactive laboratory application.

    help      -> Spock's help system.
    object?   -> Details about 'object'. ?object also works, ?? prints more.

    IPython profile: spockdoor

    Connected to Door_stretch_1

    Door_stretch_1 [1]: sar_demo
    Dummy-23       INFO     2018-02-28 22:52:21,643 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Debug: Activating polling. Reason: API_EventTimeout
    TimerLoop 1    ERROR    2018-02-28 22:52:21,646 TaurusPollingTimer[3000]: poll_reply error
    Dummy-23       INFO     2018-02-28 22:52:21,647 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Error: Activating polling. Reason: API_EventTimeout
    An error occurred while running Macro 'sar_demo() -> a30df004-1cd1-11e8-b34c-74da382e02d6':
    Either of: Controller with name ctctrl05 does not exist or Controller with name ctctrl05 does not exist made it impossible to decode parameters
    TimerLoop 1    ERROR    2018-02-28 22:52:21,649 TaurusPollingTimer[3000]: poll_reply error
    Dummy-23       INFO     2018-02-28 22:52:21,651 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Info: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:21,654 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Input: Activating polling. Reason: API_EventTimeout
    TimerLoop 1    ERROR    2018-02-28 22:52:21,659 TaurusPollingTimer[3000]: poll_reply error
    push_event generated the following python exception:
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    /usr/lib/python2.7/dist-packages/tango/green.pyc in greener(*args, **kwargs)
	195     @wraps(fn)
	196     def greener(*args, **kwargs):
    --> 197         return executor.submit(fn, *args, **kwargs)
	198 
	199     return greener

    /usr/lib/python2.7/dist-packages/tango/green.pyc in submit(self, fn, *args, **kwargs)
	 78         """Submit an operation"""
	 79         if not self.asynchronous:
    ---> 80             return fn(*args, **kwargs)
	 81         raise NotImplementedError
	 82 

    /home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/util/event.pyc in __call__(self, *args, **kwargs)
	120             func = self.func_ref()
	121             if func is not None:
    --> 122                 return func(obj, *args, **kwargs)
	123 
	124 

    /home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/tango/tangoattribute.pyc in push_event(self, event)
	788                                listeners=listeners)
	789             else:
    --> 790                 self.fireEvent(etype, evalue, listeners=listeners)
	791 
	792     def _pushAttrEvent(self, event):

    /home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/taurusmodel.pyc in fireEvent(self, event_type, event_value, listeners)
	295                 l.eventReceived(self, event_type, event_value)
	296             elif operator.isCallable(l):
    --> 297                 l(self, event_type, event_value)
	298 
	299     def isWritable(self):

    /home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/taurus/core/tango/sardana/macroserver.pyc in inputReceived(self, s, t, v)
	609         if v is None or self._running_macros is None:
	610             return
    --> 611         input_data = CodecFactory().decode(('json', v.value))
	612         self.processInput(input_data)
	613 

    /home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/util/codecs.pyc in decode(self, data, *args, **kwargs)
	923     def decode(self, data, *args, **kwargs):
	924         while len(data[0]):
    --> 925             data = self.getCodec(data[0]).decode(data, *args, **kwargs)
	926         return data[1]
	927 

    /home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/util/codecs.pyc in decode(self, data, *args, **kwargs)
	342             data = data[0], str(data[1])
	343 
    --> 344         data = json.loads(data[1])
	345         if ensure_ascii:
	346             data = self._transform_ascii(data)

    /usr/lib/python2.7/json/__init__.pyc in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
	337             parse_int is None and parse_float is None and
	338             parse_constant is None and object_pairs_hook is None and not kw):
    --> 339         return _default_decoder.decode(s)
	340     if cls is None:
	341         cls = JSONDecoder

    /usr/lib/python2.7/json/decoder.pyc in decode(self, s, _w)
	362 
	363         """
    --> 364         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	365         end = _w(s, end).end()
	366         if end != len(s):

    /usr/lib/python2.7/json/decoder.pyc in raw_decode(self, s, idx)
	380             obj, end = self.scan_once(s, idx)
	381         except StopIteration:
    --> 382             raise ValueError("No JSON object could be decoded")
	383         return obj, end

    ValueError: No JSON object could be decoded
    Dummy-23       INFO     2018-02-28 22:52:21,724 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.MacroStatus: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:21,727 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Output: Activating polling. Reason: API_EventTimeout
    Creating motor controller motctrl08 ...
    Created motctrl08
    Creating motor mot17 ...
    Created None
    Creating motor mot18 ...
    Created None
    Creating motor mot19 ...
    Created None
    Creating motor mot20 ...
    Created None
    Creating counter controller ctctrl05 ...
    Created None
    Creating counter channel ct17 ...
    Dummy-23       INFO     2018-02-28 22:52:21,731 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.RecordData: Activating polling. Reason: API_EventTimeout
    TimerLoop 1    ERROR    2018-02-28 22:52:21,733 TaurusPollingTimer[3000]: poll_reply error
    Dummy-23       INFO     2018-02-28 22:52:21,739 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Result: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:21,744 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.state: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:21,756 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Warning: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:21,780 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.MS_stretch_1.Elements: Activating polling. Reason: API_EventTimeout
    TimerLoop 1    ERROR    2018-02-28 22:52:21,785 TaurusPollingTimer[3000]: poll_reply error
    Dummy-23       INFO     2018-02-28 22:52:21,865 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.MS_stretch_1.Environment: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:31,878 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Debug: Activating polling. Reason: API_EventTimeout
    TimerLoop 1    ERROR    2018-02-28 22:52:31,880 TaurusPollingTimer[3000]: poll_reply error
    Dummy-23       INFO     2018-02-28 22:52:31,881 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Error: Activating polling. Reason: API_EventTimeout
    An error occurred while running Macro 'sar_demo() -> a30df004-1cd1-11e8-b34c-74da382e02d6':
    Either of: Controller with name ctctrl05 does not exist or Controller with name ctctrl05 does not exist made it impossible to decode parameters
    Dummy-23       INFO     2018-02-28 22:52:31,885 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Info: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:31,888 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Input: Activating polling. Reason: API_EventTimeout
    TimerLoop 1    ERROR    2018-02-28 22:52:31,889 TaurusPollingTimer[3000]: poll_reply error
    push_event generated the following python exception:
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    /usr/lib/python2.7/dist-packages/tango/green.pyc in greener(*args, **kwargs)
	195     @wraps(fn)
	196     def greener(*args, **kwargs):
    --> 197         return executor.submit(fn, *args, **kwargs)
	198 
	199     return greener

    /usr/lib/python2.7/dist-packages/tango/green.pyc in submit(self, fn, *args, **kwargs)
	 78         """Submit an operation"""
	 79         if not self.asynchronous:
    ---> 80             return fn(*args, **kwargs)
	 81         raise NotImplementedError
	 82 

    /home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/util/event.pyc in __call__(self, *args, **kwargs)
	120             func = self.func_ref()
	121             if func is not None:
    --> 122                 return func(obj, *args, **kwargs)
	123 
	124 

    /home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/tango/tangoattribute.pyc in push_event(self, event)
	788                                listeners=listeners)
	789             else:
    --> 790                 self.fireEvent(etype, evalue, listeners=listeners)
	791 
	792     def _pushAttrEvent(self, event):

    /home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/taurusmodel.pyc in fireEvent(self, event_type, event_value, listeners)
	295                 l.eventReceived(self, event_type, event_value)
	296             elif operator.isCallable(l):
    --> 297                 l(self, event_type, event_value)
	298 
	299     def isWritable(self):

    /home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/taurus/core/tango/sardana/macroserver.pyc in inputReceived(self, s, t, v)
	609         if v is None or self._running_macros is None:
	610             return
    --> 611         input_data = CodecFactory().decode(('json', v.value))
	612         self.processInput(input_data)
	613 

    /home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/util/codecs.pyc in decode(self, data, *args, **kwargs)
	923     def decode(self, data, *args, **kwargs):
	924         while len(data[0]):
    --> 925             data = self.getCodec(data[0]).decode(data, *args, **kwargs)
	926         return data[1]
	927 

    /home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/util/codecs.pyc in decode(self, data, *args, **kwargs)
	342             data = data[0], str(data[1])
	343 
    --> 344         data = json.loads(data[1])
	345         if ensure_ascii:
	346             data = self._transform_ascii(data)

    /usr/lib/python2.7/json/__init__.pyc in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
	337             parse_int is None and parse_float is None and
	338             parse_constant is None and object_pairs_hook is None and not kw):
    --> 339         return _default_decoder.decode(s)
	340     if cls is None:
	341         cls = JSONDecoder

    /usr/lib/python2.7/json/decoder.pyc in decode(self, s, _w)
	362 
	363         """
    --> 364         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	365         end = _w(s, end).end()
	366         if end != len(s):

    /usr/lib/python2.7/json/decoder.pyc in raw_decode(self, s, idx)
	380             obj, end = self.scan_once(s, idx)
	381         except StopIteration:
    --> 382             raise ValueError("No JSON object could be decoded")
	383         return obj, end

    ValueError: No JSON object could be decoded
    Dummy-23       INFO     2018-02-28 22:52:31,942 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.MacroStatus: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:31,945 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Output: Activating polling. Reason: API_EventTimeout
    Creating motor controller motctrl08 ...
    Created motctrl08
    Creating motor mot17 ...
    Created None
    Creating motor mot18 ...
    Created None
    Creating motor mot19 ...
    Created None
    Creating motor mot20 ...
    Created None
    Creating counter controller ctctrl05 ...
    Created None
    Creating counter channel ct17 ...
    Dummy-23       INFO     2018-02-28 22:52:31,949 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.RecordData: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:32,106 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Result: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:32,111 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.state: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:32,114 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Warning: Activating polling. Reason: API_EventTimeout
    TimerLoop 1    ERROR    2018-02-28 22:52:32,116 TaurusPollingTimer[3000]: poll_reply error
    Dummy-23       INFO     2018-02-28 22:52:32,136 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.MS_stretch_1.Elements: Activating polling. Reason: API_EventTimeout
    TimerLoop 1    ERROR    2018-02-28 22:52:32,141 TaurusPollingTimer[3000]: poll_reply error
    Dummy-23       INFO     2018-02-28 22:52:32,219 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.MS_stretch_1.Environment: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:42,230 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Debug: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:42,233 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Error: Activating polling. Reason: API_EventTimeout
    An error occurred while running Macro 'sar_demo() -> a30df004-1cd1-11e8-b34c-74da382e02d6':
    Either of: Controller with name ctctrl05 does not exist or Controller with name ctctrl05 does not exist made it impossible to decode parameters
    Dummy-23       INFO     2018-02-28 22:52:42,236 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Info: Activating polling. Reason: API_EventTimeout
    Dummy-23       INFO     2018-02-28 22:52:42,239 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Door_stretch_1.Input: Activating polling. Reason: API_EventTimeout
    TaurusTP.W003  ERROR    2018-02-28 22:52:42,241 TaurusManager.TaurusTP.TaurusTP.W003: Uncaught exception running job 'poll' called from thread Dummy-23:
      File "/usr/lib/python2.7/dist-packages/tango/green.py", line 197, in greener
	return executor.submit(fn, *args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/tango/green.py", line 80, in submit
	return fn(*args, **kwargs)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/util/event.py", line 122, in __call__
	return func(obj, *args, **kwargs)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/tango/tangoattribute.py", line 778, in push_event
	etype, evalue = self._pushAttrEvent(event)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/tango/tangoattribute.py", line 831, in _pushAttrEvent
	self._activatePolling()
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/taurusattribute.py", line 231, in _activatePolling
	self.factory().addAttributeToPolling(self, self.getPollingPeriod())
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/taurusfactory.py", line 347, in addAttributeToPolling
	tmr.addAttribute(attribute, self.isPollingEnabled())
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/tauruspollingtimer.py", line 111, in addAttribute
	taurus.Manager().addJob(attribute.poll, None)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/taurusmanager.py", line 129, in addJob
	self._thread_pool.add(job, callback, *args, **kw)
    Traceback (most recent call last):
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/util/threadpool.py", line 135, in run
	cmd(*args, **kw)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/tango/tangoattribute.py", line 487, in poll
	self.fireEvent(TaurusEventType.Periodic, self.__attr_value)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/taurusmodel.py", line 297, in fireEvent
	l(self, event_type, event_value)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/taurus/core/tango/sardana/macroserver.py", line 611, in inputReceived
	input_data = CodecFactory().decode(('json', v.value))
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/util/codecs.py", line 925, in decode
	data = self.getCodec(data[0]).decode(data, *args, **kwargs)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/taurus-4.3.0-py2.7.egg/taurus/core/util/codecs.py", line 344, in decode
	data = json.loads(data[1])
      File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
	return _default_decoder.decode(s)
      File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
	obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
	raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded
    push_event generated the following python exception:
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    /usr/lib/python2.7/dist-packages/tango/green.pyc in greener(*args, **kwargs)
	195     @wraps(fn)
	196     def greener(*args, **kwargs):
    --> 197         return executor.submit(fn, *args, **kwargs)
	198 
	199     return greener

    /usr/lib/python2.7/dist-packages/tango/green.pyc in submit(self, fn, *args, **kwargs)
	 78         """Submit an operation"""
	 79         if not self.asynchronous:

when in MacroServer I get

    Dummy-1        WARNING  2018-02-28 22:58:11,221 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: Received elements error event API_EventTimeout: Event channel is not responding anymore, maybe the server or event system is down
    Dummy-1        DEBUG    2018-02-28 22:58:11,221 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: DevFailed[
    DevError[
	desc = Event channel is not responding anymore, maybe the server or event system is down
      origin = EventConsumer::KeepAliveThread()
      reason = API_EventTimeout
    severity = ERR]
    ]
    Dummy-1        INFO     2018-02-28 22:58:11,223 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1.Elements: Activating polling. Reason: API_EventTimeout
    Dummy-1        DEBUG    2018-02-28 22:58:11,251 TaurusPollingTimer[3000].Timer on _pollAttributes: Timer::stop()
    SardanaTP.W002 DEBUG    2018-02-28 22:58:12,363 Door/stretch/1.MacroExecutor: [START] runMacro Macro 'sar_demo() -> 78682904-1cd2-11e8-b60a-74da382e02d6'
    SardanaTP.W002 OUTPUT   2018-02-28 22:58:12,467 Door/stretch/1.Macro[sar_demo]: Creating motor controller motctrl09 ...
    SardanaTP.W002 DEBUG    2018-02-28 22:58:12,467 Door/stretch/1.Macro[sar_demo]: Executing macro: defctrl
    SardanaTP.W002 DEBUG    2018-02-28 22:58:12,468 Door/stretch/1.MacroExecutor: [START] runMacro Macro 'defctrl(DummyMotorController, motctrl09, []) -> None'
    SardanaTP.W002 INFO     2018-02-28 22:58:13,026 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: Timed out waiting for 'motctrl09' in container
    SardanaTP.W002 OUTPUT   2018-02-28 22:58:13,026 Door/stretch/1.Macro[sar_demo].Macro[defctrl]: Created None
    SardanaTP.W002 DEBUG    2018-02-28 22:58:13,027 Door/stretch/1.MacroExecutor: [ END ] runMacro Macro 'defctrl(DummyMotorController, motctrl09, []) -> None'
    SardanaTP.W002 OUTPUT   2018-02-28 22:58:13,028 Door/stretch/1.Macro[sar_demo]: Creating motor mot21 ...
    SardanaTP.W002 DEBUG    2018-02-28 22:58:13,028 Door/stretch/1.Macro[sar_demo]: Executing macro: defelem
    SardanaTP.W002 DEBUG    2018-02-28 22:58:13,029 MS_stretch_1.MacroManager: Trying flat parameter decoder due to: Controller with name motctrl09 does not exist
    SardanaTP.W002 DEBUG    2018-02-28 22:58:13,030 Door/stretch/1.MacroExecutor: Sending exception event
    SardanaTP.W002 DEBUG    2018-02-28 22:58:13,030 Door/stretch/1.MacroExecutor: [ENDEX] (WrongParam) runMacro sar_demo
    SardanaTP.W002 DEBUG    2018-02-28 22:58:13,031 Door/stretch/1: Traceback (most recent call last):
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/macroserver/msmacromanager.py", line 1462, in runMacro
	for step in macro_obj.exec_():
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/macroserver/macro.py", line 2309, in exec_
	res = self.run(*self._in_pars)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/macroserver/macro.py", line 2481, in run
	return self._function(self, *args)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/macroserver/macros/demo.py", line 138, in sar_demo
	self.defelem(motor_name, mot_ctrl_name, axis)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/macroserver/macro.py", line 2451, in f
	return self.execMacro(*eargs, **kwargs)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/macroserver/macro.py", line 352, in new_fn
	ret = fn(*args, **kwargs)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/macroserver/macro.py", line 1325, in execMacro
	macro_obj, _ = self.prepareMacro(*args, **kwargs)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/macroserver/macro.py", line 352, in new_fn
	ret = fn(*args, **kwargs)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/macroserver/macro.py", line 1220, in prepareMacro
	return self.executor.prepareMacro(args, init_opts, kwargs)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/macroserver/msmacromanager.py", line 1241, in prepareMacro
	meta_macro, _, macro_params = self._decodeMacroParameters(pars)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/macroserver/msmacromanager.py", line 1090, in _decodeMacroParameters
	return self.macro_manager.decodeMacroParameters(self.door, params)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.4.0-py2.7.egg/sardana/macroserver/msmacromanager.py", line 758, in decodeMacroParameters
	raise WrongParam, msg
    WrongParam: Either of: Controller with name motctrl09 does not exist or Controller with name motctrl09 does not exist made it impossible to decode parameters

    SardanaTP.W002 ERROR    2018-02-28 22:58:13,031 Door/stretch/1: An error occurred while running Macro 'sar_demo() -> 78682904-1cd2-11e8-b60a-74da382e02d6':
    Either of: Controller with name motctrl09 does not exist or Controller with name motctrl09 does not exist made it impossible to decode parameters
    SardanaTP.W002 DEBUG    2018-02-28 22:58:13,031 Door/stretch/1.MacroExecutor: Job ended (stopped=False, aborted=False)
    Dummy-1        WARNING  2018-02-28 22:58:21,277 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: Received elements error event API_EventTimeout: Event channel is not responding anymore, maybe the server or event system is down
    Dummy-1        DEBUG    2018-02-28 22:58:21,277 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: DevFailed[
    DevError[
	desc = Event channel is not responding anymore, maybe the server or event system is down
      origin = EventConsumer::KeepAliveThread()
      reason = API_EventTimeout
    severity = ERR]
    ]
    Dummy-1        INFO     2018-02-28 22:58:21,287 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1.Elements: Activating polling. Reason: API_EventTimeout
    Dummy-1        DEBUG    2018-02-28 22:58:21,307 TaurusPollingTimer[3000].Timer on _pollAttributes: Timer::stop()
    Dummy-1        WARNING  2018-02-28 22:58:31,329 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: Received elements error event API_EventTimeout: Event channel is not responding anymore, maybe the server or event system is down
    Dummy-1        DEBUG    2018-02-28 22:58:31,330 jessie.Speedport_W_724V_Typ_A_05011603_00_003:10000.Pool_stretch_1: DevFailed[
    DevError[
	desc = Event channel is not responding anymore, maybe the server or event system is down
      origin = EventConsumer::KeepAliveThread()
      reason = API_EventTimeout
    severity = ERR]

I it somehow related?

Combination sardana 2.4.0  and taurus 4.0.3 works OK but sardana 2.2.2 and taurus 4.3.0 breaks with some other errors.

Bests,
Jan
PS: Sorry for long printouts

**Comment by reszelaz** [comment]
This problem is already reproducible with Taurus so I think that keeping an open ticket in Taurus is enough.
