### ISSUE TITLE
IndexError: list index out of range ; after wrong MntGrp configuration (SF#111)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#72]
Hi,

Wrong MntGrp configuration, e.g. missing timer controller,  causes crash of MS server.
To get it working one has to restart Pool server. 
Otherwise even with the right configuration one get the error listed bellow.

I attached my patch which solves this problem.

Bests,
Jan

SardanaTP.W006 DEBUG    2014-02-20 09:32:40,658 Door/demo1/1: Traceback (most recent call last):
  File "/home/jkotan/sardana/sardana/src/sardana/macroserver/msmacromanager.py", line 1132, in runMacro
    for step in macro_obj.exec_():
  File "/home/jkotan/sardana/sardana/src/sardana/macroserver/macro.py", line 2144, in exec_
    res = self.run(*self._in_pars)
  File "/home/jkotan/sardana/sardana/src/sardana/macroserver/macros/nexdatas.py", line 736, in run
    self.__updateConfiguration()
  File "/home/jkotan/sardana/sardana/src/sardana/macroserver/macros/nexdatas.py", line 787, in __updateConfiguration
    self.__mg.setConfiguration(self.__hsh)
  File "/home/jkotan/sardana/sardana/taurus/lib/taurus/core/tango/sardana/pool.py", line 1352, in setConfiguration
    self.write_attribute('configuration', data)
DevFailed: DevFailed[
DevError[
    desc = IndexError: list index out of range
           
  origin =   File "/home/jkotan/sardana/sardana/src/sardana/tango/pool/MeasurementGroup.py", line 195, in write_Configuration
    self.measurement_group.set_configuration_from_user(cfg)
  File "/home/jkotan/sardana/sardana/src/sardana/pool/poolmeasurementgroup.py", line 336, in set_configuration_from_user
    timer_name = cfg.get('timer', user_elements[0].full_name)

  reason = PyDs_PythonError
severity = ERR]

DevError[
    desc = Failed to write_attribute on device mntgrp/pool_demo1_1/mntgrp01, attribute Configuration
  origin = DeviceProxy::write_attribute()
  reason = API_AttributeFailed
severity = ERR]
]

SardanaTP.W006 ERROR    2014-02-20 09:32:40,659 Door/demo1/1: An error occurred while running Macro 'nxs_set_mntgrp_from_components(ct01, True)':
IndexError: list index out of range

SardanaTP.W006 DEBUG    2014-02-20 09:32:40,662 Door/demo1/1.MacroExecutor: Job ended (stopped=False, aborted=False)

Reported by: jkotan ( http://sf.net/u/jkotan )

Original Ticket: [sardana/tickets/111](https://sourceforge.net/p/sardana/tickets/111)

**Comment by reszelaz** [comment]
Measurement group configuration on the server side was completely refactored. I believe this issue is simply outdated. @jkotan please re-open if you find this issue in the latest version. Many thanks!
