### ISSUE TITLE
springfield controller bugs

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#721]
when playing around with Sardana and the springfield controller example I encoutered two issue:

1. in the file springfieldlib.py in the method getLimits() starting in line 549:
the `motion ` object is assigned as 
`motion = self.getMotion(axis)`
but in the later statements only `m` is used instead.
so `m` has to be replaced by `motion`
This bug will results in an warning from `PoolAction._raw_read_ctrl_state_info()` line 540 in poolaction.py which calls `PoolController.raw_read_axis_states()` in  poolcontroller.py whre the error happens in line 563.
Essentially the `ctlr.StateOne(axis)` simply fails.

2. The default values for velocities and acceleration, etc in the springfieldlib.py have to be changed to get the thing working. I would appriciate it, if such example works out-of-the-box without any adjustments.

Best

Daniel

**Comment by reszelaz** [comment]
Many thanks @dschick for pointing this out.

I've just corrected these mistakes and it is already available in the develop branch (I've pushed directly since the bugs were evident and it affects only the decumentation).

As soon as RTD compiles the docs it will be also available on the website.

**Comment by reszelaz** [comment]
It is already available in the docs.
