### ISSUE TITLE
TangoController.py not reading attribute

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#722]
When trying to implement a counter in Sardana via the `TangoCounterTimerController` class I encounter several error:

1. line 110: ` self._axis_tango_attributes[axis] = data = value, None, None` should be  `self._axis_tango_attributes[axis] = data = [value, None, None]`
2. line 91: can be deleted?!
3. thats the main issue: the `ReadTangoAttributes `class just misses the `read_one `and `read_all `methods.

Instead, when I use the `TangoAttrCTController `class found [here](https://sourceforge.net/p/sardana/controllers.git/ci/253fd8f42febe0b8310ea59f8df45b4c337bbb8c/tree/python/countertimer/TangoAttrCTCtrl.py) it works like a charm.

Maybe one should merge these to files?

Best

Daniel

**Comment by reszelaz** [comment]
You are right, the Tango attribute controllers that comes with the Sardana project are broken currently. We were discussing merging the ones from the third-party repository, which works perfectly and are widely used, in this issue: https://github.com/sardana-org/sardana/issues/181.

Now we will give it a priority so we get them merged ASAP.

Sorry for the inconvenience.

**Comment by dschick** [comment]
oh, I havn't found that issue.
But yes, resolving that issue would be of great help for beginners like me.
At least stating, that the controller is not working would save some time.

Thanks

**Comment by reszelaz** [comment]
I have added the following warning message to the controllers class docsting (I have pushed directly without the PR process cause it is just a docstring):

```
    ..warning:: As pointed in sardana-org/sardana#722 this controller is
    buggy. A working version of this and other Tango controllers can be found
    in the third-party repository: http://sf.net/p/sardana/controllers.git.
    As part of the sardana-org/sardana#181 this controller will be fixed or
    removed from Sardana.
```

so the next users at least will be warned. We will address this issue ASAP. Meanwhile I close this ticket since  we have already #181.
