### ISSUE TITLE
Improve installation instructions & automation for windows

### ISSUE THREAD

**Issue by cpascual** [sardana-org/sardana#727]
This is a spin-off from #724, in order to focus on the discussion of the best way to provide instructions for sardana installation on Windows, which is [also related to how we do the installation on our CI scripts](https://github.com/sardana-org/sardana/issues/724#issuecomment-376810492):

@reszelaz [wrote](https://github.com/sardana-org/sardana/issues/724#issuecomment-378298555)
>> you should publish this in the sardana documentation.

>I totally agree, we should have it somewhere public. But for the moment I don't have any clear idea where to put it. Just to open the brainstorming:
>  -  DirectlyIn the documentation
>  -   In the release manual test markdown document
>  -  As powershell script in the CI directory

IMHO, the best option is to publish it as a powershell script in the CI dir. Then both the vagrant file and the Appveyor.yml could use it. And **also the "getting started" section of the docs could link to it**.

Now regarding to implementation details, I have two comments:

- most of this powershell script could be converted to a single pip call with a requirements file, which would be neater IMHO
- it would be good to **not** to base our recipe on pythonxy (it is too heavy for CI, and does not seem to be updated anymore). The problem is that then we need to install some stuff that is not available in PyPI (PyQt4, Qt4?, PyQwt5?) . For this we could either try to do it "manually" or we could use conda (AFAIK, pytango is now available for windows in a conda channel).

**Comment by reszelaz** [comment]
I think in the current state the best way of installing Sardana (and its dependencies) on Windows would be to use conda. To document this we could reuse the part of the [docs](http://taurus-scada.org/users/getting_started.html#installing-in-a-conda-environment-windows-and-linux) of Taurus. Anyone willing to controbute to this?:)
