### ISSUE TITLE
Update Jan18 release problem: testsuit failures in debian9

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana#732]
The Jan18 release gives failures running sardanatestsuite in debian9.
Since then several changes have been done in Sardana and Taurus.
I have now tested it taking Sardana and Taurus from the develop branches.
The tests in sardanatestsuite are now passed (tested with the two possible domains -FQDN and PQDN - for the TANGO_HOST). 
ScanDataTestCase gives three failures, but this is not related to sardana but to the nxs package in
debian9.
The error is:

 File "/usr/lib/python2.7/dist-packages/nxs/napi.py", line 320, in __init__
    raise NeXusError, "Could not %s %s"%(op,filename)
NeXusError: Could not create /tmp/data_nxs.hdf5

The use of the nxs package outside sardana reports the same error when trying to open a file.
The installed nxs version is 4.3.2.

**Comment by cmft** [comment]
I could  run the sardana testsuite (using the current develop branch) without any trouble
```
Ran 110 tests in 83.820s
OK (skipped=6, expected failures=1)

```
I don't have `nxs` since it was dropped from debian9 and I use `h5py` instead

**Comment by teresanunez** [comment]
Thanks @cmft, yes, if nxs is not installed the tests are skipped and I get the same as you get.

**Comment by reszelaz** [comment]
@teresanunez I think this should not be a problem anymore since 6a6e249. Could you test it?

**Comment by teresanunez** [comment]
HI @reszelaz, yes, the problem is solved now. Many thanks.
