### ISSUE TITLE
New ParamRepeat interface does not work with execMacro

### ISSUE THREAD

**Issue by rhomspuron** [sardana-org/sardana#754]
The execMacro method does not work with the new ParamRepeat interface.

```
.....
class qExafsc(Macro):
    param_def = [["startPos", Type.Float, None, "Starting position"],
                 ["end_triggers", [
                     ["endPos", Type.Float, None, "Ending pos value"],
                     ["nrIntervals", Type.Integer, None, "Nr of triggers"],
                     {'min': 1}], None, 'List of [end_pos, triggers] for the '
                                        'region'],
                 ["intTime", Type.Float, None, "Integration time per point"],

                 ["waitFE", Type.Boolean, True, ("Active the waiting for "
                                                 "opening of Front End")],

                 ["configPID", Type.Boolean, True, ("Active the configuration"
                                                    " of the bragg PID ")]]

    def run(self, start_pos, end_triggers, int_time, wait_fe, config_pid):
        self.info('StartPos: {0}'.format(start_pos))
        self.info('EndTriggers: {0}'.format(end_triggers))
        self.info('IntTime: {0}'.format(int_time))
        self.info('WaitFe: {0}'.format(wait_fe))
        self.info('ConfigPID: {0}'.format(config_pid))


class runqExafsc(Macro):
    def run(self):
        self.execMacro("qExafsc 10 [[20 10] [30 40] [40 50]] 0.1")


class runMv(Macro):
    def run(self):
        self.execMacro("mv [[mot04 10] [mot05 10]]")
```

If I run the macro on spock I have the next erros: 

```
Door_clear_traj_1 [8]: qExafsc 10 [[20 10] [30 40] [40 50]] 0.1 
StartPos: 10.0
EndTriggers: [[20.0, 10], [30.0, 40], [40.0, 50]]
IntTime: 0.1
WaitFe: True
ConfigPID: True

Door_clear_traj_1 [9]: %runqExafsc
An error occurred while running Macro 'runqExafsc() -> 1780cef0-5825-11e8-b016-003064082620':
Repeat parameter must be the last one

Door_clear_traj_1 [10]: mv [[mot04 10] [mot05 10]]

Door_clear_traj_1 [11]: %relmaclib param_repeat
param_repeat successfully (re)loaded (found 2 macros)

Door_clear_traj_1 [12]: %relmaclib param_repeat
param_repeat successfully (re)loaded (found 3 macros)

Door_clear_traj_1 [13]: %runMv
An error occurred while running Macro 'runMv() -> e6c474aa-5825-11e8-b016-003064082620':
Moveable with name [[mot04 does not exist

```

There are two behaviors:

- On the runqExafsc, the execMacro assumes the old ParamRepeat interface.
- On the runMv, the execMacro takes the motor name as [[mot04

From PR #405 commends:
>  This implementation also extends the possible execMacro syntax. Now it is also possible to use, for
example:
self.execMacro("mv [[exp_dmy01 10] [exp_dmy02 10]]")
using the same spock syntax for the new ParamRepeat implementation.

But on the execMacro docstring this is not the information:
>  a space separated string of parameters (this is not compatible
 with multiple or nested repeat parameters, furthermore the repeat
 parameter must be the last one):
 self.execMacro('ascan th 0 100 10 1.0')
 self.execMacro('mv %s 0' % motor.getName())

IMHO the execMacro should allow to execute the same string than spock, it is more friendly user. What do you think about it?

**Comment by rhomspuron** [comment]
Hi @teresanunez, 

Thanks for the answer. If there are reasons not to implement it, it is not necessary to create a new PR. 
Are the reasons for not wanting it documented?

Regards,
Roberto

**Comment by teresanunez** [comment]
Hi Roberto,
                   I think the main reason for that was to keep the interface clear, and let the users do what
they do ... the other way could be confusing. We had even restricted it more (not allowing:

execMacro("mv mot1 10")

but we at the end we decide to keep the compatibility with the old interface for these cases.
As I said, it could be discussed again, but it was done like this as a decision. So I close this,
and if for some reason it has to be open we open a new Issue with another name.

                        Regards,
                                            Teresa

**Comment by rhomspuron** [comment]
Thanks, I will ask to my user If they want it as a new feature of Sardana.
