### ISSUE TITLE
wrong argout of the ReloadMacro and ReloadMacroLib tango cmds  (SF#119)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#76]
Description of the argout says: "[OK] if successfull or a traceback if there was a error (one string with complete traceback of each error". However even if the error occurs the [OK] string is returned. 

Reported by: reszelaz ( http://sf.net/u/zreszela )

Original Ticket: [sardana/tickets/119](https://sourceforge.net/p/sardana/tickets/119)

**Comment by HEnquist** [comment]
Seems closely related to https://github.com/sardana-org/sardana/issues/75
