### ISSUE TITLE
hard limit on OneDController array lengths?

### ISSUE THREAD

**Issue by alexbjorling** [sardana-org/sardana#765]
Writing a `OneDController` for a device which records a time series of scalar values. Sometimes the time series is long. Sardana doesn't seem to let me return anything longer than 2**14 elements, which seems an unnecessary limitation. My workaround is to write it as a `TwoDController` and reshape, but that is of course madness. Any good reason for this limit?

**Comment by reszelaz** [comment]
Thanks for this report!

The limit is hardcoded in the `sardana.pool.controller.OneDController` class. But I think one should be able to change it overriding the `GetAxisAttributes` method of the controller.
I think that the limit is there cause Tango requires the _MaxDimSize_ of the attribute when you declare it.

Could you explain closer your application? Could it be something similar to a timescan?

**Comment by reszelaz** [comment]
Hi, please reopen if we can still help somehow.
