### ISSUE TITLE
Pool server crash when reading tango attribute in sardana controller

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#769]
I am trying to read a motor positon in a pseudo counter.
To do so I followed @teresanunez  suggestions to use PyTango and read the position attribute of the corresponding motor like

```
self.motor_device = PyTango.DeviceProxy("mymotordevicename") 
pos = self.motor_device.position
```
This code works perfectly from within any python shell but as soon as I put the second line into the pseudo counter and execute a `ct `the pool server crashes without any error message to capture.

Again I am running under windows with the latest alpha release of Sardana and pretty much the newest version of Tango.

Best Daniel

**Comment by teresanunez** [comment]
Hi Daniel,
                   one thing, you talk about a PseudoCounter but you are actually creating a controller of
the type CounterTimerController, aren't you?. In other case you don't have the method ReadOne.
In my computer it works without any problem. Could you please try to read the attribute Value of the counter that you have in the Pool for that class?, if you read it with jive using 'Test Device' you will probably get an error. 
                                        Regards,
                                                        Teresa

**Comment by dschick** [comment]
Hej Teresa,

yes, I am currently talking about a CounterTimerController and not a PseudoCounter.

When I Test the Counter using Jive I also get the error, meaning that Jive shows a timeout error and the pool server also crashes.
When I catch the error in the counter by an except, I get the following:
`Unexpected error: <type 'exceptions.AttributeError'>`

I have to say, that I am currently running Tango in version 8.

Best

Daniel

**Comment by teresanunez** [comment]
Hi Daniel,
                  I also use tango8. Try to read the position already when you create the
 proxy and check if you get it there (with a printout for example). Try to check also
 the motor you are reading.

                                Regards,
                                                Teresa

**Comment by dschick** [comment]
It does not matter where I try to read the position of the motor in the
counter class.
There is always an error.
What do you mean with
> Try to check also the motor you are reading
From a python console I can read the motor position with pytango without
any problems.

Is there a way to get some debugging information for that tango call from
within the counter?

Best

Daniel

teresanunez <notifications@github.com> schrieb am Di., 29. Mai 2018 um
10:40 Uhr:

**Comment by teresanunez** [comment]
Hi Daniel,
                if you can not read the position anywhere I would say that you have somewhere an error.
There are many ways of debugging it. You can send to me the whole file and I would simply change
the name of the motor to one of my motors, so I can check it.

                            Regards,
                                               Teresa

**Comment by dschick** [comment]
Okay,

here is my controller:

https://github.com/dschick/sardanaControllers/blob/master/motorPosCounterController.py

in line 62 you have to remove the `1#` to return the position.

Is there maybe a problem with the motor I am reading?
I will also try reading the postion from another motor in the meantime.

Thanks

Daniel

**Comment by teresanunez** [comment]
Hi Daniel,
                 I have just tried your controller and for me it works. Have you tried with another motor?.

                           Regards,
                                             Teresa

**Comment by dschick** [comment]
same with another motor and with another attribute like "Velocity"
The syntax: `motor/kepcoctrl/1` is fine?

I also used a new measurement group with just the single counter for the motor positon, but same result.

Even in  "trace"-mode I do not get any meaningfull error message from the pool server

**Comment by teresanunez** [comment]
The syntax is fine if you are in the same database. But have you not tried to simply run it in a python script. Try simply:

import PyTango
mymot = PyTango.DeviceProxy("motor/kepcoctrl/1")
print mymot.position

in the same computer where the Pool runs.

**Comment by dschick** [comment]
This works like a charm. In normal python I can access all motor attributes
using pytango

teresanunez <notifications@github.com> schrieb am Di., 29. Mai 2018, 13:17:

**Comment by dschick** [comment]
this is why I am also confused. The only obvious difference of our setups is, I guess, the OS, since I am running under Windows. But I do not see an obvious problem here, since everything is working elsewhere outside of sardana.

Is this maybe a problem of the timing, when sardana asks the Tango attribute?
BTW. I have a TangoAttributeMotorCtrl running which works perfectly well with a TangoDeviceServer of 6axis.

Best

Daniel

**Comment by teresanunez** [comment]
There is no problem in reading things from the controllers. I guess reading your motor does not take
 more than 3 s, and if this is the case you will get also the timeouts from any python script. I can not test
 anything in windows, sorry, but it should not be any difference with Linux concerning that.

**Comment by dschick** [comment]
could anyone runnign sardana under windows test this as well?

**Comment by dschick** [comment]
uff, thanks @reszelaz for proving I am not helpless in what I am doing here.
What version of Tango are you using?

Okay, so you are talking about something like this for testing:

import time
import numpy

from tango import AttrQuality, AttrWriteType, DispLevel, DevState, DebugIt
from tango.server import Device, attribute, command, pipe, device_property


```
class A(Device):

    attr = attribute(label="attr", dtype=float,
                        access=AttrWriteType.READ, format="8.4f",)

    def init_device(self):
        Device.init_device(self)
        self.set_state(DevState.ON)

    def read_attr(self):
        return 1
```

```
class B(Device):

    def init_device(self):
        Device.init_device(self)
        self.set_state(DevState.ON)

    @command
    def cmd(self):
        remote_device = tango.DeviceProxy("A/test/1")
        return remote_device.attr
```

Anything more one needs to do? How about the threading?

**Comment by rhomspuron** [comment]
I included the thread to simulate the acquisition: [ds.txt](https://github.com/sardana-org/sardana/files/2058700/ds.txt)

**Comment by reszelaz** [comment]
I was able to reproduce it using the example provided by @rhomspuron. Many thanks!
I've already created an issue in Tango: https://github.com/tango-controls/TangoTickets/issues/19
Thanks to all!

**Comment by reszelaz** [comment]
This issue was solved in Tango/PyTango. More details in https://github.com/tango-controls/TangoTickets/issues/19#issuecomment-513276187.
