### ISSUE TITLE
pre-acq hook is not executed for ct macro

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#770]
it seems that the pre-acq hook is not available for the ct-macro. Is it possible to allows this hook place for ct? Or would this mess up the scan macros?

**Comment by teresanunez** [comment]
The general hooks are only applied to hookable macros. ct is not. The idea of the general hooks is to run
something for all the scans (mainly) even if it can be used for any Hookable macro. But I think that it
 break the idea of the implementation if you want to use it for 'concatenate' macros. For that you can define a macro where you call the macros that you want in the order you want.

**Comment by teresanunez** [comment]
I would close this because what the title says is a fact and not an error.

**Comment by dschick** [comment]
okay, I should move this one to the mailing list, I guestt

**Comment by reszelaz** [comment]
As @teresanunez explains the `ct` currently does not inherit from the `Hookable` class and it does not define any hook places. However, I still do not see problems which could occur if we implement these hook places in the `ct` macro?

Regarding the usage of mailing list vs. GitHub issues. IMHO I see mailing list for the announcements, news, etc. I like having such discucssions in the GitHub issues for easier seraches, references, clear browsing, etc. I don't know if you agree?

**Comment by dschick** [comment]
at least I would feel it to be natural that the `pre-acq` and `post-acq`
hooks are executed prior or after a `ct`.
I could update the `ct` macro locally for testing and if successful, I
might do a pull-request.

Regarding the mailinglist vs. github discussion:
There are good points for both options.
It feels rather natural to ask for the availabilty of some features, or
just a stupid beginners questions using the mailingl list.

However, I agree with @reszelaz that it is a bit of a pain for searching
and archiving of discussions to always switch between github and sf.

When asking e.g. for a solution for a problem, it also comes to the
audience one can reach with either one of the options. Are there some
numbers of how many people are suscribed to the mailinglist vs. github?

Best

Daniel

reszelaz <notifications@github.com> schrieb am Di., 29. Mai 2018 um
17:45 Uhr:

**Comment by cpascual** [comment]
> Regarding the mailinglist vs. github discussion:
>It feels rather natural to ask for the availabilty of some features, or just a stupid beginners questions using the mailingl list.

I would also encourage the use of github issues for all bidirectional communication. It just happens that many times a "beginner question" turns out to be in fact pointing to a bug, or an "availability question" can evolve into a feature request. For those cases where no further action is required (besides just responding the question), we label them as "question".

**Comment by reszelaz** [comment]
> I could update the `ct` macro locally for testing and if successful, I might do a pull-request.

Great!

> Are there some numbers of how many people are suscribed to the mailinglist vs. github?

In mailing lists we have currenty: 
* sardana-devel: 18 subscribers
* sardana-users: 26 subscribers

In GitHub we have 15 watchers.

What we could do is to send an email to the mailing list informing about the recommendation to use the GitHub issues also for user/developer questions and that we will keep the mailing lists just for the announcements/news. We could take a profit of this email and encourage the mailing list subscribers to watch the project on GitHub.

**Comment by dschick** [comment]
coming back to my original question of hooking the `pre-acq` and `post-acq` macros also to the ct macro:

this actually does not work for me!
As soon as I let ct inherit from `Hookable` instead from `Macro` it is not loaded any more into the macro server --> 
`Error: MacroCode with name ct does not exist`

it is also not listed in the `relmaclib` response.

**Comment by teresanunez** [comment]
Hi @dschick, it is not instead of, it is additionally:

class ct(Macro, Hookable):

**Comment by dschick** [comment]
@teresanunez thanks!

**Comment by reszelaz** [comment]
I think this is solved already after integrating #808.

**Comment by dschick** [comment]
Yep it is, thanks for closing

reszelaz <notifications@github.com> schrieb am Fr., 27. Juli 2018, 18:38:
