### ISSUE TITLE
sardana - log book interaction

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#789]
in the context of improving commenting to data files, see #771, and [Macro Logging](https://github.com/sardana-org/sardana-followup/blob/master/20180605-Prague/01-MacroLogging/01-MacroLogging.pdf), I was wondering if there are any solution around for letting sardana interact with any kind of electronic log book?

Here are some background information: at the beamline I am mostly working at, we implemented some goodies for the users that work with hand-written log books. So in SPEC we have e.g. a macro called `wup `(where user print) which automatically print the current user motor positions to a piece of self sticking paper, which the users can directly stick into their log book. The same works for graphs which they create in our python data analysis.

However, when we use electronic log books, like google docs, we always have to fight with copy and pasting (formatting) and doing screenshots. At LCLS in Stanford they have some kind of self-made log book which is similar to an ELOG. The great advantage is, that you can, by one click in the log book, add the current motor positons (like a pre-scan snapshot) or an image to the log book.

I know that this might be a bit outside the scope of sardana, but I was wondering if anyone of you have ever thought about similar things or maybe already implemented them?
I guess one could do pretty much anything within python to send data from sardana, to e.g. a webserver?

Best

Daniel

**Comment by jangarrevoet** [comment]
Hi Daniel,
I am also looking at several ways to integrate a logbook, although the integration with sardana will be limited to a certain feature set, logging motor positions, scan lists,.. All other info will come from other things.
There are a few things out there but non seem to be fully complete. For the online logbook a database backend is the best solution but users will also want to have an offline version available that still supports animated content such as gifs or movies, which rules out pdf.
greetings,
Jan

**Comment by dschick** [comment]
Hej Jan, thanks for the comment. I fully agree.
The LCLS approach has such kind of db backend and all macro calls from the CLI are automatically logged there.
The user can then "ONLY" add comments, images, positions in between the scans. 
So one could think of extending the macro logging feature also for an external web interface to read entries and to post additional entries.

Best

Daniel

**Comment by jangarrevoet** [comment]
Hi Daniel,

I am not sure if the logging feature of sardana should be expanded to offer this kind of functionality since many people will want to have a different integration/system. I would simply supply an API which makes it easier for people to integrate their own electronic notebook. They will anyhow have to write something if they want automatic logging from their data processing pipelines which are independent from sardana.

The scan hooks offer IMHO the perfect place to enable 3rd party logging features.

greetings,

Jan

**Comment by reszelaz** [comment]
Actually, two weeks ago, during the Tango Meeting, I heard a similar request from the MaxIV colleagues (@AntoineDupre and @hardion). They would like to add entries in their electronic logbook with the macro outputs.

Just refining the requirements, first thing we should answer is if we want to have this feature on the MacroServer level only i.e. allow to log from the macro code? Or also include the possibility to log from the Device Pool i.e. allow to log from the controllers code? I think that the macro logs would be enough.

Continuing, we have two similar features already available: [report](http://www.sardana-controls.org/en/latest/devel/howto_macros/macros_general.html#reports) and [MacroLogging](https://github.com/sardana-org/sardana-followup/blob/master/20180605-Prague/01-MacroLogging/01-MacroLogging.pdf). Is the feature that we are talking about similar to any of these? Currently both of these are limited to writing to a file, but I could imagine extending them with the possibility to plug in a custom handlers that could send information to other destinations e.g. database, webserver, etc. In this case the easiest would be to reuse the Python logging mechanism.

**Comment by dschick** [comment]
@reszelaz, I agree that macro logging would be fine.
Having file + additional handlers for e.g. a db or webservice available would be great, but I guess that this not very high priority for now.

My feeling is, that the MacroLogging and/or the report feature might do the trick, as e.g. every start and end of a scan should be silently reported to the logbook, so there is no need for extra output within the clients.
However, the MacroLogging seems to be more powerful and I would like to have the ability of an automatic logging from the macro side and some manual logging/reporting also available from the CLI.
I am not sure what are your plans for e.g merging the MacroLogging and report feature?
