### ISSUE TITLE
Docs: diffractometer documentation is missed

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana#798]
The implementation of the diffractometer in Sardana is not mentioned at all in the Sardana documentation. Some information can be seen in the description of the dedicated SEP:

https://sourceforge.net/p/sardana/wiki/SEP4/

There is also a draft with some notes in the doc-camp branch of the sardana-followup meetings.

**Comment by reszelaz** [comment]
We could add a new chapter to the User's Guide in between the Scans and "Adding real elements".

**Comment by teresanunez** [comment]
PR done
