### ISSUE TITLE
Extend repeat macro to run it easily from spock

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#802]
Currently, it is not user friendly at all to use the `repeat` macro from spock. This macro works by executing another macros hooked in the `body` hook place. This can be done in the following ways:
* programmatically
* using sequencer
* using general hooks

We could extend this macro to accept also parameters. I propose to add a param repeat of strings to accept passing macro name and parameters e.g.

```python
    param_def = [
        ['nr', Type.Integer, None, 'Nr of iterations'],
        ['macro_name_params', [['token', Type.String, None, 'Macro name or macro parameter'], {'min':0}], None, "List with macro name and parameters (if any)"]
    ]
```

This repeat parameter is not mandatory (min=0). One could use the macro as it is now i.e. with hooks.
If one runs it with parameters, this should internally call: `self.execMacro`.

The usage from spock would be (using normal spock syntax):
`Door> repeat 100 ascan mot01 0 10 10 0.1`
or (using advanced spock syntax):
`Door> repeat 100 [ascan mot01 0 10 10 0.1]`

What do you think?

**Comment by reszelaz** [comment]
This is inspired on the [macros](https://github.com/synchrotron-solaris/lib-solaris-facility-macros/blob/develop/facility_sequence.py) developed by Solaris. The idea is to merge both solutions and have only one macro for this.

**Comment by teresanunez** [comment]
HI @reszelaz, I agree with what you propose.

**Comment by reszelaz** [comment]
Great! For the moment I was thinking to restrict it and allow to repeat only one macro. In the future we could think of extendind this if necessary. I don't know what do you think?

**Comment by teresanunez** [comment]
I was also thinking on that, allowing more than one macro, I think it would be interesting to have.

**Comment by dschick** [comment]
this would be really great! especially repeating multiple macros

teresanunez <notifications@github.com> schrieb am Mi., 4. Juli 2018 um
14:53 Uhr:

**Comment by reszelaz** [comment]
In this case I see two options for passing multiple macros with their parameters.

Either use param repeat of param repeats of strings. This would require to use the advanced spock syntax e.g.
```
Door> repeat 100 [[ascan mot01 0 10 10 0.1] [ct 10] [dscan mot02 -20 20 6 0.2]]
```

Or just use repeat parameter of strings, and if the macro require passing parameters enclose them in quotes e.g. 
```
Door> repeat 100 "ascan mot01 0 10 10 0.1" "ct 10" "dscan mot02 -20 20 6 0.2"
```

**Comment by dschick** [comment]
I think the latter option would be sufficient. However, I am wondering if there is an idea about a general syntax with the advanced spock syntax - so my fear is, that users are getting confused when which syntax has to be used. So maybe from this point of view one should stick to the first option?

**Comment by reszelaz** [comment]
I also have a sligh preference for the second one. So I vote to implement it this way for Jul18. I do not anticipate changes, but just in case, we could mark it as *experimental* in the macro docstring:

```
.. note::
        The repeat macro has been included in Sardana
        on a provisional basis. Backwards incompatible changes
        (up to and including removal of the macro) may occur if
        deemed necessary by the core developers.
```

After a release or two we remove the *experimentl* tag.

Regarding the spock syntax, when #781 gets finished I will suggest to merge both concepts into one with different possibilities when passing repeat parameters.

**Comment by reszelaz** [comment]
@daneos since you at Solaris have experience with the repeat macro, do you feel like continuing with this? Many thanks!

**Comment by teresanunez** [comment]
@reszelaz, @daneos, I could take it if you want. Just tell me.

**Comment by reszelaz** [comment]
For me it's fine:)

**Comment by teresanunez** [comment]
A PR is created.
