### ISSUE TITLE
motor configuration: especially limits

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#805]
Hej all,

I was wondering if there is already some kind of gui or cli interface available to set the configuration of a movable in Sardana. I know that there was a gui client which is currently rewritten, is that right?

However, I am currently struggling setting the user and dial limits of my motors. e.g. the macros `set_lim` and `set_lm` are setting the limits but individually. Ideally they should take into account the sign and offset of the motor to set the limits accordingly.

How do I actually implement a movable that move only in discrete steps. Can I use the steps_per_unit for that?

Best

Daniel

**Comment by reszelaz** [comment]
> However, I am currently struggling setting the user and dial limits of my motors. e.g. the macros set_lim and set_lm are setting the limits but individually. Ideally they should take into account the sign and offset of the motor to set the limits accordingly.

I don't know if I understand well your concern. The limits, both for the user position and for the dial position respects these attributes. That means that the `set_lim` macro sets the limit for the user position which is calculated from the dial position and considering the offset and sign: (`user = sign x dial + offset`). The `set_lm` macro sets the limit for the dial position which is calculated from the position returned from the controller and considering the steps_per_unit (`dial = controller_position / steps_per_unit`). That means these limit values are in user position domain and dial position domain respectively.

There are however some known issues cause changes of these underneath attributes does not update the limits, see: #9 which says that the steps_per_unit attribute changes should recalculate the limit values and #159 with some more general ideas.

> How do I actually implement a movable that move only in discrete steps. Can I use the steps_per_unit for that?

Again I don’t know if I understood it correctly, maybe [DiscretePseudoMotor](https://github.com/sardana-org/sardana/blob/develop/src/sardana/pool/poolcontrollers/DiscretePseudoMotorController.py) is what you are looking for?

**Comment by dschick** [comment]
@reszelaz these where actually two independent questions :)
regarding the first one with the limits:
I think in SPEC the set_lm and set_lim functions connect the two domains. So if I change the limits in the user domain, also the limits in the dial domain are changed according to the same formula as for the position. because user and dial domain have a 1:1 dependency via sign and offset so the limits should have that as well.

Regarding the second issue with the discrete steps I am fine with the DiscretePseudoMotor, thanks!

**Comment by reszelaz** [comment]
Good that DiscretePseudoMotor will work for you.

For the limits thing I propose to continue the discussion in #9 and #159. As you can see these are very old issues and I would not expect that soon we will get into them. In the next month we will work on the documentation and the Jul18 release. I propose to come back to this after holidays. Hope you agree.

**Comment by dschick** [comment]
shall I close this issue because #159 is actually raising the same issue?
For me it is not urgent, but I think it should be not as low in the priority list as the age of this issue suggests :)

One thing that I have not tested but just came to my mind:
Assume user and dial positions have an offset of 10. The DialLimits are -10 to 10, so the userlimits should be 0 to 20. However, when I `set_lim motor 0 30 `and then do a` umv motor 30` - will this work or are both limits always checked?

**Comment by reszelaz** [comment]
> shall I close this issue because #159 is actually raising the same issue?

I would say so, for me they sounds the same.

I've checked the scenario that you describe. The dial limits are not checked.
```
Door_zreszela_1 [82]: wm mot01
                  mot01
User               
 High               inf
 Current            0.0
 Low               -inf
Dial               
 High               inf
 Current            0.0
 Low               -inf

Door_zreszela_1 [83]: set_lm mot01 -10 10
mot01 limits set to -10.0000 10.0000 (dial units)

Door_zreszela_1 [85]: mot01.offset = 10

Door_zreszela_1 [86]: wm mot01
                  mot01
User               
 High               inf
 Current           10.0
 Low               -inf
Dial               
 High              10.0
 Current            0.0
 Low              -10.0

Door_zreszela_1 [87]: set_lim mot01 0 30
mot01 limits set to 0.0000 30.0000 (user units)

Door_zreszela_1 [88]: wm mot01
                  mot01
User               
 High              30.0
 Current           10.0
 Low                0.0
Dial               
 High              10.0
 Current            0.0
 Low              -10.0

Door_zreszela_1 [89]: mv mot01 30

Door_zreszela_1 [90]: wm mot01
                  mot01
User               
 High              30.0
 Current           30.0
 Low                0.0
Dial               
 High              10.0
 Current           20.0
 Low              -10.0
```
Regarding the priority, we will do our best. Let's come to this after the Jul18 release.

**Comment by dschick** [comment]
Okay, but I guess this is quite important since one can easily crash some motors in the experiment.
