### ISSUE TITLE
expconf is not automatically updating when configuration changes

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#806]
not sure if this is already issued, but when I add new counters to my pool and I have the expconf window open, I do not seem them in the list of counters to add after a refresh. I have to close+reopen the expconf window.

Moreover, when changing the counter which are plotted I also need to close/reopen the trend window.

Best,

Daniel

**Comment by reszelaz** [comment]
Yes, this is a known limitation/bug. Actually I was thinking that it was already reported, but now I can not find any issue talking about it.

**Comment by reszelaz** [comment]
If someone finds the original report please post the link here. Meanwhile I think it is better to keep this one open for other users.

**Comment by dschick** [comment]
this is especially a bit annoying because of this #753 - so everytime you reopen the expconf you have to manually correct the FNDQ in the snapshot

**Comment by reszelaz** [comment]
I agree, we will try to continue with #753 ASAP in order to have all the FQDN issues solved in Jul18 release.

**Comment by dschick** [comment]
updating the expConf is also important in context of new macros like `newfile `or maybe like a `plotselect`.
It just happend to me several times that I run a macro which enables/disables counters while the expconf is open and when I then change a setting in the expconf, it overwrites all setting I made from within the macros. I guess a global refresh button or maybe even a periodic refresh would be nice - maybe one can trigger an update also via some events from within the macros.

**Comment by reszelaz** [comment]
I totally agree.
The events are already emitted by the server. We just need to listen to them in the expconf.
It is just that we did not have time to work on it yet. But since we are now adding macros for manipulating the same configuration it will become more urgent..

**Comment by rhomspuron** [comment]
Hi @dschick 

Could you review the PR #882? Any feedback is welcome. 

Best,
Roberto

**Comment by reszelaz** [comment]
Solved in #882
