### ISSUE TITLE
how to access environment from within a pool element (counter)

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#807]
Hej,

I am working with a pseudo counter which should return a value according to the value of an environmental variable.
However, I am just not able to access the `env` from within the counter.
How can I do that?

Best

Daniel

**Comment by teresanunez** [comment]
Hi @dschick, the PseudoCounter is a Pool element, and the environment belongs to the MacroServer, you can not access the environment from the Pool (well, you can make 'hacks' creating the MacroServer device proxy inside of your controller code and using 'try-except' in case the MacroServer is not running, but this is really dirty). Moreover you can have a Pool used in different MacroServer environments. so using the environment inside a Pool element is not really a good idea (IMO).

**Comment by dschick** [comment]
so there is no way to access the environment from a pool element?
as another workaround for my situation: can one set the value of a counter from with in a macro?
via PyTango I do not have the permission to do that.
Another option would be to simply disable the counter from a macro, instead of setting its value.

**Comment by teresanunez** [comment]
The Pool doesn't know anything about the MacroServer, and as I said, you can have several MacroServers for the same Pool, that means working with the Pool elements in different environments.
You can combine the Pool elements and the MacroServer environment in the macros, but not in the
 Pool itself.
The Value of a counter is 'only read', one can not write in a counter value, this is why PyTango doesn't
allow you to make that, the Value of a counter is an only-read attribute.
A counter will be only activated if you want (putting it in a measurement group), having it in the Pool
 does not mean that it is 'enable' for counting.

**Comment by reszelaz** [comment]
As @teresanunez there is a clear separation between the Pool and the MS, as well as the environment is an internal thing of a MS. I also see the proxy solution to the MS as a hack.

Counter can be disabled in a measurement group. There is alread an [API](https://github.com/sardana-org/sardana/blob/95feb457ed500a6848661145f31c1de19cf15f43/src/sardana/taurus/core/tango/sardana/pool.py#L1746) for this.
I hope this helps!

**Comment by dschick** [comment]
okay, en/disabled the counters from within a macro so I close this issue as well
