### ISSUE TITLE
pseudocounter controller with multiple axis

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#809]
Hej,

If I use a pseudocounter controller such as IoverI0 I can add a pseudo counter with the following command:

`%defctrl IoverI0 ioveri0ctrl IoverI0=Rel I=mySignal I0=myNormalization`

This creates a ioveri0ctrl and the Rel counter as its 1st axis.
Can I now add another axis to this controller or do I need to create a new controller for each pseudocounter which of course share the same controller logic?

Best

Daniel

**Comment by reszelaz** [comment]
You need to create another controller instance.

It could be slightly related to the dynamic roles issue https://github.com/sardana-org/sardana/issues/86.

**Comment by teresanunez** [comment]
I would said, no. The implementation of PseudoCounters and PseudoMotors work like this.

**Comment by dschick** [comment]
I was just wondering because in the pseudoCounter example there is also an `axis `parameter included.

**Comment by teresanunez** [comment]
I check it. I was mainly thinking in PseudoMotors where each instance is a controller.

**Comment by teresanunez** [comment]
I confirm it, they work in the same way.

**Comment by teresanunez** [comment]
For each PseudoCounter controller you have so many PseudoCounter 'axis' as pseudo_counter_roles your controller has.

**Comment by dschick** [comment]
Muy bien! Now I got it! Thanks  @teresanunez for this hint with the roles!
However, it is a bit nasty, since I need to hard code the number of axis into the controller.
Anyhow, thanks alot

**Comment by teresanunez** [comment]
NIce. Actually it is not nasty, the concept of axis there is in the sense of 'roles' and this is fixed
for a PseudoCounter. The concept of axis for a counter controller, for example, is the number of instances of the controller you want to have. The concept is different.
