### ISSUE TITLE
environment lost after restart

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#814]
after having a lot of trouble due to this issue/feature #812 I currently encounter the problem, that after a restart of my PC most of the environmental variables are just gone. No ActiveMntGrp is set or anything else which I set from within my macros. When I simply restart Sardana and Spock without restarting the PC, everything is fine.
I thought that the environment is also stored in the TANGO db?
Or is it locally on the PC where Sardana is running?

I might have damaged my Sardana configuration in the TANGO db, because due to the problems in #812 I had to manually delete elements in the Pool via Jive.
I was also editing the _SubDevice property of dserver/Sardana/myDoorName but now it seem to be okay again.

Best

Daniel

**Comment by reszelaz** [comment]
The environment is stored in a shelve file. By default it is in `/tmp/tango/MacroServer/<instance_name>/macroserver.properties`. In some OS the `/tmp` is deleted on reboot, for example on Debian it is (I think this can be configured). 
You can change this location with the `EnvironmentDb` property of the MacroServer.
Sorry about the inconveniences.

**Comment by dschick** [comment]
Okay, I'll try that. Thank you so much

reszelaz <notifications@github.com> schrieb am Fr., 6. Juli 2018, 16:33:

**Comment by dschick** [comment]
it is actually 
/tmp/tango/Sardana/<instance_name>/macroserver.property

**Comment by reszelaz** [comment]
Oh yes! It depends on the server architecture that you use. If you run just the Sardana server it is as you say. If you run Pool and MacroServer separatelly, it is the previous path.

Good that you found it!

**Comment by dschick** [comment]
okay, now I got it working by setting the EnvironmentDb to:
`/home/<username>/.Sardana/<instancename>/macroserver.properties`
I just saw that the macroServer logs are also saved under /tmp
In case of a restart /crash the would be gone then as well.
How can one change the folder for logging?

Best

Daniel

**Comment by reszelaz** [comment]
I'm afraid there is no such configuration yet. But it makes sense to add it.

**Comment by dschick** [comment]
okay, then I will close this issue but raise a new one for documentation and setting general configuration of Sardana
