### ISSUE TITLE
Macro help in spock shows wrong file location

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#817]
Spock macro's help e.g. `ascan?` show the path to the file where the magic command is defined e.g. `~/workspace/sardana/src/sardana/spock/spockms.py`. This does not add information to the user and even may be confusing.

Alternative options: 
* show the path to the macro module
* don't show any path

**Comment by reszelaz** [comment]
Seems like we would need to [modify the read only attribute](https://stackoverflow.com/questions/24497316/set-a-read-only-attribute-in-python) called: `func_code.co_filename` of the macro magic command functions.

**Comment by julianofjm** [comment]
It is necessary to monkey patch ipython Inspector object (`IPython/core/oinspect.py`).
For now we create a warning message to alert about the wrong path.
