### ISSUE TITLE
Docs: Spock magic commands 

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#818]
Spock magic commands are not documented. The magic commands are:
'expconf', 'showscan', 'spsplot', 'debug', 'www', 'post_mortem', 'macrodata', 'edmac'

**Comment by reszelaz** [comment]
I propose to:
1. Add section "Debugging problem" in the Spock chapter that would describe: debug, www and post_mortem.
2. Add link from the Spock chapter to the expconf documentation.
3. Add section "Accessing macro data" in the Spock chapter that would describe macrodata.
4. Add section "Editing macros" in the Spock chapter that would link to the Writing macros chapter (bidirectional link) and somehow to the Sardana editor widget.
5. spsplot could

Furthermore it should be evaluated if it is possible to autogenerate the magic commands docs and put the majority of information in the docsting and only referring to them from the Spock chapter.

**Comment by teresanunez** [comment]
PR done

**Comment by cmft** [comment]
@teresanunez you pushed an extra commit for another topic
