### ISSUE TITLE
Docs: macro logging and macro report

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#819]
Macro logging (#480) and macro report features are not documented. It is only documented [how to report from a macro](http://www.sardana-controls.org/en/latest/devel/howto_macros/macros_general.html#reports).

**Comment by reszelaz** [comment]
This could be added as a separate chapter in the User's Guide, between "Environment variable catalogue" (new) and "Screenshots".

**Comment by reszelaz** [comment]
You mean:

- ...
- Adding real elements
- Macro Hooks
- Macro Environment
- **Macro Logging**
- Environment Variable Catalog
- Standard macro catalog
- Configuration
- Screenshots

?

**Comment by teresanunez** [comment]
Yes

**Comment by reszelaz** [comment]
Thats fine! Thanks!

**Comment by teresanunez** [comment]
I have created a PR #878 for the macro logging part.

**Comment by teresanunez** [comment]
The report part is also added to #878
