### ISSUE TITLE
Docs: Taurus extensions are not documented

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#825]
Taurus extensions are very important part of the Sardana API. For example these are interfaces to the Sardana objects when used wihin macros. We should autodocument this part of the API.

Furthermore we could add a short section to "Writing macros" chapter. It could be called "How to access to pool elements". This section should explain about the possible getters e.g. getMotor, getController, about the returned objects i.e. Taurus extensions. and finally point to the autogenerated API

**Comment by teresanunez** [comment]
Continue in PR #881
