### ISSUE TITLE
Migrate docs from RTD to Travis

### ISSUE THREAD

**Issue by cpascual** [sardana-org/sardana#826]
Migrate the doc auto-buid and publication from readthedocs to Travis.
See why and how Taurus did it in: taurus-org/taurus#572

Tasks:

- [x] build docs from travis and deploy them to github (implemented in #830)
- [x] change the sardana-controls.org domain to point to https://sardana-org.github.io/sardana-doc/ and configure the sardana-doc gihub pages accordingly
- [x] add links to other doc versions (implemented in #842)

**Comment by cpascual** [comment]
I created the a PR implementing this: #830

**Comment by cpascual** [comment]
I implemented the final steps of the move in PR #842

**Comment by reszelaz** [comment]
I think this is done already. Closing...
