### ISSUE TITLE
qdo implementation

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#832]
I havn't used the `edmac `feature too much so far but I was first wondering if #574 is already resolved?
My main issue is, that I would like to differenciate between general macros I am adding to Sardana which should be located in one of the MacroPath directories.

However, when a "user" wants to write a short scan-macro which is just a sequence of scans, etc. I do not want that to be written in the same folder as the other general macros.
So I could create another folder for such macros and then `edmac `should control which folder to use.

Another way, would be the SPEC macro `qdo`, wich simply accepts an absolute or relative path to a macro file and load its content into the SPEC session (temporally).
This allows also to load macros which are in the current working directory of spock.
I learned, that the host of the macroServer and the host of the spock session must not be identically, however, I was wondering if one could inject a macro from a local file into the macroserver temporally?

**Comment by reszelaz** [comment]
> I havn't used the edmac feature too much so far but I was first wondering if #574 is already resolved?

I doubt that it is solved.


> However, when a "user" wants to write a short scan-macro which is just a sequence of scans, etc. I do not want that to be written in the same folder as the other general macros.
So I could create another folder for such macros and then edmac should control which folder to use.

Yes, this sounds to me like the *Sardana way* of doing such thing.

> Another way, would be the SPEC macro qdo, wich simply accepts an absolute or relative path to a macro file and load its content into the SPEC session (temporally).

> This allows also to load macros which are in the current working directory of spock.
I learned, that the host of the macroServer and the host of the spock session must not be identically, however, I was wondering if one could inject a macro from a local file into the macroserver temporally?

`edmac` is actually running on the client side and edits a temporary file populated with contents - either an existing macro or a template. Whenever the user ends edition and applies the changes its content is send to the server.

If I understands correctly, the `qdo` would just read the file content on the client side and then send it to the server the same way as `edmac` does it? This however would not be temporary, cause the macro module file would be created on the server side... Temporariness could be partially achieved by inserting a `MacroPath` dynamically, and not storing it in the Tango property. This way, the next time server is restarted the macros won't be loaded. But the file would be stored in the file system anyway.

I doubt that with the current *plugin system* that we have for macros, which is based on files and inspecting them after an import, we would be able to avoid the file creation on the server side. I mean without big development...

**Comment by dschick** [comment]
thanks  @reszelaz for your comment.
So I will wait till #574 is going to be solved.

Best

Daniel

**Comment by dschick** [comment]
I just found a nice workaround for the qdo implementation in the [Solaris macros](https://github.com/synchrotron-solaris/lib-solaris-facility-macros/blob/develop/facility_sequence.py)
They just parse strings in the CLI or from text files which are stored at the client side PC, e.g. in a user directory.
This actually allows to write simple sequences into the txt file simlar to SPEC macros:
```
wu
ascan mot1 0 1 01 1
ct
...
```
Although the repeat macro might be supported as well, more complex macros with looping over some array values seem not to be possible, or am I'm wrong @daneos ?

**Comment by daneos** [comment]
@dschick, regarding the repeat macro, we also have the `rep` macro which is used for simple repeats, but I'm afraid it's not compatible with `umacro` (I have not tested it, I know that nesting `rep` inside `seq` and vice versa doesn't work, and `umacro` is very similar to both of these).
This solution doesn't support any advanced features, it just executes the list of macros from the file.

Also, keep in mind that `MacroDir` should point to the directory on the server - we are using it on client machines via NFS share.

**Comment by dschick** [comment]
just for closing this issue, I am currently using the ipython parser directly to write user macros, thanks to a hint from @reszelaz and @guifrecuni .

so I can either run a sequence in spock or load a script via `%run mymacro.ipy` containg the macro.
Here is an example looping over a list:

```
positions = [0,1,2,3,4,5]
for pos in positions:
    %umv mot1 $pos
    %ascan mot2 0 1 10 1
```
With that I am pretty fine and thanks to all your comments.
