### ISSUE TITLE
Sardana does not allow to have a stateless exp. channel 

### ISSUE THREAD

**Issue by cmft** [sardana-org/sardana#870]
Sardana does not allow to have a stateless exp. channel  linked to another channel involved in the same measurement group.  The acq. loop never stop.

**Comment by reszelaz** [comment]
Just to add more information. The acquisition action leaves the loop only if there are no more channels in Moving state. If one depends on the other it indeed gets stuck.

**Comment by cpt-majkel** [comment]
@cmft closing for now. Please reopen providing more details or an example.
