### ISSUE TITLE
timescan problems

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#883]
I have to issues with the timescan:

1. with my default measurement group I cannot start a timescan with the message
`Measurement group mokeMntGrp is not compatible with timescan`
what does that actually mean?

2. when I do have my general hooks applied to the pre-acq and post-scan hook places I get the error:
`Error: argument of type 'NoneType' is not iterable`
The pre-acq hook is actually only reading env parameters

**Comment by reszelaz** [comment]
> Measurement group mokeMntGrp is not compatible with timescan
what does that actually mean?

Not all experimental channels are compatible with continuous scans, `timescan` was implemented using the same principles hence the same limitations applies: https://github.com/sardana-org/sardana/blob/4ac2a229f902f257aa729dbab60046f1d870c1d8/src/sardana/macroserver/scan/gscan.py#L1922
Hopefully in the near future we will overcome this limitation.

> when I do have my general hooks applied to the pre-acq and post-scan hook places I get the error:
Error: argument of type 'NoneType' is not iterable

I will check it later.

**Comment by reszelaz** [comment]
#885 is already integrated. I'm closing this one.
