### ISSUE TITLE
Random errors on MacroServer startup

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#898]
This was observed at BL29 at ALBA.
From time to time, the MacroServer reports the following error on startup and it is not operable anymore:
```
MainThread     INFO     2018-08-07 17:40:12,197 TaurusRootLogger: Ready to accept request in 0:00:08.880166
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' in <type 'exceptions.AttributeError'> ignored
```

**Comment by reszelaz** [comment]
Thanks for the report!

For me these looks like different problems. But the one that you describe was mentioned some time ago by @daneos. I'm not sure if there is an issue for that created. @dschick do you know how to reproduce this problem? Maybe there was some problem with the Pool? Could it be that it crashed? Or there was some network issue meanwhile? The `API_EventTimeout` makes me think so.

**Comment by dschick** [comment]
hej @reszelaz ,

I am currently trying to reproduce the error I reported. Actually the pool (and Tango DB) run on the same host as Sardana+Spock. So I guess it is no network issue.
I am also checking if this error is related to the hack I did, mentioned in #1010 
```
from sardana.taurus.core.tango.sardana.pool import registerExtensions
registerExtensions()
```

what would be the best way to debug that error? it is pretty annoying and slows down the setup substancially.

Shall I move that to a new issue?

**Comment by reszelaz** [comment]
> I am also checking if this error is related to the hack I did, mentioned in #1010

I doubt this. We also saw the same "maximum recursion depth exceeded while calling a Python object" in spock and we do not use the *extensions* in our controllers. 

> what would be the best way to debug that error?

For the moment no idea. I will analyze in deep the `TangoDevice` (taurus) class. The recursion error comes from there...

> it is pretty annoying and slows down the setup substancially.

What do you mean? From our experience it is a "one time error" in spock and it does not affect the performance.

**Comment by reszelaz** [comment]
> Shall I move that to a new issue?

Yes, I think it deserves a separate issue.

**Comment by reszelaz** [comment]
I let myself open #1035 just to be able to refer to it in the taurus project.

**Comment by reszelaz** [comment]
@jairomoldes, I let myself close this issue. It was observed with old versions of Sardana and Tango 7. Please re-open if you found it again with Sardana  3.  Thanks!
