### ISSUE TITLE
Jul18 manual release tests: openSuse 11.1

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#901]
This issue is created for reporting the results of the manual tests for Jul18 release on debian-stretch.
Tested on openSuse 11.1.

### Installation
- [x] Install Sardana from the tar.gz : `pip install <tarball_artifact_URL>`
**Note:**  There was no pip on the machine
Installed with: `tar -xzvf sardana-2.5.0.tar.gz;
python setup.py install --prefix=/tmp/sardana_2.5.0/install --root=/`

### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
**Note:** I should remove lxml from requires
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `PyTango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
- [x] In spock run `sar_demo` macro.
**Note:** Problem https://github.com/sardana-org/sardana/issues/395. Change model name to demo_macros.py
- [x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [x] Run testsuite. In another console do `sardanatestsuite`
**Note:** Change report macro code from function to class, because sardanatestsuite did not find it.
The testsuite fails [output](https://gist.github.com/rhomspuron/cf3347cd0088970da009f87c0bff0598), but I ran the tests by hand and they worked fine:
` FAILED (failures=1, errors=3, skipped=10, expected failures=1)`

### Test Sardana using Spock
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
**Note:** Change macros code from function to class
- [x] Execute `umvr` macro and verify that the position updates arrives.
- [x] Test `expconf`:
  1. Configure scan files using expconf set ScanDir to: `/tmp/` and
     ScanFile to: `demo1.h5, demo1.dat`.
**Note**: I should change the h5 to use: NXscan_FileRecorder
  2. Configure online plot to show counters: On expconf GUI select for all the counter channels, Plot Type 'Spectrum' and Plot Axes '\<mov\>'
  3. Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
     attribute.
  4. Add the `sys/tg_test/1/double_scalar` attribute to the measurement
     group.
  5. Open online plot.
  6. Set JsonRecorder to true. In spock do `senv JsonRecorder True`
  7. Run step scan and verify if:
     - Records appear in spock output.
     - Records were stored in scan files.
     - Records were plotted on the online plot

- [x] Run `showscan` and access to the last scan data.
- [x] Test `edmac`:
  1. Modify existing macro: `ask_peak` and run it to verify that the change
     was applied.
  2. Create new macro in a new macro library:
     `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py
     and run it.

### Test Sardana with TaurusGUI

- [x] Create the GUI using this [guide](https://sourceforge.net/p/sardana/wiki/Howto-GUI_creation)

#### PMTV (PoolMotorTaurusValue)
- [x] Move motors from the slit panel in absolute and relative modes.
- [x] Show expert view.
- [x] Show compact mode.

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [x] Start new sequence
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### sardanaeditor
**Note:** There is not spyder3 for OpenSuse11.1
- [ ] Open sardanaeditor with macroserver name as argument.
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by rhomspuron** [comment]
Results are satisfactory and there are not news.
