### ISSUE TITLE
Jul18 manual release tests: CentOS 7

### ISSUE THREAD

**Issue by daneos** [sardana-org/sardana#903]
This issue is created for reporting the results of the manual tests for Jul18 release on CentOS 7.

### Installation
- [x] Install Sardana from the tar.gz : `pip install <tarball_artifact_URL>`

### Create testing environment and run testsuite
- [x] Start Pool demo2. In a console do `Pool demo2`.
- [x] Start MacroServer demo2 and connect to the Pool demo2.
  In another console do: `MacroServer demo2`
- [x] Set MacroServer's MacroPath to point to the macro examples.
  In another IPython console do:
  `PyTango.DeviceProxy('macroserver/demo2/1').put_property({'MacroPath':'<path_to_sardana_installation_dir>/macroserver/macros/examples'})`
- [x] Restart MacroServer e.g. Ctrl+C in the MacroServer's console and
  start it again.
- [x] Create spock profile demo2. In another console do `spock --profile=demo2`
- [x] In spock run `sar_demo` macro.
- [x] Edit `<path_to_sardana_installation_dir>/sardanacustomsettings.py`
  to point to the demo2 door e.g. `UNITTEST_DOOR_NAME = "door/demo2/1"`
- [x] Run testsuite. In another console do `sardanatestsuite`

### Test Sardana using Spock
- [x] Test interactive macros from spock e.g. `ask_for_moveable`, `ask_peak`
- [x] Execute `umvr` macro and verify that the position updates arrives.
- [x] Test `expconf`:
  1. Configure scan files using expconf set ScanDir to: `/tmp/` and
     ScanFile to: `demo1.h5, demo1.dat`.
  2. Configure online plot to show counters: On expconf GUI select for all the counter channels, Plot Type 'Spectrum' and Plot Axes '<mov>'
  3. Configure snapshot group: with a motor and the `sys/tg_test/1/ampli`
     attribute.
  4. Add the `sys/tg_test/1/double_scalar` attribute to the measurement
     group.
  5. Open online plot.
  6. Set JsonRecorder to true. In spock do `senv JsonRecorder True`
  7. Run step scan and verify if:
     - Records appear in spock output.
     - Records were stored in scan files.
     - Records were plotted on the online plot
- [x] Run `showscan` and access to the last scan data.
- [x] Test `edmac`:
  1. Modify existing macro: `ask_peak` and run it to verify that the change
     was applied.
  2. Create new macro in a new macro library:
     `edmac my_macro <path_to_sardana_installation_dir>/macroserver/macros/examples/my_macros.py
     and run it.

### Test Sardana with TaurusGUI

- [x] Create the GUI using this [guide](https://sourceforge.net/p/sardana/wiki/Howto-GUI_creation)

#### PMTV (PoolMotorTaurusValue)
- [x] Move motors from the slit panel in absolute and relative modes.
- [x] Show expert view.
- [x] Show compact mode.

#### macroexecutor
- [x] Execute `ascan` macro
- [x] Pause it in the middel and resume
- [x] Abort it
- [x] Add it to favorites
- [x] Run `lsm` macro
- [x] Execute `ascan` from favorites
- [x] Run `lsmac` macro
- [x] Execute `ascan` from history
- [x] Edit `dscan` macro in spock yellow line and run it
- [x] Restart macroexecutor application
- [x] Run `lsm` from history
- [x] Run `ascan` from favorites

#### sequencer
- [x] Add `ascan` macro to the sequence
- [x] Add `lsct` macro as a `post-acq` hook of `ascan`
- [x] Add `dscan` macro to the sequence
- [x] Run the sequence
- [x] Save sequence to a file
- [ ] Start new sequence
- [x] Load sequence from a files
- [x] Run the loaded sequence

#### sardanaeditor
- [ ] Open sardanaeditor with macroserver name as argument.
- [ ] Browse macro libraries and open an existing macro.
- [ ] Edit existing macro and save & apply chaneges.
- [ ] Execute macro to see if changes were aplied.
- [ ] Create a new macro using template.
- [ ] Execute the newly created macro.

**Comment by daneos** [comment]
Problems found during testing:
* MacroServer depends on Qt bindings and qtpy, this makes a little sense on a headless server installation. I'm not sure about previous release but version 2.3.2 certainly didn't require Qt on the server.
* Test suite has 3 failed tests https://gist.github.com/daneos/02e4268cfb9496cfe84d340c6f354a84
* After executing testsuite I needed to restart MacroServer in order to execute umvr, otherwise it would just freeze
* sequencer: New sequence button doesn't work (I think I've seen this issue before)
* sardanaeditor requires spyder, spyder requires pylint, pylint requires Python 3.4

I think none of these is critical, but the testsuite errors require attention, and sardanaeditor is not usable.

**Comment by reszelaz** [comment]
Many thanks for the tests!

> MacroServer depends on Qt bindings and qtpy, this makes a little sense on a headless server installation. I'm not sure about previous release but version 2.3.2 certainly didn't require Qt on the server.

We need to investiage this one. Could you please provide the error messages?

> Test suite has 3 failed tests https://gist.github.com/daneos/02e4268cfb9496cfe84d340c6f354a84

These tests are pure performace tests. Their results may fail on *slowly* behaving machines. I'm not affraid about these.

> After executing testsuite I needed to restart MacroServer in order to execute umvr, otherwise it would just freeze

Yes, it is a known issue. I will add it to the manual tests documentation.

> sequencer: New sequence button doesn't work (I think I've seen this issue before)

Could it be #305?

> sardanaeditor requires spyder, spyder requires pylint, pylint requires Python 3.4

I suppose you were installing with pip? I have spyder from debian (stretch) packages and it is python 2 package. Could you then ask on the spyder project? I saw that they support python 2.7.

> I think none of these is critical, but the testsuite errors require attention, and sardanaeditor is not usable.

I agree. I'm even more affraid of the first issue. But let's see in details the error messages.

**Comment by daneos** [comment]
> We need to investiage this one. Could you please provide the error messages?

Here's the traceback from starting the MacroServer on clean VM:
https://gist.github.com/daneos/fd88c73af209c1bdabb9aa71b482c15f
And here with PyQt4 but no qtpy:
https://gist.github.com/daneos/b6f08014e579e20cbe99dc9a1e5d7a1d
It seems that MacroServer imports things from Spock which in turn tries to import Qt from Taurus.

> These tests are pure performace tests. Their results may fail on slowly behaving machines. I'm not affraid about these.

OK, my VM may run slowly, I had several other VMs running while performing the tests.

> Could it be #305?

I'm not sure if the problems are exactly the same, I'll check that tomorrow.

> I suppose you were installing with pip? I have spyder from debian (stretch) packages and it is python 2 package. Could you then ask on the spyder project? I saw that they support python 2.7.

Yes, I tried to install spyder with pip. I'll check if CentOS has spyder in its packages, but I doubt that. Even if so, it most probably won't be >=3. Maybe some older version has Python 2.7 support?

**Comment by reszelaz** [comment]
> Here's the traceback from starting the MacroServer on clean VM

Yeap, traces clearly point to a bug (some wrong modules/import management). Ive checked the changelog and i doubt that it was introduced in this release. Could you check that with Jan18 release? No need to run it with clean env, on a devel env with some prints in modules you should be able to check that. If it was already there I propose to just report it, if not we could try to fix it.

Regarding the spyder issue, could you as in their project? On the webpage they say that python 2.7 is supported.

Many thanks!

**Comment by daneos** [comment]
I checked the Qt issue on 2.4.0 and it also requires the Qt bindings to be installed. I must've been testing the previous release on a GUI-enabled machine if I didn't notice this problem then.

The sequencer problems are exactly #305.

I checked CentOS repos for spyder and unfortunately version 2.3.7 is available while sardanaeditor requires >=3. I have created the [issue in Spyder project](https://github.com/spyder-ide/spyder/issues/7661).

**Comment by reszelaz** [comment]
From the checklist I see that centos tests are satisfactory for the release. @daneos do you agree?

**Comment by daneos** [comment]
I guess we won't be able to do much more until we get a response from Spyder people.
I'm closing this issue then and marking CentOS as done in the PR.

**Comment by daneos** [comment]
From what I learned from Spyder, the issue is specific to SOLARIS environment (old pip), however after installing spyder with pip 18.0 I get the same error message as in #909. This is the same problem I noticed on both [Debian 9](https://github.com/sardana-org/sardana/pull/711#issuecomment-370470040) and [CentOS 7](https://github.com/sardana-org/sardana/pull/711#issuecomment-371190433) in Jan18 release.
