### ISSUE TITLE
Stopped at creating pool [Student seeking help] (SF#145)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#91]
Hello!
As I found no other place where to seek help regarding Sardana I'll try here.

I've installed sardana on CentOS and am facing a problem.
Running Pool from command line works, but if I run Sardana or MacroServer it stops at
"creating pool ..." debug message.

Reported by: [juvanjan@SF](http:/sf.net/u/juvanjan) ( http://sf.net/u/juvanjan )

Original Ticket: [sardana/tickets/145](https://sourceforge.net/p/sardana/tickets/145)

**Comment by dschick** [comment]
Hej,

I actually encountered the same problem.
On Linux Sardana starts without problems with the following version numbers installed:
- tango 9.2.2
- taurus 4.3.1
- Sardana 2.4.0

But on Windows (10) Sardana stops when creating the pool. Starting the Pool and the Macroserver by hand and then running Spock is also fine, but I guess it would be nice to figure out, why Sardana is not starting up correctly. I installed the following versions on the Win machine:
- tango 9.2.1
- taurus 4.3.1
- Sardana 2.4.0

Best 

Daniel
