### ISSUE TITLE
pool server inaccessible

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#915]
Hej,

I just upgraded to latest version of the develop branch and now the pool is inaccessible, with the following error after starting Sardana:

```
MainThread     DEBUG    2018-08-14 10:08:28,786 TaurusPollingTimer[3000].Timer on _pollAttributes: Timer::stop()
TaurusTSP.W001 WARNING  2018-08-14 10:08:28,787 epics-archiver.hhg.lab:10000.pool/moke/1: Received elements error event Pool was shutdown or is inaccessible
TaurusTSP.W001 DEBUG    2018-08-14 10:08:28,787 epics-archiver.hhg.lab:10000.pool/moke/1: DevFailed[
DevError[
    desc = Device dserver/sardana/moke is not exported (hint: try starting the device server)
  origin = DeviceProxy::get_corba_name()
  reason = API_DeviceNotExported
severity = ERR]

DevError[
    desc = Failed to execute command_inout on device dserver/sardana/moke, command ZmqEventSubscriptionChange
  origin = Connection::command_inout()
  reason = API_CommandFailed
severity = ERR]

DevError[
    desc = Device server send exception while trying to register event
  origin = EventConsumer::connect_event()
  reason = API_DSFailedRegisteringEvent
severity = ERR]
]
```

In jive the pool is actually accessible and I can read its attribute and can restart it, etc.

Any idea what is going wrong here?

**Comment by teresanunez** [comment]
Hi @dschick, are you working in Linux or Windows?, and how are you starting Sardana, as a whole
with Sardana ?. If it is so you can try (as a Test) to start Pool and MacroServer separately.

**Comment by dschick** [comment]
hej @teresanunez , I am working under Linux and I can try starting the thing separately for debugging, but then Sardana will create a new Pool and I cannot use the existing one, right?

**Comment by teresanunez** [comment]
Hi @dschick, yes, only try separately for testing if it works and the problem is due to starting with
the Sardana script.

**Comment by teresanunez** [comment]
Hi @dschick, I have just tried with the Sardana script, starting Pool and MacroServer together and I do not see any problem. It is running for me. And also spock.

**Comment by teresanunez** [comment]
I do get this warning:

TaurusTSP.W001 WARNING  2018-08-14 11:59:58,535 hasp029rack.desy.de:10000.Pool_demo3_1: Received elements error event Pool was shutdown or is inaccessible

But it is harmlos ... as I can see, everything works.

**Comment by dschick** [comment]
okay, so starting Pool and MacroServer separately works for me as well.
However, Sardana command give the same error as before even when I create a new Pool/MacroServer/Door like
`Sardana test`
The wired thing is, that during startup of Sardana it connects to all hardware and reads the macros as usual. So the connection to the server is obviously there.

**Comment by dschick** [comment]
it's pretty wired but after reverting the local sardana repo via git and reapplying the new changes of the 2.5 branch everything works now.
anyway, thanks a lot @teresanunez for the quick response
