### ISSUE TITLE
trend and expconf get stuck

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#917]
Currently I have big issues with the expconf and trend window.
The trend only plots one or two scans and then gets stuck/unresponsive.
I need to "force quit" it and then also the expconf closes.

I have newest Sardana version installed from the develop branch and the newest Taurus version from pip on a Linux Mint 19 machine.

Does anyone has similar problems?

Best

Daniel

**Comment by teresanunez** [comment]
Hi @dschick, where do you see the trends in expconf?, you open it independently, don't you?. Or are you talking about 'taurusgui macrogui'?.

**Comment by dschick** [comment]
hej @teresanunez I normally open the trend from the expconf which I start from spock.
I just tried with a taurusgui that contains also both elements and I get similar problems, especially when I start changing the plotted channels it get stuck.
Does this maybe connects to #882 ?

**Comment by dschick** [comment]
I just reverted the commit from #882 and run a taurusgui connected to my sardana session with expconf and trend included.
I also have a trend in this gui. If I do not run any scan from within spock, the taurusgui runs completely fine.
Then I tried running 10 ascans from spock and the taurusgui always freezes after like 4 or so repeats.

Maybe one should move that issue to taurus ...

**Comment by teresanunez** [comment]
Hi @dschick, it could be ... I am not able to reproduce it in my computer ...

**Comment by teresanunez** [comment]
Hi again, we were writing at the same time ... perhaps @cpascual has some ideas about what can be going wrong.

**Comment by dschick** [comment]
I will try to run the taurustestsuite in the meantime and also the sardanatestsuite.
Maybe one gets some information from these

**Comment by cpascual** [comment]
Hi, I'll try to see if I can reproduce. 

In order to help me in reproducing, could you please give some step-by-step instructions on how to reproduce (e.g., mentioning what you plot, and how you configure the plot, etc.)

Also it would be extra-helpful if you could reproduce it within the [taurus-test docker container](https://github.com/cpascual/taurus-test), so that we can rule-out network/installation/config differences

**Comment by dschick** [comment]
uff, I can try next week, but actually I am simply plotting a counter in an ascan from spock and then expconf/trend/taurusgui freezes. As I said, above I reverted any changes from #882 and I am just running some pre/post-scan macros which do nothing with Taurus in the ascan. The rest of the configuration is just the Sardana develop branch on Linux Mint.
And of course all my Controllers and Macros which can be found here: www.github.com/dschick/sardanaControllers www.github.com/dschick/sardanaMacros

Can I somehow check the network connectivity with my TangoServer which is on another machine in the same network?
For the taurusgui there is also no error message in the terminal wih debug loglevel.

**Comment by dschick** [comment]
I can try it also with a test door and sar_demo and see if it hangs there as well

**Comment by cpascual** [comment]
> I can try it also with a test door and sar_demo and see if it hangs there as well

That would help. Try to reproduce the problem without custom controllers or pre/post scan macros... just counters and motors from sar_demo

> Can I somehow check the network connectivity with my TangoServer which is on another machine in the same network?

not sure what kind of tests you have in mind... you can always use jive or PyTango to check if the sys/database/2 is responsive, and how long it takes to respond to a ping...

**Comment by dschick** [comment]
so here is the output from taurustestsuite which looks fine: 
https://gist.github.com/dschick/284e503405583db75ee1e805d601c2da#file-gistfile1-txt
and from the sardanatestsuite which shows several errors also related to zmq:
https://gist.github.com/dschick/6761d40b88c0aaf2b9290b72aa45bb6e#file-gistfile1-txt

**Comment by dschick** [comment]
using sar_demo with a fresh door seems to work fine.
I am doing 100 ascans in a loop using all available counters and at Nb. 25 the expconf and trend window are still fine.

So I can try disabling my hooks and then also checking my controllers one by one I guess.

Anything else from your side?

**Comment by dschick** [comment]
few more observations:
as I said, I can run 100 ascans with a fresh sar_demo environment using the develop branch without any problems with the trend and expconf.
When I try to the same but with my personal branch "moke" (see the differences here: https://github.com/sardana-org/sardana/compare/develop...dschick:moke) the trend window agains freezes after some time.
I guess the main difference is the PR #882 in my branch but I can test that next week in more detail.

The freezing actually happens sometimes abruptly and sometime more gradually - meaning that first the trend is a bit delayed, then the delay increases until it is stuck.

I will further check if any of my controllers or hooks are responsible for the freezing in addition to #882.
In any cases - spock is always responsive and the connection to the Door seems always to be finde from it.

**Comment by cpascual** [comment]
> So I can try disabling my hooks and then also checking my controllers one by one I guess.

Yes, that is the way to go...

> Anything else from your side?

Just one thing: you could check if the problem still occurs when instead of using expconf to plot the scans, you use a taurustrend directly.

In order to do this, open a new console and runt he following:
`taurustrend scan://DOORNAME`

where DOORNAME is the alias or the tango name for your door device.
Then just launch the scan(s) from spock as usual, but without opening expconf.

**Comment by dschick** [comment]
hej @cpascual , I just tested with a new branch https://github.com/dschick/sardana/tree/testtaurus which merged only the #882 into the latest development branch.

When I start the `trend` from the `expconf` I still observe the freezing.

In case I work with only the develop branch w/o #882 OR I use `taurustrend scan://DOORNAME` for starting the trend (including #882 ), it is not freezing.

Both cases are for a fresh test environment with `sar_demo`

**Comment by dschick** [comment]
in case I run sardana with real hardware and hooks but without #882 :+1: 
the trend again freezes when started from the expconf but `taurustrend scan://DOORNAME` works nicely again.
I will also try to test which hook/macro/controller in my door causes the freeze compared to the `sar_demo` test

**Comment by rhomspuron** [comment]
We found the bug on expconf see #882.

**Comment by dschick** [comment]
@rhomspuron thanks a lot! 
Some initial testing seems to work well with my real-world configuration.
I will test in more detail during the next days and if all tests are positive close this issue

**Comment by dschick** [comment]
I was running scans all night long and it was not freezing!
Thanks for solving that bug!

**Comment by cpascual** [comment]
> Thanks for solving that bug!

Thank you for spotting and reporting!

**Comment by rhomspuron** [comment]
>  Some initial testing seems to work well with my real-world configuration.
I will test in more detail during the next days and if all tests are positive close this issue

Great! Thank you for test it!
