### ISSUE TITLE
pre-scan hook execution place

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#920]
I added a simple `wu `as a `pre-scan` hook. But when I start an `ascan `there will be always first the column header of the scan counters plotted, then the pre-scan hook output, and the the scan data.
For convinience, I would suggest, that the pre-scan hook is executed before any output created by the default scan routines.

**Comment by cmft** [comment]
I agree. The pre-scan hook should be executed before start the scan_loop.

**Comment by cmft** [comment]
Hi @dschick,
I proposed a PR but I have my doubts about its integration. Since I could not find documentation about this hook and neither about the execution flow, and technically the pre-scan hooks are executed before the scan action, so lets wait the experts opinion.

Could you try the PR?

**Comment by dschick** [comment]
Hi @cmft ,
Thanks for creating the PR.
It seems to work as expected, at least the text output of the scan (scan header) is now printed after my pre-scan hook outputs.

**Comment by reszelaz** [comment]
Another solution was proposed in #933.
