### ISSUE TITLE
Decouple expconf from showscan online

### ISSUE THREAD

**Issue by cmft** [sardana-org/sardana#960]
If the trend (of the show scan online) is launched and the configuration of the ExpConf (from where it was launched) has changed, the trend is move to "background" (do not have the focus) like the ExpConf widget, but it reacts to any configuration change from others clients (e.g. another ExpConf).  So, IMO this "subwidget" should not be put in "background"

**Comment by reszelaz** [comment]
The dialog that warns about conifuration dialog is of *modal* type.

From Qt documentation:
> A modal dialog is a dialog that blocks input to other visible windows in the same application.

So the current behavior is correct according to the current design of the expconf and scan trends.
However the original design was assuming both tools as separate. The scan trends were opened with a separate command "showscan online". IMHO we should go after the original design which would automatically fulfill with your request.

So I change the subject to: "Decouple expconf from showscan online".
