### ISSUE TITLE
Add autoupdate checkbox to expconf 

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#961]
Now the expconf by default warns with a pop-up about the configuration changes coming from the server.
User may want to autoupdate the expconf with this changes.

This is now possible from spock if the expconf was started with the `--auto-update` flag.

However it would be more convenient to be albe to enable/disable auto update feature at runtime, for example, with a checkbox.

**Comment by dschick** [comment]
I totally agree, especially when the expconf is started from the taurus gui, it is a bit harder to add the --auto-update flag, I guess

**Comment by cpascual** [comment]
Also, this option should be a "configurable property" so that its value is remembered between runs of the GUI

**Comment by reszelaz** [comment]
Solved in #1028
