### ISSUE TITLE
scanID and pointNb in controller

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#979]
Hej all,

I have written a camera Ctrl class that connects to a TPC/IP Server of a CCD camera and starts acquisitions, reads the status, and reads some RIOs.

Now I would like to start every acquisition with a command like ACQUIRE #scanID #pointNB if the acquisition is launched from a scan and something like ACQUIRE -1 if it is launched from a ct command.

All this requires the following in the StartOne method:
* comes the call from a scan or single ct command
* if it is a scan, what is the current scanID (I need to acces the env) 
* what is the current pointNb of the scan

Are there any solutions to this?

The idea behind all this is, that the camera saves its image files according to the Sardana spec file.

Thanks in advance

Daniel

**Comment by teresanunez** [comment]
Hi Daniel,
                  this information is not there, the controllers are in the Pool and spock is connected to the
 Door (access to MacroServer).
We had many times the need of this kind of information, but we implemented for each case some
 kind of workaround.

                                 Regards,
                                                Teresa

**Comment by droldan** [comment]
Hi Daniel,

Maybe the SEP18 could provide _some_ of your requirements.

https://github.com/sardana-org/sardana/pull/773


Regards, Dani.

**Comment by reszelaz** [comment]
@dschick we plan to solve all these limitations with [SEP18](https://github.com/sardana-org/sardana/pull/773) (already pointed by @droldan) and [SEP2](https://github.com/sardana-org/sardana/pull/775). SEP18 is almost ready to be evaluated and voted. SEP2 has some brainstorming ideas written in the PR comments.

In general the idea is: if the controller writes data to a file (or any other persistance storage) it will report the URI of the data, and this URI (not the data) will be stored by the recorder (SPEC, H5, etc.). As the result the data will be tracable from the Sardana scan file. Of course we want to leave the possibility that Sardana will finally store the data (using the recorder). This is basically how the 1D and 2D controllers works today - so we will not remove this feature.

I think, with all these, it is not necessary that the controller knows if it is invoved in a scan, what is the scan id, or the scan point number. IMHO it is a good design idea to isolate the controller from this information. However, with SEP18, we will let the controller know that it will be part (prepared) for a measurement composed for a series of starts.

If you have other opinion respecting this, or would like to add more requiremenets to SEP18, SEP2 we would be happy to hear it. Thanks a lot in advance!

**Comment by dschick** [comment]
thank you all for your answers.
I agree that reporting the URI of the data from the controller to Sardana is working just as well as my proposal. 

Just a general question: how would you save the URI in the SPEC file, as it only allows numbers and not strings in the scan data? For the hdf5 this should be no problem.

As SEP18 and SEP2 are not finished yes, I would simply save the images from the controller using a timestamp and/or unique hash and then report this together with the actual data to Sardana and save it to the SPEC file. I guess this would be a sufficient workaround.

Best

Daniel

**Comment by reszelaz** [comment]
> Just a general question: how would you save the URI in the SPEC file, as it only allows numbers and not strings in the scan data? For the hdf5 this should be no problem.

Good point! I didn't know about it. Let's see if we can find a workaround... We will post the further information about this in the SEP2 PR comments.

> I would simply save the images from the controller using a timestamp and/or unique hash and then report this together with the actual data to Sardana and save it to the SPEC file. I guess this would be a sufficient workaround.

Let's see if I understood it well:
Your hardware (or a piece of control software handling the detector e.g. Lima) will store the images into a separate files which names will be composed from a timestamp/hash?
At te same time your controller will return the image data itself (ReadOne) to pass it to Sardana recorders?

**Comment by dschick** [comment]
> > Just a general question: how would you save the URI in the SPEC file, as it only allows numbers and not strings in the scan data? For the hdf5 this should be no problem.
> 
> Good point! I didn't know about it. Let's see if we can find a workaround... We will post the further information about this in the SEP2 PR comments.

I am pretty sure that at some analysis tool using the SPEC file will complain if there are some non-numbers in the data part

> Let's see if I understood it well:
> Your hardware (or a piece of control software handling the detector e.g. Lima) will store the images into a separate files which names will be composed from a timestamp/hash?
> At te same time your controller will return the image data itself (ReadOne) to pass it to Sardana recorders?

Yeah, that pretty much my situation. The camera is running on one PC where the raw images should be saved to file. In addition to that I would like to transfer the image and/or ROIs (see #982 ) to sardana.
For the simple case in which I simply send the ROIs to Sardana I would also like to get some link to the raw image via the ReadOne which I can store in the SPEC file. I was thinking of the dataTime for each image, which could be saved as integer (seconds from 1970) in the SPEC file.

**Comment by reszelaz** [comment]
> I am pretty sure that at some analysis tool using the SPEC file will complain if there are some non-numbers in the data part

I started a new discussion about this in #991. Let's continue this topic there.

> The camera is running on one PC where the raw images should be saved to file. In addition to that I would like to transfer the image and/or ROIs (see #982 ) to sardana.

This scenario is very interesting and will help us in designing the SEP2. This means that you would like to have in the scan file (let's think about H5 for the moment, cause this one should work without problems) both the raw image (let's forget about the ROIs now) and the data source of the image file saved on the detectors PC. I was always thinking of passing either one or the other thing.

**Comment by dschick** [comment]
hej @reszelaz , indeed it might be a bit unusual to do both.

I am also right now working on it and it seems that the communication delay in order to transfer the image from the camera PC to the sardana PC costs to much time. (it is just 200ms, but we are just integrating for 500ms)
The reasons why we tried it in the first place are:

1. we want to duplicate the data because of data safety
2. we want to have the complete measurement data in one (hdf5) file from sardana

Best

Daniel

**Comment by reszelaz** [comment]
Thanks for the clarification!

The second reason is very interesting. We also thought about it and our idea was to provide a tool for optional consolidation of the data into one hdf5 file *a posteriori* (when the data acquisition is done).

So, in the case when the detector images (or a series of them) were stored in a different hdf5 file (for example [Lima](http://lima.blissgarden.org/) can do that, and this is how we do it at ALBA), in the sardana scan file we could use the [HDF5 Virtual Data Sets](https://support.hdfgroup.org/HDF5/docNewFeatures/NewFeaturesVirtualDatasetDocs.html) to provide a way to transparently navigate to the data. Going further, the said tool, could be triggered to consolidate the data as soon as the acquisition is done and the long data transfer times are not so critical. If all the files use the hdf5 format this seems to be easy.

Now, a little bit of brainstorming... I don't know how this tool could work if the detectors data were stored in formats different than the hdf5, for example edf, or cbf? Maybe we could provide a plugin mechanism to be able to copy the data from different formats?

Anyway, as you can see the said tool was not event mentioned in the [SEP2](https://github.com/reszelaz/sardana/blob/sep2/doc/source/sep/SEP2.md) document. Actually the SEP2 scope was quite reduced cause we prefer to drive all the 1D&2D detectors features incrementally.

**Comment by dschick** [comment]
Hej @reszelaz , adding the detector data via a Link and running a delayed script would of course be the best solution.
In that case, I would simply wait and contribute to that idea.

But this would mean, that there is an external script/tool running, which is either triggered by sardana, or runs as a cron job, or automatically detects a finished scan an then consolidates the data?

We normally copy the sardana data files as well as the detector image files to a NAS after each scan - then the tool/script could work on the copied files which might save some headache with file access from multiple processes.

**Comment by dschick** [comment]
Comming back to this issue:
Although I agree that SEP18 does a good job in handling the URI of images, I still would like to save the images by the hardware (CCD) in a dedicated folder with a structure like `/basePath/ScanFile/scanNb/ptNb.img`.
For that I am trying to use the preAcq hook to send commands to the CCD controller in advance to the actual acquisition.
This works fine with everything despite of the PtNb in a scan.

Is there a way how to access the PtNb in the PreAcq hook?

**Comment by teresanunez** [comment]
Hi Daniel, at DESY we do something like this and what we do is use an attribute in our Detector Devices
that count the number of images taken, and we reset this number to I in the pre-scan hook. 
This attribute is used by the Detector Device in building the name of the output file.

**Comment by dschick** [comment]
okay, that is also a pretty smart solution.
As I do not have my detector implemented in TANGO but directly in Sardana, I would need do add this attribute to the 2dController I wrote for this CCD.
Then I should be able to read and write the attribute from within any macros/hooks using the `send2ctrl `macro, right?
Otherwise I would need create an extra TANGO DS just hosting the PtNb information.

**Comment by teresanunez** [comment]
Hi, I think it should work. Using send2ctrl or reading/writing the attribute from the Pool Device. Check what is better to implement there.

**Comment by dschick** [comment]
okay, I guess, that both options should essentially do the same under the hood, so using the Pool Device is just more direct.

Thanks so far, I let you know if it worked out

**Comment by dschick** [comment]
Hej,

I am trying to implement it using the `ctrl_extra_attributes`.
I am just wondering, why these attributes are finally added to each axis of the controller and to the controller itself? Or am I doing something wrong here?

**Comment by dschick** [comment]
I made it work using ctrl_attributes and with this I think the issue is solved.
Thanks a lot!
```
    ctrl_attributes = {'PointNb' : { Type : int,
                                             Description : "pointNb of the scan",
                                             Access : DataAccess.ReadWrite,
                                             FGet : 'getPointNb', FSet : 'setPointNb', },
                        'FileName' : { Type : str,
                                             Description : "file name of image",
                                             Access : DataAccess.ReadWrite,
                                             FGet : 'getFileName', FSet : 'setFileName', },
                        }
    
    def getPointNb(self):
        return self.pointNb
    
    def setPointNb(self, value):
        self.pointNb = int(value)
        return

    def getFileName(self):
        return self.fileName
    
    def setFileName(self, value):
        self.fileName = value
        return
```

**Comment by reszelaz** [comment]
Sorry to come to this discussion late.

> Although I agree that SEP18 does a good job in handling the URI of images, I still would like to save the images by the hardware (CCD) in a dedicated folder with a structure like /basePath/ScanFile/scanNb/ptNb.img.
For that I am trying to use the preAcq hook to send commands to the CCD controller in advance to the actual acquisition.
This works fine with everything despite of the PtNb in a scan.

> Is there a way how to access the PtNb in the PreAcq hook?
> 

It was the SEP2 which introduced the value referencing. SEP18 introduced the concept of preparation of measurement group (and experimental channel controllers) for complex measurements composed from multiple acquisitions. So, SEP18 gives the controller (plugin)  the possibility to know the acquisition number which in step scan corresponds to PtNb.

Sorry there is no official documentation yet for neither of these features. Just the SEP documents..
To understand it better you could follow these [SEP2 guide](https://github.com/sardana-org/sardana-followup/blob/master/20190603-DESY/04_SEP2/SEP2.md) (especially "Scans: Virtual Datasets (VDS) in SEP2" section) and [SEP18 guide](https://github.com/sardana-org/sardana-followup/blob/master/20190603-DESY/02_SEP18/SEP18.md). Also the [DummyTwoDController](https://github.com/sardana-org/sardana/blob/9ea3b041491e776cd674e1b62700ede76037b536/src/sardana/pool/poolcontrollers/DummyTwoDController.py#L442) class could serve as an example.

**Comment by dschick** [comment]
Hej @reszelaz ,

thanks for the clarifications. I guess I got the idea behind SEP2 and 18 now a bit better.
(we could move [part of] this discussion also to a other/dedicated issue)

So having the `prepareOne `method available I can easily reset the counter for indexing the PtNb during a scan. However, in the DummyTwoDController example this will always result in overwriting the detector files of the last scan, unless I do change the `refPattern `e.g. in the `preScan `hook, right? Or is there another way to have e.g. the ScanID included in the detector file name.

What is actually the difference between the value and value_buffer?

I will then try to implement the ROIs of my CCD as PseudoCounters, as described in #982

**Comment by reszelaz** [comment]
> So having the prepareOne method available I can easily reset the counter for indexing the PtNb during a scan. However, in the DummyTwoDController example this will always result in overwriting the detector files of the last scan, unless I do change the refPattern e.g. in the preScan hook, right?

Exactly! I think that currently there is no better way of doing this. Well, you could also change the value reference to avoid the override according to your own criteria. The value reference pattern is just a suggestion to the controller. At the end what counts, and what is written in the scan file, is the value reference returned after the acquisition.  

> Or is there another way to have e.g. the ScanID included in the detector file name.

We have planned that. This was described in [Scan framework API for referencing configuration](https://github.com/sardana-org/sardana/commit/f406e3f53dc91558dde8a90c20ceaa6b631f67e5#diff-8a2da20893c5b775765d77de0ea3c284). Finally we decided to remove it from SEP2 scope to not delay its integration. We plan to implement it as soon as we finish with migration to Python 3. Similarly to the examples with scan file and scan dir we could also use the scan id.
> 
> What is actually the difference between the value and value_buffer?

value is for storing the result of the last acquisition controlled by sardana (currently this is not 100% true, cause you could also trigger an ad-hoc readout of the hardware by reading value attribute - we will change it whenever we migrate to Python 3) . value_buffer is for passing chunks with multiple values (currently accompanied by the index to facilitate reconstruction of the records) in continuous acquisition e.g. continuous scan.

**Comment by dschick** [comment]
i think this issue has been solved by SEP2
