### ISSUE TITLE
ROI pseudocounters from 2Dcounter

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#982]
Hej all,

I am going to implement a 2D counter acquiring images from a CCD.
The actual program controlling the CCD (LabView) not only provides access to the full image, but also to a 1D integration of the image and up to 10 ROIs which are an array of 10 floats. Since LabView already provides a GUI for all this, I do not want to transfer the ROI definition and calculation to Sardana but keep it all in LabView.
The CCD program is interfaced from Sardana by an TCP/IP server which I can modify as I wish.

Now I would like realize the 2D image, the 1D integration as well as the 10 ROIs as 2Dcounter, 1Dcounter, as well as 10 Timer/Counters respectively. I can get all the data with one TCP/IP command from the server, but of course I need to distribute it between the different counter types.

Are there already concepts around for such a situation?

Best

Daniel

**Comment by teresanunez** [comment]
Hi Daniel,
                   we also have the case to send information from a detector as 2d or as counters (for the
 RoIs), we simply create controllers for the different types and take care about the synchronization, but
 in principle there is no problem.

                                   Regards,
                                                       Teresa

**Comment by dschick** [comment]
Hej @teresanunez , thanks for the quick reply.

Okay, but how do you do the synchronization exactly? Is your code online available?

I guess you have to open a separate connection to the camera server (I guess you have implemented the camera in Tango?) in each Sardana controller?

Best

Daniel

**Comment by rhomspuron** [comment]
Hi @dschick, 

As @teresanunez commented, in ALBA we also use a controller `CounterTimerController` for the ROIs. We base this controller on the Lima ROI Device Server.  There is another controller to configure the detector. The SEP2 should solve the ROI integration on Sardana. 

ROI controller: https://sourceforge.net/p/sardana/controllers.git/ci/master/tree/python/countertimer/LimaRoICoTiCtrl.py
Lima controller: https://sourceforge.net/p/sardana/controllers.git/ci/master/tree/python/countertimer/LimaCoTiCtrl.py

Cheers,
Roberto

**Comment by reszelaz** [comment]
SEP2 should answer to all this questions. 

Meanwhile mutliple contollers seems to workaround it quite well.
You could develop an interface with the hardware as a [singleton](https://en.wikipedia.org/wiki/Singleton_pattern) class together with some serialization primitives (if necessary) and them use it in all controllers.

In case you use an intermediate Tango device to talk to the hardware there is no need to use the singleton pattern and custom serialization (Tango does the serialization on the server side). Multiple DeviceProxies should not be a problem, but if you want to avoid them Taurus Devices would do this job for you.

**Comment by dschick** [comment]
@reszelaz the idea with the singleton is a good idea - it has been a long time since I learned the OO design pattern.
@teresanunez and @rhomspuron : will have a look how the synchronization between the 2d and counterTimer controller has been realized in your code, but I fear most of this is done in the Tango DSs?

**Comment by dschick** [comment]
okay, maybe you could also comments on this design idea:

I have a 2Dctrl that handles all the communication with the actual hardware using a singelton.
I then programm a PseudoCounter that depends on this 2Dctrl (is this actually possible?)
In the PseudoCounter I can either calculate the ROIs myself in Sardana, or I can also call the singelton to get the ROIs from the controller.
Using the PseudoCounter will solve all synchronization issues intrinsically, right?

Best

Daniel

**Comment by reszelaz** [comment]
If you finally go for the singleton implementation you can use the one provided by `taurus.core.util.singleton`.

> I then programm a PseudoCounter that depends on this 2Dctrl (is this actually possible?)

Yes. Initially pseudo counters worked only with the counter/timer experimental channels. In #370 we fixed them to work also on 0D. And if I remember well at that time we also tested them on 1D and 2D. I just quickly checked it and they still seem to work. So your approach looks promising... If you finally go in this direction please give us feedback on it cause I think noone is using pseudo counters based on 1D/2D.

> Using the PseudoCounter will solve all synchronization issues intrinsically, right?

Regarding the synchronization issues. There are two different ways the pseudo counters are calculated. I simplify a little bit the explanation so it is easier to follow...

In case of the step scans these are read from the MacroServer when the measurement group has already finished. Here you don't know the order in which they would be read and the read is done simultaneously (PyTango asynchronous reads).

In case of the continuous scans, these are calculated whenever all the physical channels reported the values and then the pseudo counter calculated value is pushed to the MacroServer.
You won't be able to use the 2D in the continuous scans - these are not supported yet.

Hope this helps!

**Comment by teresanunez** [comment]
>Yes. Initially pseudo counters worked only with the counter/timer experimental channels. In #370 we fixed them to work also on 0D. And if I remember well at that time we also tested them on 1D and 2D. I just quickly checked it and they still seem to work. So your approach looks promising... If you finally go in this direction please give us feedback on it cause I think noone is using pseudo counters based on 1D/2D.

We have a PseudoCounter based on 1D, MCA2SCACtrl.

**Comment by dschick** [comment]
thanks @reszelaz and @teresanunez 
I will test it as soon as possbile.

because of the continuous scans:
From the hardware point of view I could also have the 0D data as counter/timer and the 2D data depends on that as pseudocounter. Then the continuous scan should work at least for the 0D data.
However, I would need to test, if a 2D pseudocounter can depent on a 0D counter/timer

**Comment by dschick** [comment]
@reszelaz sorry for the mess in my head.

The first scenario we discussed a few days ago, was most natural:
There is a 2d experimental channel and then one can derive the 1d and 0d data from this as pseudocounters. The draw back of this scenario is, that it will not work for continuous scans, as the 2d channel isno working here, yet.
As I already proposed for this scenario, the 1d and 0d pseudocounters can either calculate their values from the real 2d data (integrate over one dimension, calculate ROIs) or they again call the camera controller via a singleton interface, because the 1d and 0d data is also calculated by the camera itself.

In the latter case, it does not matter for me which is the physical channel and which is a pseudocounter.
So I was supposing to interchange the roles and use the scalar data as the physical channel and then implement the 1D and 2D as pseudocounters which use the singleton interface to get their data from the camera controller.

**Comment by reszelaz** [comment]
> There is a 2d experimental channel and then one can derive the 1d and 0d data from this as pseudocounters. The draw back of this scenario is, that it will not work for continuous scans, as the 2d channel isno working here, yet.

Please don't worry about this, the 2D support in continuous scans will be added in SEP2. This should come shortly.

> As I already proposed for this scenario, the 1d and 0d pseudocounters can either calculate their values from the real 2d data (integrate over one dimension, calculate ROIs) or they again call the camera controller via a singleton interface, because the 1d and 0d data is also calculated by the camera itself.

> In the latter case, it does not matter for me which is the physical channel and which is a pseudocounter.
So I was supposing to interchange the roles and use the scalar data as the physical channel and then implement the 1D and 2D as pseudocounters which use the singleton interface to get their data from the camera controller.

There is one blocking issue here. Currently you can not change the shape of the pseudocounter's value - it must be a scalar. Today I started fixing this but will need some more time to propose a PR and I'll be busy until Friday... With this fix it will be possible to define pseudocounters producing spectrums or even images. Well, in this case the name "pseudocounter" may become not too accurate. But we could discuss if we need to adapt its name afterwards...

**Comment by reszelaz** [comment]
> There is one blocking issue here. Currently you can not change the shape of the pseudocounter's value - it must be a scalar. Today I started fixing this but will need some more time to propose a PR and I'll be busy until Friday... With this fix it will be possible to define pseudocounters producing spectrums or even images. Well, in this case the name "pseudocounter" may become not too accurate. But we could discuss if we need to adapt its name afterwards...

@dschick #986 should overcome this limitation. It would be great if you could test it. This for sure will speed up the integration process. Thanks!

**Comment by dschick** [comment]
Just another idea, how to maybe simplify the ROI issue and avoiding the use of a singleton implementation, as I do not have a intermediate TANGO DS:

In the 2Dcontroller axis, when I do get the URI of the Images according to SEP2, I could also ask the hardware for the values of the ROIs (which are calculated by the hardware).
I then save the ROI values as an `axis_extra_attribute`.

In the ROI pseudo counter (which is only called, when the input 2Dcontroller has finished) I simply read the ROI values via an `AttributeProxy `from the 2Dcontroller axis via TANGO or Taurus.

What do you think, is that feasible?

**Comment by reszelaz** [comment]
If I understand correclty in your scenario, the detector (not the controller plugin) stores the images in files and calculates ROIs (I usu the _hardware ROI_ naming for this).
If you plan to use only step scans, maybe you don't even need a pseudo counter. In a step scan you can include in the measurement group directly an arbitrary Tango attribute. So, you could just write a `Referable` 2D controller to report value references and then export the ROI values as [extra axis attributes](https://sardana-controls.org/devel/howto_controllers/howto_controller.html#extra-axis-attributes). If you include them in the measurement group these will be read after the acquisition has finished.

Of course this is kind of hacky solution. At some point we need to unify the software and hardware ROIs which was out of the SEP2 scope...

**Comment by dschick** [comment]
I fear I will still need the pseudo counter approach since I need to use my XMCD hack as discussed in #812 and thus create a pseudoCounter of a pseudoCounter (#823 )
or is it possible to have an pseudoCounter with a TANGO attribute as input role?

**Comment by reszelaz** [comment]
> I fear I will still need the pseudo counter approach since I need to use my XMCD hack as discussed in #812 and thus create a pseudoCounter of a pseudoCounter (#823 )
or is it possible to have an pseudoCounter with a TANGO attribute as input role?

Ah, I see. Then you need a pseudo counter. It is not possible to base a pseudo counter directly on a Tango attribute.
