### ISSUE TITLE
ascanct gets wrong motor range when position unit is configured

### ISSUE THREAD

**Issue by julianofjm** [sardana-org/sardana#989]
I have done some tests with continuous scan using the ascanct macro and I noted that when we have the motor limits different of -inf inf and position unit configured, sardana gets wrong motor range.

For example:
```
set_lim mot01 -500 500
ascanct mot01 0 10 10 0.01 0
```
If the position unit of mot01 is configured to "degrees" sardana will get wrong motor range.
I have tested it with sardana 2.5.0 and taurus 4.4.0.

**Comment by reszelaz** [comment]
Thanks for the report @julianofjm.

The cast to float of the angle quantity in degrees unit seems to return the magnitute but after prior change of the unit to radians. Since Sardana does not support quantities and its scan parameters are pure numbers the limits comparison was wrong.
